// Product categories for the field workflow. A category is a SHORTCUT, not a conclusion: choosing / inferring one only adds PROBABLE trait evidence
// (never stronger), so every rule keeps asking for the real facts. HS entries are CANDIDATE HINTS at heading level (HS6), never a classification.
//
// Trait vocabulary (flat names; true / false / number / string; unknown = absent):
//   electrical.present, electrical.mainsConnected, electrical.maxVoltageAc, electrical.maxVoltageDc, battery.present, battery.chemistry,
//   battery.integrated, radio.present, radio.bluetooth, radio.wifi, childrenUse, toy, foodContact, cosmetic, ppe, textile, medical, chemicalMixture, jewelry
export const KEY_TRAITS = Object.freeze(['electrical.present', 'battery.present', 'radio.present', 'childrenUse', 'foodContact', 'cosmetic', 'ppe', 'textile', 'medical', 'chemicalMixture']);

const none = { 'electrical.present': false, 'battery.present': false, 'radio.present': false, foodContact: false, cosmetic: false, ppe: false, medical: false, chemicalMixture: false, textile: false, toy: false };
const hs = (code, desc, confidence = 'LOW') => ({ code, desc, confidence });

export const CATEGORIES = Object.freeze({
  household_general: { label: 'Household item (non-electrical)', keywords: ['storage box', 'organizer', 'hanger', 'basket', 'holder', 'rangement', 'opbergdoos', '收纳', '置物'], traits: { ...none, childrenUse: false }, hs: [hs('3924.90', 'Plastic household articles (if plastic)'), hs('7323.99', 'Household articles of iron/steel (if metal)')], amazon: 'Home & Kitchen' },
  kitchenware_plastic: { label: 'Plastic kitchenware / food container', keywords: ['lunch box', 'food container', 'plastic cup', 'tupperware', 'boîte alimentaire', 'voorraaddoos', '饭盒', '保鲜盒'], traits: { ...none, foodContact: true, childrenUse: false }, hs: [hs('3924.10', 'Tableware and kitchenware of plastics', 'MEDIUM')], amazon: 'Home & Kitchen' },
  water_bottle: { label: 'Drinking bottle / flask', keywords: ['water bottle', 'drinking bottle', 'thermos', 'flask', 'tumbler', 'gourde', 'drinkfles', '水杯', '保温杯', '水壶'], traits: { ...none, foodContact: true }, hs: [hs('3924.10', 'Plastic tableware/kitchenware (if plastic)'), hs('7323.93', 'Stainless-steel table/kitchenware (if stainless)'), hs('9617.00', 'Vacuum flasks (insulated)')], amazon: 'Sports & Outdoors / Home & Kitchen' },
  tableware_glass_ceramic: { label: 'Glass / ceramic tableware', keywords: ['mug', 'ceramic', 'porcelain', 'glass cup', 'plate', 'bowl', 'tasse', 'mok', '陶瓷', '玻璃杯', '杯子'], traits: { ...none, foodContact: true }, hs: [hs('6912.00', 'Ceramic tableware/kitchenware (not porcelain)'), hs('6911.10', 'Porcelain tableware'), hs('7013.99', 'Glassware')], amazon: 'Home & Kitchen' },
  usb_charger: { label: 'USB / mains charger or adapter', keywords: ['charger', 'adapter', 'adaptor', 'power supply', 'gan', 'usb-c charger', 'chargeur', 'oplader', '充电器', '适配器'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': true, 'electrical.maxVoltageAc': 230, 'radio.present': false, childrenUse: false }, hs: [hs('8504.40', 'Static converters (chargers/adapters)', 'MEDIUM')], amazon: 'Electronics' },
  power_bank: { label: 'Power bank (portable battery pack)', keywords: ['power bank', 'powerbank', 'portable charger', 'battery pack', 'external battery', 'batterie externe', 'externe accu', '充电宝', '移动电源'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': false, 'electrical.maxVoltageAc': 0, 'electrical.maxVoltageDc': 5, 'battery.present': true, 'battery.chemistry': 'li_ion', 'battery.integrated': true, childrenUse: false }, hs: [hs('8507.60', 'Lithium-ion accumulators (power banks)', 'MEDIUM'), hs('8504.40', 'Static converters (alternative reading)', 'LOW')], amazon: 'Electronics' },
  bluetooth_speaker: { label: 'Bluetooth / wireless speaker', keywords: ['bluetooth speaker', 'wireless speaker', 'portable speaker', 'enceinte', 'luidspreker', '蓝牙音箱', '音响'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': false, 'electrical.maxVoltageAc': 0, 'electrical.maxVoltageDc': 5, 'battery.present': true, 'battery.chemistry': 'li_ion', 'battery.integrated': true, 'radio.present': true, 'radio.bluetooth': true, childrenUse: false }, hs: [hs('8518.21', 'Single loudspeaker mounted in enclosure', 'LOW'), hs('8518.22', 'Multiple loudspeakers in same enclosure', 'LOW'), hs('8518.29', 'Other loudspeakers', 'LOW')], amazon: 'Electronics' },
  bluetooth_earbuds: { label: 'Bluetooth earbuds / headphones', keywords: ['earbuds', 'earphones', 'headphones', 'tws', 'headset', 'écouteurs', 'oordopjes', '耳机', '蓝牙耳机'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': false, 'electrical.maxVoltageAc': 0, 'electrical.maxVoltageDc': 5, 'battery.present': true, 'battery.chemistry': 'li_ion', 'battery.integrated': true, 'radio.present': true, 'radio.bluetooth': true, childrenUse: false }, hs: [hs('8518.30', 'Headphones and earphones', 'MEDIUM'), hs('8517.62', 'Communication apparatus (headsets with microphone, alternative)', 'LOW')], amazon: 'Electronics' },
  led_lamp_mains: { label: 'LED lamp / light (mains)', keywords: ['led lamp', 'led bulb', 'desk lamp', 'light strip', 'lampe', 'lamp', '台灯', '灯带', '灯泡'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': true, 'electrical.maxVoltageAc': 230, 'radio.present': false }, hs: [hs('9405.42', 'LED electric lamps/lighting fittings', 'LOW'), hs('8539.50', 'LED lamps (bulbs)', 'LOW')], amazon: 'Lighting' },
  usb_cable: { label: 'USB / charging cable', keywords: ['usb cable', 'charging cable', 'lightning cable', 'type-c cable', 'câble usb', 'usb-kabel', '数据线', '充电线'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': false, 'electrical.maxVoltageAc': 0, 'electrical.maxVoltageDc': 20, 'radio.present': false, childrenUse: false }, hs: [hs('8544.42', 'Insulated conductors fitted with connectors, <=1000V', 'MEDIUM')], amazon: 'Electronics' },
  phone_case: { label: 'Phone case / accessory (passive)', keywords: ['phone case', 'cover', 'coque', 'telefoonhoesje', '手机壳'], traits: { ...none, childrenUse: false }, hs: [hs('3926.90', 'Other articles of plastics', 'LOW'), hs('4202.32', 'Cases with outer surface of plastic sheeting (if applicable)', 'LOW')], amazon: 'Electronics Accessories' },
  toy_plastic: { label: "Toy (plastic / mechanical)", keywords: ['toy', 'kids toy', 'jouet', 'speelgoed', 'building blocks', '玩具', '积木'], traits: { ...none, childrenUse: true, toy: true }, hs: [hs('9503.00', 'Toys (tricycles, puzzles, models, other toys)', 'MEDIUM')], amazon: 'Toys & Games' },
  plush_toy: { label: 'Plush / soft toy', keywords: ['plush', 'stuffed', 'soft toy', 'peluche', 'knuffel', '毛绒', '公仔'], traits: { ...none, childrenUse: true, toy: true, textile: true }, hs: [hs('9503.00', 'Toys', 'MEDIUM')], amazon: 'Toys & Games' },
  textile_adult: { label: 'Apparel / textile (adult)', keywords: ['t-shirt', 'shirt', 'hoodie', 'jacket', 'dress', 'socks', 'vêtement', 'kleding', '服装', '衣服'], traits: { ...none, textile: true, childrenUse: false }, hs: [hs('6109.10', 'T-shirts, knitted, cotton', 'LOW'), hs('6110.20', 'Jerseys/pullovers, knitted, cotton', 'LOW'), hs('6203.42', 'Trousers, woven, cotton (men)', 'LOW')], amazon: 'Clothing' },
  textile_children: { label: "Children's apparel / textile", keywords: ['baby clothes', 'kids clothing', "children's wear", 'vêtements enfant', 'kinderkleding', '童装', '婴儿服'], traits: { ...none, textile: true, childrenUse: true }, hs: [hs('6111.20', "Babies' garments, knitted, cotton", 'LOW'), hs('6209.20', "Babies' garments, woven, cotton", 'LOW')], amazon: 'Clothing / Baby' },
  cosmetic_product: { label: 'Cosmetic / personal care product', keywords: ['cream', 'lotion', 'lipstick', 'shampoo', 'mascara', 'serum', 'perfume', 'crème', 'cosmetica', '护肤', '化妆品', '面霜'], traits: { ...none, cosmetic: true, chemicalMixture: true }, hs: [hs('3304.99', 'Beauty/skin-care preparations', 'LOW'), hs('3305.10', 'Shampoos', 'LOW'), hs('3303.00', 'Perfumes and toilet waters', 'LOW')], amazon: 'Beauty' },
  jewelry_costume: { label: 'Costume jewellery / accessories', keywords: ['necklace', 'bracelet', 'earring', 'ring', 'jewelry', 'jewellery', 'bijoux', 'sieraden', '项链', '耳环', '手链'], traits: { ...none, jewelry: true }, hs: [hs('7117.19', 'Imitation jewellery of base metal', 'MEDIUM'), hs('7117.90', 'Other imitation jewellery', 'LOW')], amazon: 'Jewelry' },
  ppe_item: { label: 'Protective equipment (PPE)', keywords: ['safety gloves', 'helmet', 'safety glasses', 'face mask', 'respirator', 'gants de protection', 'veiligheidshandschoenen', '防护手套', '口罩', '安全帽'], traits: { ...none, ppe: true }, hs: [hs('6116.10', 'Gloves impregnated/coated with plastics', 'LOW'), hs('6307.90', 'Other made-up textile articles (masks)', 'LOW'), hs('6506.10', 'Safety headgear', 'LOW')], amazon: 'Industrial & Scientific' },
  battery_standalone: { label: 'Battery / rechargeable cell (standalone)', keywords: ['battery', 'rechargeable battery', 'aa battery', '18650', 'pile', 'batterij', '电池', '锂电池'], traits: { ...none, 'battery.present': true, 'battery.integrated': false, 'electrical.present': false }, hs: [hs('8507.60', 'Lithium-ion accumulators', 'MEDIUM'), hs('8506.10', 'Manganese dioxide primary cells', 'LOW')], amazon: 'Electronics / Batteries' },
  small_appliance_mains: { label: 'Small mains appliance', keywords: ['hair dryer', 'kettle', 'blender', 'heater', 'fan', 'sèche-cheveux', 'haardroger', '吹风机', '电热水壶', '风扇'], traits: { ...none, 'electrical.present': true, 'electrical.mainsConnected': true, 'electrical.maxVoltageAc': 230, 'radio.present': false }, hs: [hs('8516.31', 'Hair dryers', 'LOW'), hs('8516.10', 'Electric water heaters', 'LOW'), hs('8414.51', 'Table/wall/ceiling fans', 'LOW')], amazon: 'Home & Kitchen' },
  gift_decor_generic: { label: 'Decor / gift / stationery (generic)', keywords: ['gift', 'decoration', 'ornament', 'stationery', 'notebook', 'cadeau', 'decoratie', '礼品', '装饰', '文具'], traits: { ...none, childrenUse: false }, hs: [hs('9505.90', 'Festive/carnival articles', 'LOW'), hs('4820.10', 'Registers, notebooks', 'LOW'), hs('6913.90', 'Ceramic statuettes/ornaments', 'LOW')], amazon: 'Home & Kitchen / Office' },
  pet_product: { label: 'Pet product', keywords: ['pet', 'dog toy', 'cat', 'leash', 'animal', 'chien', 'hond', '宠物'], traits: { ...none, childrenUse: false }, hs: [hs('4201.00', 'Saddlery/harness for animals', 'LOW'), hs('9508.90', 'Other amusement articles', 'LOW')], amazon: 'Pet Supplies' },
});

export const CATEGORY_IDS = Object.freeze(Object.keys(CATEGORIES));

const norm = (s) => String(s ?? '').toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '');

/** Keyword inference over any text (product name, listing, OCR text). Ranked candidates with the keywords that matched: a SUGGESTION (PROBABLE), never a conclusion. */
export function inferCategories(text) {
  const t = norm(text); const raw = String(text ?? '');
  const out = [];
  for (const [id, c] of Object.entries(CATEGORIES)) {
    const matched = c.keywords.filter((k) => (/[^\u0000-\u007f]/.test(k) ? raw.includes(k) : t.includes(norm(k))));
    if (matched.length) out.push({ categoryId: id, score: matched.length + matched.reduce((a, k) => a + Math.min(k.length, 12) / 24, 0), matched });
  }
  return out.sort((a, b) => b.score - a.score || (a.categoryId < b.categoryId ? -1 : 1));
}
