export const BRANDING_VERSION = '1.0';

export const SNAPSHOT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  READY: 'READY',
  STALE: 'STALE',
  SUPERSEDED: 'SUPERSEDED',
});

export const GOVERNED_DOCUMENT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  APPROVED: 'APPROVED',
  SUPERSEDED: 'SUPERSEDED',
});

export const EVIDENCE_KIND = Object.freeze({
  FACT: 'FACT',
  INFERENCE: 'INFERENCE',
  HYPOTHESIS: 'HYPOTHESIS',
});

export const EVIDENCE_COMPLETENESS = Object.freeze({
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const SNAPSHOT_REFRESH_TRIGGER = Object.freeze({
  NEW_RELEVANT_COMPETITOR: 'NEW_RELEVANT_COMPETITOR',
  CUSTOMER_REVIEW_SIGNAL_CHANGED: 'CUSTOMER_REVIEW_SIGNAL_CHANGED',
  OFFER_PORTFOLIO_CHANGED: 'OFFER_PORTFOLIO_CHANGED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const DISTINCTIVE_ASSET_TYPE = Object.freeze({
  LOGO: 'LOGO',
  SYMBOL: 'SYMBOL',
  COLOR: 'COLOR',
  TYPOGRAPHY: 'TYPOGRAPHY',
  SHAPE: 'SHAPE',
  PATTERN: 'PATTERN',
  PACKAGING: 'PACKAGING',
  PHOTOGRAPHY_STYLE: 'PHOTOGRAPHY_STYLE',
  MOTION: 'MOTION',
  SOUND: 'SOUND',
  CHARACTER: 'CHARACTER',
  VERBAL_CUE: 'VERBAL_CUE',
  OTHER: 'OTHER',
});

export const BRAND_RULE_TYPE = Object.freeze({
  LOGO: 'LOGO',
  COLOR: 'COLOR',
  TYPOGRAPHY: 'TYPOGRAPHY',
  WORDING: 'WORDING',
  CLAIM: 'CLAIM',
  VISUAL: 'VISUAL',
  TONE: 'TONE',
  PRODUCT_FIDELITY: 'PRODUCT_FIDELITY',
  ASSET_USAGE: 'ASSET_USAGE',
  LAYOUT: 'LAYOUT',
});

export const RULE_ENFORCEMENT = Object.freeze({
  DETERMINISTIC: 'DETERMINISTIC',
  QUALITATIVE: 'QUALITATIVE',
  HYBRID: 'HYBRID',
});

export const RULE_SEVERITY = Object.freeze({
  BLOCK: 'BLOCK',
  REVIEW: 'REVIEW',
});

export const RULE_OPERATOR = Object.freeze({
  EQUALS: 'EQUALS',
  ONE_OF: 'ONE_OF',
  NOT_ONE_OF: 'NOT_ONE_OF',
  CONTAINS: 'CONTAINS',
  NOT_CONTAINS: 'NOT_CONTAINS',
  RANGE: 'RANGE',
  REFERENCE: 'REFERENCE',
  CUSTOM: 'CUSTOM',
});

export const GUARDIAN_OUTCOME = Object.freeze({
  PASS: 'PASS',
  FAIL: 'FAIL',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  NOT_MEASURABLE: 'NOT_MEASURABLE',
});

export const GUARDIAN_METHOD = Object.freeze({
  DETERMINISTIC: 'DETERMINISTIC',
  OCR: 'OCR',
  VISION: 'VISION',
  QUALITATIVE_MODEL: 'QUALITATIVE_MODEL',
  HUMAN_OBSERVATION: 'HUMAN_OBSERVATION',
});

export const BRAND_CONTEXT_STATUS = Object.freeze({
  READY: 'READY',
  GATED: 'GATED',
});
