// case screen (extracted from app.js, no behaviour change).
import { esc, chip, money, list, field, selectOf, seg, quoteOf, VERDICT_TEXT } from '../dom.js';
import { S } from '../state.js';
import { CATEGORIES } from '/core/taxonomy.js';
import { effective } from '/core/identity.js';
import { suggestCategories } from '/core/case.js';
import { getBlob } from '../storage.js';

export const TRAITS = [['electrical.present', 'Electrical / electronic'], ['electrical.mainsConnected', 'Plugs into mains (230 V)'], ['battery.present', 'Contains a battery'], ['radio.present', 'Bluetooth / Wi-Fi / radio'], ['childrenUse', 'Designed for children'], ['toy', 'Toy / made for play (under 14)'], ['foodContact', 'Touches food or drink'], ['cosmetic', 'Cosmetic / skin product'], ['textile', 'Textile / clothing'], ['ppe', 'Protective equipment'], ['medical', 'Medical claim']];
export function caseScreen(A, c) {
  const id = c.identity; const cat = effective(id, 'category'); const sugg = suggestCategories(id.workingName);
  const level = (t) => { const e = effective(id, t); return e.known ? (e.level === 'PROBABLE' ? 'assumed from category' : e.level.toLowerCase().replace(/_/g, ' ')) : e.contradiction ? 'CONTRADICTORY' : 'unknown'; };
  const photos = id.photos.map((p, i) => { const d = getBlob(`photo:${c.id}.${i}`); return d ? `<img src="${esc(d)}" alt="product photo ${i + 1}" style="width:96px;height:96px;object-fit:cover;border-radius:8px;margin-right:6px">` : `<span class="chip">photo ${i + 1}</span>`; }).join('');
  const radioOn = effective(id, 'radio.present').value === true;
  return `<div class="card"><h2>PRODUCT</h2><form data-form="product">${field('name', 'What is it? (name, or what the label says)', id.workingName, 'autocomplete="off"')}
    <div class="row">${field('model', 'Model number', id.identifiers.model ?? '')}${field('brand', 'Brand', id.identifiers.brand ?? '')}</div>${field('manufacturer', 'Manufacturer (legal name on label)', id.identifiers.manufacturer ?? '')}${field('gtin', 'Barcode (GTIN / EAN)', id.identifiers.gtin ?? '', 'inputmode="numeric"')}
    ${selectOf('category', 'Category (probable - you confirm)', [['', cat.known ? '(keep)' : '- choose -'], ...Object.entries(CATEGORIES).map(([k, v]) => [k, v.label])], '')}<button class="btn" style="margin-top:10px">Save product</button></form>
    ${sugg.length ? `<p class="small muted">From the name, probably: ${sugg.map((s) => `<button type="button" class="btn sec" data-act="cat" data-key="${esc(s.id)}" style="min-height:36px;padding:4px 10px;margin:2px">${esc(s.label)}</button>`).join('')}</p>` : ''}
    <p class="small">Category now: <b>${esc(cat.known ? (CATEGORIES[cat.value]?.label ?? cat.value) : 'not set')}</b> <span class="muted">(${esc(cat.known ? cat.level.toLowerCase().replace(/_/g, ' ') : 'unknown')})</span></p>
    ${S.suggestions.length ? `<div class="note"><b>AI SUGGESTED</b> (not a fact until you confirm)${S.suggestions.map((x) => `<div style="margin-top:6px">${esc(CATEGORIES[x.categoryId]?.label ?? x.categoryId)} <span class="muted small">(${esc(x.confidence)}${x.why ? `: ${esc(x.why)}` : ''})</span><br><button type="button" class="btn sec" data-act="cat-confirm" data-key="${esc(x.categoryId)}" style="min-height:36px;padding:4px 10px">Yes, it is this</button> <button type="button" class="btn sec" data-act="cat-guess" data-key="${esc(x.categoryId)}" style="min-height:36px;padding:4px 10px">Keep as an unconfirmed guess</button></div>`).join('')}</div>` : ''}
    <label>Photo of the product / label / packaging (kept as evidence)</label><input type="file" accept="image/*" capture="environment" data-act="photo"><div style="margin-top:6px">${photos}</div></div>
  <div class="card"><h2>WHAT IS IT, FOR REAL?</h2><p class="small muted">Each answer is stronger than the category guess. Unknown stays unknown.</p>
    ${TRAITS.map(([t, l]) => `<div class="trait"><div><div class="nm">${esc(l)}</div><div class="lv">${esc(level(t))}</div></div>${seg('trait', t, effective(id, t).known ? effective(id, t).value : null)}</div>`).join('')}
    ${radioOn ? `<div class="trait"><div><div class="nm">Connects to the internet / app</div><div class="lv">${esc(level('radio.internetConnected'))}</div></div>${seg('trait', 'radio.internetConnected', effective(id, 'radio.internetConnected').known ? effective(id, 'radio.internetConnected').value : null)}</div><div class="trait"><div><div class="nm">Handles personal data (account, voice, location)</div><div class="lv">${esc(level('radio.processesPersonalData'))}</div></div>${seg('trait', 'radio.processesPersonalData', effective(id, 'radio.processesPersonalData').known ? effective(id, 'radio.processesPersonalData').value : null)}</div>` : ''}
    <form data-form="electrics"><div class="row">${field('vac', 'Rated AC volts', effective(id, 'electrical.maxVoltageAc').value ?? '', 'inputmode="decimal"')}${field('vdc', 'Rated DC volts', effective(id, 'electrical.maxVoltageDc').value ?? '', 'inputmode="decimal"')}</div>${selectOf('chem', 'Battery type', [['', '(unknown)'], ['li_ion', 'Lithium-ion'], ['li_po', 'Lithium-polymer'], ['other', 'Other / not lithium']], effective(id, 'battery.chemistry').value ?? '')}<button class="btn sec" style="margin-top:8px">Save ratings</button></form></div>
  <div class="card"><h2>WHO IS RESPONSIBLE?</h2><div class="trait"><div class="nm">Sold under MY name / brand (private label)</div>${seg('place', 'underOwnNameOrBrand', c.placing.underOwnNameOrBrand ?? null)}</div>
    <div class="trait"><div class="nm">Manufacturer is in the EU</div>${seg('place', 'manufacturerEstablishedInEU', c.placing.manufacturerEstablishedInEU ?? null)}</div>
    <div class="trait"><div class="nm">Supplier names an EU representative</div>${seg('place', 'euAuthorisedRepresentative', c.placing.euAuthorisedRepresentative ?? null)}</div>
    <div class="trait"><div class="nm">I modify the product (design, firmware, accessories)</div>${seg('place', 'modifiedProduct', c.placing.modifiedProduct ?? null)}</div>
    ${c.placing.modifiedProduct === true ? `<div class="trait"><div class="nm">The modification can affect safety or compliance</div>${seg('place', 'modificationAffectsCompliance', c.placing.modificationAffectsCompliance ?? null)}</div>` : ''}
    <div class="trait"><div class="nm">I repack it</div>${seg('place', 'repackaged', c.placing.repackaged ?? null)}</div>
    ${c.placing.repackaged === true ? `<div class="trait"><div class="nm">The new packaging carries MY name / brand</div>${seg('place', 'repackagedUnderOwnName', c.placing.repackagedUnderOwnName ?? null)}</div>` : ''}
    <div class="trait"><div class="nm">I change the labels or instructions</div>${seg('place', 'changedInstructionsOrLabels', c.placing.changedInstructionsOrLabels ?? null)}</div>
    ${c.placing.changedInstructionsOrLabels === true ? `<div class="trait"><div class="nm">Safety information or warnings change (not only translation)</div>${seg('place', 'changedSafetyInformation', c.placing.changedSafetyInformation ?? null)}</div>` : ''}
    ${A.role.basis.length ? `<p class="small muted">Basis: ${esc(A.role.basis.join(' | '))}</p>` : ''}
    <p class="note">${esc(A.role.note)} Role now: <b>${esc(A.role.role.replace(/_/g, ' '))}</b>${A.role.status === 'UNRESOLVED' ? ' - <b>NOT DECIDED</b>: answer the open role questions (a deciding fact is unknown)' : ''}</p></div>
  <div class="card"><h2>WHERE WILL IT BE SOLD?</h2><div class="trait"><div class="nm">Own shop / retail</div>${seg('chan', 'own_site', c.context.channels.includes('own_site'))}</div><div class="trait"><div class="nm">Amazon (BE/FR/DE/NL)</div>${seg('chan', 'amazon', c.context.channels.includes('amazon'))}</div></div>
  <div class="card"><h2>SUPPLIER</h2><form data-form="supplier">${field('name', 'Company', c.supplier.name ?? '')}<div class="row">${field('booth', 'Booth / hall', c.supplier.booth ?? '')}${field('market', 'Fair / market', c.supplier.market ?? '')}</div>${field('contact', 'Contact (name, WeChat, phone)', c.supplier.contact ?? '')}${field('link', 'Listing / link', c.supplier.link ?? '')}<button class="btn sec" style="margin-top:8px">Save supplier</button></form><p class="small muted">Stored on this device and your own server only. Never sent to an AI provider.</p></div>`;
}
