// docs screen (extracted from app.js, no behaviour change).
import { esc, chip, money, list, field, selectOf, seg, quoteOf, VERDICT_TEXT } from '../dom.js';
import { S } from '../state.js';
import { getBlob } from '../storage.js';

export function docsScreen(A, c) {
  const docCard = (d) => {
    const photo = getBlob(`docphoto:${c.id}.${d.id}`);
    const src = { NATIVE: 'text layer of a PDF', PASTED: 'pasted text', TRANSCRIBED: 'typed by you from the paper', OCR: 'read from a photo by an AI reader', PHOTO_ONLY: 'photo only (not read)' }[d.textSource] ?? d.textSource;
    const ocrPending = d.textSource === 'OCR' && !d.confirmed;
    return `<div class="card"><h2>${esc(d.fileName ?? d.id)} <span class="muted small">${esc(d.docType)}</span></h2><p class="small muted">Source: ${esc(src)}${d.textSource === 'OCR' ? (d.confirmed ? ' - confirmed by you' : ' - UNVERIFIED until you confirm') : ''}</p><p>${chip('Evidence', d.evidenceState, d.evidenceState === 'CONFIRMED_AGAINST_DOCUMENT' ? 'AMBER' : d.evidenceState === 'UNVERIFIED' ? 'RED' : 'UNKNOWN')} <span class="muted small">a supplier document is never VERIFIED</span></p>${photo ? `<img src="${esc(photo)}" alt="photo of the document" style="max-width:100%;max-height:220px;border-radius:8px">` : ''}
    ${chip('Consistency', d.consistency, d.consistency === 'NO_ISSUE_FOUND' ? 'GREEN' : d.consistency === 'UNVERIFIED' || d.consistency === 'INSUFFICIENT_EVIDENCE' ? 'AMBER' : 'RED')}${d.findings.length ? list(d.findings.map((f) => `<b>${esc(f.code.replace(/_/g, ' '))}</b> (${esc(f.severity)}) - ${esc(f.detail)}`)) : ''}${d.note ? `<p class="note">${esc(d.note)}</p>` : ''}
    <p class="small muted">Models: ${esc(d.models.join(', ') || '-')} - Standards: ${esc(d.standards.slice(0, 5).join(', ') || '-')}</p>
    ${d.textSource === 'OCR' || d.textSource === 'PHOTO_ONLY' ? `<details ${ocrPending || d.textSource === 'PHOTO_ONLY' ? 'open' : ''}><summary>${d.textSource === 'PHOTO_ONLY' ? 'Type what the paper says' : 'Text read from the photo (fix it while looking at the paper)'}</summary><form data-form="doc-correct" data-id="${esc(d.id)}"><textarea name="text">${esc(d.ocrText ?? '')}</textarea><button class="btn sec" style="margin-top:6px">Save corrections</button></form>${ocrPending ? `<button class="btn" data-act="doc-confirm" data-key="${esc(d.id)}" style="margin-top:8px">I checked the fields against the paper: confirm</button>` : ''}</details>` : ''}</div>`;
  };
  return `<div class="card"><h2>ADD A SUPPLIER DOCUMENT</h2><p class="small muted">PDF with text, photo of a paper document, pasted text, or typed from the paper. A photographed document is only a MACHINE READING until you check it against the paper. Nordla never says "fake": only what the evidence shows.</p>
  <form data-form="doc"><label>PDF, .txt or photo (camera)<input type="file" name="file" accept=".pdf,.txt,text/plain,application/pdf,image/*"></label><label>Or paste the text<textarea name="text" placeholder="Paste the text of the document"></textarea></label>${selectOf('claimed', 'The supplier calls it', [['', '(not stated)'], ['EU_DOC', 'EU Declaration of Conformity'], ['TEST_REPORT', 'Test report'], ['CERTIFICATE', 'Certificate'], ['SDS', 'Safety data sheet'], ['UN383', 'UN 38.3 report'], ['FCM_DOC', 'Food-contact declaration'], ['MANUAL', 'Manual']])}
  <button class="btn" style="margin-top:10px" ${S.busy === 'doc' ? 'disabled' : ''}>${S.busy === 'doc' ? 'Reading...' : 'Inspect document'}</button></form>
  <p class="small muted">Photo reading uses an AI reader ${S.ai?.enabled ? `(${esc(S.ai.provider)}, ${esc(S.ai.region)}): you are asked before each image is sent` : 'only if one is configured (none now): the photo is kept as evidence and you type what the paper says'}.</p></div>
  <div class="card"><h2>TYPE FROM THE PAPER</h2><p class="small muted">Works offline and with no reader. Key fields only: it can show a model or standard mismatch, not whether the original is complete.</p>
  <form data-form="doc-typed">${selectOf('docType', 'Document', [['EU_DOC', 'EU Declaration of Conformity'], ['TEST_REPORT', 'Test report'], ['CERTIFICATE', 'Certificate'], ['SDS', 'Safety data sheet'], ['UN383', 'UN 38.3 report'], ['FCM_DOC', 'Food-contact declaration'], ['MANUAL', 'Manual']])}<div class="row">${field('model', 'Model on the paper')}${field('date', 'Date of issue (YYYY-MM-DD)')}</div>${field('manufacturer', 'Manufacturer / applicant on the paper')}${field('directives', 'Directives / regulations cited (e.g. 2014/35/EU, 2014/30/EU)')}${field('standards', 'Standards cited (e.g. EN 62368-1, EN 55032)')}<div class="row">${field('lab', 'Laboratory (reports)')}${field('pages', 'Page x of y (e.g. 1 of 4)')}</div><button class="btn sec" style="margin-top:8px">Add typed document</button></form></div>
  ${A.documents.length ? A.documents.map(docCard).join('') : '<p class="muted">No document yet.</p>'}
  ${A.crossChecks.length ? `<div class="card"><h2>BETWEEN DOCUMENTS</h2>${list(A.crossChecks.map((f) => esc(f.detail)))}</div>` : ''}`;
}
