// market screen (extracted from app.js, no behaviour change).
import { esc, chip, money, list, field, selectOf, seg, quoteOf, VERDICT_TEXT } from '../dom.js';
import { S } from '../state.js';
import { MARKETPLACES } from '/core/amazon.js';

export function marketScreen(A, c) {
  const m = A.market; const az = c.context.channels.includes('amazon'); const last = c.amazon.observations.at(-1);
  return `<div class="card"><h2>AMAZON - WHAT YOU SAW</h2><p class="small muted">Nordla does not scrape Amazon. Type the listings you looked at (consumer price incl. VAT). A similar listing is NOT proof that you may sell this product.</p>
  <form data-form="obs">${selectOf('marketplace', 'Marketplace', MARKETPLACES.map((x) => [x, x.replace('amazon.', 'Amazon ').toUpperCase().replace('AMAZON ', 'Amazon ')]), last?.marketplace ?? 'amazon.be')}<div class="row">${field('price', 'Price shown (EUR)', '', 'inputmode="decimal" required')}${field('packQty', 'Pack of (units)', 1, 'inputmode="numeric"')}</div><div class="row">${field('asin', 'ASIN (if known)', '', 'autocapitalize="characters"')}${field('reviews', 'Reviews', '', 'inputmode="numeric"')}</div><div class="row">${field('rating', 'Rating (0-5)', '', 'inputmode="decimal"')}${field('title', 'Title / seller')}</div>${field('notes', 'Notes')}<button class="btn" style="margin-top:8px">Add and next</button></form></div>
  <div class="card"><h2>PRICES SEEN (per unit)</h2><table><tr><th>Marketplace</th><th class="n">Min</th><th class="n">Median</th><th class="n">Max</th></tr>${m.byMarketplace.map((x) => `<tr><td>${esc(x.marketplace)}<br><span class="muted small">${esc(x.status)}${x.freshness ? ` - ${esc(x.freshness)}` : ''}</span></td><td class="n">${esc(money(x.minMinor))}</td><td class="n">${esc(money(x.medianMinor))}</td><td class="n">${esc(money(x.maxMinor))}</td></tr>`).join('')}</table>${m.referencePriceMinor ? `<p>Median of observed listings: <b>${esc(money(m.referencePriceMinor))}</b> <button class="btn sec" data-act="useprice" data-key="${m.referencePriceMinor}" style="min-height:36px;padding:4px 10px">Use as selling price (OBSERVED)</button></p>` : ''}${list(m.caveats.map(esc))}
  ${c.amazon.observations.length ? `<h3>Entered</h3><table>${c.amazon.observations.map((o, i) => `<tr><td>${esc(o.marketplace)} ${esc(money(o.priceMinor))}${o.packQty > 1 ? ` /${o.packQty}` : ''}<br><span class="muted small">${esc([o.asin, o.reviews != null ? `${o.reviews} reviews` : null, o.rating != null ? `${o.rating}*` : null, o.notes].filter(Boolean).join(' - '))}</span></td><td class="n"><button class="btn danger" data-act="obs-remove" data-key="${i}" style="min-height:34px;padding:2px 8px">Remove</button></td></tr>`).join('')}</table>` : ''}</div>
  <div class="card"><h2>AMAZON READINESS</h2>${az ? `${chip('', A.amazon.status, A.amazon.status === 'READY' ? 'GREEN' : A.amazon.status === 'NOT_READY' ? 'RED' : A.amazon.status === 'UNKNOWN' ? 'UNKNOWN' : 'AMBER')}<div class="trait" style="margin-top:8px"><div class="nm">Category restricted / gated for you (checked in Seller Central)</div>${seg('amz', 'restricted', c.amazon.restricted ?? null)}</div>${list(A.amazon.notes.map(esc))}${A.amazon.items.length ? `<table>${A.amazon.items.map((i) => `<tr><td>${esc(i.label)}</td><td class="n"><span class="chip t-${i.coverage === 'PRESENT' ? 'GREEN' : i.coverage === 'OWN_ACTION' ? 'UNKNOWN' : 'RED'}">${esc(i.coverage.replace(/_/g, ' '))}</span></td></tr>`).join('')}</table>` : ''}` : '<p class="muted">Amazon is not a target channel: turn it on in Case.</p>'}</div>`;
}
