// money screen (extracted from app.js, no behaviour change).
import { esc, chip, money, list, field, selectOf, seg, quoteOf, VERDICT_TEXT } from '../dom.js';
import { S } from '../state.js';
import { INCOTERMS } from '/core/landed.js';
import { numbersInner } from '../numbers.js';

export function moneyScreen(A, c) {
  const q = quoteOf(c); const co = c.costs.costs ?? {}; const fx = c.costs.fx ?? {}; const iv = c.costs.importVat ?? {}; const sl = c.sale ?? {}; const sa = c.saleAmazon ?? {}; const L = A.landed; const E = A.economics;
  const lineOf = (k) => co[k]?.total ?? co[k]?.perUnit ?? '';
  return `<div class="card" id="money-live-card"><h2>RESULT (updates as you type)</h2><div id="money-live">${numbersInner(A, c)}</div></div>
  <div class="card"><h2>SUPPLIER QUOTE</h2><form data-form="quote"><div class="row">${field('unitPrice', 'Unit price', q.unitPrice ?? '', 'inputmode="decimal"')}${selectOf('currency', 'Currency', [['USD', 'USD'], ['CNY', 'CNY'], ['EUR', 'EUR']], q.currency ?? 'USD')}</div><div class="row">${field('qty', 'Quantity I would buy', q.qty ?? '', 'inputmode="numeric"')}${field('moq', 'Supplier MOQ', q.moq ?? '', 'inputmode="numeric"')}</div>${selectOf('incoterm', 'Incoterm', [['', '(not stated)'], ...Object.keys(INCOTERMS).map((k) => [k, k])], q.incoterm ?? '')}<div class="row">${field('leadTimeDays', 'Lead time (days)', q.leadTimeDays ?? '', 'inputmode="numeric"')}${field('carton', 'Carton (cm / kg / units)', q.carton ?? '')}</div><button class="btn" style="margin-top:8px">Save quote</button></form>${(c.quotes.at(-1)?.tiers ?? []).length ? `<p class="small muted">Price tiers from the supplier: ${esc(c.quotes.at(-1).tiers.map((t) => `${t.minQty} pcs: ${t.unitPrice}`).join(' / '))}. The unit price above follows the quantity. Typing a different price replaces the tiers.</p>` : ''}</div>
  <div class="card"><h2>IMPORT COSTS (EUR, whole order)</h2><p class="small muted">Leave blank = UNKNOWN. Nothing is assumed: an unknown critical cost gives INFORMATION INSUFFICIENT.</p><form data-form="costs"><div class="row">${field('fxRate', 'FX: EUR per 1 unit of currency', fx.rate ?? '', 'inputmode="decimal"')}${field('fxDate', 'FX date', fx.date ?? '')}</div><button type="button" class="btn sec" data-act="fx" style="min-height:36px;padding:4px 10px">Fetch today's ECB rate</button><div class="row">${field('freight', 'Freight (total)', lineOf('freight'), 'inputmode="decimal"')}${field('insurance', 'Insurance (total)', lineOf('insurance'), 'inputmode="decimal"')}</div><div class="row">${field('originCharges', 'Origin charges', lineOf('originCharges'), 'inputmode="decimal"')}${field('brokerage', 'Customs broker', lineOf('brokerage'), 'inputmode="decimal"')}</div><div class="row">${field('testing', 'Lab testing', lineOf('testing'), 'inputmode="decimal"')}${field('inspection', 'Inspection', lineOf('inspection'), 'inputmode="decimal"')}</div><div class="row">${field('labelling', 'Labelling / translation', lineOf('labelling'), 'inputmode="decimal"')}${field('epr', 'Recupel / Bebat / packaging', lineOf('epr'), 'inputmode="decimal"')}</div><div class="row">${field('inboundLogistics', 'Delivery to your shop / FBA', lineOf('inboundLogistics'), 'inputmode="decimal"')}${field('importVat', 'Import VAT %', iv.ratePct ?? '', 'inputmode="decimal"')}</div><label><input type="checkbox" name="vatRecoverable" ${iv.recoverable === false ? '' : 'checked'} style="width:auto;min-height:0"> import VAT is recoverable</label><p class="small muted">Amounts are treated as estimates (not quotes).</p><button class="btn" style="margin-top:8px">Save costs</button></form></div>
  <div class="card"><h2>SELLING SIDE</h2><form data-form="sale"><div class="row">${field('price', 'Selling price (incl. VAT)', sl.sellingPriceGross ?? '', 'inputmode="decimal"')}${field('vat', 'VAT %', sl.vatRatePct ?? 21, 'inputmode="decimal"')}</div>${selectOf('basis', 'This price is', [['TARGET', 'TARGET: the price I intend to charge'], ['OBSERVED', 'OBSERVED: a listing I saw'], ['ASSUMED', 'ASSUMED: a placeholder']], sl.priceBasis ?? 'TARGET')}${field('target', 'Target margin (% of price without VAT)', sl.targetContributionPct ?? '', 'inputmode="decimal"')}<button class="btn" style="margin-top:8px">Save</button></form>
  ${c.context.channels.includes('amazon') ? `<h3>Amazon fees (from Seller Central - never guessed)</h3><form data-form="amazon-sale"><div class="row">${field('aprice', 'Amazon price (incl. VAT)', sa.sellingPriceGross ?? '', 'inputmode="decimal"')}${field('avat', 'VAT %', sa.vatRatePct ?? 21, 'inputmode="decimal"')}</div><div class="row">${field('referral', 'Referral fee %', sa.lines?.find((l) => l.key === 'referral')?.value ?? '', 'inputmode="decimal"')}${field('fulfilment', 'FBA fee / unit EUR', sa.lines?.find((l) => l.key === 'fulfilment')?.value ?? '', 'inputmode="decimal"')}</div><button class="btn sec" style="margin-top:8px">Save Amazon</button></form>${A.economicsAmazon ? `<p class="small">Amazon: <b>${esc(A.economicsAmazon.status)}</b>${A.economicsAmazon.contributionMinor != null ? ` - contribution ${esc(money(A.economicsAmazon.contributionMinor))}${A.economicsAmazon.contributionIsUpperBound ? ' (UPPER BOUND)' : ''}` : ''}</p>` : ''}` : ''}</div>
  <div class="card"><h2>LANDED COST</h2>${chip('', L.status, L.status === 'COMPLETE' ? 'GREEN' : L.status === 'RANGE' ? 'AMBER' : 'RED')}${L.status === 'INFORMATION_INSUFFICIENT' ? `<p class="warn">Critical unknown: ${esc((L.criticalUnknown ?? []).join(', '))}</p>` : `<div class="big">${esc(money(L.totals.landedPerUnitEurMinor))}<span class="muted small"> per unit${L.totals.rangeEurMinor ? ` (range ${esc(money(L.totals.rangeEurMinor.perUnit.min))} - ${esc(money(L.totals.rangeEurMinor.perUnit.max))})` : ''}</span></div>`}
  <table>${(L.lines ?? []).map((l) => `<tr><td>${esc(l.key)}</td><td class="n"><span class="muted small">${esc(l.status)}</span> ${esc(money(l.totalMinor))}</td></tr>`).join('')}</table>${L.warnings?.length ? list(L.warnings.map(esc)) : ''}${E.contributionMinor != null ? `<h3>Per unit</h3><p>Contribution <b>${esc(money(E.contributionMinor))}</b>${E.contributionPct != null ? ` = ${(E.contributionPct * 100).toFixed(1)}% of net revenue` : ''}${E.breakEvenGrossMinor ? `; break-even selling price ${esc(money(E.breakEvenGrossMinor))}` : ''}</p>` : `<p class="muted">${esc(E.reason ?? '')}</p>`}</div>`;
}
