// rules screen (extracted from app.js, no behaviour change).
import { esc, chip, money, list, field, selectOf, seg, quoteOf, VERDICT_TEXT } from '../dom.js';
import { S } from '../state.js';

export function rulesScreen(A, c) {
  const rs = A.rules.results; const order = { APPLIES: 0, UNRESOLVED: 1, NOT_APPLICABLE: 2 };
  const sorted = [...rs].sort((a, b) => order[a.status] - order[b.status] || (b.severity === 'HIGH') - (a.severity === 'HIGH'));
  const s = A.safety; const cu = A.customs;
  const one = (r) => `<details ${r.status === 'APPLIES' && r.severity === 'HIGH' ? 'open' : ''}><summary>${esc(r.title)} <span class="chip t-${r.status === 'APPLIES' ? 'AMBER' : r.status === 'UNRESOLVED' ? 'UNKNOWN' : 'GREEN'}">${esc(r.status.replace(/_/g, ' '))}</span> ${r.jurisdiction !== 'EU' ? `<span class="chip">${esc(r.jurisdiction)}</span>` : ''} <span class="chip t-${r.review.status === 'VERIFIED_CURRENT' ? 'GREEN' : r.review.status === 'PRIMARY_TEXT_ONLY' ? 'AMBER' : 'RED'}" title="${esc(r.review.basis)}">rule review <b>${esc(r.review.status.replace(/_/g, ' '))}</b></span></summary><p class="small"><b>Rule review:</b> ${esc(r.review.status.replace(/_/g, ' '))}${r.reviewFreshness?.status === 'STALE' ? ' - STALE: re-check before relying on it' : ''} - checked ${esc(r.review.checkedAt)}. <b>Layer:</b> ${esc(r.layer)} - <b>${esc(r.materiality.replace(/_/g, ' '))}</b>, ${esc(r.scope)}.</p>
    <p class="small">${esc(r.review.interpretation)}</p>
    <p class="small muted"><b>Instruments:</b> ${r.review.instruments.map((i) => `${esc(i.name)}${i.consolidated ? ` [consolidated ${esc(i.consolidated)}]` : ''}${i.articles ? ` - ${esc(i.articles)}` : ''}`).join('; ')}<br><b>Dates:</b> ${esc((r.review.applicationDates ?? []).join(' | ') || 'none recorded')}<br><b>Uncertainty:</b> ${esc(r.review.uncertainty)}${r.review.pendingChange ? `<br><b>Pending change:</b> ${esc(r.review.pendingChange)}` : ''}</p>
    <p>${esc(r.why)}</p>${r.requiredEvidence.length && r.status !== 'NOT_APPLICABLE' ? `<table>${r.requiredEvidence.map((e) => `<tr><td>${esc(e.label)}<br><span class="muted small">${esc(e.requirement)}</span></td><td class="n"><span class="chip t-${e.coverage.status === 'PRESENT' ? 'GREEN' : e.coverage.status === 'OWN_ACTION' ? 'UNKNOWN' : 'RED'}">${esc(e.coverage.status.replace(/_/g, ' '))}</span></td></tr>`).join('')}</table>` : ''}
    <p class="small muted">Sources: ${r.sources.map((x) => `${x.url ? `<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a>` : esc(x.title)} [${esc(x.verification.replace(/_/g, ' '))}]`).join('; ') || 'none'}<br>${esc(r.sourceVerification.replace(/_/g, ' '))} - ${esc(r.freshness)} - rule ${esc(r.ruleVersion)}${r.requiresAuthorityConfirmation ? ' - REQUIRES EXPERT / AUTHORITY CONFIRMATION' : ''}</p>${r.notes ? `<p class="note">${esc(r.notes)}</p>` : ''}</details>`;
  return `<div class="card"><h2>CE MARKING</h2>${chip('', A.rules.ce?.status ?? 'CE_APPLICABILITY_UNRESOLVED', A.rules.ce?.status === 'CE_REQUIRED' ? 'AMBER' : A.rules.ce?.status === 'CE_NOT_APPLICABLE' ? 'GREEN' : 'UNKNOWN')}<p>${esc(A.rules.ce?.why ?? '')}</p><p class="small muted">A CE logo on a product or a listing proves nothing; the EU declaration of conformity and its evidence do.</p></div>
  <div class="card"><h2>EU SAFETY GATE</h2>${chip('', s.status, s.status === 'EXACT_MATCH' || s.status === 'PROBABLE_MATCH' ? 'RED' : s.status === 'SIMILAR_PRODUCT_RISK' ? 'AMBER' : s.status === 'NO_MATCH_FOUND' ? 'GREEN' : 'UNKNOWN')} ${chip('Data', A.dataMode.replace(/_/g, ' '), A.dataMode === 'LIVE_VERIFIED' ? 'GREEN' : A.dataMode === 'CACHED' ? 'AMBER' : 'RED')}
    ${s.note ? `<p>${esc(s.note)}</p>` : ''}${s.matches?.length ? list(s.matches.slice(0, 5).map((m) => `<b>${esc(m.basis.replace(/_/g, ' '))}</b> ${esc(m.alertNumber ?? '')} - ${esc(m.name ?? '')} ${esc(m.brand ?? '')} - ${esc((m.hazards ?? []).join(', '))}`)) : ''}<p class="small muted">${esc(s.source?.coverage ?? '')} ${esc(s.source?.attribution ?? '')}</p>
    <button class="btn" data-act="safety" ${S.busy === 'safety' || !S.token ? 'disabled' : ''}>${S.busy === 'safety' ? 'Checking...' : 'Refresh live evidence (Safety Gate)'}</button>${S.token ? `<p class="small muted">The cache is kept on this phone and matched here, so it also works offline (shown as CACHED).${S.A.safety.source?.newestPublication ? ` Newest weekly report ingested: ${esc(S.A.safety.source.newestPublication)}.` : ''}</p>` : '<p class="small muted">Add the access token (menu) to download the Safety Gate cache to this phone.</p>'}</div>
  <div class="card"><h2>CUSTOMS</h2><p class="warn">CUSTOMS CLASSIFICATION REQUIRES CONFIRMATION. The codes below are <b>HS/CN CANDIDATES</b>, not a classification. ${esc(cu.limitation)}</p><p><b>${esc(cu.codeLabel)}</b></p>${list(cu.candidates.map((h) => `HS/CN CANDIDATE <b>${esc(h.code)}</b> ${esc(h.desc)} <span class="muted">(${esc(h.confidence)})</span>`))}
    <form data-form="customs"><div class="row">${field('code', 'Candidate code you choose (stays unconfirmed)', cu.chosenCode ?? '')}${field('rate', 'Duty rate % (from your broker / TARIC)', cu.duty?.ratePct ?? '', 'inputmode="decimal"')}</div><div class="row">${field('origin', 'Origin', cu.duty?.origin ?? 'CN')}${field('source', 'Where the duty comes from', cu.duty?.source ?? '')}</div>${field('notes', 'Notes (anti-dumping? broker name?)', cu.duty?.notes ?? '')}<button class="btn sec" style="margin-top:8px">Save customs</button></form>${cu.duty?.ratePct != null ? '<p class="small"><b>Duty: USER PROVIDED</b>, not verified by Nordla. The code stays an HS/CN CANDIDATE.</p>' : ''}${cu.notes.length ? list(cu.notes.map(esc)) : ''}</div>
  <div class="card"><h2>RULES (${A.rules.summary.applies} apply, ${A.rules.summary.unresolved} unresolved)</h2>${sorted.map(one).join('')}</div>
  <div class="card"><h2>FRESHNESS</h2>${list(A.freshness.map((f) => `${esc(f.name)}: <b>${esc(f.status)}</b>${f.checkedAt ? ` (${esc(String(f.checkedAt).slice(0, 10))})` : ''}${f.mode ? ` - ${esc(f.mode.replace(/_/g, ' '))}` : ''}`))}</div>`;
}
