'use strict';
// French (Belgium) - primary language of the Finance dashboard. Keys are the English message ids used in app.js.
(function () {
  const messages = {
    // validation, errors
    'Required': 'Obligatoire', 'Enter a quantity (up to 3 decimals)': 'Saisissez une quantité (jusqu\'à 3 décimales)', 'Enter a unit price (up to 4 decimals)': 'Saisissez un prix unitaire (jusqu\'à 4 décimales)',
    'Choose a VAT rate': 'Choisissez un taux de TVA', 'Invalid discount': 'Remise invalide', 'Invalid date': 'Date invalide', 'Enter an amount like 12.34': 'Saisissez un montant du type 12,34',
    'Invalid email address': 'Adresse e-mail invalide', 'Invalid IBAN': 'IBAN invalide', 'Use a 2-letter country code': 'Utilisez un code pays à 2 lettres', 'Add at least one line': 'Ajoutez au moins une ligne',
    'Fix the items listed below first': 'Corrigez d\'abord les points listés ci-dessous', 'This action is not allowed in the current status': 'Cette action n\'est pas autorisée dans l\'état actuel',
    'This shop/POS order already has an active invoice': 'Cette commande boutique/caisse a déjà une facture active', 'The document changed meanwhile: reload and retry': 'Le document a changé entre-temps : rechargez et réessayez',
    'Issued documents cannot be edited: create a credit note instead': 'Un document émis ne peut plus être modifié : créez un avoir', 'The payment is higher than the amount still due': 'Le paiement dépasse le solde restant dû',
    'The credit is higher than what can still be credited': 'L\'avoir dépasse ce qui peut encore être crédité', 'This company is already in the directory': 'Cette société figure déjà dans l\'annuaire',
    'Wrong access token': 'Jeton d\'accès incorrect', 'Too many attempts. Wait a few minutes.': 'Trop de tentatives. Patientez quelques minutes.', 'Please log in again': 'Veuillez vous reconnecter',
    'Confirm the VAT treatment': 'Confirmez le traitement de la TVA', 'Choose whether this invoice is linked to a shop order or a new B2B sale': 'Indiquez si cette facture est liée à une commande de la boutique ou à une nouvelle vente B2B',
    'Enter the customer VAT or enterprise number': 'Saisissez le numéro de TVA ou d\'entreprise du client', 'Complete your company details in Settings': 'Complétez les données de votre société dans les Paramètres',
    'Add your VAT number in Settings': 'Ajoutez votre numéro de TVA dans les Paramètres', 'Add your IBAN in Settings (or payment terms on the invoice)': 'Ajoutez votre IBAN dans les Paramètres (ou les conditions de paiement sur la facture)',
    'Set a due date': 'Indiquez une date d\'échéance', 'Select the shop/POS order to link': 'Sélectionnez la commande boutique/caisse à lier', 'The linked order was not found': 'La commande liée est introuvable',
    'Give a reason for the credit note': 'Indiquez le motif de l\'avoir', 'Line {0}: {1}': 'Ligne {0} : {1}', 'Customer address: {0} is missing': 'Adresse du client : {0} manquant(e)',
    'This looks like a shop sale that is not linked. Link it, or confirm it is a separate sale.': 'Cela ressemble à une vente en boutique non liée. Liez-la, ou confirmez qu\'il s\'agit d\'une vente distincte.',
    'street': 'rue', 'postalcode': 'code postal', 'city': 'ville', 'countrycode': 'pays', 'Something went wrong': 'Une erreur est survenue',
    // statuses and types
    'Draft': 'Brouillon', 'Ready for approval': 'À approuver', 'Issued': 'Émise', 'Sent': 'Envoyée', 'Partially paid': 'Partiellement payée', 'Paid': 'Payée', 'Overdue': 'En retard', 'Credited': 'Créditée',
    'Cancelled': 'Annulée', 'Accepted': 'Accepté', 'Rejected': 'Refusé', 'Converted': 'Converti', 'Invoice': 'Facture', 'Quote': 'Devis', 'Credit note': 'Avoir',
    'Domestic - VAT charged': 'National - TVA appliquée', 'Intra-EU B2B - VAT exempt': 'B2B intracommunautaire - exonéré de TVA', 'Reverse charge (customer accounts for VAT)': 'Autoliquidation (le client déclare la TVA)',
    'Export outside the EU': 'Exportation hors UE', 'VAT-exempt (small business scheme)': 'Exonéré de TVA (franchise des petites entreprises)',
    'COMPLETE': 'COMPLET', 'PARTIAL': 'PARTIEL', 'CLEAN': 'CONFORME', 'REVIEW_REQUIRED': 'À VÉRIFIER', 'NOT CONFIGURED': 'NON CONFIGURÉ',
    // relative dates
    '{0} day late': '{0} jour de retard', '{0} days late': '{0} jours de retard', 'Due today': 'Échéance aujourd\'hui', 'Due in {0} day': 'Échéance dans {0} jour', 'Due in {0} days': 'Échéance dans {0} jours',
    // shell
    'Overview': 'Vue d\'ensemble', 'Invoices': 'Factures', 'Quotes': 'Devis', 'Companies': 'Sociétés', 'Payments': 'Paiements', 'Accountant pack': 'Pack comptable', 'Settings': 'Paramètres', 'Finance': 'Finance',
    'New invoice': 'Nouvelle facture', 'Peppol: not configured': 'Peppol : non configuré', 'Nothing is sent externally': 'Rien n\'est envoyé à l\'extérieur', 'Log out': 'Se déconnecter',
    'Access token': 'Jeton d\'accès', 'Enter the access token stored in your .env file (FINANCE_DASHBOARD_TOKEN).': 'Saisissez le jeton d\'accès de votre fichier .env (FINANCE_DASHBOARD_TOKEN).', 'Log in': 'Se connecter',
    'Interface language': 'Langue de l\'interface',
    // overview
    'Good morning': 'Bonjour', 'Good afternoon': 'Bon après-midi', 'Good evening': 'Bonsoir', 'Here is what needs your attention.': 'Voici ce qui demande votre attention.', 'New quote': 'Nouveau devis',
    'Finish your setup before issuing real invoices:': 'Terminez la configuration avant d\'émettre de vraies factures :', '{0} setting(s) missing.': '{0} paramètre(s) manquant(s).', 'Open settings': 'Ouvrir les paramètres',
    'Awaiting your approval': 'En attente de votre approbation', 'Review and issue': 'Vérifier et émettre', 'Nothing to approve': 'Rien à approuver', 'Overdue invoices': 'Factures en retard',
    '{0} {1} to collect': '{0} {1} à encaisser', 'Nothing is late': 'Rien n\'est en retard', 'Accepted quotes to convert': 'Devis acceptés à convertir', '{0} quote(s) awaiting response': '{0} devis en attente de réponse',
    'Unpaid invoices': 'Factures impayées', '{0} {1} outstanding': '{0} {1} en attente', 'Outstanding': 'Encours', '{0} unpaid invoice(s)': '{0} facture(s) impayée(s)', '{0} invoice(s)': '{0} facture(s)',
    'Paid this month': 'Payé ce mois-ci', '{0} payment(s)': '{0} paiement(s)', 'Not yet due': 'Pas encore échues', '0-7 days': '0-7 jours', '8-30 days': '8-30 jours', '31-60 days': '31-60 jours', '60+ days': '60+ jours',
    'Ageing of unpaid invoices': 'Ancienneté des factures impayées', 'Open payments': 'Ouvrir les paiements', 'All caught up': 'Tout est à jour', 'No unpaid invoices right now.': 'Aucune facture impayée pour le moment.',
    '{0} inv.': '{0} fact.', 'To approve': 'À approuver', 'Nothing overdue': 'Rien en retard', 'Every invoice is on time.': 'Toutes les factures sont dans les temps.', 'Waiting for you': 'En attente de vous',
    'Nothing is waiting': 'Rien n\'attend', 'Drafts and quotes will show up here.': 'Les brouillons et les devis apparaîtront ici.', 'Accountant pack - last closed quarter': 'Pack comptable - dernier trimestre clôturé',
    'Checking...': 'Vérification…', 'Open the pack': 'Ouvrir le pack', 'Retail data is not available.': 'Les données de vente ne sont pas disponibles.', '{0} anomaly(ies)': '{0} anomalie(s)', 'Pack status unavailable.': 'État du pack indisponible.',
    // lists
    'All': 'Toutes', 'Proposals for your customers.': 'Propositions pour vos clients.', 'Everything you have issued or are preparing.': 'Tout ce que vous avez émis ou préparez.',
    'Search quotes by customer or number': 'Rechercher un devis par client ou numéro', 'Search invoices by customer or number': 'Rechercher une facture par client ou numéro', 'No match': 'Aucun résultat',
    'No quotes yet': 'Aucun devis pour l\'instant', 'No invoices yet': 'Aucune facture pour l\'instant', 'Try another word or status.': 'Essayez un autre mot ou un autre statut.', 'Create your first one in a minute.': 'Créez la première en une minute.',
    '{0} still due': '{0} restant dû', 'Valid until {0}': 'Valable jusqu\'au {0}',
    // company search
    'Belgian company register (KBO/BCE)': 'Registre belge des sociétés (BCE)', 'EU VIES (official VAT service)': 'VIES UE (service officiel de TVA)', 'OpenPeppol Directory': 'Annuaire OpenPeppol', 'your company directory': 'votre annuaire de sociétés',
    'Belgian company register (KBO/BCE via CBEAPI)': 'Registre belge des sociétés (BCE via CBEAPI)', 'Your company directory': 'Votre annuaire de sociétés',
    'Source: entered by hand.': 'Source : saisi à la main.', 'Source: {0}': 'Source : {0}', 'VAT number confirmed': 'numéro de TVA confirmé', 'no active VAT registration found (VAT number left empty)': 'aucun assujettissement actif trouvé (numéro de TVA laissé vide)',
    'VAT could not be checked (VAT number left empty)': 'TVA non vérifiable (numéro de TVA laissé vide)', 'then edited by you': 'puis modifié par vous', 'SOLE TRADER / PERSONAL DATA': 'INDÉPENDANT / DONNÉES PERSONNELLES',
    'Search company name or VAT / enterprise number': 'Rechercher une société par nom ou numéro de TVA / d\'entreprise', 'Check the fields below: you can still correct them.': 'Vérifiez les champs ci-dessous : vous pouvez encore les corriger.',
    'Filled in from: {0}. Check the fields below: you can still correct them.': 'Renseigné depuis : {0}. Vérifiez les champs ci-dessous : vous pouvez encore les corriger.',
    'Type a company name, or a VAT / enterprise number.': 'Saisissez un nom de société ou un numéro de TVA / d\'entreprise.', 'Searching...': 'Recherche…', 'Number kept. Complete the other fields by hand.': 'Numéro conservé. Complétez les autres champs à la main.',
    'Use this number and complete by hand': 'Utiliser ce numéro et compléter à la main', 'select it to fill in what is available (the address may be missing)': 'sélectionnez-la pour remplir ce qui est disponible (l\'adresse peut manquer)',
    'Find the company': 'Trouver la société', 'Search': 'Rechercher', 'Type a name or a VAT / enterprise number. Or skip this and fill the fields by hand.': 'Saisissez un nom ou un numéro de TVA / d\'entreprise. Ou passez et remplissez les champs à la main.',
    // product search
    'Stock n/a': 'Stock n.d.', 'Out of stock': 'Rupture de stock', 'Low: {0}': 'Bas : {0}', '{0} in stock': '{0} en stock', 'Search product name, variant or SKU': 'Rechercher un produit, une variante ou un SKU',
    'Type at least 2 characters: a product name, variant or SKU.': 'Saisissez au moins 2 caractères : un nom de produit, une variante ou un SKU.',
    'No product found in the catalogue. Use "+ Add custom line" for a service or a special item.': 'Aucun produit trouvé dans le catalogue. Utilisez « + Ajouter une ligne libre » pour un service ou un article spécial.',
    '{0} matches': '{0} résultats', '{0} match': '{0} résultat', 'SKU {0}': 'SKU {0}', 'No SKU': 'Sans SKU', 'incl. VAT': 'TVAC', 'excl. VAT': 'HTVA', 'Search failed.': 'La recherche a échoué.', 'Close': 'Fermer',
    // totals and lines
    'Live summary': 'Récapitulatif en direct', 'Complete the lines to see totals.': 'Complétez les lignes pour voir les totaux.', 'Add lines to see totals.': 'Ajoutez des lignes pour voir les totaux.', 'Subtotal excl. VAT': 'Sous-total HTVA',
    'VAT {0}% on {1}': 'TVA {0} % sur {1}', 'Total VAT': 'Total TVA', 'Total incl. VAT': 'Total TVAC', 'Rounding adjustment': 'Ajustement d\'arrondi', 'Amount to pay': 'Montant à payer', 'Amount due': 'Montant dû',
    // Homepage "Create an invoice" preview card (real latest-invoice data, see invoicePreviewNode() in app.js).
    'VAT {0}%': 'TVA {0} %', 'Blank template': 'Modèle vierge', '{0} more line': '{0} ligne supplémentaire', '{0} more lines': '{0} lignes supplémentaires', 'Preview unavailable.': 'Aperçu indisponible.',
    'Explicit rounding (EN 16931) so the catalogue price stays exactly as published.': 'Arrondi explicite (EN 16931) : le prix du catalogue reste exactement celui publié.', 'Calculated by the finance engine, not by this page.': 'Calculé par le moteur financier, pas par cette page.',
    'VAT ?': 'TVA ?', 'Catalogue {0} incl. VAT': 'Catalogue {0} TVAC', '→ {0} excl. VAT': '→ {0} HTVA', 'Catalogue price excl. VAT': 'Prix catalogue HTVA', 'Catalogue price kept': 'Prix catalogue conservé',
    'Price override (excl. VAT)': 'Prix modifié (HTVA)', 'More than in stock': 'Plus que le stock', 'Confirm VAT rate': 'Confirmez le taux de TVA', 'Change product': 'Changer de produit', 'Search product': 'Rechercher un produit',
    'Use catalogue price': 'Utiliser le prix catalogue', 'Make custom': 'Passer en ligne libre', 'Remove line': 'Supprimer la ligne', 'Description': 'Description', 'Custom line: describe the service or item': 'Ligne libre : décrivez le service ou l\'article',
    'Custom line': 'Ligne libre', 'Stock': 'Stock', 'Qty': 'Qté', 'Unit price excl. VAT': 'Prix unitaire HTVA', 'Discount': 'Remise', 'Line total excl. VAT': 'Total ligne HTVA',
    // customer
    'Edit details': 'Modifier les détails', 'Change customer': 'Changer de client', 'Company from your directory.': 'Société de votre annuaire.', 'Detach and edit manually': 'Détacher et modifier à la main', 'Company name': 'Nom de la société',
    'VAT number': 'Numéro de TVA', 'Enterprise number': 'Numéro d\'entreprise', 'Street and number': 'Rue et numéro', 'Postal code': 'Code postal', 'City': 'Ville', 'Country': 'Pays', 'Email (optional)': 'E-mail (facultatif)',
    'Stored only if you enter it. Not needed for the invoice.': 'Enregistré seulement si vous le saisissez. Inutile pour la facture.', 'Save this company to my directory': 'Enregistrer cette société dans mon annuaire', 'Done': 'Terminé',
    // revenue basis
    'New B2B sale (outside the shop)': 'Nouvelle vente B2B (hors boutique)', 'This is ADDITIVE revenue: it is counted on top of your shop and POS sales.': 'Il s\'agit d\'un chiffre d\'affaires ADDITIONNEL : il s\'ajoute à vos ventes boutique et caisse.',
    'Invoice for an existing shop / POS order': 'Facture pour une commande boutique / caisse existante', 'This invoice does NOT create additional revenue: the sale is already counted from the shop. Each order can have one active invoice.': 'Cette facture ne crée PAS de chiffre d\'affaires supplémentaire : la vente est déjà comptée par la boutique. Chaque commande peut avoir une facture active.',
    'Linked to order {0}. No additional revenue will be counted.': 'Liée à la commande {0}. Aucun chiffre d\'affaires supplémentaire ne sera compté.', 'Choose the order below.': 'Choisissez la commande ci-dessous.', 'Change order': 'Changer de commande', 'Find the order': 'Trouver la commande',
    'Only if the system warns that this looks like a shop sale: confirm it is a separate sale.': 'Seulement si le système signale une vente boutique : confirmez qu\'il s\'agit d\'une vente distincte.', 'Order number or product...': 'Numéro de commande ou produit…',
    'Select the shop / POS order': 'Sélectionner la commande boutique / caisse', 'From': 'Du', 'Amount from': 'Montant de', 'Amount to': 'Montant à', 'Order': 'Commande', 'Date': 'Date', 'Channel': 'Canal', 'Items': 'Articles', 'Total': 'Total',
    'refunded {0}': 'remboursé {0}', 'Invoiced {0}': 'Facturée {0}', 'Select': 'Sélectionner', 'No matching orders.': 'Aucune commande correspondante.',
    // VAT
    'VAT treatment': 'Traitement de la TVA', 'Your confirmation': 'Votre confirmation', 'I confirm this VAT treatment applies to this document': 'Je confirme que ce traitement de la TVA s\'applique à ce document', 'Legal mention printed on the document': 'Mention légale imprimée sur le document',
    'e.g. VAT reverse charge - article 51 par. 2 ...': 'p. ex. Autoliquidation de la TVA - article 51 §2 …', 'Required for this treatment. The system does not decide which text is legally correct: you do.': 'Requis pour ce traitement. Le système ne décide pas quel texte est juridiquement correct : c\'est à vous de le faire.',
    // form
    'Submitted for approval': 'Soumis pour approbation', 'Saved as draft. Fix the listed items to submit.': 'Enregistré en brouillon. Corrigez les points listés pour soumettre.', 'Draft saved': 'Brouillon enregistré', 'Before you save': 'Avant d\'enregistrer',
    'Customer identified': 'Client identifié', 'Lines with prices': 'Lignes avec prix', 'VAT treatment confirmed': 'Traitement de la TVA confirmé', 'Revenue basis chosen': 'Base de revenu choisie', 'Customer': 'Client', 'Dates and terms': 'Dates et conditions',
    'Issue {0} · {1}': 'Émission {0} · {1}', 'Issue date': 'Date d\'émission', 'Valid until': 'Valable jusqu\'au', 'Due date': 'Date d\'échéance', 'Leave empty to use the payment terms': 'Laissez vide pour utiliser les conditions de paiement',
    'Payment terms (days)': 'Délai de paiement (jours)', 'Currency': 'Devise', 'Commercial terms': 'Conditions commerciales', 'Payment terms text': 'Texte des conditions de paiement', 'Document language': 'Langue du document',
    'Francais': 'Français', 'Français': 'Français', 'Nederlands': 'Nederlands', 'English': 'English', 'Revenue basis': 'Base de revenu', 'Lines': 'Lignes', 'Products come from your catalogue, prices from the shop': 'Les produits viennent de votre catalogue, les prix de la boutique',
    'Product': 'Produit', '+ Add product': '+ Ajouter un produit', '+ Add custom line': '+ Ajouter une ligne libre', 'Notes': 'Notes', 'Printed on the document': 'Imprimées sur le document', 'Notes (printed on the document)': 'Notes (imprimées sur le document)',
    'Save draft': 'Enregistrer le brouillon', 'Save and review': 'Enregistrer et vérifier', 'Unit price': 'Prix unitaire', 'Net': 'HTVA', 'linked - no extra revenue': 'lié - pas de revenu en plus', 'standalone - additive': 'autonome - additionnel',
    'today': 'aujourd\'hui', 'no terms': 'sans conditions', '{0} days': '{0} jours',
    // document detail
    'Edit draft': 'Modifier le brouillon', 'Submit for approval': 'Soumettre pour approbation', 'Send quote': 'Envoyer le devis', 'This numbers the quote ({0}) and locks it. Send the PDF to your customer yourself; the system sends nothing.': 'Cela numérote le devis ({0}) et le verrouille. Envoyez le PDF à votre client vous-même ; le système n\'envoie rien.',
    'Number and lock': 'Numéroter et verrouiller', 'Quote numbered': 'Devis numéroté', 'Mark as sent': 'Marquer comme envoyé', 'Quote accepted': 'Devis accepté', 'Quote rejected': 'Devis refusé', 'Invoice draft created from the quote': 'Brouillon de facture créé à partir du devis',
    'Convert to invoice': 'Convertir en facture', 'Record that you have sent this document to your customer. The system does not send anything.': 'Indiquez que vous avez envoyé ce document à votre client. Le système n\'envoie rien.', 'Mark sent': 'Marquer envoyé', 'Marked as sent': 'Marqué comme envoyé',
    'Add payment': 'Ajouter un paiement', 'Create credit note': 'Créer un avoir', 'Cancel draft': 'Annuler le brouillon', 'This draft will be cancelled. No number is used.': 'Ce brouillon sera annulé. Aucun numéro n\'est utilisé.', 'Draft cancelled': 'Brouillon annulé',
    'Download PDF': 'Télécharger le PDF', 'Peppol/UBL file': 'Fichier Peppol/UBL', 'Ready': 'Prêt', 'Review before you approve.': 'Vérifiez avant d\'approuver.',
    'Approving issues the document, assigns its number ({0}) and freezes it. Afterwards it can only be corrected with a credit note. Nothing is sent to your customer.': 'Approuver émet le document, lui attribue son numéro ({0}) et le fige. Ensuite il ne peut être corrigé que par un avoir. Rien n\'est envoyé à votre client.',
    'next in sequence': 'suivant dans la séquence', 'Approve and issue': 'Approuver et émettre', 'Issue this {0} now? It will receive the next number and cannot be edited afterwards.': 'Émettre ce document ({0}) maintenant ? Il recevra le prochain numéro et ne pourra plus être modifié.',
    'Approve': 'Approuver', 'Modify': 'Modifier',
    '{0} {1}': '{0} {1}', 'not numbered yet': 'pas encore numéroté', '2-digit': '2-digit', '{0}: {1}': '{0} : {1}',
    'Cash position': 'Solde de trésorerie', 'Bank + cash': 'Banque + caisse', 'Connect a bank to see this': 'Connectez une banque pour voir ceci',
    'Amount to collect': 'Factures en attente', 'Supplier bills due': 'Factures fournisseurs à payer', '{0} bill(s) to pay': '{0} facture(s) à payer',
    'Critical actions': 'Actions critiques', 'need your attention': 'nécessitent votre attention', 'all clear': 'rien à signaler',
    'Trends': 'Tendances', 'Payments received - last 7 days': 'Paiements reçus - 7 derniers jours', 'Invoices paid vs overdue': 'Factures payées vs en retard',
    'Recent activity': 'Activité récente', 'Loading...': 'Chargement...', 'Nothing yet': 'Rien pour l\'instant',
    'Issued invoices, payments and credit notes will show up here.': 'Les factures émises, paiements et avoirs apparaîtront ici.', 'Activity unavailable.': 'Activité indisponible.',
    'a document': 'un document', '{0} issued': '{0} émis(e)', '{0} marked as sent': '{0} marqué(e) comme envoyé(e)', '{0} sent': '{0} envoyé(e)',
    'Payment of {0} received on {1}': 'Paiement de {0} reçu sur {1}', 'Payment received on {0}': 'Paiement reçu sur {0}',
    // Homepage Activité récente: title-only variants (no document reference appended - it moves to the row's
    // own muted subtitle line, see activityRow() in app.js) so the title stays a single short line.
    'Payment of {0} received': 'Paiement de {0} reçu', 'Payment received': 'Paiement reçu',
    '{0} created': '{0} créé(e)',
    '{0} accepted': '{0} accepté(e)', '{0} rejected': '{0} refusé(e)', '{0} submitted for approval': '{0} soumis(e) pour approbation',
    '{0} cancelled': '{0} annulé(e)', '{0} returned to draft': '{0} remis(e) en brouillon', '{0} status updated': 'Statut de {0} mis à jour',
    'Impact of this credit note': 'Impact de cet avoir', 'Original invoice': 'Facture d\'origine', 'Credit note amount': 'Montant de l\'avoir', 'Effect on balance': 'Effet sur le solde',
    '{0} owed on {1}': '{0} dû sur {1}', 'VAT impact': 'Impact TVA', '{0} VAT reversed': '{0} de TVA annulée', 'Restock decision': 'Décision de restockage', 'Refund': 'Remboursement',
    'Not linked yet': 'Pas encore lié', 'Not applicable (original sale did not decrement stock)': 'Non applicable (la vente d\'origine n\'a pas décrémenté le stock)',
    'Decision pending': 'Décision en attente', 'Restocked': 'Restocké', 'Restock approved (processing)': 'Restockage approuvé (en cours)', 'Not restocked (merchant declined)': 'Non restocké (refusé par le marchand)',
    'Not tracked separately - deducts from what the customer owes': 'Non suivi séparément - vient en déduction de ce que doit le client',
    'Reason: {0}': 'Motif : {0}', 'Draft - this impact applies once the credit note is approved and issued.': 'Brouillon - cet impact s\'applique une fois l\'avoir approuvé et émis.',
    'Customers': 'Clients', 'Search an invoice, a client, a supplier...': 'Rechercher une facture, un client, un fournisseur...', 'Finance navigation': 'Navigation Finance', 'Notifications': 'Notifications',
    'Here is a summary of your financial activity.': 'Voici la synthèse de votre activité financière.', 'vs. last month': 'vs. mois dernier', 'Revenue': 'Chiffre d\'affaires', 'Expenses': 'Dépenses',
    'Cash-flow unavailable.': 'Trésorerie indisponible.', 'Last 3 months': '3 derniers mois', 'Last 6 months': '6 derniers mois', 'Last 12 months': '12 derniers mois',
    'Real inflows, outflows and running balance': 'Entrées, sorties et solde cumulé réels', 'Inflows': 'Entrées', 'Outflows': 'Sorties', 'Cumulative balance': 'Solde cumulé',
    'Quick actions': 'Actions rapides', 'Create an invoice': 'Créer une facture', 'Add an expense': 'Ajouter une dépense', 'New client': 'Nouveau client', 'Import a bank statement': 'Importer un relevé bancaire',
    'Upcoming due dates': 'Échéances à venir', 'See all': 'Tout voir', '{0} day(s) late': 'En retard de {0} jour(s)', 'Due {0}': 'Échéance {0}', 'Nothing coming up.': 'Rien à venir.',
    'Client invoices': 'Factures clients', 'tab2 {}': 'tab2 {}', 'Nothing here.': 'Rien ici.', 'Invoice no.': 'N° de facture', 'Bank accounts': 'Comptes bancaires',
    'Connected account': 'Compte connecté', 'No bank account connected': 'Aucun compte bancaire connecté', 'Read-only: no payment can ever be initiated.': 'Lecture seule : aucun paiement ne peut être initié.',
    'Connect a read-only account': 'Connecter un compte en lecture seule', 'Breakdown by supplier': 'Répartition par fournisseur',
    'var(--accent)': 'var(--accent)', 'var(--warm)': 'var(--warm)', 'var(--info)': 'var(--info)', 'var(--ok)': 'var(--ok)', 'var(--muted)': 'var(--muted)', 'rotate(-90 {} {})': 'rotate(-90 {} {})',
    'No supplier invoices yet.': 'Pas encore de factures fournisseurs.', 'balance': 'solde', 'Client': 'Client', '{0} {1},': '{0} {1},', '{0},': '{0},',
    'tab2 {0}': 'tab2 {0}', 'rotate(-90 {0} {0})': 'rotate(-90 {0} {0})',
    'Connect the bank': 'Connecter la banque', '{0} unpaid invoice': '{0} facture impayée', '{0} unpaid invoices': '{0} factures impayées',
    'Revenue − recorded expenses: {0}': 'CA − dépenses enregistrées : {0}', '(not an accounting net profit figure - no VAT, depreciation or accruals)': '(pas un résultat comptable - hors TVA, amortissements et régularisations)',
    'Invoice status': 'Statut des factures', '{0} invoice': '{0} facture', '{0} invoices': '{0} factures',
    'Not enough history yet': 'Pas encore assez d\'historique', 'Record payments and supplier bills to see real cash movement here.': 'Enregistrez des paiements et des factures fournisseurs pour voir ici de vrais mouvements de trésorerie.',
    'Real inflows, outflows and running documented balance': 'Entrées, sorties et solde cumulé documentés réels', 'Revenue vs. expenses': 'Chiffre d\'affaires vs dépenses',
    'Due dates': 'Échéances', 'Nothing overdue.': 'Rien en retard.', 'Upcoming': 'À venir', 'Nothing due soon.': 'Rien à venir prochainement.',
    'Last sync: {0}': 'Dernière synchro : {0}', 'Latest transactions': 'Dernières transactions', '(no counterparty)': '(sans contrepartie)', 'Connect bank': 'Connecter une banque',
    '{0} - your only supplier so far. A breakdown becomes useful once you have more than one.': '{0} - votre seul fournisseur pour l\'instant. Une répartition devient utile à partir de deux fournisseurs.',
    // Homepage "Repartition des depenses" card (real supplier-invoice totals, see /api/overview/expense-breakdown).
    'Expense breakdown': 'Répartition des dépenses', 'All time': 'Depuis le début', 'A breakdown will appear here once expenses are recorded.': 'Une répartition apparaîtra ici une fois des dépenses enregistrées.',
    'Your expenses are down {0}% from last month.': 'Vos dépenses sont en baisse de {0} % par rapport au mois dernier.', 'Your expenses are up {0}% from last month.': 'Vos dépenses sont en hausse de {0} % par rapport au mois dernier.',
    'Breakdown unavailable.': 'Répartition indisponible.', 'No expenses documented': 'Aucune dépense documentée',
    'LINKED: this invoice documents an existing shop/POS sale. It does NOT create additional revenue.': 'LIÉ : cette facture documente une vente boutique/caisse existante. Elle ne crée pas de chiffre d\'affaires supplémentaire.',
    'STANDALONE: this is a new B2B sale outside the shop. It is ADDITIVE revenue.': 'AUTONOME : il s\'agit d\'une nouvelle vente B2B en dehors de la boutique. Ce chiffre d\'affaires s\'ajoute au reste.',
    'Returned to draft': 'Remis en brouillon', 'Reject': 'Refuser', 'The draft will be cancelled. No number is used.': 'Le brouillon sera annulé. Aucun numéro n\'est utilisé.', 'Not ready to issue:': 'Pas prêt à être émis :',
    'INTEGRITY WARNING: the stored fingerprint does not match this document. Do not use it and contact support.': 'AVERTISSEMENT D\'INTÉGRITÉ : l\'empreinte enregistrée ne correspond pas à ce document. Ne l\'utilisez pas et contactez le support.',
    'Seller': 'Vendeur', 'Name': 'Nom', 'Address': 'Adresse', 'VAT / no.': 'TVA / n°', 'Email': 'E-mail', 'Details': 'Détails', 'Number': 'Numéro', '(assigned on approval: {0})': '(attribué à l\'approbation : {0})', 'next': 'prochain',
    'Payment terms': 'Conditions de paiement', 'Legal mention': 'Mention légale', 'Language': 'Langue', 'Related': 'Lié', 'Converted to': 'Converti en', 'Invoice {0}': 'Facture {0}', '(draft)': '(brouillon)', 'Shop/POS order': 'Commande boutique/caisse',
    'Totals': 'Totaux', 'Amount': 'Montant', 'Method': 'Méthode', 'Reference': 'Référence', 'Credit notes': 'Avoirs', 'PDF preview': 'Aperçu PDF', '(draft watermark)': '(filigrane brouillon)', 'Show preview': 'Afficher l\'aperçu', 'Audit trail': 'Journal d\'audit',
    'When': 'Quand', 'Action': 'Action', 'Status': 'Statut', 'Peppol: NOT CONFIGURED. Structured invoices can be prepared, but nothing is transmitted until a provider is selected.': 'Peppol : NON CONFIGURÉ. Des factures structurées peuvent être préparées, mais rien n\'est transmis tant qu\'aucun prestataire n\'est choisi.',
    'Cancel': 'Annuler', 'Bank transfer': 'Virement bancaire', 'Cash': 'Espèces', 'Card': 'Carte', 'Other': 'Autre', 'Bank reference (optional)': 'Référence bancaire (facultatif)', 'Note (optional)': 'Note (facultatif)', 'Add a payment': 'Ajouter un paiement',
    'Still due: {0} {1}': 'Reste dû : {0} {1}', 'Date paid': 'Date de paiement', 'Note': 'Note', 'Payment recorded': 'Paiement enregistré', 'Record payment': 'Enregistrer le paiement', 'Reason (required)': 'Motif (obligatoire)', 'Remove': 'Retirer',
    'Create a credit note': 'Créer un avoir', 'A credit note corrects an issued invoice. The invoice itself is never changed.': 'Un avoir corrige une facture émise. La facture elle-même n\'est jamais modifiée.', 'Reason': 'Motif', 'Credit the whole invoice': 'Créditer toute la facture',
    'Credit note draft created': 'Brouillon d\'avoir créé', 'Create draft': 'Créer le brouillon',
    // companies
    'Add a company': 'Ajouter une société', 'Search name or VAT number...': 'Rechercher un nom ou un numéro de TVA…', 'Company': 'Société', 'Source': 'Source',
    'No companies yet. They are added automatically when you create an invoice, or click "Add a company".': 'Aucune société pour l\'instant. Elles sont ajoutées automatiquement lors de la création d\'une facture, ou cliquez sur « Ajouter une société ».',
    'Country (2 letters)': 'Pays (2 lettres)', 'This company is already in your directory': 'Cette société figure déjà dans votre annuaire', 'Edit company': 'Modifier la société', 'Company saved': 'Société enregistrée', 'Save': 'Enregistrer',
    '{0} - source: {1}': '{0} - source : {1}', 'no number': 'sans numéro', 'Edit': 'Modifier', 'Outstanding ({0})': 'Encours ({0})', 'Paid so far ({0} payment(s){1})': 'Payé à ce jour ({0} paiement(s){1})', ', last {0}': ', dernier le {0}',
    'Peppol ID': 'Identifiant Peppol', 'Credit scoring': 'Scoring de crédit', 'Not implemented (no solvency provider)': 'Non implémenté (aucun prestataire de solvabilité)', 'Documents': 'Documents', 'Type': 'Type', 'No documents yet.': 'Aucun document pour l\'instant.',
    // payments
    'Payments and receivables': 'Paiements et créances', 'No reminders are sent automatically.': 'Aucun rappel n\'est envoyé automatiquement.', 'Unpaid': 'Impayé', 'Due soon': 'Bientôt dû', '{0}: {1} invoice(s) ({2})': '{0} : {1} facture(s) ({2})',
    'Ageing (days past due)': 'Ancienneté (jours de retard)', 'Open invoices': 'Factures ouvertes', 'Due': 'Échéance', 'Days late': 'Jours de retard', 'Still due': 'Reste dû', 'No open invoices.': 'Aucune facture ouverte.',
    'Open an invoice from the Invoices page to register a payment.': 'Ouvrez une facture depuis la page Factures pour enregistrer un paiement.', 'Shop/POS sales come from the validated retail figures; only standalone B2B invoices are added.': 'Les ventes boutique/caisse viennent des chiffres retail validés ; seules les factures B2B autonomes sont ajoutées.',
    // pack
    'Generate pack': 'Générer le pack', 'Generating...': 'Génération…', 'Reconciliation: {0}': 'Rapprochement : {0}', 'generated {0}': 'généré le {0}', 'All source data for this period is present.': 'Toutes les données sources de cette période sont présentes.',
    'Sources: {0}': 'Sources : {0}', 'Shop and POS (retail)': 'Boutique et caisse (retail)', 'Gross sales': 'Ventes brutes', 'Discounts': 'Remises', 'Refunds': 'Remboursements', 'Net sales incl. VAT': 'Ventes nettes TVAC', 'Net sales excl. VAT': 'Ventes nettes HTVA',
    'POS excl. VAT': 'Caisse HTVA', 'Online excl. VAT': 'En ligne HTVA', 'Invoices and credit notes': 'Factures et avoirs', 'Standalone B2B invoices': 'Factures B2B autonomes', 'Standalone credit notes': 'Avoirs autonomes', 'B2B net excl. VAT': 'B2B net HTVA',
    'B2B VAT': 'TVA B2B', 'Linked invoices (not added)': 'Factures liées (non ajoutées)', 'Credit notes issued': 'Avoirs émis', 'Totals (retail + standalone B2B)': 'Totaux (retail + B2B autonome)', 'Sales excl. VAT': 'Ventes HTVA',
    'VAT collected': 'TVA collectée', 'Sales incl. VAT': 'Ventes TVAC', 'VAT by rate': 'TVA par taux', 'Rate': 'Taux', 'Taxable base': 'Base imposable',
    'Unavailable: {0} retail line(s) have no captured VAT rate (base {1}, VAT {2}). They are not spread across rates.': 'Indisponible : {0} ligne(s) retail n\'ont pas de taux de TVA enregistré (base {1}, TVA {2}). Elles ne sont pas réparties par taux.',
    'B2B {0}: base {1} (no VAT)': 'B2B {0} : base {1} (sans TVA)', 'Payment status of B2B invoices in the period': 'Statut de paiement des factures B2B de la période', '{0} invoice(s) - {1}': '{0} facture(s) - {1}',
    'Anomalies ({0})': 'Anomalies ({0})', 'None detected.': 'Aucune détectée.', 'Downloads': 'Téléchargements',
    // settings
    'Your company details, numbering and VAT rates. No passwords or keys are stored here.': 'Les données de votre société, la numérotation et les taux de TVA. Aucun mot de passe ni clé n\'est enregistré ici.',
    'Still needed before real invoices:': 'Encore nécessaire avant de vraies factures :', 'Your company (seller)': 'Votre société (vendeur)', 'Legal name': 'Dénomination légale', 'Finance email': 'E-mail finance', 'BIC (optional)': 'BIC (facultatif)',
    'VAT and payment': 'TVA et paiement', 'Allowed VAT rates (%)': 'Taux de TVA autorisés (%)', 'The rates you may choose on domestic invoices. You decide these; nothing is assumed.': 'Les taux que vous pouvez choisir sur les factures nationales. C\'est vous qui décidez ; rien n\'est supposé.',
    'Default payment terms (days)': 'Délai de paiement par défaut (jours)', 'Default language': 'Langue par défaut', 'Extra payment instructions': 'Instructions de paiement supplémentaires',
    'Print a Belgian structured communication (+++xxx/xxxx/xxxxx+++)': 'Imprimer une communication structurée belge (+++xxx/xxxx/xxxxx+++)', 'Numbering': 'Numérotation', 'Invoice prefix': 'Préfixe des factures', 'Credit note prefix': 'Préfixe des avoirs',
    'Quote prefix': 'Préfixe des devis', 'Digits': 'Chiffres', 'Format': 'Format', 'Use {prefix}, {year} and {seq}, e.g. {prefix}-{year}-{seq} gives INV-2026-0001. Numbers are assigned when a document is issued and never skip.': 'Utilisez {prefix}, {year} et {seq}, p. ex. {prefix}-{year}-{seq} donne INV-2026-0001. Les numéros sont attribués à l\'émission et ne sautent jamais.',
    'Look and feel': 'Apparence', 'Accent colour': 'Couleur d\'accent', 'Footer text on documents': 'Texte de pied de page des documents', 'Logo (PNG or JPEG, max 400 KB)': 'Logo (PNG ou JPEG, 400 Ko max)', 'a logo is set': 'un logo est défini', 'Logo saved': 'Logo enregistré',
    'Company lookup and e-invoicing': 'Recherche de sociétés et facturation électronique', 'VAT / enterprise number lookup': 'Recherche par numéro de TVA / d\'entreprise', 'EU VIES (free, official) with manual fallback': 'VIES UE (gratuit, officiel) avec repli manuel',
    'Manual entry only': 'Saisie manuelle uniquement', 'Belgian company register (primary)': 'Registre belge des sociétés (principal)', 'CBEAPI: official KBO/BCE data (needs CBEAPI_KEY)': 'CBEAPI : données officielles BCE (requiert CBEAPI_KEY)', 'Off': 'Désactivé',
    'Secondary name search (if the register finds nothing)': 'Recherche par nom secondaire (si le registre ne trouve rien)', 'OpenPeppol Directory (Peppol-registered companies) + VIES for the address': 'Annuaire OpenPeppol (sociétés inscrites sur Peppol) + VIES pour l\'adresse',
    'Off: search by number or type by hand': 'Désactivé : recherche par numéro ou saisie à la main', 'Peppol provider': 'Prestataire Peppol', 'Nothing is transmitted. Structured invoices (UBL) can be prepared and downloaded.': 'Rien n\'est transmis. Les factures structurées (UBL) peuvent être préparées et téléchargées.',
    'Settings saved': 'Paramètres enregistrés', 'Save settings': 'Enregistrer les paramètres',
  };
  // Messages produced by the server (company search, catalogue notes): matched as patterns because they carry numbers or amounts.
  const patterns = [
    [/^(\d+) companies found\. Choose the right one\.(.*)$/, '{0} sociétés trouvées. Choisissez la bonne.{1}'],
    [/^One company found\. Select it to fill the form\.(.*)$/, 'Une société trouvée. Sélectionnez-la pour remplir le formulaire.{0}'],
    [/^One company found\.$/, 'Une société trouvée.'],
    [/^Rounding: the invoice total for one unit is ([\d.]+), the shop price is ([\d.]+)\.$/, 'Arrondi : le total facturé pour une unité est {0}, le prix boutique est {1}.'],
    [/^VAT rate: not set automatically \(no consistent sales history for this product\)\. The catalogue price is ([\d.]+) including VAT and will be kept once you choose the rate\.$/, 'Taux de TVA : non défini automatiquement (pas d\'historique de ventes cohérent pour ce produit). Le prix catalogue est de {0} TVAC et sera conservé dès que vous choisirez le taux.'],
    [/^(\d+) sole traders? (?:was|were) not listed \(personal data\): search by exact enterprise \/ VAT number to find one\.$/, '{0} indépendant(s) non listé(s) (données personnelles) : recherchez par numéro d\'entreprise / de TVA exact pour en trouver un.'],
  ];
  const server = {
    'Filled in from the Belgian company register.': 'Renseigné depuis le registre belge des sociétés.',
    'No active VAT registration was found in VIES, so the VAT number was left empty.': 'Aucun assujettissement actif n\'a été trouvé dans VIES : le numéro de TVA a été laissé vide.',
    'The VAT number could not be checked right now, so it was left empty.': 'Le numéro de TVA n\'a pas pu être vérifié maintenant : il a été laissé vide.',
    'Official data filled in from EU VIES. Check it before saving.': 'Données officielles renseignées depuis VIES UE. Vérifiez-les avant d\'enregistrer.',
    'The official lookup is not available right now. The name and enterprise number were kept: complete the address by hand.': 'La recherche officielle est indisponible pour le moment. Le nom et le numéro d\'entreprise ont été conservés : complétez l\'adresse à la main.',
    'This number is not VAT-registered according to VIES, so no address is available. The name and enterprise number were kept: complete the rest by hand.': 'Ce numéro n\'est pas assujetti à la TVA selon VIES : aucune adresse n\'est disponible. Le nom et le numéro d\'entreprise ont été conservés : complétez le reste à la main.',
    'Type at least 3 letters of the name, or a VAT / enterprise number.': 'Saisissez au moins 3 lettres du nom, ou un numéro de TVA / d\'entreprise.',
    'This is not a valid Belgian VAT / enterprise number. Check it, or enter the company manually.': 'Ce n\'est pas un numéro de TVA / d\'entreprise belge valide. Vérifiez-le, ou saisissez la société à la main.',
    'This company is already in your directory.': 'Cette société figure déjà dans votre annuaire.', 'Official data found and filled in. Check it, then save.': 'Données officielles trouvées et renseignées. Vérifiez-les, puis enregistrez.',
    'The official VAT lookup is switched off in Settings. Enter the company manually.': 'La recherche officielle de TVA est désactivée dans les Paramètres. Saisissez la société à la main.',
    'The number is valid but VIES has no VAT registration for it. Enter the company manually.': 'Le numéro est valide mais VIES n\'a aucun assujettissement à la TVA pour lui. Saisissez la société à la main.',
    'The official lookup is not available right now. Enter the company manually.': 'La recherche officielle est indisponible pour le moment. Saisissez la société à la main.',
    'Showing your saved companies. Company-name search is not configured: use a VAT number or enter manually.': 'Affichage de vos sociétés enregistrées. La recherche par nom n\'est pas configurée : utilisez un numéro de TVA ou saisissez à la main.',
    'Company-name search is not configured. Search by VAT / enterprise number, or enter the company manually.': 'La recherche par nom n\'est pas configurée. Recherchez par numéro de TVA / d\'entreprise, ou saisissez la société à la main.',
    'The company search is not available right now.': 'La recherche de sociétés est indisponible pour le moment.', 'Showing your saved companies.': 'Affichage de vos sociétés enregistrées.', 'Enter the company manually.': 'Saisissez la société à la main.',
    'No company found. This search only knows companies registered on Peppol: try the VAT / enterprise number, or enter the company manually.': 'Aucune société trouvée. Cette recherche ne connaît que les sociétés inscrites sur Peppol : essayez le numéro de TVA / d\'entreprise, ou saisissez la société à la main.',
    'Current price could not be read: type the unit price yourself.': 'Le prix actuel n\'a pas pu être lu : saisissez le prix unitaire vous-même.',
    'VAT rate: not set automatically (no consistent sales history for this product). Choose it yourself.': 'Taux de TVA : non défini automatiquement (pas d\'historique de ventes cohérent pour ce produit). Choisissez-le vous-même.',
  };
  Object.assign(messages, server);
  Object.assign(messages, {
    'Selling': 'Ventes',
    'Buying': 'Fournisseurs',
    'Finance Inbox': 'Boîte finance',
    'Purchases': 'Achats',
    'Accountant': 'Comptable',
    'This invoice took products out of stock. Are the goods returned to sellable stock?': 'Cette facture a sorti des produits du stock. Les marchandises reviennent-elles en stock vendable ?',
    'Yes, put them back into stock': 'Oui, les remettre en stock',
    'No, do not change the stock': 'Non, ne pas modifier le stock',
    '{0} setting(s) missing to issue real invoices': '{0} paramètre(s) manquant(s) pour émettre de vraies factures',
    '{0} invoice(s) are overdue: {1} to collect': '{0} facture(s) en retard : {1} à encaisser',
    '{0} to collect in the next {1} days': '{0} à encaisser dans les {1} prochains jours',
    '{0} invoice(s) waiting for your approval': '{0} facture(s) en attente de votre approbation',
    '{0} document(s) are missing VAT information': '{0} document(s) sans information TVA complète',
    '{0} accepted quote(s) can become invoices': '{0} devis accepté(s) peuvent devenir des factures',
    '{0} supplier invoice(s) require validation': '{0} facture(s) fournisseur à valider',
    '{0} supplier invoice(s) to pay: {1}': '{0} facture(s) fournisseur à payer : {1}',
    '{0} stock movement(s) need your attention': '{0} mouvement(s) de stock demandent votre attention',
    'Q{0} {1} closes in {2} days': 'Le T{0} {1} se clôture dans {2} jours',
    'The accountant pack for {0} is ready': 'Le pack comptable de {0} est prêt',
    'The accountant pack for {0} needs review ({1} anomalies)': 'Le pack comptable de {0} demande une vérification ({1} anomalies)',
    '{0} orders reconciled': '{0} commandes rapprochées',
    'Review': 'Vérifier',
    'Validate supplier invoices': 'Valider les factures fournisseurs',
    'Prepare the accountant file': 'Préparer le dossier comptable',
    'Action Center': 'Centre d\'actions',
    'What to do next': 'Ce qu\'il faut faire ensuite',
    'Nothing needs your attention': 'Rien ne demande votre attention',
    'Everything is up to date.': 'Tout est à jour.',
    'Peppol': 'Peppol',
    'E-mail': 'E-mail',
    'Upload': 'Téléversement',
    'Manual': 'Manuel',
    'Received': 'Reçue',
    'To review': 'À vérifier',
    'Validated': 'Validée',
    'To pay': 'À payer',
    'No automatic extraction': 'Aucune extraction automatique',
    'Confidence {0}%': 'Confiance {0} %',
    'Supplier name is missing': 'Le nom du fournisseur manque',
    'Invoice number is missing': 'Le numéro de facture manque',
    'Invoice date is missing or invalid': 'La date de facture manque ou est invalide',
    'Due date is invalid': 'La date d\'échéance est invalide',
    'Amount excl. VAT is missing': 'Le montant HTVA manque',
    'VAT amount is missing': 'Le montant de TVA manque',
    'Amount incl. VAT is missing': 'Le montant TVAC manque',
    'Excl. VAT + VAT does not equal the total': 'HTVA + TVA ne donne pas le total',
    'Currency is missing': 'La devise manque',
    'Supplier invoice': 'Facture fournisseur',
    'Rejected: {0}': 'Refusée : {0}',
    'The extracted totals do not add up: check them.': 'Les totaux extraits ne concordent pas : vérifiez-les.',
    'This looks like a supplier credit note: review it manually.': 'Cela ressemble à une note de crédit fournisseur : vérifiez-la à la main.',
    'Open the source document': 'Ouvrir le document source',
    'Supplier': 'Fournisseur',
    'Supplier VAT number': 'Numéro de TVA du fournisseur',
    'Invoice number': 'Numéro de facture',
    'Invoice date': 'Date de facture',
    'Excl. VAT': 'HTVA',
    'Incl. VAT': 'TVAC',
    'Payment reference': 'Référence de paiement',
    'Still needed before validation:': 'Encore nécessaire avant la validation :',
    'Saved': 'Enregistré',
    'Validate': 'Valider',
    'Reject this document': 'Refuser ce document',
    'It is not a supplier invoice, or it is a duplicate.': 'Ce n\'est pas une facture fournisseur, ou c\'est un doublon.',
    'Marked to pay': 'Marquée à payer',
    'Mark to pay': 'Marquer à payer',
    'Reopened': 'Rouverte',
    'Reopen for correction': 'Rouvrir pour correction',
    'Record the payment': 'Enregistrer le paiement',
    'Amount: {0} {1}': 'Montant : {0} {1}',
    'Mark as paid': 'Marquer comme payée',
    'Paid on {0}': 'Payée le {0}',
    'Incoming financial documents, reviewed by you before anything is recorded.': 'Documents financiers entrants, vérifiés par vous avant tout enregistrement.',
    '+ Add manually': '+ Ajouter à la main',
    'File upload': 'Téléversement de fichier',
    'Dedicated finance mailbox': 'Boîte e-mail finance dédiée',
    'Peppol invoices received': 'Factures Peppol reçues',
    'Active': 'Actif',
    'Drop invoices here, or click to choose': 'Déposez les factures ici, ou cliquez pour choisir',
    'PDF, image or structured XML (UBL). They stay private and are never sent anywhere.': 'PDF, image ou XML structuré (UBL). Ils restent privés et ne sont envoyés nulle part.',
    '{0} was already received': '{0} avait déjà été reçu',
    '{0} received': '{0} reçu',
    // Achats: 3-pane workspace (queue/preview/form), restored Import action, real document preview.
    'Import': 'Importer', 'Import supplier documents': 'Importer des documents fournisseurs',
    'This entry has no source document.': 'Cette entrée n\'a pas de document source.', 'Preview is not available for this file type.': 'L\'aperçu n\'est pas disponible pour ce type de fichier.',
    'Select a document to preview it here.': 'Sélectionnez un document pour l\'aperçu ici.', 'Select a document from the queue to review it here.': 'Sélectionnez un document dans la file pour le vérifier ici.',
    'Source file': 'Fichier source',
    'The inbox is empty': 'La boîte de réception est vide',
    'Documents you receive will appear here for review.': 'Les documents reçus apparaîtront ici pour vérification.',
    'Unknown supplier': 'Fournisseur inconnu',
    'Add a supplier invoice manually': 'Ajouter une facture fournisseur à la main',
    'Supplier invoices you validated: to pay and paid.': 'Factures fournisseurs validées : à payer et payées.',
    'Open the Finance Inbox': 'Ouvrir la boîte de réception finance',
    'No supplier invoices yet': 'Aucune facture fournisseur pour l\'instant',
    'Validate a document from the Finance Inbox to see it here.': 'Validez un document depuis la boîte de réception finance pour le voir ici.',
    'Validated, not yet to pay': 'Validées, pas encore à payer',
    'supplier invoice(s)': 'facture(s) fournisseur',
    'Month': 'Mois',
    'Quarter': 'Trimestre',
    'Year': 'Année',
    'Custom period': 'Période personnalisée',
    'Period': 'Période',
    'No accountant address is set: add it in Settings.': 'Aucune adresse de comptable n\'est définie : ajoutez-la dans les Paramètres.',
    'The period data is incomplete: see the anomalies file in the package.': 'Les données de la période sont incomplètes : voir le fichier des anomalies dans le dossier.',
    'Direct sending is not configured: download the package or the .eml file and send it yourself.': 'L\'envoi direct n\'est pas configuré : téléchargez le dossier ou le fichier .eml et envoyez-le vous-même.',
    'Preview': 'Aperçu',
    'Recipient': 'Destinataire',
    'Message': 'Message',
    'Subject': 'Objet',
    'Attachment': 'Pièce jointe',
    'Contents': 'Contenu',
    '{0} invoice(s) · {1} credit note(s) · {2} refund(s) · {3} supplier invoice(s)': '{0} facture(s) · {1} avoir(s) · {2} remboursement(s) · {3} facture(s) fournisseur',
    'Download the ZIP': 'Télécharger le ZIP',
    'Download the .eml (fallback)': 'Télécharger le .eml (solution de repli)',
    'Send to accountant': 'Envoyer au comptable',
    'Nothing is sent until you approve.': 'Rien n\'est envoyé tant que vous n\'avez pas approuvé.',
    'Sent to the accountant': 'Envoyé au comptable',
    'APPROVE and send': 'APPROUVER et envoyer',
    'You are about to send {0} to:': 'Vous allez envoyer {0} à :',
    'The package contains your sales, VAT and documents for the period. Sending goes through: {0}.': 'Le dossier contient vos ventes, votre TVA et vos documents de la période. L\'envoi passe par : {0}.',
    'I approve sending this package to this recipient.': 'J\'approuve l\'envoi de ce dossier à ce destinataire.',
    'Close the period': 'Clôturer la période',
    'One click: the whole accountant file, checked and ready.': 'Un clic : tout le dossier comptable, vérifié et prêt.',
    'Stored on this computer only': 'Enregistré sur cet ordinateur uniquement',
    'Name / company': 'Nom / société',
    'Preferred export format': 'Format d\'export préféré',
    'ZIP package': 'Dossier ZIP',
    'Excel (XLSX)': 'Excel (XLSX)',
    'Accounting software / provider': 'Logiciel / prestataire comptable',
    'Name used in file names': 'Nom utilisé dans les fichiers',
    'Pending': 'En attente',
    'Applied': 'Appliqué',
    'Failed': 'Échoué',
    'Uncertain': 'Incertain',
    'Skipped': 'Ignoré',
    'Stock synchronisation': 'Synchronisation du stock',
    'Shopify stays the source of truth': 'Shopify reste la source de vérité',
    'A standalone B2B invoice takes its catalogue products out of Shopify stock once, when it is issued. Shop and POS invoices never do.': 'Une facture B2B autonome sort ses produits du catalogue du stock Shopify une seule fois, à l\'émission. Les factures boutique et caisse ne le font jamais.',
    'The Shopify permission to adjust inventory is granted.': 'L\'autorisation Shopify d\'ajuster l\'inventaire est accordée.',
    'The Shopify permission write_inventory is not granted yet: movements wait as pending.': 'L\'autorisation Shopify write_inventory n\'est pas encore accordée : les mouvements restent en attente.',
    'The Shopify permission could not be checked.': 'L\'autorisation Shopify n\'a pas pu être vérifiée.',
    'Mode': 'Mode',
    'Dry run (report only)': 'Simulation (rapport seulement)',
    'Live': 'Réel',
    'Stock location': 'Emplacement de stock',
    'Automatic if there is a single location': 'Automatique s\'il n\'y a qu\'un emplacement',
    'Blocked: {0}': 'Bloqué : {0}',
    '{0} movement(s) applied': '{0} mouvement(s) appliqué(s)',
    'Apply pending movements': 'Appliquer les mouvements en attente',
    '{0} missing movement(s) created': '{0} mouvement(s) manquant(s) créé(s)',
    'Reconcile': 'Rapprocher',
    'Finance Inbox source': 'Source de la boîte finance',
    'Only finance messages, never a personal mailbox': 'Uniquement des messages finance, jamais une messagerie personnelle',
    'Documents enter through a dedicated finance address only. Nothing reads your personal or historical mailbox.': 'Les documents entrent uniquement par une adresse finance dédiée. Rien ne lit votre messagerie personnelle ou historique.',
    'Dedicated finance address': 'Adresse finance dédiée',
    'Allowed senders (comma separated)': 'Expéditeurs autorisés (séparés par des virgules)',
    'Provider-neutral until the topology is confirmed': 'Neutre vis-à-vis des prestataires tant que la topologie n\'est pas confirmée',
    'Do not register a second receiving Access Point before the topology is confirmed with your accountant / provider.': 'Ne vous inscrivez pas auprès d\'un second point d\'accès récepteur avant d\'avoir confirmé la topologie avec votre comptable / prestataire.',
    'Who owns the current receiving registration?': 'Qui détient l\'inscription de réception actuelle ?',
    'Is Codabox VOILA the receiver?': 'Codabox VOILA est-il le récepteur ?',
    'Does it expose an export or an API?': 'Expose-t-il un export ou une API ?',
    'Should we only send through another Access Point, or integrate the existing one?': 'Doit-on seulement envoyer via un autre point d\'accès, ou intégrer l\'existant ?',
    'Current receiving Access Point': 'Point d\'accès récepteur actuel',
    'Unknown': 'Inconnu',
    'Codabox': 'Codabox',
    'Decision': 'Décision',
    'Undecided': 'Non décidé',
    'Send only (through another Access Point)': 'Envoi seul (via un autre point d\'accès)',
    'Receive through the existing provider': 'Réception via le prestataire existant',
    'Integrated with the existing provider': 'Intégré avec le prestataire existant',
    'Confirmed with': 'Confirmé avec',
    'Confirmed on': 'Confirmé le',
    'Sending: {0}': 'Envoi : {0}',
    'Receiving: {0}': 'Réception : {0}',
    'Connectors': 'Connecteurs',
    'Replaceable: nothing is hard-wired to one provider': 'Remplaçables : rien n\'est figé sur un seul prestataire',
    'Applying': 'Application',
    'Stock movements': 'Mouvements de stock',
    'Line': 'Ligne',
    'Change': 'Variation',
    'Shopify adjustment': 'Ajustement Shopify',
    'Not sent': 'Non envoyée',
    'Delivered': 'Remise',
    'Prepared': 'Préparée',
    'The Access Point reported a problem: {0}': 'Le point d\'accès a signalé un problème : {0}',
    'Confirm the Peppol topology in Settings before sending.': 'Confirmez la topologie Peppol dans les Paramètres avant d\'envoyer.',
    'Send via Peppol': 'Envoyer via Peppol',
    'This sends the structured invoice through your Peppol Access Point. It cannot be recalled.': 'Cela envoie la facture structurée via votre point d\'accès Peppol. Elle ne peut pas être rappelée.',
    'Sent via Peppol': 'Envoyée via Peppol',
    'Refresh status': 'Actualiser le statut',
    'No Peppol Access Point is configured. Nothing is sent externally.': 'Aucun point d\'accès Peppol n\'est configuré. Rien n\'est envoyé à l\'extérieur.',
  });
  Object.assign(messages, { '+ {0} more files': '+ {0} autres fichiers' });
  Object.assign(messages, { 'VAT': 'TVA', 'to schedule': 'à planifier' });
  Object.assign(messages, { 'To': 'Au', 'not set': 'non défini' });
  Object.assign(messages, {
    'Bank & Treasury': 'Banque et trésorerie',
    'Not connected': 'Non connectée',
    'Connected': 'Connectée',
    'Consent expired': 'Consentement expiré',
    'Disconnected': 'Déconnectée',
    'Treasury': 'Trésorerie',
    'Short-term liquidity, not accounting cash flow': 'Liquidités à court terme, pas un flux de trésorerie comptable',
    'Bank': 'Banque',
    'Total liquidity': 'Liquidités totales',
    'Receivables due in {0} days': 'À encaisser sous {0} jours',
    'To pay in {0} days': 'À payer sous {0} jours',
    'Projection': 'Projection',
    'No bank balance available: connect a bank or import a statement.': 'Aucun solde bancaire disponible : connectez une banque ou importez un relevé.',
    'No physical cash count confirmed yet.': 'Aucun comptage de caisse confirmé pour l\'instant.',
    '{0} of overdue receivables is NOT included in the projection above (assumed, not expected).': '{0} de créances en retard ne sont PAS inclus dans la projection ci-dessus (supposé, pas attendu).',
    'Observed = bank balance / confirmed cash count. Expected = invoices and supplier invoices due. Assumed = excluded from the projection.': 'Observé = solde bancaire / comptage de caisse confirmé. Attendu = factures et factures fournisseurs échues. Supposé = exclu de la projection.',
    'Exact match': 'Correspondance exacte',
    'Probable match': 'Correspondance probable',
    'Partial payment': 'Paiement partiel',
    'Overpayment': 'Trop-perçu',
    'Several candidates': 'Plusieurs candidats',
    'No match': 'Aucune correspondance',
    'Reconciled': 'Rapproché',
    'Confirm': 'Confirmer',
    'Choose...': 'Choisir…',
    'Ignored': 'Ignoré',
    'Ignore': 'Ignorer',
    'IN': 'ENTRÉE',
    'OUT': 'SORTIE',
    'Unknown': 'Inconnu',
    'Read-only: balances and transactions, never a payment or a transfer.': 'Lecture seule : soldes et transactions, jamais un paiement ou un virement.',
    'Bank connection': 'Connexion bancaire',
    'Read-only access only. This connection can never initiate a payment, a transfer or change a beneficiary.': 'Accès en lecture seule uniquement. Cette connexion ne peut jamais initier un paiement, un virement ou modifier un bénéficiaire.',
    'Provider': 'Prestataire',
    'Scopes': 'Portées',
    'Connected since': 'Connectée depuis',
    '{0} new transaction(s)': '{0} nouvelle(s) transaction(s)',
    'Sync now': 'Synchroniser maintenant',
    'Disconnect bank': 'Déconnecter la banque',
    'This revokes local and, where supported, remote access. No transactions are deleted.': 'Cela révoque l\'accès local et, si le prestataire le permet, l\'accès distant. Aucune transaction n\'est supprimée.',
    'Disconnect': 'Déconnecter',
    'Provider: {0}': 'Prestataire : {0}',
    'Connect a bank': 'Connecter une banque',
    'No bank provider is configured yet.': 'Aucun prestataire bancaire n\'est encore configuré.',
    'Paste your bank statement CSV export here': 'Collez ici l\'export CSV de votre relevé bancaire',
    'Or import a CSV statement (no bank connection needed)': 'Ou importez un relevé CSV (aucune connexion bancaire requise)',
    '{0} transaction(s) imported': '{0} transaction(s) importée(s)',
    'Import CSV': 'Importer le CSV',
    'Physical cash': 'Caisse physique',
    'Only confirmed counts are used: cash sales are never assumed to stay in the till.': 'Seuls les comptages confirmés sont utilisés : les ventes en espèces ne sont jamais supposées rester en caisse.',
    'Amount counted': 'Montant compté',
    'Confirm cash count': 'Confirmer le comptage',
    'Transactions to reconcile': 'Transactions à rapprocher',
    'Nothing to reconcile': 'Rien à rapprocher',
  });
  // Phase 2: unified Contacts workspace (views-contacts.js).
  Object.assign(messages, {
    'Contacts': 'Contacts', 'Business': 'Entreprise', 'Individual': 'Personne', 'Customer · Supplier': 'Client · Fournisseur',
    'A financial directory of your customers and suppliers.': 'Répertoire financier de vos clients et fournisseurs.',
    '+ New contact': '+ Nouveau contact', 'Search by name, VAT number...': 'Rechercher par nom, TVA…',
    'All contacts': 'Tous', 'Suppliers': 'Fournisseurs',
    'Your contacts will appear here.': 'Vos contacts apparaîtront ici.',
    'Add a client or a company now; suppliers will also be gathered in this directory once they are linked to your purchase documents.': 'Ajoutez un client ou une entreprise maintenant ; les fournisseurs seront également réunis dans ce répertoire lorsqu\'ils seront liés à vos documents d\'achat.',
    'Add a contact': 'Ajouter un contact',
    'No supplier matches this search.': 'Aucun fournisseur ne correspond à cette recherche.',
    'No customer matches this search.': 'Aucun client ne correspond à cette recherche.',
    'No contact matches this search.': 'Aucun contact ne correspond à cette recherche.',
    // Achats: real "link a contact" control (POST /api/inbox/:id/contact), previously supported by the
    // backend but with no UI control anywhere.
    'Linked contact': 'Contact lié', 'Search contacts by name or VAT...': 'Rechercher un contact par nom ou TVA...', 'No contact matches.': 'Aucun contact ne correspond.',
    'Contact linked': 'Contact lié', 'Contact unlinked': 'Contact délié', 'Unlink': 'Délier',
    'Clear the search': 'Effacer la recherche',
    'Contact': 'Contact', 'Relation': 'Relation', 'Amount receivable': 'À recevoir', 'Amount payable': 'À payer', 'Last activity': 'Dernière activité',
    'Contacts could not be loaded.': 'Impossible de charger les contacts.', 'Retry': 'Réessayer',
    '(no number)': '(sans numéro)',
    'This contact has no invoiced activity yet.': 'Aucune activité facturée pour ce contact pour le moment.',
    'Sales documents': 'Documents de vente', 'No sales documents yet.': 'Aucun document de vente.',
    'Supplier documents': 'Documents fournisseurs', 'No supplier documents yet.': 'Aucun document fournisseur.',
  });
  // HABB Finance unified module (2026-09-24): shell nav, Accueil hero/CTA, "Nous contacter".
  Object.assign(messages, {
    'Home': 'Accueil', 'To do': 'À faire', 'Sales': 'Ventes', 'Bank & Cash': 'Banque & Caisse', 'More': 'Plus',
    'Contact us': 'Nous contacter', 'Reach your configured finance contact:': 'Contactez votre adresse finance configurée :', 'No contact address is configured yet.': 'Aucune adresse de contact n\'est configurée pour le moment.',
    'Working with clarity.': 'Entreprendre avec clarté.', 'Moving forward with peace of mind.': 'Avancer avec sérénité.',
    'Every invoice, told simply.': 'Chaque facture racontée simplement.', 'Financial clarity, day after day.': 'La clarté financière, jour après jour.',
    'Create, send and track your invoices with ease.': 'Créez, envoyez et suivez vos factures en toute simplicité.',
    'Most recent: {0} · {1} {2}': 'Plus récente : {0} · {1} {2}', 'No invoice yet - create your first one.': 'Aucune facture pour le moment - créez la première.',
  });
  // À faire (viewTodo, views-workspace.js).
  Object.assign(messages, {
    'Everything that needs your attention, in one place.': 'Tout ce qui demande votre attention, au même endroit.',
    'To handle': 'À traiter', 'Documents and actions to finalise': 'Documents et actions à finaliser',
    'Urgent': 'Urgent', 'Needs attention now': 'Nécessite une action maintenant',
    'Worth a look soon': 'À regarder prochainement', 'Informational': 'Informatif', 'No action required yet': 'Aucune action requise pour le moment',
    'By priority': 'Par priorité', 'Up to date': 'À jour', 'Recommended action': 'Action recommandée',
  });
  // Ventes/Achats workspaces + shared analytics panel (views-workspace.js).
  Object.assign(messages, {
    'This month': 'Ce mois-ci', 'Last month': 'Le mois dernier', 'Last 3 months': 'Les 3 derniers mois', 'This quarter': 'Ce trimestre', 'This year': 'Cette année', 'Custom range': 'Période personnalisée',
    'Search a product or SKU...': 'Rechercher un produit ou une référence…',
    'Sales (excl. VAT)': 'Ventes (HTVA)', 'Credit notes (excl. VAT)': 'Avoirs (HTVA)', 'Net after credit notes': 'Net après avoirs', 'Documents': 'Documents',
    'By product': 'Par produit', 'Product': 'Produit', 'SKU': 'Référence', 'Qty': 'Qté', 'Revenue': 'Chiffre d\'affaires',
    'No catalogue product on any sales line in this period.': 'Aucun produit du catalogue sur les lignes de vente de cette période.',
    '{0} of sales lines have no catalogue product/SKU and are not included in the breakdown above.': '{0} de lignes de vente n\'ont pas de produit/référence catalogue et ne figurent pas dans la répartition ci-dessus.',
    'Purchases (incl. VAT)': 'Achats (TVAC)', 'By supplier': 'Par fournisseur', 'Supplier': 'Fournisseur', 'Total': 'Total',
    'No supplier invoice in this period.': 'Aucune facture fournisseur sur cette période.',
    'Invoices, quotes and credit notes in one place.': 'Factures, devis et avoirs au même endroit.', 'New invoice': 'Nouvelle facture',
    'Invoices': 'Factures', 'Credit notes': 'Avoirs', 'Analytics': 'Analytique',
    'Amount receivable': 'À recevoir', 'Overdue': 'En retard', '{0} case(s)': '{0} cas', 'Collected this month': 'Encaissé ce mois-ci', '{0} payment(s)': '{0} paiement(s)',
    'Quotes to convert': 'Devis à convertir', 'Accepted, not yet invoiced': 'Acceptés, pas encore facturés',
    'Search number or customer...': 'Rechercher un numéro ou un client…', 'Export': 'Exporter',
    'Select a document to see its summary here.': 'Sélectionnez un document pour voir son résumé ici.',
    'Open': 'Ouvrir', 'Still due': 'Reste dû', 'No document matches.': 'Aucun document ne correspond.', 'Issued': 'Émise', 'Due': 'Échéance', 'Document': 'Document', 'Customer': 'Client', 'Amount': 'Montant', 'Status': 'Statut',
    '{0} unit(s) · {1} {2} across {3} document(s).': '{0} unité(s) · {1} {2} sur {3} document(s).',
    'Process supplier invoices, validate the data and track what remains to pay.': 'Traitez les factures fournisseurs, validez les données et suivez ce qui reste à payer.',
    '+ Add manually': '+ Ajouter manuellement', 'To pay': 'À payer', 'Documents awaiting validation': 'Documents en attente de validation',
    '{0} document(s)': '{0} document(s)', 'Supplier invoice(s)': 'Facture(s) fournisseur', 'Supplier, invoice number...': 'Fournisseur, numéro de facture…',
    'Nothing here.': 'Rien ici.',
  });
  // Banque & Caisse / Trésorerie (views-workspace.js).
  Object.assign(messages, {
    'Justify': 'Justifier', 'Justified': 'Justifié', 'Nothing to justify': 'Rien à justifier', 'Transactions to justify': 'Transactions à justifier',
    // Server-provided (analytics.js's own English message id, translated here like every other key -
    // never hardcoded French in the backend module itself).
    'Supplier invoices are stored as one total per document (net/VAT/gross) - there is no per-product line detail to break down.': 'Les factures fournisseurs sont enregistrées comme un seul total par document (HT/TVA/TVAC) - il n\'y a pas de détail par ligne/produit à décomposer.',
    'Understand every inflow and outflow, without accounting jargon.': 'Comprenez chaque entrée et sortie, sans jargon comptable.',
    'Confirmed count only': 'Comptage confirmé uniquement',
    'Visualise what is realised, what is committed and your projected position.': 'Visualisez le réalisé, les engagements à venir et votre position projetée.',
    'Available today': 'Disponible aujourd\'hui', 'Receivable in {0} days': 'À recevoir sous {0} jours', 'Payable in {0} days': 'À payer sous {0} jours',
    'Treasury position': 'Position de trésorerie', 'Realised documented balance, last 12 months': 'Solde documenté réalisé, 12 derniers mois',
    'Not enough history yet.': 'Pas encore assez d\'historique.',
    'Expected customer invoices': 'Factures clients attendues', 'Supplier invoices to pay': 'Factures fournisseurs à payer',
    '{0} of overdue receivables is NOT included in this projection (assumed, not expected).': '{0} de créances en retard ne sont PAS inclus dans cette projection (supposé, pas attendu).',
    'VAT is not provisioned here - see the Accountant pack for the authoritative per-period VAT figure.': 'La TVA n\'est pas provisionnée ici - consultez le pack comptable pour le chiffre de TVA officiel par période.',
    'Projection detail unavailable.': 'Détail de la projection indisponible.',
  });
  // Contacts (views-contacts.js), unified visual pass.
  Object.assign(messages, {
    'Both': 'Les deux', 'To complete': 'À compléter',
    'Customers, suppliers and financial relationships in one directory.': 'Clients, fournisseurs et relations financières dans un seul répertoire.',
    'Search name, VAT, email...': 'Rechercher par nom, TVA, e-mail…', 'Contact details': 'Coordonnées', '+ Create': '+ Créer',
  });
  window.FINANCE_LANG = window.FINANCE_LANG || {};
  window.FINANCE_LANG.fr = { messages, patterns };
})();
