'use strict';
// Dutch (Belgium). Keys are the English message ids used in app.js.
(function () {
  const messages = {
    'Required': 'Verplicht', 'Enter a quantity (up to 3 decimals)': 'Geef een hoeveelheid in (tot 3 decimalen)', 'Enter a unit price (up to 4 decimals)': 'Geef een eenheidsprijs in (tot 4 decimalen)',
    'Choose a VAT rate': 'Kies een btw-tarief', 'Invalid discount': 'Ongeldige korting', 'Invalid date': 'Ongeldige datum', 'Enter an amount like 12.34': 'Geef een bedrag in zoals 12,34',
    'Invalid email address': 'Ongeldig e-mailadres', 'Invalid IBAN': 'Ongeldig IBAN', 'Use a 2-letter country code': 'Gebruik een landcode van 2 letters', 'Add at least one line': 'Voeg minstens één lijn toe',
    'Fix the items listed below first': 'Los eerst de onderstaande punten op', 'This action is not allowed in the current status': 'Deze actie is niet toegestaan in de huidige status',
    'This shop/POS order already has an active invoice': 'Deze winkel-/kassabestelling heeft al een actieve factuur', 'The document changed meanwhile: reload and retry': 'Het document is intussen gewijzigd: herlaad en probeer opnieuw',
    'Issued documents cannot be edited: create a credit note instead': 'Een uitgegeven document kan niet meer gewijzigd worden: maak een creditnota', 'The payment is higher than the amount still due': 'De betaling is hoger dan het openstaande bedrag',
    'The credit is higher than what can still be credited': 'De creditnota is hoger dan wat nog gecrediteerd kan worden', 'This company is already in the directory': 'Dit bedrijf staat al in de lijst',
    'Wrong access token': 'Verkeerde toegangstoken', 'Too many attempts. Wait a few minutes.': 'Te veel pogingen. Wacht enkele minuten.', 'Please log in again': 'Log opnieuw in',
    'Confirm the VAT treatment': 'Bevestig de btw-behandeling', 'Choose whether this invoice is linked to a shop order or a new B2B sale': 'Kies of deze factuur gekoppeld is aan een winkelbestelling of aan een nieuwe B2B-verkoop',
    'Enter the customer VAT or enterprise number': 'Geef het btw- of ondernemingsnummer van de klant in', 'Complete your company details in Settings': 'Vul de gegevens van uw bedrijf aan in de Instellingen',
    'Add your VAT number in Settings': 'Voeg uw btw-nummer toe in de Instellingen', 'Add your IBAN in Settings (or payment terms on the invoice)': 'Voeg uw IBAN toe in de Instellingen (of betalingsvoorwaarden op de factuur)',
    'Set a due date': 'Geef een vervaldatum in', 'Select the shop/POS order to link': 'Selecteer de winkel-/kassabestelling om te koppelen', 'The linked order was not found': 'De gekoppelde bestelling werd niet gevonden',
    'Give a reason for the credit note': 'Geef de reden van de creditnota', 'Line {0}: {1}': 'Lijn {0}: {1}', 'Customer address: {0} is missing': 'Adres van de klant: {0} ontbreekt',
    'This looks like a shop sale that is not linked. Link it, or confirm it is a separate sale.': 'Dit lijkt op een niet-gekoppelde winkelverkoop. Koppel ze, of bevestig dat het een aparte verkoop is.',
    'street': 'straat', 'postalcode': 'postcode', 'city': 'stad', 'countrycode': 'land', 'Something went wrong': 'Er is iets misgegaan',
    'Draft': 'Ontwerp', 'Ready for approval': 'Goed te keuren', 'Issued': 'Uitgegeven', 'Sent': 'Verzonden', 'Partially paid': 'Gedeeltelijk betaald', 'Paid': 'Betaald', 'Overdue': 'Te laat', 'Credited': 'Gecrediteerd',
    'Cancelled': 'Geannuleerd', 'Accepted': 'Aanvaard', 'Rejected': 'Geweigerd', 'Converted': 'Omgezet', 'Invoice': 'Factuur', 'Quote': 'Offerte', 'Credit note': 'Creditnota',
    'Domestic - VAT charged': 'Binnenlands - btw aangerekend', 'Intra-EU B2B - VAT exempt': 'Intracommunautaire B2B - vrijgesteld van btw', 'Reverse charge (customer accounts for VAT)': 'Btw verlegd (de klant voldoet de btw)',
    'Export outside the EU': 'Uitvoer buiten de EU', 'VAT-exempt (small business scheme)': 'Vrijgesteld van btw (kleine ondernemingen)',
    'COMPLETE': 'VOLLEDIG', 'PARTIAL': 'GEDEELTELIJK', 'CLEAN': 'CONFORM', 'REVIEW_REQUIRED': 'NAZIEN', 'NOT CONFIGURED': 'NIET GECONFIGUREERD',
    '{0} day late': '{0} dag te laat', '{0} days late': '{0} dagen te laat', 'Due today': 'Vervalt vandaag', 'Due in {0} day': 'Vervalt over {0} dag', 'Due in {0} days': 'Vervalt over {0} dagen',
    'Overview': 'Overzicht', 'Invoices': 'Facturen', 'Quotes': 'Offertes', 'Companies': 'Bedrijven', 'Payments': 'Betalingen', 'Accountant pack': 'Boekhoudpakket', 'Settings': 'Instellingen', 'Finance': 'Finance',
    'New invoice': 'Nieuwe factuur', 'Peppol: not configured': 'Peppol: niet geconfigureerd', 'Nothing is sent externally': 'Er wordt niets extern verzonden', 'Log out': 'Afmelden',
    'Access token': 'Toegangstoken', 'Enter the access token stored in your .env file (FINANCE_DASHBOARD_TOKEN).': 'Geef de toegangstoken uit uw .env-bestand in (FINANCE_DASHBOARD_TOKEN).', 'Log in': 'Aanmelden',
    'Interface language': 'Taal van de interface',
    'Good morning': 'Goedemorgen', 'Good afternoon': 'Goedemiddag', 'Good evening': 'Goedenavond', 'Here is what needs your attention.': 'Dit vraagt uw aandacht.', 'New quote': 'Nieuwe offerte',
    'Finish your setup before issuing real invoices:': 'Rond de configuratie af voor u echte facturen uitgeeft:', '{0} setting(s) missing.': '{0} instelling(en) ontbreken.', 'Open settings': 'Instellingen openen',
    'Awaiting your approval': 'Wacht op uw goedkeuring', 'Review and issue': 'Nazien en uitgeven', 'Nothing to approve': 'Niets goed te keuren', 'Overdue invoices': 'Facturen te laat',
    '{0} {1} to collect': '{0} {1} te innen', 'Nothing is late': 'Niets is te laat', 'Accepted quotes to convert': 'Aanvaarde offertes om om te zetten', '{0} quote(s) awaiting response': '{0} offerte(s) wachten op antwoord',
    'Unpaid invoices': 'Onbetaalde facturen', '{0} {1} outstanding': '{0} {1} openstaand', 'Outstanding': 'Openstaand', '{0} unpaid invoice(s)': '{0} onbetaalde factu(u)r(en)', '{0} invoice(s)': '{0} factu(u)r(en)',
    'Paid this month': 'Deze maand betaald', '{0} payment(s)': '{0} betaling(en)', 'Not yet due': 'Nog niet vervallen', '0-7 days': '0-7 dagen', '8-30 days': '8-30 dagen', '31-60 days': '31-60 dagen', '60+ days': '60+ dagen',
    'Ageing of unpaid invoices': 'Ouderdom van onbetaalde facturen', 'Open payments': 'Betalingen openen', 'All caught up': 'Alles is bij', 'No unpaid invoices right now.': 'Momenteel geen onbetaalde facturen.',
    '{0} inv.': '{0} fact.', 'To approve': 'Goed te keuren', 'Nothing overdue': 'Niets te laat', 'Every invoice is on time.': 'Alle facturen zijn op tijd.', 'Waiting for you': 'Wacht op u',
    'Nothing is waiting': 'Niets wacht', 'Drafts and quotes will show up here.': 'Ontwerpen en offertes verschijnen hier.', 'Accountant pack - last closed quarter': 'Boekhoudpakket - laatste afgesloten kwartaal',
    'Checking...': 'Controle…', 'Open the pack': 'Pakket openen', 'Retail data is not available.': 'De verkoopgegevens zijn niet beschikbaar.', '{0} anomaly(ies)': '{0} afwijking(en)', 'Pack status unavailable.': 'Status van het pakket niet beschikbaar.',
    'All': 'Alle', 'Proposals for your customers.': 'Voorstellen voor uw klanten.', 'Everything you have issued or are preparing.': 'Alles wat u uitgaf of voorbereidt.',
    'Search quotes by customer or number': 'Zoek offertes op klant of nummer', 'Search invoices by customer or number': 'Zoek facturen op klant of nummer', 'No match': 'Geen resultaat',
    'No quotes yet': 'Nog geen offertes', 'No invoices yet': 'Nog geen facturen', 'Try another word or status.': 'Probeer een ander woord of een andere status.', 'Create your first one in a minute.': 'Maak de eerste in een minuut.',
    '{0} still due': '{0} nog verschuldigd', 'Valid until {0}': 'Geldig tot {0}',
    'Belgian company register (KBO/BCE)': 'Belgisch ondernemingsregister (KBO)', 'EU VIES (official VAT service)': 'EU VIES (officiële btw-dienst)', 'OpenPeppol Directory': 'OpenPeppol-directory', 'your company directory': 'uw bedrijvenlijst',
    'Belgian company register (KBO/BCE via CBEAPI)': 'Belgisch ondernemingsregister (KBO via CBEAPI)', 'Your company directory': 'Uw bedrijvenlijst',
    'Source: entered by hand.': 'Bron: handmatig ingevoerd.', 'Source: {0}': 'Bron: {0}', 'VAT number confirmed': 'btw-nummer bevestigd', 'no active VAT registration found (VAT number left empty)': 'geen actieve btw-registratie gevonden (btw-nummer leeg gelaten)',
    'VAT could not be checked (VAT number left empty)': 'btw kon niet gecontroleerd worden (btw-nummer leeg gelaten)', 'then edited by you': 'nadien door u gewijzigd', 'SOLE TRADER / PERSONAL DATA': 'EENMANSZAAK / PERSOONSGEGEVENS',
    'Search company name or VAT / enterprise number': 'Zoek een bedrijf op naam of btw- / ondernemingsnummer', 'Check the fields below: you can still correct them.': 'Controleer de onderstaande velden: u kunt ze nog verbeteren.',
    'Filled in from: {0}. Check the fields below: you can still correct them.': 'Ingevuld vanuit: {0}. Controleer de onderstaande velden: u kunt ze nog verbeteren.',
    'Type a company name, or a VAT / enterprise number.': 'Typ een bedrijfsnaam of een btw- / ondernemingsnummer.', 'Searching...': 'Zoeken…', 'Number kept. Complete the other fields by hand.': 'Nummer bewaard. Vul de andere velden handmatig aan.',
    'Use this number and complete by hand': 'Dit nummer gebruiken en handmatig aanvullen', 'select it to fill in what is available (the address may be missing)': 'selecteer het om in te vullen wat beschikbaar is (het adres kan ontbreken)',
    'Find the company': 'Zoek het bedrijf', 'Search': 'Zoeken', 'Type a name or a VAT / enterprise number. Or skip this and fill the fields by hand.': 'Typ een naam of een btw- / ondernemingsnummer. Of sla dit over en vul de velden handmatig in.',
    'Stock n/a': 'Voorraad n.b.', 'Out of stock': 'Uitverkocht', 'Low: {0}': 'Laag: {0}', '{0} in stock': '{0} in voorraad', 'Search product name, variant or SKU': 'Zoek een product, variant of SKU',
    'Type at least 2 characters: a product name, variant or SKU.': 'Typ minstens 2 tekens: een productnaam, variant of SKU.',
    'No product found in the catalogue. Use "+ Add custom line" for a service or a special item.': 'Geen product gevonden in de catalogus. Gebruik "+ Vrije lijn toevoegen" voor een dienst of een speciaal artikel.',
    '{0} matches': '{0} resultaten', '{0} match': '{0} resultaat', 'SKU {0}': 'SKU {0}', 'No SKU': 'Geen SKU', 'incl. VAT': 'incl. btw', 'excl. VAT': 'excl. btw', 'Search failed.': 'Zoeken mislukt.', 'Close': 'Sluiten',
    'Live summary': 'Live overzicht', 'Complete the lines to see totals.': 'Vul de lijnen aan om de totalen te zien.', 'Add lines to see totals.': 'Voeg lijnen toe om de totalen te zien.', 'Subtotal excl. VAT': 'Subtotaal excl. btw',
    'VAT {0}% on {1}': 'Btw {0}% op {1}', 'Total VAT': 'Totaal btw', 'Total incl. VAT': 'Totaal incl. btw', 'Rounding adjustment': 'Afrondingscorrectie', 'Amount to pay': 'Te betalen bedrag', 'Amount due': 'Verschuldigd bedrag',
    // Homepage "Create an invoice" preview card (real latest-invoice data, see invoicePreviewNode() in app.js).
    'VAT {0}%': 'Btw {0}%', 'Blank template': 'Leeg sjabloon', '{0} more line': '{0} extra regel', '{0} more lines': '{0} extra regels', 'Preview unavailable.': 'Voorbeeld niet beschikbaar.',
    'Explicit rounding (EN 16931) so the catalogue price stays exactly as published.': 'Expliciete afronding (EN 16931) zodat de catalogusprijs exact blijft zoals gepubliceerd.', 'Calculated by the finance engine, not by this page.': 'Berekend door de financiële motor, niet door deze pagina.',
    'VAT ?': 'Btw ?', 'Catalogue {0} incl. VAT': 'Catalogus {0} incl. btw', '→ {0} excl. VAT': '→ {0} excl. btw', 'Catalogue price excl. VAT': 'Catalogusprijs excl. btw', 'Catalogue price kept': 'Catalogusprijs behouden',
    'Price override (excl. VAT)': 'Prijs aangepast (excl. btw)', 'More than in stock': 'Meer dan in voorraad', 'Confirm VAT rate': 'Bevestig het btw-tarief', 'Change product': 'Product wijzigen', 'Search product': 'Product zoeken',
    'Use catalogue price': 'Catalogusprijs gebruiken', 'Make custom': 'Vrije lijn maken', 'Remove line': 'Lijn verwijderen', 'Description': 'Omschrijving', 'Custom line: describe the service or item': 'Vrije lijn: omschrijf de dienst of het artikel',
    'Custom line': 'Vrije lijn', 'Stock': 'Voorraad', 'Qty': 'Aantal', 'Unit price excl. VAT': 'Eenheidsprijs excl. btw', 'Discount': 'Korting', 'Line total excl. VAT': 'Lijntotaal excl. btw',
    'Edit details': 'Details wijzigen', 'Change customer': 'Klant wijzigen', 'Company from your directory.': 'Bedrijf uit uw lijst.', 'Detach and edit manually': 'Loskoppelen en handmatig wijzigen', 'Company name': 'Bedrijfsnaam',
    'VAT number': 'Btw-nummer', 'Enterprise number': 'Ondernemingsnummer', 'Street and number': 'Straat en nummer', 'Postal code': 'Postcode', 'City': 'Gemeente', 'Country': 'Land', 'Email (optional)': 'E-mail (optioneel)',
    'Stored only if you enter it. Not needed for the invoice.': 'Enkel bewaard als u het invult. Niet nodig voor de factuur.', 'Save this company to my directory': 'Dit bedrijf bewaren in mijn lijst', 'Done': 'Klaar',
    'New B2B sale (outside the shop)': 'Nieuwe B2B-verkoop (buiten de winkel)', 'This is ADDITIVE revenue: it is counted on top of your shop and POS sales.': 'Dit is EXTRA omzet: ze komt bovenop uw winkel- en kassaverkopen.',
    'Invoice for an existing shop / POS order': 'Factuur voor een bestaande winkel- / kassabestelling', 'This invoice does NOT create additional revenue: the sale is already counted from the shop. Each order can have one active invoice.': 'Deze factuur creëert GEEN extra omzet: de verkoop wordt al door de winkel geteld. Elke bestelling kan één actieve factuur hebben.',
    'Linked to order {0}. No additional revenue will be counted.': 'Gekoppeld aan bestelling {0}. Er wordt geen extra omzet geteld.', 'Choose the order below.': 'Kies hieronder de bestelling.', 'Change order': 'Bestelling wijzigen', 'Find the order': 'Bestelling zoeken',
    'Only if the system warns that this looks like a shop sale: confirm it is a separate sale.': 'Enkel als het systeem waarschuwt dat dit op een winkelverkoop lijkt: bevestig dat het een aparte verkoop is.', 'Order number or product...': 'Bestelnummer of product…',
    'Select the shop / POS order': 'Selecteer de winkel- / kassabestelling', 'From': 'Van', 'Amount from': 'Bedrag van', 'Amount to': 'Bedrag tot', 'Order': 'Bestelling', 'Date': 'Datum', 'Channel': 'Kanaal', 'Items': 'Artikelen', 'Total': 'Totaal',
    'refunded {0}': 'terugbetaald {0}', 'Invoiced {0}': 'Gefactureerd {0}', 'Select': 'Selecteren', 'No matching orders.': 'Geen overeenkomstige bestellingen.',
    'VAT treatment': 'Btw-behandeling', 'Your confirmation': 'Uw bevestiging', 'I confirm this VAT treatment applies to this document': 'Ik bevestig dat deze btw-behandeling van toepassing is op dit document', 'Legal mention printed on the document': 'Wettelijke vermelding op het document',
    'e.g. VAT reverse charge - article 51 par. 2 ...': 'bv. Btw verlegd - artikel 51 §2 …', 'Required for this treatment. The system does not decide which text is legally correct: you do.': 'Vereist voor deze behandeling. Het systeem beslist niet welke tekst juridisch correct is: dat doet u.',
    'Submitted for approval': 'Ingediend voor goedkeuring', 'Saved as draft. Fix the listed items to submit.': 'Bewaard als ontwerp. Los de vermelde punten op om in te dienen.', 'Draft saved': 'Ontwerp bewaard', 'Before you save': 'Voor u bewaart',
    'Customer identified': 'Klant geïdentificeerd', 'Lines with prices': 'Lijnen met prijzen', 'VAT treatment confirmed': 'Btw-behandeling bevestigd', 'Revenue basis chosen': 'Omzetbasis gekozen', 'Customer': 'Klant', 'Dates and terms': 'Data en voorwaarden',
    'Issue {0} · {1}': 'Uitgifte {0} · {1}', 'Issue date': 'Uitgiftedatum', 'Valid until': 'Geldig tot', 'Due date': 'Vervaldatum', 'Leave empty to use the payment terms': 'Laat leeg om de betalingsvoorwaarden te gebruiken',
    'Payment terms (days)': 'Betalingstermijn (dagen)', 'Currency': 'Munt', 'Commercial terms': 'Commerciële voorwaarden', 'Payment terms text': 'Tekst betalingsvoorwaarden', 'Document language': 'Taal van het document',
    'Francais': 'Français', 'Français': 'Français', 'Nederlands': 'Nederlands', 'English': 'English', 'Revenue basis': 'Omzetbasis', 'Lines': 'Lijnen', 'Products come from your catalogue, prices from the shop': 'Producten komen uit uw catalogus, prijzen uit de winkel',
    'Product': 'Product', '+ Add product': '+ Product toevoegen', '+ Add custom line': '+ Vrije lijn toevoegen', 'Notes': 'Notities', 'Printed on the document': 'Afgedrukt op het document', 'Notes (printed on the document)': 'Notities (afgedrukt op het document)',
    'Save draft': 'Ontwerp bewaren', 'Save and review': 'Bewaren en nazien', 'Unit price': 'Eenheidsprijs', 'Net': 'Excl. btw', 'linked - no extra revenue': 'gekoppeld - geen extra omzet', 'standalone - additive': 'alleenstaand - extra',
    'today': 'vandaag', 'no terms': 'geen voorwaarden', '{0} days': '{0} dagen',
    'Edit draft': 'Ontwerp wijzigen', 'Submit for approval': 'Indienen voor goedkeuring', 'Send quote': 'Offerte versturen', 'This numbers the quote ({0}) and locks it. Send the PDF to your customer yourself; the system sends nothing.': 'Dit nummert de offerte ({0}) en vergrendelt ze. Stuur de PDF zelf naar uw klant; het systeem verstuurt niets.',
    'Number and lock': 'Nummeren en vergrendelen', 'Quote numbered': 'Offerte genummerd', 'Mark as sent': 'Markeren als verzonden', 'Quote accepted': 'Offerte aanvaard', 'Quote rejected': 'Offerte geweigerd', 'Invoice draft created from the quote': 'Factuurontwerp aangemaakt vanuit de offerte',
    'Convert to invoice': 'Omzetten naar factuur', 'Record that you have sent this document to your customer. The system does not send anything.': 'Leg vast dat u dit document naar uw klant stuurde. Het systeem verstuurt niets.', 'Mark sent': 'Markeer verzonden', 'Marked as sent': 'Gemarkeerd als verzonden',
    'Add payment': 'Betaling toevoegen', 'Create credit note': 'Creditnota maken', 'Cancel draft': 'Ontwerp annuleren', 'This draft will be cancelled. No number is used.': 'Dit ontwerp wordt geannuleerd. Er wordt geen nummer gebruikt.', 'Draft cancelled': 'Ontwerp geannuleerd',
    'Download PDF': 'PDF downloaden', 'Peppol/UBL file': 'Peppol/UBL-bestand', 'Ready': 'Klaar', 'Review before you approve.': 'Nazien voor u goedkeurt.',
    'Approving issues the document, assigns its number ({0}) and freezes it. Afterwards it can only be corrected with a credit note. Nothing is sent to your customer.': 'Goedkeuren geeft het document uit, kent het nummer ({0}) toe en bevriest het. Nadien kan het enkel met een creditnota verbeterd worden. Er wordt niets naar uw klant gestuurd.',
    'next in sequence': 'volgende in de reeks', 'Approve and issue': 'Goedkeuren en uitgeven', 'Issue this {0} now? It will receive the next number and cannot be edited afterwards.': 'Dit document ({0}) nu uitgeven? Het krijgt het volgende nummer en kan nadien niet meer gewijzigd worden.',
    'Approve': 'Goedkeuren', 'Modify': 'Wijzigen',
    '{0} {1}': '{0} {1}', 'not numbered yet': 'nog niet genummerd', '2-digit': '2-digit', '{0}: {1}': '{0}: {1}',
    'Cash position': 'Kaspositie', 'Bank + cash': 'Bank + kas', 'Connect a bank to see this': 'Koppel een bank om dit te zien',
    'Amount to collect': 'Openstaande facturen', 'Supplier bills due': 'Te betalen leveranciersfacturen', '{0} bill(s) to pay': '{0} factu(u)r(en) te betalen',
    'Critical actions': 'Kritieke acties', 'need your attention': 'vragen uw aandacht', 'all clear': 'niets te melden',
    'Trends': 'Trends', 'Payments received - last 7 days': 'Ontvangen betalingen - laatste 7 dagen', 'Invoices paid vs overdue': 'Betaalde vs achterstallige facturen',
    'Recent activity': 'Recente activiteit', 'Loading...': 'Laden...', 'Nothing yet': 'Nog niets',
    'Issued invoices, payments and credit notes will show up here.': 'Uitgereikte facturen, betalingen en creditnota\'s verschijnen hier.', 'Activity unavailable.': 'Activiteit niet beschikbaar.',
    'a document': 'een document', '{0} issued': '{0} uitgereikt', '{0} marked as sent': '{0} gemarkeerd als verzonden', '{0} sent': '{0} verzonden',
    'Payment of {0} received on {1}': 'Betaling van {0} ontvangen op {1}', 'Payment received on {0}': 'Betaling ontvangen op {0}', '{0} created': '{0} aangemaakt',
    '{0} accepted': '{0} geaccepteerd', '{0} rejected': '{0} geweigerd', '{0} submitted for approval': '{0} ingediend ter goedkeuring',
    '{0} cancelled': '{0} geannuleerd', '{0} returned to draft': '{0} teruggezet naar concept', '{0} status updated': 'Status van {0} bijgewerkt',
    'Impact of this credit note': 'Impact van deze creditnota', 'Original invoice': 'Oorspronkelijke factuur', 'Credit note amount': 'Bedrag van de creditnota', 'Effect on balance': 'Effect op het saldo',
    '{0} owed on {1}': '{0} verschuldigd op {1}', 'VAT impact': 'Btw-impact', '{0} VAT reversed': '{0} btw teruggedraaid', 'Restock decision': 'Herbevoorradingsbeslissing', 'Refund': 'Terugbetaling',
    'Not linked yet': 'Nog niet gekoppeld', 'Not applicable (original sale did not decrement stock)': 'Niet van toepassing (oorspronkelijke verkoop verminderde de voorraad niet)',
    'Decision pending': 'Beslissing in behandeling', 'Restocked': 'Herbevoorraad', 'Restock approved (processing)': 'Herbevoorrading goedgekeurd (in verwerking)', 'Not restocked (merchant declined)': 'Niet herbevoorraad (geweigerd door handelaar)',
    'Not tracked separately - deducts from what the customer owes': 'Niet apart bijgehouden - wordt in mindering gebracht op wat de klant verschuldigd is',
    'Reason: {0}': 'Reden: {0}', 'Draft - this impact applies once the credit note is approved and issued.': 'Concept - deze impact geldt zodra de creditnota is goedgekeurd en uitgereikt.',
    'Customers': 'Klanten', 'Search an invoice, a client, a supplier...': 'Zoek een factuur, een klant, een leverancier...', 'Finance navigation': 'Financiën-navigatie', 'Notifications': 'Meldingen',
    'Here is a summary of your financial activity.': 'Hier is het overzicht van uw financiële activiteit.', 'vs. last month': 'vs. vorige maand', 'Revenue': 'Omzet', 'Expenses': 'Uitgaven',
    'Cash-flow unavailable.': 'Kasstroom niet beschikbaar.', 'Last 3 months': 'Laatste 3 maanden', 'Last 6 months': 'Laatste 6 maanden', 'Last 12 months': 'Laatste 12 maanden',
    'Real inflows, outflows and running balance': 'Werkelijke instromen, uitstromen en lopend saldo', 'Inflows': 'Instromen', 'Outflows': 'Uitstromen', 'Cumulative balance': 'Cumulatief saldo',
    'Quick actions': 'Snelle acties', 'Create an invoice': 'Factuur aanmaken', 'Add an expense': 'Uitgave toevoegen', 'New client': 'Nieuwe klant', 'Import a bank statement': 'Bankafschrift importeren',
    'Upcoming due dates': 'Komende vervaldata', 'See all': 'Alles bekijken', '{0} day(s) late': '{0} dag(en) te laat', 'Due {0}': 'Vervalt {0}', 'Nothing coming up.': 'Niets op komst.',
    'Client invoices': 'Klantfacturen', 'tab2 {}': 'tab2 {}', 'Nothing here.': 'Niets hier.', 'Invoice no.': 'Factuurnr.', 'Bank accounts': 'Bankrekeningen',
    'Connected account': 'Gekoppelde rekening', 'No bank account connected': 'Geen bankrekening gekoppeld', 'Read-only: no payment can ever be initiated.': 'Alleen-lezen: er kan nooit een betaling worden gestart.',
    'Connect a read-only account': 'Alleen-lezen rekening koppelen', 'Breakdown by supplier': 'Verdeling per leverancier',
    'var(--accent)': 'var(--accent)', 'var(--warm)': 'var(--warm)', 'var(--info)': 'var(--info)', 'var(--ok)': 'var(--ok)', 'var(--muted)': 'var(--muted)', 'rotate(-90 {} {})': 'rotate(-90 {} {})',
    'No supplier invoices yet.': 'Nog geen leveranciersfacturen.', 'balance': 'saldo', 'Client': 'Klant', '{0} {1},': '{0} {1},', '{0},': '{0},',
    'tab2 {0}': 'tab2 {0}', 'rotate(-90 {0} {0})': 'rotate(-90 {0} {0})',
    'Connect the bank': 'Koppel de bank', '{0} unpaid invoice': '{0} onbetaalde factuur', '{0} unpaid invoices': '{0} onbetaalde facturen',
    'Revenue − recorded expenses: {0}': 'Omzet − geregistreerde uitgaven: {0}', '(not an accounting net profit figure - no VAT, depreciation or accruals)': '(geen boekhoudkundige nettowinst - exclusief btw, afschrijvingen en overlopende posten)',
    'Invoice status': 'Factuurstatus', '{0} invoice': '{0} factuur', '{0} invoices': '{0} facturen',
    'Not enough history yet': 'Nog niet genoeg geschiedenis', 'Record payments and supplier bills to see real cash movement here.': 'Registreer betalingen en leveranciersfacturen om hier echte kasstromen te zien.',
    'Real inflows, outflows and running documented balance': 'Werkelijke, gedocumenteerde instromen, uitstromen en lopend saldo', 'Revenue vs. expenses': 'Omzet vs uitgaven',
    'Due dates': 'Vervaldata', 'Nothing overdue.': 'Niets te laat.', 'Upcoming': 'Binnenkort', 'Nothing due soon.': 'Niets binnenkort te vervallen.',
    'Last sync: {0}': 'Laatste synchronisatie: {0}', 'Latest transactions': 'Laatste transacties', '(no counterparty)': '(geen tegenpartij)', 'Connect bank': 'Bank koppelen',
    '{0} - your only supplier so far. A breakdown becomes useful once you have more than one.': '{0} - vooralsnog uw enige leverancier. Een verdeling wordt nuttig zodra u er meer dan één heeft.',
    'LINKED: this invoice documents an existing shop/POS sale. It does NOT create additional revenue.': 'GEKOPPELD: deze factuur documenteert een bestaande winkel-/kassaverkoop. Ze creëert GEEN extra omzet.',
    'STANDALONE: this is a new B2B sale outside the shop. It is ADDITIVE revenue.': 'ZELFSTANDIG: dit is een nieuwe B2B-verkoop buiten de winkel. Dit is bijkomende omzet.',
    'Returned to draft': 'Teruggezet naar ontwerp', 'Reject': 'Weigeren', 'The draft will be cancelled. No number is used.': 'Het ontwerp wordt geannuleerd. Er wordt geen nummer gebruikt.', 'Not ready to issue:': 'Nog niet klaar om uit te geven:',
    'INTEGRITY WARNING: the stored fingerprint does not match this document. Do not use it and contact support.': 'INTEGRITEITSWAARSCHUWING: de opgeslagen vingerafdruk komt niet overeen met dit document. Gebruik het niet en contacteer de support.',
    'Seller': 'Verkoper', 'Name': 'Naam', 'Address': 'Adres', 'VAT / no.': 'Btw / nr.', 'Email': 'E-mail', 'Details': 'Details', 'Number': 'Nummer', '(assigned on approval: {0})': '(toegekend bij goedkeuring: {0})', 'next': 'volgende',
    'Payment terms': 'Betalingsvoorwaarden', 'Legal mention': 'Wettelijke vermelding', 'Language': 'Taal', 'Related': 'Gerelateerd', 'Converted to': 'Omgezet naar', 'Invoice {0}': 'Factuur {0}', '(draft)': '(ontwerp)', 'Shop/POS order': 'Winkel-/kassabestelling',
    'Totals': 'Totalen', 'Amount': 'Bedrag', 'Method': 'Methode', 'Reference': 'Referentie', 'Credit notes': 'Creditnota\'s', 'PDF preview': 'PDF-voorbeeld', '(draft watermark)': '(watermerk ontwerp)', 'Show preview': 'Voorbeeld tonen', 'Audit trail': 'Auditspoor',
    'When': 'Wanneer', 'Action': 'Actie', 'Status': 'Status', 'Peppol: NOT CONFIGURED. Structured invoices can be prepared, but nothing is transmitted until a provider is selected.': 'Peppol: NIET GECONFIGUREERD. Gestructureerde facturen kunnen voorbereid worden, maar er wordt niets verzonden zolang er geen aanbieder gekozen is.',
    'Cancel': 'Annuleren', 'Bank transfer': 'Overschrijving', 'Cash': 'Contant', 'Card': 'Kaart', 'Other': 'Andere', 'Bank reference (optional)': 'Bankreferentie (optioneel)', 'Note (optional)': 'Notitie (optioneel)', 'Add a payment': 'Een betaling toevoegen',
    'Still due: {0} {1}': 'Nog verschuldigd: {0} {1}', 'Date paid': 'Betaaldatum', 'Note': 'Notitie', 'Payment recorded': 'Betaling geregistreerd', 'Record payment': 'Betaling registreren', 'Reason (required)': 'Reden (verplicht)', 'Remove': 'Verwijderen',
    'Create a credit note': 'Een creditnota maken', 'A credit note corrects an issued invoice. The invoice itself is never changed.': 'Een creditnota corrigeert een uitgegeven factuur. De factuur zelf wordt nooit gewijzigd.', 'Reason': 'Reden', 'Credit the whole invoice': 'De hele factuur crediteren',
    'Credit note draft created': 'Ontwerp van creditnota aangemaakt', 'Create draft': 'Ontwerp maken',
    'Add a company': 'Een bedrijf toevoegen', 'Search name or VAT number...': 'Zoek een naam of btw-nummer…', 'Company': 'Bedrijf', 'Source': 'Bron',
    'No companies yet. They are added automatically when you create an invoice, or click "Add a company".': 'Nog geen bedrijven. Ze worden automatisch toegevoegd wanneer u een factuur maakt, of klik op "Een bedrijf toevoegen".',
    'Country (2 letters)': 'Land (2 letters)', 'This company is already in your directory': 'Dit bedrijf staat al in uw lijst', 'Edit company': 'Bedrijf wijzigen', 'Company saved': 'Bedrijf bewaard', 'Save': 'Bewaren',
    '{0} - source: {1}': '{0} - bron: {1}', 'no number': 'geen nummer', 'Edit': 'Wijzigen', 'Outstanding ({0})': 'Openstaand ({0})', 'Paid so far ({0} payment(s){1})': 'Tot nu betaald ({0} betaling(en){1})', ', last {0}': ', laatste op {0}',
    'Peppol ID': 'Peppol-id', 'Credit scoring': 'Kredietscore', 'Not implemented (no solvency provider)': 'Niet geïmplementeerd (geen solvabiliteitsaanbieder)', 'Documents': 'Documenten', 'Type': 'Type', 'No documents yet.': 'Nog geen documenten.',
    'Payments and receivables': 'Betalingen en vorderingen', 'No reminders are sent automatically.': 'Er worden geen herinneringen automatisch verstuurd.', 'Unpaid': 'Onbetaald', 'Due soon': 'Binnenkort verschuldigd', '{0}: {1} invoice(s) ({2})': '{0}: {1} factu(u)r(en) ({2})',
    'Ageing (days past due)': 'Ouderdom (dagen te laat)', 'Open invoices': 'Openstaande facturen', 'Due': 'Vervaldatum', 'Days late': 'Dagen te laat', 'Still due': 'Nog verschuldigd', 'No open invoices.': 'Geen openstaande facturen.',
    'Open an invoice from the Invoices page to register a payment.': 'Open een factuur via de pagina Facturen om een betaling te registreren.', 'Shop/POS sales come from the validated retail figures; only standalone B2B invoices are added.': 'Winkel-/kassaverkopen komen uit de gevalideerde retailcijfers; enkel alleenstaande B2B-facturen worden toegevoegd.',
    'Generate pack': 'Pakket genereren', 'Generating...': 'Genereren…', 'Reconciliation: {0}': 'Afstemming: {0}', 'generated {0}': 'gegenereerd op {0}', 'All source data for this period is present.': 'Alle brongegevens voor deze periode zijn aanwezig.',
    'Sources: {0}': 'Bronnen: {0}', 'Shop and POS (retail)': 'Winkel en kassa (retail)', 'Gross sales': 'Brutoverkopen', 'Discounts': 'Kortingen', 'Refunds': 'Terugbetalingen', 'Net sales incl. VAT': 'Nettoverkopen incl. btw', 'Net sales excl. VAT': 'Nettoverkopen excl. btw',
    'POS excl. VAT': 'Kassa excl. btw', 'Online excl. VAT': 'Online excl. btw', 'Invoices and credit notes': 'Facturen en creditnota\'s', 'Standalone B2B invoices': 'Alleenstaande B2B-facturen', 'Standalone credit notes': 'Alleenstaande creditnota\'s', 'B2B net excl. VAT': 'B2B netto excl. btw',
    'B2B VAT': 'B2B-btw', 'Linked invoices (not added)': 'Gekoppelde facturen (niet toegevoegd)', 'Credit notes issued': 'Uitgegeven creditnota\'s', 'Totals (retail + standalone B2B)': 'Totalen (retail + alleenstaande B2B)', 'Sales excl. VAT': 'Verkopen excl. btw',
    'VAT collected': 'Geïnde btw', 'Sales incl. VAT': 'Verkopen incl. btw', 'VAT by rate': 'Btw per tarief', 'Rate': 'Tarief', 'Taxable base': 'Belastbare basis',
    'Unavailable: {0} retail line(s) have no captured VAT rate (base {1}, VAT {2}). They are not spread across rates.': 'Niet beschikbaar: {0} retaillijn(en) hebben geen vastgelegd btw-tarief (basis {1}, btw {2}). Ze worden niet over de tarieven verdeeld.',
    'B2B {0}: base {1} (no VAT)': 'B2B {0}: basis {1} (geen btw)', 'Payment status of B2B invoices in the period': 'Betalingsstatus van de B2B-facturen in de periode', '{0} invoice(s) - {1}': '{0} factu(u)r(en) - {1}',
    'Anomalies ({0})': 'Afwijkingen ({0})', 'None detected.': 'Geen vastgesteld.', 'Downloads': 'Downloads',
    'Your company details, numbering and VAT rates. No passwords or keys are stored here.': 'De gegevens van uw bedrijf, de nummering en de btw-tarieven. Hier worden geen wachtwoorden of sleutels bewaard.',
    'Still needed before real invoices:': 'Nog nodig voor echte facturen:', 'Your company (seller)': 'Uw bedrijf (verkoper)', 'Legal name': 'Juridische naam', 'Finance email': 'Finance-e-mail', 'BIC (optional)': 'BIC (optioneel)',
    'VAT and payment': 'Btw en betaling', 'Allowed VAT rates (%)': 'Toegelaten btw-tarieven (%)', 'The rates you may choose on domestic invoices. You decide these; nothing is assumed.': 'De tarieven die u kunt kiezen op binnenlandse facturen. U beslist; er wordt niets verondersteld.',
    'Default payment terms (days)': 'Standaard betalingstermijn (dagen)', 'Default language': 'Standaardtaal', 'Extra payment instructions': 'Extra betalingsinstructies',
    'Print a Belgian structured communication (+++xxx/xxxx/xxxxx+++)': 'Een Belgische gestructureerde mededeling afdrukken (+++xxx/xxxx/xxxxx+++)', 'Numbering': 'Nummering', 'Invoice prefix': 'Voorvoegsel facturen', 'Credit note prefix': 'Voorvoegsel creditnota\'s',
    'Quote prefix': 'Voorvoegsel offertes', 'Digits': 'Cijfers', 'Format': 'Formaat', 'Use {prefix}, {year} and {seq}, e.g. {prefix}-{year}-{seq} gives INV-2026-0001. Numbers are assigned when a document is issued and never skip.': 'Gebruik {prefix}, {year} en {seq}, bv. {prefix}-{year}-{seq} geeft INV-2026-0001. Nummers worden toegekend bij uitgifte en slaan nooit over.',
    'Look and feel': 'Uitzicht', 'Accent colour': 'Accentkleur', 'Footer text on documents': 'Voettekst op documenten', 'Logo (PNG or JPEG, max 400 KB)': 'Logo (PNG of JPEG, max. 400 KB)', 'a logo is set': 'een logo is ingesteld', 'Logo saved': 'Logo bewaard',
    'Company lookup and e-invoicing': 'Bedrijvenzoeker en e-facturatie', 'VAT / enterprise number lookup': 'Zoeken op btw- / ondernemingsnummer', 'EU VIES (free, official) with manual fallback': 'EU VIES (gratis, officieel) met handmatige terugval',
    'Manual entry only': 'Enkel handmatige invoer', 'Belgian company register (primary)': 'Belgisch ondernemingsregister (primair)', 'CBEAPI: official KBO/BCE data (needs CBEAPI_KEY)': 'CBEAPI: officiële KBO-gegevens (vereist CBEAPI_KEY)', 'Off': 'Uit',
    'Secondary name search (if the register finds nothing)': 'Secundair zoeken op naam (als het register niets vindt)', 'OpenPeppol Directory (Peppol-registered companies) + VIES for the address': 'OpenPeppol-directory (bedrijven op Peppol) + VIES voor het adres',
    'Off: search by number or type by hand': 'Uit: zoeken op nummer of handmatig invoeren', 'Peppol provider': 'Peppol-aanbieder', 'Nothing is transmitted. Structured invoices (UBL) can be prepared and downloaded.': 'Er wordt niets verzonden. Gestructureerde facturen (UBL) kunnen voorbereid en gedownload worden.',
    'Settings saved': 'Instellingen bewaard', 'Save settings': 'Instellingen bewaren',
  };
  const patterns = [
    [/^(\d+) companies found\. Choose the right one\.(.*)$/, '{0} bedrijven gevonden. Kies het juiste.{1}'],
    [/^One company found\. Select it to fill the form\.(.*)$/, 'Eén bedrijf gevonden. Selecteer het om het formulier in te vullen.{0}'],
    [/^One company found\.$/, 'Eén bedrijf gevonden.'],
    [/^Rounding: the invoice total for one unit is ([\d.]+), the shop price is ([\d.]+)\.$/, 'Afronding: het factuurtotaal voor één eenheid is {0}, de winkelprijs is {1}.'],
    [/^VAT rate: not set automatically \(no consistent sales history for this product\)\. The catalogue price is ([\d.]+) including VAT and will be kept once you choose the rate\.$/, 'Btw-tarief: niet automatisch ingesteld (geen consistente verkoopgeschiedenis voor dit product). De catalogusprijs is {0} incl. btw en blijft behouden zodra u het tarief kiest.'],
    [/^(\d+) sole traders? (?:was|were) not listed \(personal data\): search by exact enterprise \/ VAT number to find one\.$/, '{0} eenmanszaak/-zaken niet weergegeven (persoonsgegevens): zoek op het exacte ondernemings- / btw-nummer om er een te vinden.'],
  ];
  Object.assign(messages, {
    'Filled in from the Belgian company register.': 'Ingevuld vanuit het Belgisch ondernemingsregister.',
    'No active VAT registration was found in VIES, so the VAT number was left empty.': 'Er werd geen actieve btw-registratie gevonden in VIES: het btw-nummer werd leeg gelaten.',
    'The VAT number could not be checked right now, so it was left empty.': 'Het btw-nummer kon nu niet gecontroleerd worden en werd leeg gelaten.',
    'Official data filled in from EU VIES. Check it before saving.': 'Officiële gegevens ingevuld vanuit EU VIES. Controleer ze voor u bewaart.',
    'The official lookup is not available right now. The name and enterprise number were kept: complete the address by hand.': 'De officiële opzoeking is momenteel niet beschikbaar. De naam en het ondernemingsnummer werden bewaard: vul het adres handmatig aan.',
    'This number is not VAT-registered according to VIES, so no address is available. The name and enterprise number were kept: complete the rest by hand.': 'Dit nummer is volgens VIES niet btw-plichtig: er is geen adres beschikbaar. De naam en het ondernemingsnummer werden bewaard: vul de rest handmatig aan.',
    'Type at least 3 letters of the name, or a VAT / enterprise number.': 'Typ minstens 3 letters van de naam, of een btw- / ondernemingsnummer.',
    'This is not a valid Belgian VAT / enterprise number. Check it, or enter the company manually.': 'Dit is geen geldig Belgisch btw- / ondernemingsnummer. Controleer het, of voer het bedrijf handmatig in.',
    'This company is already in your directory.': 'Dit bedrijf staat al in uw lijst.', 'Official data found and filled in. Check it, then save.': 'Officiële gegevens gevonden en ingevuld. Controleer ze en bewaar.',
    'The official VAT lookup is switched off in Settings. Enter the company manually.': 'De officiële btw-opzoeking staat uit in de Instellingen. Voer het bedrijf handmatig in.',
    'The number is valid but VIES has no VAT registration for it. Enter the company manually.': 'Het nummer is geldig maar VIES heeft er geen btw-registratie voor. Voer het bedrijf handmatig in.',
    'The official lookup is not available right now. Enter the company manually.': 'De officiële opzoeking is momenteel niet beschikbaar. Voer het bedrijf handmatig in.',
    'Showing your saved companies. Company-name search is not configured: use a VAT number or enter manually.': 'Uw bewaarde bedrijven worden getoond. Zoeken op bedrijfsnaam is niet geconfigureerd: gebruik een btw-nummer of voer handmatig in.',
    'Company-name search is not configured. Search by VAT / enterprise number, or enter the company manually.': 'Zoeken op bedrijfsnaam is niet geconfigureerd. Zoek op btw- / ondernemingsnummer, of voer het bedrijf handmatig in.',
    'The company search is not available right now.': 'De bedrijvenzoeker is momenteel niet beschikbaar.', 'Showing your saved companies.': 'Uw bewaarde bedrijven worden getoond.', 'Enter the company manually.': 'Voer het bedrijf handmatig in.',
    'No company found. This search only knows companies registered on Peppol: try the VAT / enterprise number, or enter the company manually.': 'Geen bedrijf gevonden. Deze zoekopdracht kent enkel bedrijven op Peppol: probeer het btw- / ondernemingsnummer, of voer het bedrijf handmatig in.',
    'Current price could not be read: type the unit price yourself.': 'De huidige prijs kon niet gelezen worden: typ de eenheidsprijs zelf.',
    'VAT rate: not set automatically (no consistent sales history for this product). Choose it yourself.': 'Btw-tarief: niet automatisch ingesteld (geen consistente verkoopgeschiedenis voor dit product). Kies het zelf.',
  });
  Object.assign(messages, {
    'Selling': 'Verkoop',
    'Buying': 'Leveranciers',
    'Finance Inbox': 'Financiële inbox',
    'Purchases': 'Aankopen',
    'Accountant': 'Boekhouder',
    'This invoice took products out of stock. Are the goods returned to sellable stock?': 'Deze factuur haalde producten uit de voorraad. Komen de goederen terug in verkoopbare voorraad?',
    'Yes, put them back into stock': 'Ja, terug in voorraad plaatsen',
    'No, do not change the stock': 'Nee, de voorraad niet wijzigen',
    '{0} setting(s) missing to issue real invoices': '{0} instelling(en) ontbreken om echte facturen uit te geven',
    '{0} invoice(s) are overdue: {1} to collect': '{0} factu(u)r(en) te laat: {1} te innen',
    '{0} to collect in the next {1} days': '{0} te innen in de volgende {1} dagen',
    '{0} invoice(s) waiting for your approval': '{0} factu(u)r(en) wachten op uw goedkeuring',
    '{0} document(s) are missing VAT information': '{0} document(en) missen btw-informatie',
    '{0} accepted quote(s) can become invoices': '{0} aanvaarde offerte(s) kunnen facturen worden',
    '{0} supplier invoice(s) require validation': '{0} leveranciersfactu(u)r(en) te valideren',
    '{0} supplier invoice(s) to pay: {1}': '{0} leveranciersfactu(u)r(en) te betalen: {1}',
    '{0} stock movement(s) need your attention': '{0} voorraadbeweging(en) vragen uw aandacht',
    'Q{0} {1} closes in {2} days': 'K{0} {1} sluit over {2} dagen',
    'The accountant pack for {0} is ready': 'Het boekhoudpakket voor {0} is klaar',
    'The accountant pack for {0} needs review ({1} anomalies)': 'Het boekhoudpakket voor {0} moet nagekeken worden ({1} afwijkingen)',
    '{0} orders reconciled': '{0} bestellingen afgestemd',
    'Review': 'Nakijken',
    'Validate supplier invoices': 'Leveranciersfacturen valideren',
    'Prepare the accountant file': 'Het boekhoudpakket voorbereiden',
    'Action Center': 'Actiecentrum',
    'What to do next': 'Wat u nu moet doen',
    'Nothing needs your attention': 'Niets vraagt uw aandacht',
    'Everything is up to date.': 'Alles is bij.',
    'Peppol': 'Peppol',
    'E-mail': 'E-mail',
    'Upload': 'Upload',
    'Manual': 'Handmatig',
    'Received': 'Ontvangen',
    'To review': 'Na te kijken',
    'Validated': 'Gevalideerd',
    'To pay': 'Te betalen',
    'No automatic extraction': 'Geen automatische extractie',
    'Confidence {0}%': 'Betrouwbaarheid {0}%',
    'Supplier name is missing': 'De naam van de leverancier ontbreekt',
    'Invoice number is missing': 'Het factuurnummer ontbreekt',
    'Invoice date is missing or invalid': 'De factuurdatum ontbreekt of is ongeldig',
    'Due date is invalid': 'De vervaldatum is ongeldig',
    'Amount excl. VAT is missing': 'Het bedrag excl. btw ontbreekt',
    'VAT amount is missing': 'Het btw-bedrag ontbreekt',
    'Amount incl. VAT is missing': 'Het bedrag incl. btw ontbreekt',
    'Excl. VAT + VAT does not equal the total': 'Excl. btw + btw is niet gelijk aan het totaal',
    'Currency is missing': 'De munt ontbreekt',
    'Supplier invoice': 'Leveranciersfactuur',
    'Rejected: {0}': 'Geweigerd: {0}',
    'The extracted totals do not add up: check them.': 'De geëxtraheerde totalen kloppen niet: controleer ze.',
    'This looks like a supplier credit note: review it manually.': 'Dit lijkt op een creditnota van een leverancier: bekijk ze handmatig.',
    'Open the source document': 'Brondocument openen',
    'Supplier': 'Leverancier',
    'Supplier VAT number': 'Btw-nummer leverancier',
    'Invoice number': 'Factuurnummer',
    'Invoice date': 'Factuurdatum',
    'Excl. VAT': 'Excl. btw',
    'Incl. VAT': 'Incl. btw',
    'Payment reference': 'Betalingsreferentie',
    'Still needed before validation:': 'Nog nodig voor de validatie:',
    'Saved': 'Bewaard',
    'Validate': 'Valideren',
    'Reject this document': 'Dit document weigeren',
    'It is not a supplier invoice, or it is a duplicate.': 'Het is geen leveranciersfactuur, of het is een dubbel.',
    'Marked to pay': 'Gemarkeerd om te betalen',
    'Mark to pay': 'Markeer om te betalen',
    'Reopened': 'Heropend',
    'Reopen for correction': 'Heropenen om te corrigeren',
    'Record the payment': 'De betaling registreren',
    'Amount: {0} {1}': 'Bedrag: {0} {1}',
    'Mark as paid': 'Markeren als betaald',
    'Paid on {0}': 'Betaald op {0}',
    'Incoming financial documents, reviewed by you before anything is recorded.': 'Binnenkomende financiële documenten, door u nagekeken voor er iets geregistreerd wordt.',
    '+ Add manually': '+ Handmatig toevoegen',
    'File upload': 'Bestand uploaden',
    'Dedicated finance mailbox': 'Aparte finance-mailbox',
    'Peppol invoices received': 'Ontvangen Peppol-facturen',
    'Active': 'Actief',
    'Drop invoices here, or click to choose': 'Sleep facturen hierheen, of klik om te kiezen',
    'PDF, image or structured XML (UBL). They stay private and are never sent anywhere.': 'PDF, afbeelding of gestructureerde XML (UBL). Ze blijven privé en worden nergens naartoe verstuurd.',
    '{0} was already received': '{0} was al ontvangen',
    '{0} received': '{0} ontvangen',
    'The inbox is empty': 'De inbox is leeg',
    'Documents you receive will appear here for review.': 'Ontvangen documenten verschijnen hier ter controle.',
    'Unknown supplier': 'Onbekende leverancier',
    'Add a supplier invoice manually': 'Een leveranciersfactuur handmatig toevoegen',
    'Supplier invoices you validated: to pay and paid.': 'Leveranciersfacturen die u valideerde: te betalen en betaald.',
    'Open the Finance Inbox': 'De financiële inbox openen',
    'No supplier invoices yet': 'Nog geen leveranciersfacturen',
    'Validate a document from the Finance Inbox to see it here.': 'Valideer een document uit de financiële inbox om het hier te zien.',
    'Validated, not yet to pay': 'Gevalideerd, nog niet te betalen',
    'supplier invoice(s)': 'leveranciersfactu(u)r(en)',
    'Month': 'Maand',
    'Quarter': 'Kwartaal',
    'Year': 'Jaar',
    'Custom period': 'Aangepaste periode',
    'Period': 'Periode',
    'No accountant address is set: add it in Settings.': 'Er is geen adres van de boekhouder ingesteld: voeg het toe in de Instellingen.',
    'The period data is incomplete: see the anomalies file in the package.': 'De gegevens van de periode zijn onvolledig: zie het bestand met afwijkingen in het pakket.',
    'Direct sending is not configured: download the package or the .eml file and send it yourself.': 'Rechtstreeks verzenden is niet geconfigureerd: download het pakket of het .eml-bestand en verstuur het zelf.',
    'Preview': 'Voorbeeld',
    'Recipient': 'Ontvanger',
    'Message': 'Bericht',
    'Subject': 'Onderwerp',
    'Attachment': 'Bijlage',
    'Contents': 'Inhoud',
    '{0} invoice(s) · {1} credit note(s) · {2} refund(s) · {3} supplier invoice(s)': '{0} factu(u)r(en) · {1} creditnota(\'s) · {2} terugbetaling(en) · {3} leveranciersfactu(u)r(en)',
    'Download the ZIP': 'De ZIP downloaden',
    'Download the .eml (fallback)': 'Het .eml downloaden (alternatief)',
    'Send to accountant': 'Naar de boekhouder sturen',
    'Nothing is sent until you approve.': 'Er wordt niets verstuurd tot u goedkeurt.',
    'Sent to the accountant': 'Naar de boekhouder verstuurd',
    'APPROVE and send': 'GOEDKEUREN en versturen',
    'You are about to send {0} to:': 'U staat op het punt {0} te sturen naar:',
    'The package contains your sales, VAT and documents for the period. Sending goes through: {0}.': 'Het pakket bevat uw verkopen, btw en documenten van de periode. Verzending gebeurt via: {0}.',
    'I approve sending this package to this recipient.': 'Ik keur het versturen van dit pakket naar deze ontvanger goed.',
    'Close the period': 'De periode afsluiten',
    'One click: the whole accountant file, checked and ready.': 'Eén klik: het hele boekhoudpakket, gecontroleerd en klaar.',
    'Stored on this computer only': 'Enkel op deze computer bewaard',
    'Name / company': 'Naam / bedrijf',
    'Preferred export format': 'Voorkeursformaat voor export',
    'ZIP package': 'ZIP-pakket',
    'Excel (XLSX)': 'Excel (XLSX)',
    'Accounting software / provider': 'Boekhoudsoftware / aanbieder',
    'Name used in file names': 'Naam in de bestandsnamen',
    'Pending': 'In behandeling',
    'Applied': 'Toegepast',
    'Failed': 'Mislukt',
    'Uncertain': 'Onzeker',
    'Skipped': 'Overgeslagen',
    'Stock synchronisation': 'Voorraadsynchronisatie',
    'Shopify stays the source of truth': 'Shopify blijft de bron van waarheid',
    'A standalone B2B invoice takes its catalogue products out of Shopify stock once, when it is issued. Shop and POS invoices never do.': 'Een alleenstaande B2B-factuur haalt zijn catalogusproducten één keer uit de Shopify-voorraad, bij uitgifte. Winkel- en kassafacturen doen dat nooit.',
    'The Shopify permission to adjust inventory is granted.': 'De Shopify-toestemming om de voorraad aan te passen is verleend.',
    'The Shopify permission write_inventory is not granted yet: movements wait as pending.': 'De Shopify-toestemming write_inventory is nog niet verleend: bewegingen blijven in behandeling.',
    'The Shopify permission could not be checked.': 'De Shopify-toestemming kon niet gecontroleerd worden.',
    'Mode': 'Modus',
    'Dry run (report only)': 'Proefrun (enkel rapport)',
    'Live': 'Live',
    'Stock location': 'Voorraadlocatie',
    'Automatic if there is a single location': 'Automatisch als er één locatie is',
    'Blocked: {0}': 'Geblokkeerd: {0}',
    '{0} movement(s) applied': '{0} beweging(en) toegepast',
    'Apply pending movements': 'Bewegingen in behandeling toepassen',
    '{0} missing movement(s) created': '{0} ontbrekende beweging(en) aangemaakt',
    'Reconcile': 'Afstemmen',
    'Finance Inbox source': 'Bron van de financiële inbox',
    'Only finance messages, never a personal mailbox': 'Enkel financiële berichten, nooit een persoonlijke mailbox',
    'Documents enter through a dedicated finance address only. Nothing reads your personal or historical mailbox.': 'Documenten komen enkel binnen via een aparte finance-adres. Niets leest uw persoonlijke of historische mailbox.',
    'Dedicated finance address': 'Aparte finance-adres',
    'Allowed senders (comma separated)': 'Toegelaten afzenders (gescheiden door komma\'s)',
    'Provider-neutral until the topology is confirmed': 'Aanbieder-neutraal tot de topologie bevestigd is',
    'Do not register a second receiving Access Point before the topology is confirmed with your accountant / provider.': 'Registreer geen tweede ontvangend toegangspunt voor de topologie bevestigd is met uw boekhouder / aanbieder.',
    'Who owns the current receiving registration?': 'Wie bezit de huidige registratie voor ontvangst?',
    'Is Codabox VOILA the receiver?': 'Is Codabox VOILA de ontvanger?',
    'Does it expose an export or an API?': 'Biedt het een export of een API?',
    'Should we only send through another Access Point, or integrate the existing one?': 'Moeten we enkel via een ander toegangspunt verzenden, of het bestaande integreren?',
    'Current receiving Access Point': 'Huidig ontvangend toegangspunt',
    'Unknown': 'Onbekend',
    'Codabox': 'Codabox',
    'Decision': 'Beslissing',
    'Undecided': 'Onbeslist',
    'Send only (through another Access Point)': 'Enkel verzenden (via een ander toegangspunt)',
    'Receive through the existing provider': 'Ontvangen via de bestaande aanbieder',
    'Integrated with the existing provider': 'Geïntegreerd met de bestaande aanbieder',
    'Confirmed with': 'Bevestigd met',
    'Confirmed on': 'Bevestigd op',
    'Sending: {0}': 'Verzenden: {0}',
    'Receiving: {0}': 'Ontvangen: {0}',
    'Connectors': 'Connectoren',
    'Replaceable: nothing is hard-wired to one provider': 'Vervangbaar: niets ligt vast aan één aanbieder',
    'Applying': 'Wordt toegepast',
    'Stock movements': 'Voorraadbewegingen',
    'Line': 'Lijn',
    'Change': 'Wijziging',
    'Shopify adjustment': 'Shopify-aanpassing',
    'Not sent': 'Niet verzonden',
    'Delivered': 'Afgeleverd',
    'Prepared': 'Voorbereid',
    'The Access Point reported a problem: {0}': 'Het toegangspunt meldde een probleem: {0}',
    'Confirm the Peppol topology in Settings before sending.': 'Bevestig de Peppol-topologie in de Instellingen voor u verzendt.',
    'Send via Peppol': 'Verzenden via Peppol',
    'This sends the structured invoice through your Peppol Access Point. It cannot be recalled.': 'Dit verzendt de gestructureerde factuur via uw Peppol-toegangspunt. Ze kan niet teruggehaald worden.',
    'Sent via Peppol': 'Verzonden via Peppol',
    'Refresh status': 'Status vernieuwen',
    'No Peppol Access Point is configured. Nothing is sent externally.': 'Er is geen Peppol-toegangspunt geconfigureerd. Er wordt niets extern verzonden.',
  });
  Object.assign(messages, { '+ {0} more files': '+ {0} andere bestanden' });
  Object.assign(messages, { 'VAT': 'Btw', 'to schedule': 'te plannen' });
  Object.assign(messages, { 'To': 'Tot', 'not set': 'niet ingesteld' });
  Object.assign(messages, {
    'Bank & Treasury': 'Bank en treasury',
    'Not connected': 'Niet verbonden',
    'Connected': 'Verbonden',
    'Consent expired': 'Toestemming verlopen',
    'Disconnected': 'Losgekoppeld',
    'Treasury': 'Treasury',
    'Short-term liquidity, not accounting cash flow': 'Kortetermijnliquiditeit, geen boekhoudkundige cashflow',
    'Bank': 'Bank',
    'Total liquidity': 'Totale liquiditeit',
    'Receivables due in {0} days': 'Te innen binnen {0} dagen',
    'To pay in {0} days': 'Te betalen binnen {0} dagen',
    'Projection': 'Projectie',
    'No bank balance available: connect a bank or import a statement.': 'Geen banksaldo beschikbaar: verbind een bank of importeer een rekeninguittreksel.',
    'No physical cash count confirmed yet.': 'Nog geen kastelling bevestigd.',
    '{0} of overdue receivables is NOT included in the projection above (assumed, not expected).': '{0} aan achterstallige vorderingen is NIET opgenomen in de projectie hierboven (verondersteld, niet verwacht).',
    'Observed = bank balance / confirmed cash count. Expected = invoices and supplier invoices due. Assumed = excluded from the projection.': 'Waargenomen = banksaldo / bevestigde kastelling. Verwacht = vervallen facturen en leveranciersfacturen. Verondersteld = uitgesloten van de projectie.',
    'Exact match': 'Exacte overeenkomst',
    'Probable match': 'Waarschijnlijke overeenkomst',
    'Partial payment': 'Gedeeltelijke betaling',
    'Overpayment': 'Overbetaling',
    'Several candidates': 'Meerdere kandidaten',
    'No match': 'Geen overeenkomst',
    'Reconciled': 'Afgestemd',
    'Confirm': 'Bevestigen',
    'Choose...': 'Kiezen…',
    'Ignored': 'Genegeerd',
    'Ignore': 'Negeren',
    'IN': 'IN',
    'OUT': 'UIT',
    'Unknown': 'Onbekend',
    'Read-only: balances and transactions, never a payment or a transfer.': 'Alleen-lezen: saldi en transacties, nooit een betaling of overschrijving.',
    'Bank connection': 'Bankverbinding',
    'Read-only access only. This connection can never initiate a payment, a transfer or change a beneficiary.': 'Enkel toegang met leesrechten. Deze verbinding kan nooit een betaling of overschrijving starten of een begunstigde wijzigen.',
    'Provider': 'Aanbieder',
    'Scopes': 'Rechten',
    'Connected since': 'Verbonden sinds',
    '{0} new transaction(s)': '{0} nieuwe transactie(s)',
    'Sync now': 'Nu synchroniseren',
    'Disconnect bank': 'Bank loskoppelen',
    'This revokes local and, where supported, remote access. No transactions are deleted.': 'Dit trekt de lokale toegang in en, indien ondersteund, de externe toegang. Er worden geen transacties verwijderd.',
    'Disconnect': 'Loskoppelen',
    'Provider: {0}': 'Aanbieder: {0}',
    'Connect a bank': 'Een bank verbinden',
    'No bank provider is configured yet.': 'Nog geen bankaanbieder geconfigureerd.',
    'Paste your bank statement CSV export here': 'Plak hier de CSV-export van uw rekeninguittreksel',
    'Or import a CSV statement (no bank connection needed)': 'Of importeer een CSV-uittreksel (geen bankverbinding nodig)',
    '{0} transaction(s) imported': '{0} transactie(s) geïmporteerd',
    'Import CSV': 'CSV importeren',
    'Physical cash': 'Fysieke kas',
    'Only confirmed counts are used: cash sales are never assumed to stay in the till.': 'Enkel bevestigde tellingen worden gebruikt: kasverkopen worden nooit verondersteld in de kassa te blijven.',
    'Amount counted': 'Geteld bedrag',
    'Confirm cash count': 'Kastelling bevestigen',
    'Transactions to reconcile': 'Af te stemmen transacties',
    'Nothing to reconcile': 'Niets af te stemmen',
  });
  // Phase 2: unified Contacts workspace (views-contacts.js).
  Object.assign(messages, {
    'Contacts': 'Contacten', 'Business': 'Onderneming', 'Individual': 'Particulier', 'Customer · Supplier': 'Klant · Leverancier',
    'A financial directory of your customers and suppliers.': 'Financieel overzicht van uw klanten en leveranciers.',
    '+ New contact': '+ Nieuw contact', 'Search by name, VAT number...': 'Zoeken op naam, btw-nummer…',
    'All contacts': 'Alle', 'Suppliers': 'Leveranciers',
    'Your contacts will appear here.': 'Uw contacten verschijnen hier.',
    'Add a client or a company now; suppliers will also be gathered in this directory once they are linked to your purchase documents.': 'Voeg nu een klant of onderneming toe; leveranciers worden eveneens in dit overzicht opgenomen zodra ze aan uw aankoopdocumenten zijn gekoppeld.',
    'Add a contact': 'Contact toevoegen',
    'No supplier matches this search.': 'Geen leverancier komt overeen met deze zoekopdracht.',
    'No customer matches this search.': 'Geen klant komt overeen met deze zoekopdracht.',
    'No contact matches this search.': 'Geen contact komt overeen met deze zoekopdracht.',
    'Clear the search': 'Zoekopdracht wissen',
    'Contact': 'Contact', 'Relation': 'Relatie', 'Amount receivable': 'Te ontvangen', 'Amount payable': 'Te betalen', 'Last activity': 'Laatste activiteit',
    'Contacts could not be loaded.': 'Contacten konden niet worden geladen.', 'Retry': 'Opnieuw proberen',
    '(no number)': '(geen nummer)',
    'This contact has no invoiced activity yet.': 'Dit contact heeft nog geen gefactureerde activiteit.',
    'Sales documents': 'Verkoopdocumenten', 'No sales documents yet.': 'Nog geen verkoopdocument.',
    'Supplier documents': 'Leveranciersdocumenten', 'No supplier documents yet.': 'Nog geen leveranciersdocument.',
  });
  // Unified Finance module (2026-09-24): shell nav, Home hero/CTA, "Contact us".
  Object.assign(messages, {
    'Home': 'Start', 'To do': 'Te doen', 'Sales': 'Verkoop', 'Bank & Cash': 'Bank & Kas', 'More': 'Meer',
    'Contact us': 'Contact opnemen', 'Reach your configured finance contact:': 'Neem contact op via uw ingesteld financieel adres:', 'No contact address is configured yet.': 'Er is nog geen contactadres ingesteld.',
    'Working with clarity.': 'Ondernemen met duidelijkheid.', 'Moving forward with peace of mind.': 'Vooruitgaan met gemoedsrust.',
    'Every invoice, told simply.': 'Elke factuur, eenvoudig verteld.', 'Financial clarity, day after day.': 'Financiële duidelijkheid, dag na dag.',
    'Create, send and track your invoices with ease.': 'Maak, verstuur en volg uw facturen moeiteloos op.',
    'Most recent: {0} · {1} {2}': 'Meest recent: {0} · {1} {2}', 'No invoice yet - create your first one.': 'Nog geen factuur - maak uw eerste aan.',
  });
  // À faire (viewTodo, views-workspace.js).
  Object.assign(messages, {
    'Everything that needs your attention, in one place.': 'Alles wat uw aandacht vereist, op één plek.',
    'To handle': 'Te behandelen', 'Documents and actions to finalise': 'Documenten en acties om af te ronden',
    'Urgent': 'Urgent', 'Needs attention now': 'Vereist nu actie',
    'Worth a look soon': 'Binnenkort te bekijken', 'Informational': 'Informatief', 'No action required yet': 'Nog geen actie vereist',
    'By priority': 'Op prioriteit', 'Up to date': 'Up-to-date', 'Recommended action': 'Aanbevolen actie',
  });
  // Sales/Purchases workspaces + shared analytics panel (views-workspace.js).
  Object.assign(messages, {
    'This month': 'Deze maand', 'Last month': 'Vorige maand', 'Last 3 months': 'Laatste 3 maanden', 'This quarter': 'Dit kwartaal', 'This year': 'Dit jaar', 'Custom range': 'Aangepaste periode',
    'Search a product or SKU...': 'Zoek een product of SKU…',
    'Sales (excl. VAT)': 'Verkopen (excl. btw)', 'Credit notes (excl. VAT)': 'Creditnota\'s (excl. btw)', 'Net after credit notes': 'Netto na creditnota\'s', 'Documents': 'Documenten',
    'By product': 'Per product', 'Product': 'Product', 'SKU': 'SKU', 'Qty': 'Aantal', 'Revenue': 'Omzet',
    'No catalogue product on any sales line in this period.': 'Geen catalogusproduct op de verkooplijnen van deze periode.',
    '{0} of sales lines have no catalogue product/SKU and are not included in the breakdown above.': '{0} aan verkooplijnen heeft geen catalogusproduct/SKU en is niet opgenomen in het overzicht hierboven.',
    'Purchases (incl. VAT)': 'Aankopen (incl. btw)', 'By supplier': 'Per leverancier', 'Supplier': 'Leverancier', 'Total': 'Totaal',
    'No supplier invoice in this period.': 'Geen leveranciersfactuur in deze periode.',
    'Invoices, quotes and credit notes in one place.': 'Facturen, offertes en creditnota\'s op één plek.', 'New invoice': 'Nieuwe factuur',
    'Invoices': 'Facturen', 'Credit notes': 'Creditnota\'s', 'Analytics': 'Analyse',
    'Amount receivable': 'Te ontvangen', 'Overdue': 'Achterstallig', '{0} case(s)': '{0} geval(len)', 'Collected this month': 'Geïnd deze maand', '{0} payment(s)': '{0} betaling(en)',
    'Quotes to convert': 'Offertes om om te zetten', 'Accepted, not yet invoiced': 'Aanvaard, nog niet gefactureerd',
    'Search number or customer...': 'Zoek een nummer of klant…', 'Export': 'Exporteren',
    'Select a document to see its summary here.': 'Selecteer een document om het overzicht hier te zien.',
    'Open': 'Openen', 'Still due': 'Nog verschuldigd', 'No document matches.': 'Geen document komt overeen.', 'Issued': 'Uitgereikt', 'Due': 'Vervaldatum', 'Document': 'Document', 'Customer': 'Klant', 'Amount': 'Bedrag', 'Status': 'Status',
    '{0} unit(s) · {1} {2} across {3} document(s).': '{0} eenhe(i)d(en) · {1} {2} over {3} document(en).',
    'Process supplier invoices, validate the data and track what remains to pay.': 'Verwerk leveranciersfacturen, valideer de gegevens en volg wat nog te betalen is.',
    '+ Add manually': '+ Handmatig toevoegen', 'To pay': 'Te betalen', 'Documents awaiting validation': 'Documenten in afwachting van validatie',
    '{0} document(s)': '{0} document(en)', 'Supplier invoice(s)': 'Leveranciersfactu(u)r(en)', 'Supplier, invoice number...': 'Leverancier, factuurnummer…',
    'Nothing here.': 'Niets hier.',
  });
  // Bank & Cash / Treasury (views-workspace.js).
  Object.assign(messages, {
    'Justify': 'Verantwoorden', 'Justified': 'Verantwoord', 'Nothing to justify': 'Niets te verantwoorden', 'Transactions to justify': 'Te verantwoorden transacties',
    // Server-provided (analytics.js's own English message id, translated here like every other key -
    // never hardcoded Dutch in the backend module itself).
    'Supplier invoices are stored as one total per document (net/VAT/gross) - there is no per-product line detail to break down.': 'Leveranciersfacturen worden opgeslagen als één totaal per document (netto/btw/bruto) - er is geen detail per lijn/product om uit te splitsen.',
    'Understand every inflow and outflow, without accounting jargon.': 'Begrijp elke inkomende en uitgaande beweging, zonder boekhoudjargon.',
    'Confirmed count only': 'Enkel bevestigde tellingen',
    'Visualise what is realised, what is committed and your projected position.': 'Visualiseer wat gerealiseerd is, wat vaststaat en uw geprojecteerde positie.',
    'Available today': 'Vandaag beschikbaar', 'Receivable in {0} days': 'Te ontvangen binnen {0} dagen', 'Payable in {0} days': 'Te betalen binnen {0} dagen',
    'Treasury position': 'Kaspositie', 'Realised documented balance, last 12 months': 'Gerealiseerd gedocumenteerd saldo, laatste 12 maanden',
    'Not enough history yet.': 'Nog niet genoeg geschiedenis.',
    'Expected customer invoices': 'Verwachte klantfacturen', 'Supplier invoices to pay': 'Te betalen leveranciersfacturen',
    '{0} of overdue receivables is NOT included in this projection (assumed, not expected).': '{0} aan achterstallige vorderingen is NIET opgenomen in deze projectie (verondersteld, niet verwacht).',
    'VAT is not provisioned here - see the Accountant pack for the authoritative per-period VAT figure.': 'Btw wordt hier niet voorzien - raadpleeg het boekhoudpakket voor het officiële btw-cijfer per periode.',
    'Projection detail unavailable.': 'Projectiedetail niet beschikbaar.',
  });
  // Contacts (views-contacts.js), unified visual pass.
  Object.assign(messages, {
    'Both': 'Beide', 'To complete': 'Aan te vullen',
    'Customers, suppliers and financial relationships in one directory.': 'Klanten, leveranciers en financiële relaties in één overzicht.',
    'Search name, VAT, email...': 'Zoeken op naam, btw, e-mail…', 'Contact details': 'Contactgegevens', '+ Create': '+ Aanmaken',
  });
  window.FINANCE_LANG = window.FINANCE_LANG || {};
  window.FINANCE_LANG.nl = { messages, patterns };
})();
