'use strict';
// English - third language of Nordla AI. Complete translation, natural business tone for SME owners.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.en = {
  'brand.name': 'Nordla AI',

  'nav.brief': 'Brief',
  'nav.changed': 'What Changed',
  'nav.explore': 'Explore',
  'nav.customers': 'Customers',
  'nav.products': 'Products',
  'nav.askNordla': 'Ask Nordla',

  'sidebar.askSubtitle': 'Get insights about your business',

  'topbar.title': 'Analytics Premium',
  'topbar.lastSynced': 'Report generated {0}',

  'time.justNow': 'just now',
  'time.minAgo': '{0} min ago',
  'time.hAgo': '{0} h ago',
  'time.dAgo': '{0} d ago',

  'period.last30Days': 'Last 30 days',

  'greeting.morning': 'Good morning',
  'greeting.afternoon': 'Good afternoon',
  'greeting.evening': 'Good evening',
  'hero.subtitle': 'Here’s what changed this week.',

  'kpi.netRevenue': 'Net Revenue',
  'kpi.orders': 'Orders',
  'kpi.aov': 'AOV',
  'kpi.grossMargin': 'Gross Margin',
  'kpi.thisPeriod': 'This period',
  'kpi.partialCostCoverage': 'Partial cost coverage',
  'kpi.infoTitle': 'Current period, real data',
  'kpi.noData': 'No sales data available for this period.',
  'kpi.insufficientHistory': 'Not enough daily history yet for a chart.',

  'insight.badge': 'Top products',
  'insight.title': 'Your top products by revenue',
  'insight.subtitle': 'Last 30 days, real sales data.',
  'insight.body': 'Actual ranking of the current period. The comparison with the previous 30 days is available in “What changed” and in Explorer.',
  'insight.seeWhy': 'See why',
  'insight.seeWhyTitle': 'This action is not available yet.',
  'insight.addToCommandCenter': 'Add to Command Center',
  'insight.commandCenterTitle': 'Command Center is not built yet',
  'insight.rankTitle': 'Revenue by top products',
  'insight.noProducts': 'No product sales in this period.',
  'insight.units': '{0} units',
  'insight.shareNote': 'Share shown is of these {0} products’ combined revenue ({1}), not of total store revenue.',

  'watch.heading': 'Other things to watch',
  'watch.aovTitle': 'AOV trend',
  'watch.aovText': 'The comparison of the average order value with the previous period is not available.',
  'watch.dormantTitle': 'Dormant customers',
  'watch.dormantText': 'This metric is not computed yet - it needs a dormancy definition and richer customer history than is currently available.',

  'health.title': 'Data health',
  'health.upToDate': 'Data up to date',
  'health.lastGenerated': 'Last generated',
  'health.viewSources': 'View data sources',

  'app.noReport': 'No report snapshot found yet. Run `npm run metrics:report` to generate one.',

  'common.dash': '—',
  'common.and': 'and',

  'wc.title': 'What Changed',
  'wc.subtitle': 'Here are this week’s key changes in your business, with simple explanations and possible next steps.',
  'wc.badgeUp': 'Good performance',
  'wc.badgeDown': 'High priority',
  'wc.badgeFlat': 'Stable',
  'wc.headlineUp': 'Net revenue increased by {0}.',
  'wc.headlineDown': 'Net revenue decreased by {0}.',
  'wc.headlineFlat': 'Net revenue stayed stable ({0}).',
  'wc.noContributors': 'No single product stands out in this change.',
  'wc.bodyText': 'Compared to the previous period ({0} → {1}), net revenue went from {2} to {3}.',
  'wc.noComparison': 'Comparison with the previous period is not available yet - there isn’t enough history.',
  'wc.dataReliable': 'The revenue in this comparison comes from real, verified orders.',
  'wc.contributorsTitle': 'Top contributors',
  'wc.vsPreviousPeriod': 'vs previous period',
  'wc.watchlistLabel': 'Watchlist',
  'wc.partialDataLabel': 'Partial data',
  'wc.dismiss': 'Dismiss',
  'wc.dismissTitle': 'This action is not available yet.',

  'wc.watchHeading': 'Other things to watch',
  'wc.watchAovUp': 'AOV increased by {0}%.',
  'wc.watchAovDown': 'AOV decreased by {0}%.',
  'wc.watchAovDetail': 'It went from {0} to {1}.',
  'wc.watchMoversUp': '{0} product(s) drove the increase.',
  'wc.watchMoversDown': '{0} product(s) drove the decline.',
  'wc.dqLabel': 'Purchase cost known (share of revenue)',
  'wc.watchCostCoverage': 'Costs known for {0}% of revenue.',
  'wc.watchCostCoverageDetail': 'The rest isn’t classified yet - real margin may differ.',

  'wc.otherChangesHeading': 'Other changes ({0})',
  'wc.rowOrdersTitle': 'Orders',
  'wc.rowOrdersDetail': 'You received {0} orders, up from {1} previously.',
  'wc.rowGrossMarginTitle': 'Gross margin',
  'wc.rowGrossMarginDetail': 'Your gross margin is {0}%, compared to {1}% previously.',
  'wc.rowActiveProductsTitle': 'Active products sold',
  'wc.rowActiveProductsDetail': '{0} products sold this period, compared to {1} previously.',

  // ---------- Explorer ----------
  'ex.title': 'Explorer',
  'ex.subtitle': 'Dig into your data to understand what performs, where to act and which opportunities to seize.',
  'ex.export': 'Export',
  'ex.tab.overview': 'Overview',
  'ex.tab.sales': 'Sales',
  'ex.tab.products': 'Products',
  'ex.tab.customers': 'Customers',
  'ex.tab.channels': 'Channels',
  'ex.tab.zones': 'Regions',
  'ex.tab.period': 'Period',
  'ex.tab.comparison': 'Comparison',
  'ex.kpi.revenue': 'Revenue',
  'ex.kpi.orders': 'Orders',
  'ex.kpi.customers': 'Active customers',
  'ex.kpi.units': 'Products sold',
  'ex.vsPrevious': 'vs previous period',
  'ex.noComparison': 'Comparison unavailable',
  'ex.identifiedNote': 'Identified customers · {0} of orders',
  'ex.salesTitle': 'Sales over the period',
  'ex.granularity': 'Granularity',
  'ex.byDay': 'By day',
  'ex.byWeek': 'By week',
  'ex.partialWeeks': 'Weeks at the edges of the period are partial.',
  'ex.categoryTitle': 'Breakdown by category',
  'ex.uncategorised': 'Uncategorised',
  'ex.others': 'Others',
  'ex.total': 'Total',
  'ex.topProducts': 'Top products',
  'ex.topCustomers': 'Top customers',
  'ex.col.product': 'Product',
  'ex.col.sales': 'Sales',
  'ex.col.revenue': 'Revenue',
  'ex.col.evolution': 'Trend',
  'ex.col.customer': 'Customer',
  'ex.col.orders': 'Orders',
  'ex.customerLabel': 'Customer {0}',
  'ex.customerNote': 'Only identified customers are listed ({0} of orders). No name is stored: customers are pseudonymised.',
  'ex.insufficient': 'Insufficient data',
  'ex.insufficientSub': 'At least 2 real data points are needed to draw this chart.',
  'ex.noCategories': 'No categorised sales in the period.',
  'ex.noProducts': 'No product sales in the period.',
  'ex.noCustomers': 'No identified customer in the period: orders without a customer key are never attributed to a customer.',
  'ex.noReport': 'The report does not contain Explorer data yet. Regenerate the report.',
  'ex.soonTitle': 'Coming soon',
  'ex.soonSub': 'This Explorer view is not available yet.',
  'period.fixed': 'Fixed',
  'period.fixedNote': 'Explorer shows a fixed period: the last 30 days compared with the previous 30.',
  'ex.trendTitle': 'Sales evolution',
  'ex.kpi.aov': 'Average order value',
  'ex.kpi.items': 'Items sold',
  'ex.channelTitle': 'Sales by channel',
  'ex.channelUnknown': 'Channel not set',
  'ex.noChannels': 'No sale with a channel in the period.',
  'ex.cmpTitle': 'Current vs previous period',
  'ex.cmpPrev': 'Previous period',
  'ex.cmpCur': 'Current period',
  'ex.cmpNote': '7-day blocks from the start of each period, compared day by day in the same order.',
  'ex.cmpPartial': 'Last block: {0} days.',
  'ex.noPrevious': 'Sales in the previous period are needed to compare.',
  'ex.contribTitle': 'Contribution to revenue',
  'ex.contribNote': 'Total revenue change: {0} vs previous period.',
  'ex.noContrib': 'A previous period with sales is needed to measure contributions.',
  'ex.bestDay': 'Best sales day',
  'ex.weakDay': 'Weakest day',
  'ex.weakNote': 'Among days with at least one sale.',
  'ex.daysNoSale': '{0} days without a sale out of {1}.',
  'ex.dayOrders1': '1 order',
  'ex.dayOrdersN': '{0} orders',
  'ex.noDays': 'No day with a sale in the period.',
  'ex.kpi.productsSold': 'Products sold',
  'ex.kpi.topProduct': 'Top product by revenue',
  'ex.kpi.topCategory': 'Top category',
  'ex.kpi.top3': 'Top 3 share of revenue',
  'ex.distinctProducts': '{0} distinct products sold',
  'ex.currentOnly': 'Current period only',
  'ex.concentrationNote': 'Revenue concentration, not a performance',
  'ex.rankingTitle': 'Product ranking',
  'ex.units': '{0} units',
  'ex.statusNew': 'New in the period',
  'ex.statusNotBefore': 'Not sold before',
  'ex.unmatched': 'Deleted catalogue product',
  'ex.growthTitle': 'Growing products',
  'ex.declineTitle': 'Declining products',
  'ex.noGrowth': 'No product growing versus a sale in the previous period.',
  'ex.noDecline': 'No product declining versus a sale in the previous period.',
  'ex.noSaleNow': 'No sales now',
  'ex.contribChangeTitle': 'Contribution to the revenue change',
  'ex.catShareTitle': 'Revenue share by category',
  'ex.concTitle': 'Revenue concentration',
  'ex.topN': 'Top {0}',
  'ex.concSentence': 'The top 3 products account for {0} of revenue.',
  'ex.concNeutral': 'Descriptive indicator, no judgement: read it against your catalogue.',
  'ex.unitsVsRevenue': 'Units sold vs revenue',
  'ex.unitsShare': 'Share of units',
  'ex.revenueShare': 'Share of revenue',
  'ex.unitsNote': 'Markers #n = the product’s rank in the ranking above. Units versus revenue only, no margin.',
  'ex.marginTitle': 'Margin by product',
  'ex.marginPartial': 'Partial data',
  'ex.marginSub': 'Product margin not shown: costs known for {0} of revenue, {1} of it verified. A margin ranking would need complete costs.',
  'ex.unit1': '1 unit',
  'ex.kpi.activeCustomers': 'Active customers',
  'ex.kpi.newCustomers': 'New customers',
  'ex.kpi.returningCustomers': 'Returning customers',
  'ex.kpi.identifiedRevenue': 'Revenue from identified customers',
  'ex.covNote': 'Identified customers · {0} of orders',
  'ex.covNotePrev': 'Identified customers · {0} of orders ({1} in the previous period)',
  'ex.newDef': 'First order of their history falls in the period',
  'ex.returningDef': 'Already ordered before the period, or 2 or more orders',
  'ex.seg.new': 'New customers',
  'ex.seg.returning': 'Returning customers',
  'ex.seg.unknown': 'Unknown history',
  'ex.seg.newShort': 'New',
  'ex.seg.returningShort': 'Returning',
  'ex.seg.unknownShort': 'Unknown',
  'ex.nCustomers': '{0} customers',
  'ex.identifiedShort': 'identified',
  'ex.newVsReturningTitle': 'New vs returning customers',
  'ex.segDefs': 'New: the first order of their history falls in the period (source order index). Returning: an earlier order is already recorded, or 2 or more orders. Unknown: order index not reliable.',
  'ex.custRevenueTitle': 'Customer revenue breakdown',
  'ex.custRevenueNote': 'Share of orders with an identified customer: {0}. This is not the mix of all the store’s customers.',
  'ex.custTrendTitle': 'Identified customers over time',
  'ex.seriesNew': 'New customers',
  'ex.seriesActive': 'Active customers',
  'ex.custTrendNote': 'By week (weeks of the period, the edges can be partial).',
  'ex.activityTitle': 'Customer activity',
  'ex.rec.d30': 'Last purchase 30 days ago or less',
  'ex.rec.d60': 'Last purchase 31 to 60 days ago',
  'ex.rec.d90': 'Last purchase 61 to 90 days ago',
  'ex.rec.d90plus': 'Last purchase more than 90 days ago',
  'ex.recNote': 'Descriptive buckets over {0} days of available history. Nordla has no approved definition of a “dormant” customer: none is applied.',
  'ex.lastOrder': 'Last purchase: {0}',
  'ex.basketShort': 'basket',
  'ex.frequencyTitle': 'Purchase frequency',
  'ex.freq.one': '1 order',
  'ex.freq.two': '2 orders',
  'ex.freq.three': '3 orders or more',
  'ex.freqNote': 'Orders in the period per identified customer.',
  'ex.avgOrders': 'Orders per customer: {0} on average.',
  'ex.valueTitle': 'Customer value',
  'ex.sampleTitle': 'Insufficient sample',
  'ex.gated': 'Averages not shown: {0} identified customers, minimum {1} (existing Nordla rule for per-customer averages).',
  'ex.noClv': 'No customer lifetime value (CLV) is computed: the required method and history are not available.',
  'ex.val.avgRevenue': 'Average revenue per identified customer',
  'ex.val.median': 'Median revenue per identified customer',
  'ex.val.basket': 'Average basket of identified customers',
  'ex.cohortTitle': 'Retention cohorts',
  'ex.cohortSub': 'No cohort is drawn: the current data does not allow a reliable retention calculation.',
  'ex.cohortReason.SHORT_HISTORY': 'History of {0} days, below the required {1} days.',
  'ex.cohortReason.TOO_FEW_RETURNING_CUSTOMERS': 'Too few identified returning customers.',
  'ex.cohortReason.NO_APPROVED_COHORT_DEFINITION': 'No cohort definition has been approved yet.',
  'ex.channelName.Point of Sale': 'Point of sale',
  'ex.channelName.Online Store': 'Online store',
  'ex.noChannelData': 'No sales by channel in the period.',
  'ex.metricLabel': 'Metric',
  'ex.kpi.topChannel': 'Top channel by revenue',
  'ex.kpi.topChannelShare': 'Share of the main channel',
  'ex.kpi.topChannelOrders': 'Orders of the main channel',
  'ex.kpi.topChannelAov': 'Average order value of the main channel',
  'ex.prevShare': 'Previous period: {0}',
  'ex.chShareTitle': 'Revenue share by channel',
  'ex.chPerfTitle': 'Performance by channel',
  'ex.chTrendTitle': 'Channels over time',
  'ex.chTrendNote': 'Revenue per week and per channel (weeks of the period, the edges can be partial).',
  'ex.chInsightTitle': 'Reading the numbers',
  'ex.insShare': '{0} accounts for {1} of the period’s revenue.',
  'ex.insAov': 'The average order value of the {0} channel is {1} higher than that of the {2} channel.',
  'ex.insNeutral': 'Factual statements, no judgement.',
  'ex.chVarTitle': 'Change vs previous period',
  'ex.noSalesPeriod': 'No sales in the period',
  'ex.chContribTitle': 'Channel contribution to the revenue change',
  'ex.chProductsTitle': 'Products by channel',
  'ex.chCustomersTitle': 'Customers by channel',
  'ex.chCustLine': '{0} identified customers · {1} of the channel’s orders',
  'ex.chCustSplit': '{0} new · {1} returning',
  'ex.chCustNote': 'Identified customers only (pseudonymous key). Orders without an identified customer are attributed to nobody.',
  'ex.geo.kpiCoverage': 'Geographic coverage',
  'ex.geo.covNote': '{0} of {1} orders have a usable city',
  'ex.geo.covNeutral': 'Orders without a location are never extrapolated',
  'ex.geo.kpiSaleLoc': 'Sale location recorded',
  'ex.geo.saleLocNote': '{0} of {1} orders',
  'ex.geo.saleLocNeutral': 'The store’s location, not the customer’s',
  'ex.geo.kpiZones': 'Usable zones',
  'ex.geo.zonesNote': 'City, postal code, province or country',
  'ex.geo.kpiOrders': 'Orders in the period',
  'ex.geo.blockedTitle': 'Geographic analysis unavailable',
  'ex.geo.blockedSub': 'Only {0} of orders have a usable city. No chart or map is shown rather than misleading figures.',
  'ex.geo.foundTitle': 'Geographic data present',
  'ex.geo.colField': 'Data',
  'ex.geo.colMeaning': 'What it is',
  'ex.geo.colOrders': 'Orders',
  'ex.geo.colUsable': 'Usable',
  'ex.geo.saleLocation': 'Sale location: {0}',
  'ex.geo.saleLocMeaning': 'Sale location (a store), not the customer’s location',
  'ex.geo.noSaleLocation': 'No sale location is linked to the orders.',
  'ex.geo.no': 'No',
  'ex.geo.absentTitle': 'Missing data',
  'ex.geo.absentLine': 'Shipping or billing address (city, postal code, province, country): not synced. Online orders therefore have no known destination.',
  'ex.geo.unlockTitle': 'To unlock this analysis',
  'ex.geo.unlock1': 'Sync, for each order, at least the destination city or postal code (no street, no name).',
  'ex.geo.unlock2': 'Or record the city of each point of sale, if several sale locations exist.',
  'ex.geo.unlock3': 'Sufficient coverage of located orders, across at least two different zones (threshold to be defined with the product owner).',
  'ex.geo.privacy': 'Privacy: no address is stored. The analysis will stay aggregated (city, province or country) and never show an individual customer.',
  'ex.geo.kpiOrdersNote': 'Locked period: last 30 days',
  'ex.per.kpiCur': 'Revenue, current period',
  'ex.per.kpiPrev': 'Revenue, previous period',
  'ex.per.kpiAbs': 'Absolute change',
  'ex.per.kpiPct': 'Change in %',
  'ex.per.last30': 'Last 30 days',
  'ex.per.prev30': 'Previous 30 days',
  'ex.per.noPrev': 'No previous period available',
  'ex.per.pctInvalid': 'Unavailable: no sales in the previous period',
  'ex.per.trendTitle': 'Trend over the period',
  'ex.per.bestTitle': 'Strongest period',
  'ex.per.weakTitle': 'Weakest period',
  'ex.per.bestWeek': 'Strongest complete week: {0} ({1})',
  'ex.per.weakWeek': 'Weakest complete week: {0} ({1})',
  'ex.per.weekOf': 'week of {0}',
  'ex.per.activityTitle': 'Activity distribution',
  'ex.per.daysWith': '{0} days with sales',
  'ex.per.daysWithout': '{0} days without sales',
  'ex.per.daysAbove': '{0} days above the daily average',
  'ex.per.daysBelow': '{0} days below the daily average',
  'ex.per.activityNote': 'Counts over {0} days; the average includes days without sales.',
  'ex.per.weeksTitle': 'Weekly contribution to revenue',
  'ex.per.weeksNote': 'Share of each week in the period’s revenue. Weeks at the edges are partial ({0} days).',
  'ex.per.weekLabel': 'Wk {0}',
  'ex.per.regTitle': 'Sales consistency',
  'ex.per.mean': 'Average per day',
  'ex.per.median': 'Median per day',
  'ex.per.sd': 'Standard deviation',
  'ex.per.cv': 'Coefficient of variation',
  'ex.per.regNote': 'Computed over the {0} days of the period, days without sales included. The standard deviation measures how spread out daily sales are around the average; the coefficient of variation relates it to the average. The higher they are, the more sales vary from one day to the next.',
  'ex.per.weekdayTitle': 'Performance by day of the week',
  'ex.per.weekdayNote': 'Average per occurrence: each weekday is divided by the number of times it appears in the period.',
  'ex.per.weekdayLine': '{0} order(s) · {1}×',
  'ex.per.todTitle': 'Performance by time of day',
  'ex.per.tod.night': 'Night (0–6 am)',
  'ex.per.tod.morning': 'Morning (6 am–12 pm)',
  'ex.per.tod.midday': 'Midday (12–2 pm)',
  'ex.per.tod.afternoon': 'Afternoon (2–6 pm)',
  'ex.per.tod.evening': 'Evening (6 pm–12 am)',
  'ex.per.todNote': 'Local time ({0}) of {1} order(s) out of {2}. Net revenue, refunds attached to their order.',
  'ex.per.orders': '{0} order(s)',
  'ex.per.whyTitle': 'Where does the change come from?',
  'ex.per.whyOrders': 'The number of orders changes by {0} ({1} vs {2}).',
  'ex.per.whyAov': 'The average order value changes by {0} ({1} vs {2}).',
  'ex.per.whyNote': 'Arithmetic reading: revenue = orders × average order value. No cause is established.',
  'ex.per.noData': 'Not enough days for this analysis.',
  'ex.cp.periodCur': 'Current period',
  'ex.cp.periodPrev': 'Previous period',
  'ex.cp.range': '{0} – {1} ({2} days)',
  'ex.cp.previousValue': 'Before: {0}',
  'ex.cp.change': 'Change: {0}',
  'ex.cp.blocksTitle': 'Current vs previous period',
  'ex.cp.blocksNote': '7-day blocks aligned by position: block 1 of each period, then block 2, and so on. The last block is partial ({0} days).',
  'ex.cp.blocksNoteFull': '7-day blocks aligned by position: block 1 of each period, then block 2, and so on.',
  'ex.cp.blockTip': '{0}: {1} to {2} vs {3} to {4}',
  'ex.cp.blockLabel': 'W{0}',
  'ex.cp.blockLabelPartial': 'W{0} ({1} d)',
  'ex.cp.trendTitle': 'Compared trend',
  'ex.cp.trendNote': 'Aligned by relative day (day 1 to day {0}): the calendar dates of the two periods are not the same.',
  'ex.cp.dayN': 'D{0}',
  'ex.cp.wfTitle': 'Breakdown of the revenue change',
  'ex.cp.wfPrev': 'Previous revenue',
  'ex.cp.wfPrevShort': 'Before',
  'ex.cp.wfCur': 'Current revenue',
  'ex.cp.wfCurShort': 'Now',
  'ex.cp.wfOther': 'Other categories ({0})',
  'ex.cp.wfOtherShort': 'Other',
  'ex.cp.wfNote': 'Breakdown by catalogue category (“No category” included): each sale belongs to exactly one category, so the sum of the changes lands exactly on the current revenue.',
  'ex.cp.productsTitle': 'Products behind the change',
  'ex.cp.channelsTitle': 'Change by channel',
  'ex.cp.categoriesTitle': 'Change by category',
  'ex.cp.shareOfChange': '{0} of the change',
  'ex.cp.statusNew': 'New in the period',
  'ex.cp.statusAbsent': 'No sales in the period',
  'ex.cp.noCategory': 'No category',
  'ex.cp.volumeTitle': 'Volume vs average order value',
  'ex.cp.ordersLine': 'Orders: {0}',
  'ex.cp.aovLine': 'Average order value: {0}',
  'ex.cp.up': 'an increase',
  'ex.cp.down': 'a decrease',
  'ex.cp.flat': 'stability',
  'ex.cp.volumeSentence': 'Revenue changes in a context of {0} in the number of orders and {1} in the average order value.',
  'ex.cp.unavailable': 'Unavailable',
  'ex.cp.customersTitle': 'Identified customers',
  'ex.cp.custActive': 'Active identified customers',
  'ex.cp.custRevenue': 'Revenue from identified customers',
  'ex.cp.custNew': 'New customers',
  'ex.cp.custReturning': 'Returning customers',
  'ex.cp.coverage': '{0} of orders identified vs {1} before',
  'ex.cp.coverageWarn': 'Identification coverage is not the same in the two periods: these changes do not necessarily measure a change in the customer base.',
  'ex.cp.coverageOk': 'Identification coverage is close between the two periods.',
  'ex.cp.watchUp': 'Strongest increase',
  'ex.cp.watchDown': 'Strongest decrease',
  'ex.cp.watchNote': 'Product, by absolute change in euros.',
  'ex.cp.noMove': 'No product movement to show.',
  'ex.cp.mostTitle': 'What changed the most',
  'ex.cp.mostRevenue': 'Revenue: {0}',
  'ex.cp.mostOrders': 'Orders: {0}',
  'ex.cp.mostAov': 'Average order value: {0}',
  'ex.cp.mostProduct': 'Top product contributor: {0} ({1})',
  'ex.cp.mostChannel': 'Channel with the largest change: {0} ({1})',
  'ex.cp.qualityTitle': 'Comparison quality',
  'ex.cp.q.comparable': 'Comparable',
  'ex.cp.q.caution': 'Interpret with caution',
  'ex.cp.q.partial': 'Partial data',
  'ex.cp.q.days': 'Number of days',
  'ex.cp.q.daysDetail': '{0} days vs {1} days.',
  'ex.cp.q.last_block': 'Last block',
  'ex.cp.q.lastBlockPartial': 'The last block only has {0} days, compared with the {1} matching days.',
  'ex.cp.q.lastBlockFull': 'All blocks have 7 days.',
  'ex.cp.q.customer_coverage': 'Customer identification',
  'ex.cp.q.coverageUnknown': 'Coverage cannot be measured in one of the periods.',
  'ex.cp.q.categories': 'Category classification',
  'ex.cp.q.categoriesDetail': '{0} of current revenue has no category.',
  'ex.cp.q.costs': 'Costs and margin',
  'ex.cp.q.costsDetail': 'Margin not compared: costs recorded for {0} of products, verified for {1}.',
  'ex.cp.qualityNote': 'Explicit rules, no overall score.',
  'ex.cp.noPrevious': 'No previous period to compare with.',
  'ex.cp.exportSection': 'comparison',
  'ex.days': 'days',
  'topbar.reportGenerated': 'Report generated {0}',
  'kpi.costCoverageDetail': '{0} of revenue covered · {1} of costs verified',
  'watch.aovCompared': 'Average order value: {0} vs {1} over the previous 30 days ({2}).',
  'wc.gainsLine': 'The strongest-rising products ({0}) add {1}.',
  'wc.lossesLine': 'The strongest-falling products ({0}) remove {1}.',
  'wc.netLine': 'Net change in revenue: {0}.',
  'wc.marginCaveat': 'Costs partially known: {0} of revenue covered · {1} of costs verified.',
  'ex.geo.pendingSub': 'Usable zones exist, but the minimum coverage threshold is not defined yet: the zone analysis is not enabled.',

  // ---- Clients (main customer workspace) ----
  'cl.title': 'Customers',
  'cl.subtitle': 'Understand your customer base and quickly spot the customers who need your attention.',
  'cl.toExplorer': 'Analyse customers in Explorer',
  'cl.coverageTitle': 'Customer coverage',
  'cl.coverageLine': '{0} of orders have an identified customer',
  'cl.coverageCounts': '({0} of {1} orders, last 30 days)',
  'cl.coveragePrev': '{0} in the previous period',
  'cl.scopePeriod': 'Indicators and statuses: last 30 days',
  'cl.scopeHistory': 'Available history: since {0} ({1} days), {2} of orders identified',
  'cl.coverageShift': 'The share of identified orders went from {0} to {1}: a change in customer counts also reflects this coverage change, not only a change in activity.',
  'cl.tag30': 'Last 30 days',
  'cl.tagHistory': 'Available history',
  'cl.tagMixed': '30 days + history',
  'cl.topTitle': 'Top customers by revenue',
  'cl.distTitle': 'Customer breakdown',
  'cl.distNote': 'Customers active in the period, using Explorer’s definitions. Only orders with an identified customer are counted ({0}).',
  'cl.watchHeading': 'To watch',
  'cl.watch.lapsedTitle': 'No purchase in the period',
  'cl.watch.lapsedText': '{0} customer(s) bought during the previous 30 days but not during the last 30 days. This is an observation across two periods, not a forecast.',
  'cl.watch.lapsedNone': 'No identified customer bought in the previous period without buying again in the current one.',
  'cl.watch.bothTitle': 'Active in both periods',
  'cl.watch.bothText': '{0} customer(s) bought in both periods: their change is comparable.',
  'cl.watch.bothNone': 'No identified customer bought in both the current and the previous period: no individual change is comparable.',
  'cl.watch.rhythmTitle': 'Individual purchase rhythm',
  'cl.watch.rhythmInsufficient': 'A customer’s recency cannot be compared with their own rhythm: {0} gap(s) between orders observed, {1} required.',
  'cl.watch.rhythmNoRule': '{0} gaps observed, but Nordla has no approved rule to call a delay unusual: no customer is flagged.',
  'cl.andMore': '+ {0} more',
  'cl.listTitle': 'Customers',
  'cl.searchPlaceholder': 'Search a customer (e.g. #A4B7)',
  'cl.searchLabel': 'Search a customer by identifier',
  'cl.filtersLabel': 'Filter customers',
  'cl.recencyLabel': 'Filter by recency',
  'cl.sortLabel': 'Sort customers',
  'cl.filter.all': 'All',
  'cl.filter.active': 'Active',
  'cl.filter.new': 'New',
  'cl.filter.returning': 'Returning',
  'cl.filter.unknown': 'Unknown history',
  'cl.filter.inactive': 'No purchase in the period',
  'cl.recency.all': 'Any recency',
  'cl.recency.d0_30': 'Last purchase ≤ 30 days',
  'cl.recency.d31_60': 'Last purchase 31–60 days',
  'cl.recency.d61_90': 'Last purchase 61–90 days',
  'cl.recency.d90_plus': 'Last purchase > 90 days',
  'cl.sort.recent': 'Sort: last purchase',
  'cl.sort.revenue': 'Sort: 30-day revenue',
  'cl.sort.orders': 'Sort: 30-day orders',
  'cl.sort.known': 'Sort: known orders',
  'cl.col.customer': 'Customer',
  'cl.col.status': 'Status / activity',
  'cl.col.revenue': 'Revenue 30 d',
  'cl.col.orders': 'Orders 30 d',
  'cl.col.aov': 'Avg. basket 30 d',
  'cl.col.lastOrder': 'Last purchase',
  'cl.col.recency': 'Recency',
  'cl.col.evolution': 'Change',
  'cl.status.new': 'New',
  'cl.status.returning': 'Returning',
  'cl.status.unknown': 'Unknown history',
  'cl.status.inactive': 'No purchase in the period',
  'cl.evo.compared': 'Compared with the previous 30 days',
  'cl.evo.no_current_purchase': 'No purchase in the current period',
  'cl.evo.no_previous_purchase': 'No purchase in the previous 30 days: no percentage can be computed',
  'cl.evo.no_previous_window': 'No previous period available',
  'cl.evo.none': 'No purchase in either period',
  'cl.evo.newShort': 'No earlier purchase',
  'cl.today': 'today',
  'cl.daysAgo': '{0} d ago',
  'cl.count': '{0} customer(s) shown of {1} identified',
  'cl.noIdentified': 'No identified customer in the available history: orders without a customer are never attributed.',
  'cl.noMatchTitle': 'No matching customer',
  'cl.noMatch': 'Change the search or the filters.',
  'cl.listNote': 'Revenue excl. VAT, net of refunds. Status, revenue, orders and average basket: last 30 days (Explorer definitions). Last purchase and recency: available history. Customers are pseudonymised; no name is stored.',
  'cl.openDetail': 'Open the details of {0}',
  'cl.close': 'Close the details',
  'cl.loading': 'Loading customer…',
  'cl.detailError': 'This customer’s details are not available in the current report.',
  'cl.d.activeLine': 'Bought in the last 30 days',
  'cl.d.inactiveLine': 'No purchase in the last 30 days',
  'cl.d.periodTitle': 'Current period',
  'cl.d.previous': 'Previous 30 days: {0} · {1} order(s)',
  'cl.d.historyTitle': 'Available history',
  'cl.d.firstKnown': 'First known purchase',
  'cl.d.lastKnown': 'Last known purchase',
  'cl.d.knownOrders': 'Known orders',
  'cl.d.knownRevenue': 'Known revenue (excl. VAT)',
  'cl.d.earlierOutside': 'According to the source, this customer had already placed {0} order(s) before the available history starts: they are not included here.',
  'cl.d.earlierNone': 'According to the source, their first order is within the available history.',
  'cl.d.earlierUnknown': 'The source does not tell whether this customer ordered before the available history.',
  'cl.d.trendTitle': 'Purchase trend',
  'cl.d.trendOne': 'One known order: no curve, see the history below.',
  'cl.d.trendFew': '{0} known orders: too few points for a curve, see the history below.',
  'cl.d.ordersTitle': 'Purchase history',
  'cl.d.inPeriod': 'Last 30 days',
  'cl.d.refunded': 'Refund',
  'cl.d.ordersNote': 'Amount per order: excl. VAT, net of recorded refunds.',
  'cl.d.productsTitle': 'Products bought',
  'cl.d.units': '× {0}',
  'cl.d.refundedUnits': '{0} refunded',

  // ---- Produits (main product workspace) ----
  'pr.title': 'Products',
  'pr.subtitle': 'Follow your products, spot the important movements and focus on the ones that deserve your attention.',
  'pr.toExplorer': 'Analyse products in Explorer',
  'pr.scopeCurrent': 'Current period: last 30 days (since {0})',
  'pr.scopePrevious': 'compared with the previous 30 days (since {0})',
  'pr.scopeNoPrevious': 'no previous period available',
  'pr.scopeHistory': 'last sale: available history',
  'pr.catalogueLine': 'Revenue without category: {0} · revenue from items outside the catalogue: {1}',
  'pr.marginOmitted': 'Product margin not shown: partial costs ({0} of revenue covered, {1} verified)',
  'pr.kpi.sold': 'Products sold',
  'pr.kpi.soldPrev': 'Distinct products sold · {0} in the previous period',
  'pr.kpi.top': 'No. 1 product by revenue',
  'pr.shareOfRevenue': '{0} of revenue',
  'pr.kpi.top3': 'Top 3 share of revenue',
  'pr.kpi.top3Note': 'A concentration indicator, not performance',
  'pr.kpi.top3Prev': '{0} in the previous period ({1})',
  'pr.kpi.declining': 'Declining products',
  'pr.kpi.decliningNote': 'Including {0} with no sale in the period',
  'pr.kpi.decliningScope': 'Against a sale in the previous 30 days',
  'pr.status.compared': 'Comparable',
  'pr.status.new': 'New in the period',
  'pr.status.notBefore': 'No earlier sale',
  'pr.status.absent': 'No sale in the period',
  'pr.status.noPrevious': 'No previous period',
  'pr.status.partial': 'Partial data',
  'pr.status.negative': 'Refunds > sales',
  'pr.partialTitle': 'Item sold that no longer matches a catalogue product: no image, no category, no stable identity.',
  'pr.noSaleNowShort': 'No sale now',
  'pr.evo.compared': 'Compared with the previous 30 days',
  'pr.evo.new': 'New in the period: no percentage',
  'pr.evo.not_sold_before': 'No sale in the previous 30 days: no percentage',
  'pr.evo.absent': 'No sale in the period',
  'pr.evo.no_previous': 'No previous period available',
  'pr.noImage': 'No image in the catalogue',
  'pr.noCatalogue': 'Outside the catalogue',
  'pr.growthTitle': 'Growing products',
  'pr.declineTitle': 'Declining products',
  'pr.tagCompare': '30 d vs previous 30 d',
  'pr.tag30': 'Last 30 days',
  'pr.tagPrevious': 'Previous 30 days',
  'pr.tagHistory': 'Available history',
  'pr.prevToCur': '{0} → {1}',
  'pr.newLine': 'Created and sold in the period: no comparison',
  'pr.moversMore': '{0} shown of {1}: see the full list below (Growing / Declining filters).',
  'pr.moversNote': 'Only products sold in the previous period (a real comparison base), as in Explorer.',
  'pr.listTitle': 'Products',
  'pr.searchPlaceholder': 'Search a product (name or identifier)',
  'pr.searchLabel': 'Search a product by name or Shopify identifier',
  'pr.sortLabel': 'Sort products',
  'pr.filtersLabel': 'Filter products',
  'pr.filter.all': 'All',
  'pr.filter.up': 'Growing',
  'pr.filter.down': 'Declining',
  'pr.filter.new': 'New in the period',
  'pr.filter.absent': 'No sale in the period',
  'pr.filter.uncategorised': 'No category',
  'pr.sort.revenue': 'Sort: 30-day revenue',
  'pr.sort.units': 'Sort: 30-day units',
  'pr.sort.gain': 'Sort: largest increase (€)',
  'pr.sort.loss': 'Sort: largest decrease (€)',
  'pr.sort.recent': 'Sort: last sale',
  'pr.sort.name': 'Sort: name (A → Z)',
  'pr.col.product': 'Product',
  'pr.col.revenue': 'Revenue 30 d',
  'pr.col.units': 'Units 30 d',
  'pr.col.share': 'Share of revenue',
  'pr.col.evolution': 'Change',
  'pr.col.lastSale': 'Last sale',
  'pr.col.status': 'Status',
  'pr.count': '{0} product(s) shown of {1}',
  'pr.noMatchTitle': 'No matching product',
  'pr.noMatch': 'Change the search or the filters.',
  'pr.listNote': 'Products sold in the last 30 days or in the previous 30 days. Revenue excl. VAT, net of refunds. Change: only against a real sale in the previous period. Last sale: available history.',
  'pr.openDetail': 'Open the details of {0}',
  'pr.watchHeading': 'To watch',
  'pr.watch.compareTitle': 'Comparison',
  'pr.watch.absentTitle': 'No sale in the period',
  'pr.watch.absentText': '{0} product(s) sold in the previous 30 days did not sell in the last 30 days.',
  'pr.watch.absentNone': 'Every product sold in the previous period also sold in the current period.',
  'pr.watch.lowerTitle': 'Declining, still selling',
  'pr.watch.lowerText': '{0} product(s) still sell, with lower revenue than in the previous period.',
  'pr.watch.lowerNone': 'No product that still sells has lower revenue than in the previous period.',
  'pr.watch.catalogueTitle': 'Product data quality',
  'pr.watch.uncat': '{0} product(s) sold without a category in the catalogue ({1} of revenue).',
  'pr.watch.uncatNone': 'Every product sold has a category.',
  'pr.watch.unmatched': '{0} item(s) sold no longer match the catalogue ({1} of revenue).',
  'pr.watch.unmatchedNone': 'Every item sold matches a catalogue product.',
  'pr.watch.negative': '{0} product(s) have more refunds than sales in the period (negative contribution).',
  'pr.andMore': '+ {0} more',
  'pr.catTitle': 'Revenue by category',
  'pr.catNote': 'Category = the catalogue product type. “No category” stays visible: that revenue is not assigned.',
  'pr.concNote': '{0} products sold in the period. Share of revenue of the first 1, 3 and 5 products.',
  'pr.loading': 'Loading product…',
  'pr.detailError': 'This product’s details are not available in the current report.',
  'pr.close': 'Close the details',
  'pr.d.currentTitle': 'Current period',
  'pr.d.perUnit': 'Revenue per unit',
  'pr.d.compareTitle': 'Previous period',
  'pr.d.prevRevenue': 'Previous revenue',
  'pr.d.prevUnits': 'Previous units',
  'pr.d.change': 'Change',
  'pr.d.changePct': 'Change (%)',
  'pr.d.contribution': 'Contribution to the change in total revenue: {0} of {1}.',
  'pr.d.trendTitle': 'Sales trend',
  'pr.d.trendFew': 'Sales on only {0} day(s): no curve, see the recent sales below.',
  'pr.d.trendNone': 'No sale in the period: no curve.',
  'pr.d.lastSale': 'Last known sale: {0}',
  'pr.d.recentTitle': 'Recent sales',
  'pr.d.refunded': '{0} refunded',
  'pr.d.noRecent': 'No sale in the available history.',
  'pr.d.recentNote': 'One row per order line: amount excl. VAT, net of recorded refunds.',

  // ---- Account control (top-right profile menu) ----
  'account.menuLabel': 'Account menu',
  'account.title': 'Account',
  'account.statusLocal': 'Local preview · no active session',
  'account.noSession': 'Analytics Premium does not have sign-in yet: there is no session to end and no account settings page. These actions will appear here as soon as they really exist.',
  'account.settings': 'Settings',
  'account.logout': 'Sign out',
};
