'use strict';
// Français - langue source/par defaut de Nordla AI.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.fr = {
  'brand.name': 'Nordla AI',

  'nav.brief': 'Résumé',
  'nav.changed': 'Ce qui a changé',
  'nav.explore': 'Explorer',
  'nav.customers': 'Clients',
  'nav.products': 'Produits',
  'nav.askNordla': 'Parle à Nordla',

  'sidebar.askSubtitle': 'Obtenez des informations sur votre activité',

  'topbar.title': 'Analytics Premium',
  'topbar.lastSynced': 'Rapport généré {0}',

  'time.justNow': 'à l’instant',
  'time.minAgo': 'il y a {0} min',
  'time.hAgo': 'il y a {0} h',
  'time.dAgo': 'il y a {0} j',

  'period.last30Days': '30 derniers jours',

  'greeting.morning': 'Bonjour',
  'greeting.afternoon': 'Bon après-midi',
  'greeting.evening': 'Bonsoir',
  'hero.subtitle': 'Voici ce qui a changé cette semaine.',

  'kpi.netRevenue': 'Chiffre d’affaires net',
  'kpi.orders': 'Commandes',
  'kpi.aov': 'Panier moyen',
  'kpi.grossMargin': 'Marge brute',
  'kpi.thisPeriod': 'Cette période',
  'kpi.partialCostCoverage': 'Coûts partiellement connus',
  'kpi.infoTitle': 'Période en cours, données réelles',
  'kpi.noData': 'Aucune donnée de vente disponible pour cette période.',
  'kpi.insufficientHistory': 'Historique quotidien insuffisant pour un graphique.',

  'insight.badge': 'Meilleurs produits',
  'insight.title': 'Vos meilleurs produits par chiffre d’affaires',
  'insight.subtitle': '30 derniers jours, données de vente réelles.',
  'insight.body': 'Classement réel de la période en cours. La comparaison avec les 30 jours précédents est disponible dans « Ce qui a changé » et dans Explorer.',
  'insight.seeWhy': 'Voir pourquoi',
  'insight.seeWhyTitle': 'Cette action n’est pas encore disponible.',
  'insight.addToCommandCenter': 'Ajouter au Centre de commande',
  'insight.commandCenterTitle': 'Le Centre de commande n’est pas encore disponible',
  'insight.rankTitle': 'Chiffre d’affaires des meilleurs produits',
  'insight.noProducts': 'Aucune vente de produit sur cette période.',
  'insight.units': '{0} unités',
  'insight.shareNote': 'La part indiquée correspond au chiffre d’affaires combiné de ces {0} produits ({1}), et non au chiffre d’affaires total du magasin.',

  'watch.heading': 'Autres points à surveiller',
  'watch.aovTitle': 'Évolution du panier moyen',
  'watch.aovText': 'La comparaison du panier moyen avec la période précédente n’est pas disponible.',
  'watch.dormantTitle': 'Clients inactifs',
  'watch.dormantText': 'Cet indicateur n’est pas encore calculé - il nécessite une définition de l’inactivité et un historique client plus riche que celui disponible actuellement.',

  'health.title': 'État des données',
  'health.upToDate': 'Données à jour',
  'health.lastGenerated': 'Dernière génération',
  'health.viewSources': 'Voir les sources de données',

  'app.noReport': 'Aucun instantané de rapport trouvé pour le moment. Exécutez `npm run metrics:report` pour en générer un.',

  'common.dash': '—',
  'common.and': 'et',

  'wc.title': 'Ce qui a changé',
  'wc.subtitle': 'Voici les principaux changements de votre activité cette semaine, avec des explications simples et les prochaines actions possibles.',
  'wc.badgeUp': 'Bonne performance',
  'wc.badgeDown': 'À surveiller en priorité',
  'wc.badgeFlat': 'Stable',
  'wc.headlineUp': 'Le chiffre d’affaires net a augmenté de {0}.',
  'wc.headlineDown': 'Le chiffre d’affaires net a baissé de {0}.',
  'wc.headlineFlat': 'Le chiffre d’affaires net est resté stable ({0}).',
  'wc.noContributors': 'Aucun produit ne ressort clairement de cette variation.',
  'wc.bodyText': 'Comparé à la période précédente ({0} → {1}), le chiffre d’affaires net est passé de {2} à {3}.',
  'wc.noComparison': 'La comparaison avec la période précédente n’est pas encore disponible - il n’y a pas encore assez d’historique.',
  'wc.dataReliable': 'Le chiffre d’affaires de cette comparaison provient de commandes réelles et vérifiées.',
  'wc.contributorsTitle': 'Principaux contributeurs',
  'wc.vsPreviousPeriod': 'vs période précédente',
  'wc.watchlistLabel': 'À suivre',
  'wc.partialDataLabel': 'Données partielles',
  'wc.dismiss': 'Ignorer',
  'wc.dismissTitle': 'Cette action n’est pas encore disponible.',

  'wc.watchHeading': 'Autres éléments à surveiller',
  'wc.watchAovUp': 'Le panier moyen a augmenté de {0} %.',
  'wc.watchAovDown': 'Le panier moyen a diminué de {0} %.',
  'wc.watchAovDetail': 'Il est passé de {0} à {1}.',
  'wc.watchMoversUp': '{0} produit(s) ont porté la hausse.',
  'wc.watchMoversDown': '{0} produit(s) ont porté la baisse.',
  'wc.dqLabel': 'Coût d’achat connu (part du chiffre d’affaires)',
  'wc.watchCostCoverage': 'Coûts connus pour {0} % du chiffre d’affaires.',
  'wc.watchCostCoverageDetail': 'Le reste n’est pas encore classifié - la marge réelle peut différer.',

  'wc.otherChangesHeading': 'Autres changements ({0})',
  'wc.rowOrdersTitle': 'Commandes',
  'wc.rowOrdersDetail': 'Vous avez reçu {0} commandes, contre {1} précédemment.',
  'wc.rowGrossMarginTitle': 'Marge brute',
  'wc.rowGrossMarginDetail': 'Votre marge brute est de {0} %, contre {1} % précédemment.',
  'wc.rowActiveProductsTitle': 'Produits actifs vendus',
  'wc.rowActiveProductsDetail': '{0} produits vendus sur la période, contre {1} précédemment.',

  // ---------- Explorer ----------
  'ex.title': 'Explorer',
  'ex.subtitle': 'Analysez en profondeur vos données pour comprendre ce qui performe, où agir et quelles opportunités saisir.',
  'ex.export': 'Exporter',
  'ex.tab.overview': 'Vue d’ensemble',
  'ex.tab.sales': 'Ventes',
  'ex.tab.products': 'Produits',
  'ex.tab.customers': 'Clients',
  'ex.tab.channels': 'Canaux',
  'ex.tab.zones': 'Zones',
  'ex.tab.period': 'Période',
  'ex.tab.comparison': 'Comparaison',
  'ex.kpi.revenue': 'Chiffre d’affaires',
  'ex.kpi.orders': 'Commandes',
  'ex.kpi.customers': 'Clients actifs',
  'ex.kpi.units': 'Produits vendus',
  'ex.vsPrevious': 'vs période précédente',
  'ex.noComparison': 'Comparaison indisponible',
  'ex.identifiedNote': 'Clients identifiés · {0} des commandes',
  'ex.salesTitle': 'Ventes sur la période',
  'ex.granularity': 'Granularité',
  'ex.byDay': 'Par jour',
  'ex.byWeek': 'Par semaine',
  'ex.partialWeeks': 'Les semaines aux extrémités de la période sont partielles.',
  'ex.categoryTitle': 'Répartition par catégorie',
  'ex.uncategorised': 'Sans catégorie',
  'ex.others': 'Autres',
  'ex.total': 'Total',
  'ex.topProducts': 'Top produits',
  'ex.topCustomers': 'Top clients',
  'ex.col.product': 'Produit',
  'ex.col.sales': 'Ventes',
  'ex.col.revenue': 'CA',
  'ex.col.evolution': 'Évolution',
  'ex.col.customer': 'Client',
  'ex.col.orders': 'Commandes',
  'ex.customerLabel': 'Client {0}',
  'ex.customerNote': 'Seuls les clients identifiés sont listés ({0} des commandes). Aucun nom n’est stocké : les clients sont pseudonymisés.',
  'ex.insufficient': 'Données insuffisantes',
  'ex.insufficientSub': 'Il faut au moins 2 points de données réelles pour tracer ce graphique.',
  'ex.noCategories': 'Aucune vente catégorisée sur la période.',
  'ex.noProducts': 'Aucune vente de produit sur la période.',
  'ex.noCustomers': 'Aucun client identifié sur la période : les commandes sans clé client ne sont jamais attribuées à un client.',
  'ex.noReport': 'Le rapport ne contient pas encore les données Explorer. Régénérez le rapport.',
  'ex.soonTitle': 'Bientôt disponible',
  'ex.soonSub': 'Cette vue d’Explorer n’est pas encore disponible.',
  'period.fixed': 'Fixe',
  'period.fixedNote': 'Explorer affiche une période fixe : les 30 derniers jours comparés aux 30 précédents.',
  'ex.trendTitle': 'Évolution des ventes',
  'ex.kpi.aov': 'Panier moyen',
  'ex.kpi.items': 'Articles vendus',
  'ex.channelTitle': 'Ventes par canal',
  'ex.channelUnknown': 'Canal non renseigné',
  'ex.noChannels': 'Aucune vente avec un canal sur la période.',
  'ex.cmpTitle': 'Période actuelle vs précédente',
  'ex.cmpPrev': 'Période précédente',
  'ex.cmpCur': 'Période actuelle',
  'ex.cmpNote': 'Blocs de 7 jours à partir du début de chaque période, comparés jour par jour dans le même ordre.',
  'ex.cmpPartial': 'Dernier bloc : {0} jours.',
  'ex.noPrevious': 'Il faut des ventes sur la période précédente pour la comparer.',
  'ex.contribTitle': 'Contribution au chiffre d’affaires',
  'ex.contribNote': 'Variation totale du chiffre d’affaires : {0} vs période précédente.',
  'ex.noContrib': 'Il faut une période précédente avec des ventes pour mesurer les contributions.',
  'ex.bestDay': 'Meilleur jour de vente',
  'ex.weakDay': 'Jour le plus faible',
  'ex.weakNote': 'Parmi les jours avec au moins une vente.',
  'ex.daysNoSale': '{0} jours sans vente sur {1}.',
  'ex.dayOrders1': '1 commande',
  'ex.dayOrdersN': '{0} commandes',
  'ex.noDays': 'Aucun jour avec vente sur la période.',
  'ex.kpi.productsSold': 'Produits vendus',
  'ex.kpi.topProduct': 'Produit n°1 en CA',
  'ex.kpi.topCategory': 'Catégorie n°1',
  'ex.kpi.top3': 'Part du Top 3 dans le CA',
  'ex.distinctProducts': '{0} produits distincts vendus',
  'ex.currentOnly': 'Période actuelle uniquement',
  'ex.concentrationNote': 'Concentration du CA, pas une performance',
  'ex.rankingTitle': 'Classement des produits',
  'ex.units': '{0} unités',
  'ex.statusNew': 'Nouveau sur la période',
  'ex.statusNotBefore': 'Pas de vente avant',
  'ex.unmatched': 'Produit du catalogue supprimé',
  'ex.growthTitle': 'Produits en hausse',
  'ex.declineTitle': 'Produits en baisse',
  'ex.noGrowth': 'Aucun produit en hausse par rapport à une vente de la période précédente.',
  'ex.noDecline': 'Aucun produit en baisse par rapport à une vente de la période précédente.',
  'ex.noSaleNow': 'Plus de vente',
  'ex.contribChangeTitle': 'Contribution à la variation du chiffre d’affaires',
  'ex.catShareTitle': 'Répartition du CA par catégorie',
  'ex.concTitle': 'Concentration du chiffre d’affaires',
  'ex.topN': 'Top {0}',
  'ex.concSentence': 'Les 3 premiers produits représentent {0} du chiffre d’affaires.',
  'ex.concNeutral': 'Indicateur descriptif, sans jugement : à lire selon votre catalogue.',
  'ex.unitsVsRevenue': 'Unités vendues vs chiffre d’affaires',
  'ex.unitsShare': 'Part des unités',
  'ex.revenueShare': 'Part du CA',
  'ex.unitsNote': 'Repères #n = rang du produit dans le classement ci-dessus. Unités contre chiffre d’affaires uniquement, sans marge.',
  'ex.marginTitle': 'Marge par produit',
  'ex.marginPartial': 'Données partielles',
  'ex.marginSub': 'Marge par produit non affichée : coûts connus pour {0} du chiffre d’affaires, dont {1} vérifiés. Un classement par marge exigerait des coûts complets.',
  'ex.unit1': '1 unité',
  'ex.kpi.activeCustomers': 'Clients actifs',
  'ex.kpi.newCustomers': 'Nouveaux clients',
  'ex.kpi.returningCustomers': 'Clients récurrents',
  'ex.kpi.identifiedRevenue': 'CA des clients identifiés',
  'ex.covNote': 'Clients identifiés · {0} des commandes',
  'ex.covNotePrev': 'Clients identifiés · {0} des commandes ({1} la période précédente)',
  'ex.newDef': 'Première commande de leur historique dans la période',
  'ex.returningDef': 'Déjà des commandes avant la période, ou 2 commandes ou plus',
  'ex.seg.new': 'Nouveaux clients',
  'ex.seg.returning': 'Clients récurrents',
  'ex.seg.unknown': 'Historique inconnu',
  'ex.seg.newShort': 'Nouveau',
  'ex.seg.returningShort': 'Récurrent',
  'ex.seg.unknownShort': 'Inconnu',
  'ex.nCustomers': '{0} clients',
  'ex.identifiedShort': 'identifiés',
  'ex.newVsReturningTitle': 'Nouveaux vs clients récurrents',
  'ex.segDefs': 'Nouveau : première commande de son historique dans la période (index de commande de la source). Récurrent : commande précédente déjà enregistrée, ou 2 commandes ou plus. Inconnu : index de commande non fiable.',
  'ex.custRevenueTitle': 'Répartition du CA clients',
  'ex.custRevenueNote': 'Part des commandes avec client identifié : {0}. Ce n’est pas la répartition de tous les clients de la boutique.',
  'ex.custTrendTitle': 'Évolution des clients identifiés',
  'ex.seriesNew': 'Nouveaux clients',
  'ex.seriesActive': 'Clients actifs',
  'ex.custTrendNote': 'Par semaine (semaines de la période, les extrémités peuvent être partielles).',
  'ex.activityTitle': 'Activité des clients',
  'ex.rec.d30': 'Dernier achat il y a 30 jours ou moins',
  'ex.rec.d60': 'Dernier achat il y a 31 à 60 jours',
  'ex.rec.d90': 'Dernier achat il y a 61 à 90 jours',
  'ex.rec.d90plus': 'Dernier achat il y a plus de 90 jours',
  'ex.recNote': 'Tranches descriptives sur {0} jours d’historique disponible. Nordla n’a pas de définition approuvée d’un client « dormant » : aucune n’est appliquée.',
  'ex.lastOrder': 'Dernier achat : {0}',
  'ex.basketShort': 'panier',
  'ex.frequencyTitle': 'Fréquence d’achat',
  'ex.freq.one': '1 commande',
  'ex.freq.two': '2 commandes',
  'ex.freq.three': '3 commandes ou plus',
  'ex.freqNote': 'Commandes de la période par client identifié.',
  'ex.avgOrders': 'Commandes par client : {0} en moyenne.',
  'ex.valueTitle': 'Valeur client',
  'ex.sampleTitle': 'Échantillon insuffisant',
  'ex.gated': 'Moyennes non affichées : {0} clients identifiés, minimum requis {1} (règle Nordla existante pour les moyennes par client).',
  'ex.noClv': 'Aucune valeur vie client (CLV) n’est calculée : la méthode et l’historique nécessaires ne sont pas disponibles.',
  'ex.val.avgRevenue': 'CA moyen par client identifié',
  'ex.val.median': 'CA médian par client identifié',
  'ex.val.basket': 'Panier moyen des clients identifiés',
  'ex.cohortTitle': 'Cohortes de rétention',
  'ex.cohortSub': 'Aucune cohorte n’est tracée : les données actuelles ne permettent pas un calcul de rétention fiable.',
  'ex.cohortReason.SHORT_HISTORY': 'Historique de {0} jours, moins que les {1} jours requis.',
  'ex.cohortReason.TOO_FEW_RETURNING_CUSTOMERS': 'Trop peu de clients récurrents identifiés.',
  'ex.cohortReason.NO_APPROVED_COHORT_DEFINITION': 'Aucune définition de cohorte n’est encore approuvée.',
  'ex.channelName.Point of Sale': 'Point de vente',
  'ex.channelName.Online Store': 'Boutique en ligne',
  'ex.noChannelData': 'Aucune vente par canal sur la période.',
  'ex.metricLabel': 'Indicateur',
  'ex.kpi.topChannel': 'Canal n°1 en CA',
  'ex.kpi.topChannelShare': 'Part du canal principal',
  'ex.kpi.topChannelOrders': 'Commandes du canal principal',
  'ex.kpi.topChannelAov': 'Panier moyen du canal principal',
  'ex.prevShare': 'Période précédente : {0}',
  'ex.chShareTitle': 'Répartition du chiffre d’affaires par canal',
  'ex.chPerfTitle': 'Performance par canal',
  'ex.chTrendTitle': 'Évolution des canaux',
  'ex.chTrendNote': 'Chiffre d’affaires par semaine et par canal (semaines de la période, les extrémités peuvent être partielles).',
  'ex.chInsightTitle': 'Lecture des chiffres',
  'ex.insShare': '{0} représente {1} du chiffre d’affaires de la période.',
  'ex.insAov': 'Le panier moyen du canal {0} est supérieur de {1} à celui du canal {2}.',
  'ex.insNeutral': 'Constats chiffrés, sans jugement.',
  'ex.chVarTitle': 'Variation vs période précédente',
  'ex.noSalesPeriod': 'Aucune vente sur la période',
  'ex.chContribTitle': 'Contribution des canaux à la variation du CA',
  'ex.chProductsTitle': 'Produits par canal',
  'ex.chCustomersTitle': 'Clients par canal',
  'ex.chCustLine': '{0} clients identifiés · {1} des commandes du canal',
  'ex.chCustSplit': '{0} nouveaux · {1} récurrents',
  'ex.chCustNote': 'Clients identifiés uniquement (clé pseudonyme). Les commandes sans client identifié ne sont attribuées à personne.',
  'ex.geo.kpiCoverage': 'Couverture géographique',
  'ex.geo.covNote': '{0} commande(s) sur {1} avec une ville exploitable',
  'ex.geo.covNeutral': 'Aucune extrapolation des commandes non localisées',
  'ex.geo.kpiSaleLoc': 'Lieu de vente renseigné',
  'ex.geo.saleLocNote': '{0} commande(s) sur {1}',
  'ex.geo.saleLocNeutral': 'Lieu du magasin, pas celui du client',
  'ex.geo.kpiZones': 'Zones exploitables',
  'ex.geo.zonesNote': 'Ville, code postal, province ou pays',
  'ex.geo.kpiOrders': 'Commandes de la période',
  'ex.geo.blockedTitle': 'Analyse géographique non disponible',
  'ex.geo.blockedSub': 'Seulement {0} des commandes disposent d\'une ville exploitable. Aucun graphique ni carte n\'est affiché plutôt que des chiffres trompeurs.',
  'ex.geo.foundTitle': 'Données géographiques présentes',
  'ex.geo.colField': 'Donnée',
  'ex.geo.colMeaning': 'Ce que c\'est',
  'ex.geo.colOrders': 'Commandes',
  'ex.geo.colUsable': 'Utilisable',
  'ex.geo.saleLocation': 'Lieu de vente : {0}',
  'ex.geo.saleLocMeaning': 'Lieu de vente (magasin), pas la localisation du client',
  'ex.geo.noSaleLocation': 'Aucun lieu de vente n\'est associé aux commandes.',
  'ex.geo.no': 'Non',
  'ex.geo.absentTitle': 'Données absentes',
  'ex.geo.absentLine': 'Adresse de livraison ou de facturation (ville, code postal, province, pays) : non synchronisée. Les commandes en ligne n\'ont donc aucune destination connue.',
  'ex.geo.unlockTitle': 'Pour débloquer cette analyse',
  'ex.geo.unlock1': 'Synchroniser, pour chaque commande, au minimum la ville ou le code postal de destination (sans rue, sans nom).',
  'ex.geo.unlock2': 'Ou renseigner la ville de chaque point de vente, si plusieurs lieux de vente existent.',
  'ex.geo.unlock3': 'Une couverture suffisante des commandes localisées, sur au moins deux zones différentes (seuil à définir avec le responsable produit).',
  'ex.geo.privacy': 'Confidentialité : aucune adresse n\'est stockée. L\'analyse restera agrégée (ville, province ou pays) et ne montrera jamais de client individuel.',
  'ex.geo.kpiOrdersNote': 'Période verrouillée : 30 derniers jours',
  'ex.per.kpiCur': 'CA période actuelle',
  'ex.per.kpiPrev': 'CA période précédente',
  'ex.per.kpiAbs': 'Variation absolue',
  'ex.per.kpiPct': 'Variation en %',
  'ex.per.last30': '30 derniers jours',
  'ex.per.prev30': '30 jours précédents',
  'ex.per.noPrev': 'Aucune période précédente disponible',
  'ex.per.pctInvalid': 'Indisponible : aucune vente sur la période précédente',
  'ex.per.trendTitle': 'Évolution sur la période',
  'ex.per.bestTitle': 'Meilleure période',
  'ex.per.weakTitle': 'Période la plus faible',
  'ex.per.bestWeek': 'Meilleure semaine complète : {0} ({1})',
  'ex.per.weakWeek': 'Semaine complète la plus faible : {0} ({1})',
  'ex.per.weekOf': 'semaine du {0}',
  'ex.per.activityTitle': 'Répartition de l\'activité',
  'ex.per.daysWith': '{0} jours avec ventes',
  'ex.per.daysWithout': '{0} jours sans vente',
  'ex.per.daysAbove': '{0} jours au-dessus de la moyenne journalière',
  'ex.per.daysBelow': '{0} jours sous la moyenne journalière',
  'ex.per.activityNote': 'Constats chiffrés sur {0} jours ; la moyenne compte les jours sans vente.',
  'ex.per.weeksTitle': 'Contribution des semaines au CA',
  'ex.per.weeksNote': 'Part de chaque semaine dans le CA de la période. Les semaines aux extrémités sont partielles ({0} jours).',
  'ex.per.weekLabel': 'Sem. {0}',
  'ex.per.regTitle': 'Régularité des ventes',
  'ex.per.mean': 'Moyenne par jour',
  'ex.per.median': 'Médiane par jour',
  'ex.per.sd': 'Écart-type',
  'ex.per.cv': 'Coefficient de variation',
  'ex.per.regNote': 'Calculé sur les {0} jours de la période, jours sans vente inclus. L\'écart-type mesure la dispersion des ventes journalières autour de la moyenne ; le coefficient de variation le rapporte à la moyenne. Plus ils sont élevés, plus les ventes varient d\'un jour à l\'autre.',
  'ex.per.weekdayTitle': 'Performance par jour de la semaine',
  'ex.per.weekdayNote': 'Moyenne par occurrence : chaque jour de la semaine est divisé par le nombre de fois où il apparaît dans la période.',
  'ex.per.weekdayLine': '{0} commande(s) · {1}×',
  'ex.per.todTitle': 'Performance par moment de la journée',
  'ex.per.tod.night': 'Nuit (0 h–6 h)',
  'ex.per.tod.morning': 'Matin (6 h–12 h)',
  'ex.per.tod.midday': 'Midi (12 h–14 h)',
  'ex.per.tod.afternoon': 'Après-midi (14 h–18 h)',
  'ex.per.tod.evening': 'Soirée (18 h–24 h)',
  'ex.per.todNote': 'Heure locale ({0}) de {1} commande(s) sur {2}. CA net, remboursements rattachés à la commande.',
  'ex.per.orders': '{0} commande(s)',
  'ex.per.whyTitle': 'D\'où vient la variation ?',
  'ex.per.whyOrders': 'Le nombre de commandes varie de {0} ({1} contre {2}).',
  'ex.per.whyAov': 'Le panier moyen varie de {0} ({1} contre {2}).',
  'ex.per.whyNote': 'Lecture arithmétique : CA = commandes × panier moyen. Aucune cause n\'est établie.',
  'ex.per.noData': 'Pas assez de jours pour cette analyse.',
  'ex.cp.periodCur': 'Période actuelle',
  'ex.cp.periodPrev': 'Période précédente',
  'ex.cp.range': '{0} – {1} ({2} jours)',
  'ex.cp.previousValue': 'Avant : {0}',
  'ex.cp.change': 'Écart : {0}',
  'ex.cp.blocksTitle': 'Période actuelle vs précédente',
  'ex.cp.blocksNote': 'Blocs de 7 jours alignés par position : le bloc 1 de chaque période, puis le bloc 2, etc. Le dernier bloc est partiel ({0} jours).',
  'ex.cp.blocksNoteFull': 'Blocs de 7 jours alignés par position : le bloc 1 de chaque période, puis le bloc 2, etc.',
  'ex.cp.blockTip': '{0} : du {1} au {2} contre du {3} au {4}',
  'ex.cp.blockLabel': 'S{0}',
  'ex.cp.blockLabelPartial': 'S{0} ({1} j)',
  'ex.cp.trendTitle': 'Évolution comparée',
  'ex.cp.trendNote': 'Alignement par jour relatif (jour 1 à jour {0}) : les dates calendaires des deux périodes ne sont pas les mêmes.',
  'ex.cp.dayN': 'J{0}',
  'ex.cp.wfTitle': 'Décomposition de la variation du chiffre d\'affaires',
  'ex.cp.wfPrev': 'CA précédent',
  'ex.cp.wfPrevShort': 'Avant',
  'ex.cp.wfCur': 'CA actuel',
  'ex.cp.wfCurShort': 'Actuel',
  'ex.cp.wfOther': 'Autres catégories ({0})',
  'ex.cp.wfOtherShort': 'Autres',
  'ex.cp.wfNote': 'Décomposition par catégorie du catalogue (« Sans catégorie » incluse) : chaque vente appartient à une seule catégorie, la somme des écarts rejoint donc exactement le CA actuel.',
  'ex.cp.productsTitle': 'Produits qui expliquent la variation',
  'ex.cp.channelsTitle': 'Évolution par canal',
  'ex.cp.categoriesTitle': 'Évolution par catégorie',
  'ex.cp.shareOfChange': '{0} de la variation',
  'ex.cp.statusNew': 'Nouveau sur la période',
  'ex.cp.statusAbsent': 'Aucune vente sur la période',
  'ex.cp.noCategory': 'Sans catégorie',
  'ex.cp.volumeTitle': 'Volume vs panier moyen',
  'ex.cp.ordersLine': 'Commandes : {0}',
  'ex.cp.aovLine': 'Panier moyen : {0}',
  'ex.cp.up': 'hausse',
  'ex.cp.down': 'baisse',
  'ex.cp.flat': 'stabilité',
  'ex.cp.volumeSentence': 'Le CA évolue dans un contexte de {0} du nombre de commandes et de {1} du panier moyen.',
  'ex.cp.unavailable': 'Indisponible',
  'ex.cp.customersTitle': 'Clients identifiés',
  'ex.cp.custActive': 'Clients identifiés actifs',
  'ex.cp.custRevenue': 'CA des clients identifiés',
  'ex.cp.custNew': 'Nouveaux clients',
  'ex.cp.custReturning': 'Clients récurrents',
  'ex.cp.coverage': '{0} des commandes identifiées vs {1} auparavant',
  'ex.cp.coverageWarn': 'La couverture d’identification n’est pas la même dans les deux périodes : ces écarts ne mesurent pas nécessairement une évolution de la clientèle.',
  'ex.cp.coverageOk': 'La couverture d\'identification est proche entre les deux périodes.',
  'ex.cp.watchUp': 'Plus forte progression',
  'ex.cp.watchDown': 'Plus forte baisse',
  'ex.cp.watchNote': 'Produit, en écart absolu en euros.',
  'ex.cp.noMove': 'Aucun mouvement de produit à afficher.',
  'ex.cp.mostTitle': 'Ce qui a le plus changé',
  'ex.cp.mostRevenue': 'CA : {0}',
  'ex.cp.mostOrders': 'Commandes : {0}',
  'ex.cp.mostAov': 'Panier moyen : {0}',
  'ex.cp.mostProduct': 'Principal contributeur produit : {0} ({1})',
  'ex.cp.mostChannel': 'Canal avec la plus forte variation : {0} ({1})',
  'ex.cp.qualityTitle': 'Qualité de comparaison',
  'ex.cp.q.comparable': 'Comparable',
  'ex.cp.q.caution': 'À interpréter avec prudence',
  'ex.cp.q.partial': 'Données partielles',
  'ex.cp.q.days': 'Nombre de jours',
  'ex.cp.q.daysDetail': '{0} jours contre {1} jours.',
  'ex.cp.q.last_block': 'Dernier bloc',
  'ex.cp.q.lastBlockPartial': 'Le dernier bloc ne compte que {0} jours, comparés aux {1} jours correspondants.',
  'ex.cp.q.lastBlockFull': 'Tous les blocs comptent 7 jours.',
  'ex.cp.q.customer_coverage': 'Identification des clients',
  'ex.cp.q.coverageUnknown': 'Couverture non mesurable sur l\'une des périodes.',
  'ex.cp.q.categories': 'Classement en catégories',
  'ex.cp.q.categoriesDetail': '{0} du CA actuel est sans catégorie.',
  'ex.cp.q.costs': 'Coûts et marge',
  'ex.cp.q.costsDetail': 'Marge non comparée : coûts renseignés pour {0} des produits, vérifiés pour {1}.',
  'ex.cp.qualityNote': 'Règles explicites, sans score global.',
  'ex.cp.noPrevious': 'Aucune période précédente à comparer.',
  'ex.cp.exportSection': 'comparaison',
  'ex.days': 'jours',
  'topbar.reportGenerated': 'Rapport généré {0}',
  'kpi.costCoverageDetail': '{0} du CA couvert · {1} des coûts vérifiés',
  'watch.aovCompared': 'Panier moyen : {0} contre {1} sur les 30 jours précédents ({2}).',
  'wc.gainsLine': 'Les produits en plus forte hausse ({0}) ajoutent {1}.',
  'wc.lossesLine': 'Les produits en plus forte baisse ({0}) retirent {1}.',
  'wc.netLine': 'Variation nette du chiffre d’affaires : {0}.',
  'wc.marginCaveat': 'Coûts partiellement connus : {0} du CA couvert · {1} des coûts vérifiés.',
  'ex.geo.pendingSub': 'Des zones exploitables existent, mais le seuil de couverture minimal n’est pas encore défini : l’analyse par zone n’est pas activée.',
};
