'use strict';
// Nederlands - tweede taal van Nordla AI. Volledige vertaling, natuurlijke zakelijke toon.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.nl = {
  'brand.name': 'Nordla AI',

  'nav.brief': 'Overzicht',
  'nav.changed': 'Wat is veranderd',
  'nav.explore': 'Verkennen',
  'nav.customers': 'Klanten',
  'nav.products': 'Producten',
  'nav.askNordla': 'Vraag het Nordla',

  'sidebar.askSubtitle': 'Krijg inzicht in uw bedrijf',

  'topbar.title': 'Analytics Premium',
  'topbar.lastSynced': 'Rapport gegenereerd {0}',

  'time.justNow': 'zojuist',
  'time.minAgo': '{0} min geleden',
  'time.hAgo': '{0} u geleden',
  'time.dAgo': '{0} d geleden',

  'period.last30Days': 'Laatste 30 dagen',

  'greeting.morning': 'Goedemorgen',
  'greeting.afternoon': 'Goedemiddag',
  'greeting.evening': 'Goedenavond',
  'hero.subtitle': 'Dit is er deze week veranderd.',

  'kpi.netRevenue': 'Netto-omzet',
  'kpi.orders': 'Bestellingen',
  'kpi.aov': 'Gemiddelde bestelwaarde',
  'kpi.grossMargin': 'Brutomarge',
  'kpi.thisPeriod': 'Deze periode',
  'kpi.partialCostCoverage': 'Kosten gedeeltelijk bekend',
  'kpi.infoTitle': 'Huidige periode, echte gegevens',
  'kpi.noData': 'Geen verkoopgegevens beschikbaar voor deze periode.',
  'kpi.insufficientHistory': 'Onvoldoende dagelijkse geschiedenis voor een grafiek.',

  'insight.badge': 'Beste producten',
  'insight.title': 'Uw best verkopende producten naar omzet',
  'insight.subtitle': 'Laatste 30 dagen, echte verkoopgegevens.',
  'insight.body': 'Werkelijke rangschikking van de lopende periode. De vergelijking met de voorgaande 30 dagen vindt u onder «Wat er veranderde» en in Explorer.',
  'insight.seeWhy': 'Bekijk waarom',
  'insight.seeWhyTitle': 'Deze actie is nog niet beschikbaar.',
  'insight.addToCommandCenter': 'Toevoegen aan Command Center',
  'insight.commandCenterTitle': 'Command Center is nog niet beschikbaar',
  'insight.rankTitle': 'Omzet van topproducten',
  'insight.noProducts': 'Geen productverkopen in deze periode.',
  'insight.units': '{0} stuks',
  'insight.shareNote': 'Het getoonde aandeel is van de gecombineerde omzet van deze {0} producten ({1}), niet van de totale winkelomzet.',

  'watch.heading': 'Andere aandachtspunten',
  'watch.aovTitle': 'AOV-trend',
  'watch.aovText': 'De vergelijking van het gemiddelde bestelbedrag met de vorige periode is niet beschikbaar.',
  'watch.dormantTitle': 'Inactieve klanten',
  'watch.dormantText': 'Deze metriek wordt nog niet berekend - hiervoor is een definitie van inactiviteit nodig en een rijkere klanthistorie dan momenteel beschikbaar is.',

  'health.title': 'Datastatus',
  'health.upToDate': 'Gegevens up-to-date',
  'health.lastGenerated': 'Laatst gegenereerd',
  'health.viewSources': 'Databronnen bekijken',

  'app.noReport': 'Er is nog geen rapportmoment gevonden. Voer `npm run metrics:report` uit om er een te genereren.',

  'common.dash': '—',
  'common.and': 'en',

  'wc.title': 'Wat is veranderd',
  'wc.subtitle': 'Dit zijn de belangrijkste veranderingen in uw bedrijf deze week, met eenvoudige uitleg en mogelijke vervolgstappen.',
  'wc.badgeUp': 'Goede prestatie',
  'wc.badgeDown': 'Prioriteit voor aandacht',
  'wc.badgeFlat': 'Stabiel',
  'wc.headlineUp': 'De netto-omzet is gestegen met {0}.',
  'wc.headlineDown': 'De netto-omzet is gedaald met {0}.',
  'wc.headlineFlat': 'De netto-omzet bleef stabiel ({0}).',
  'wc.noContributors': 'Geen enkel product springt duidelijk uit bij deze verandering.',
  'wc.bodyText': 'Vergeleken met de vorige periode ({0} → {1}) ging de netto-omzet van {2} naar {3}.',
  'wc.noComparison': 'De vergelijking met de vorige periode is nog niet beschikbaar - er is nog niet genoeg geschiedenis.',
  'wc.dataReliable': 'De omzet in deze vergelijking komt van echte, geverifieerde bestellingen.',
  'wc.contributorsTitle': 'Belangrijkste bijdragers',
  'wc.vsPreviousPeriod': 'vs vorige periode',
  'wc.watchlistLabel': 'Volgen',
  'wc.partialDataLabel': 'Gedeeltelijke gegevens',
  'wc.dismiss': 'Negeren',
  'wc.dismissTitle': 'Deze actie is nog niet beschikbaar.',

  'wc.watchHeading': 'Andere aandachtspunten',
  'wc.watchAovUp': 'De gemiddelde bestelwaarde is gestegen met {0}%.',
  'wc.watchAovDown': 'De gemiddelde bestelwaarde is gedaald met {0}%.',
  'wc.watchAovDetail': 'Ze ging van {0} naar {1}.',
  'wc.watchMoversUp': '{0} product(en) droegen bij aan de stijging.',
  'wc.watchMoversDown': '{0} product(en) droegen bij aan de daling.',
  'wc.dqLabel': 'Aankoopprijs bekend (deel van de omzet)',
  'wc.watchCostCoverage': 'Kosten bekend voor {0}% van de omzet.',
  'wc.watchCostCoverageDetail': 'De rest is nog niet geclassificeerd - de werkelijke marge kan afwijken.',

  'wc.otherChangesHeading': 'Andere veranderingen ({0})',
  'wc.rowOrdersTitle': 'Bestellingen',
  'wc.rowOrdersDetail': 'U ontving {0} bestellingen, tegenover {1} eerder.',
  'wc.rowGrossMarginTitle': 'Brutomarge',
  'wc.rowGrossMarginDetail': 'Uw brutomarge is {0}%, tegenover {1}% eerder.',
  'wc.rowActiveProductsTitle': 'Actief verkochte producten',
  'wc.rowActiveProductsDetail': '{0} producten verkocht in deze periode, tegenover {1} eerder.',

  // ---------- Explorer ----------
  'ex.title': 'Verkennen',
  'ex.subtitle': 'Analyseer uw gegevens grondig om te begrijpen wat goed presteert, waar u kunt ingrijpen en welke kansen u kunt grijpen.',
  'ex.export': 'Exporteren',
  'ex.tab.overview': 'Overzicht',
  'ex.tab.sales': 'Verkoop',
  'ex.tab.products': 'Producten',
  'ex.tab.customers': 'Klanten',
  'ex.tab.channels': 'Kanalen',
  'ex.tab.zones': 'Zones',
  'ex.tab.period': 'Periode',
  'ex.tab.comparison': 'Vergelijking',
  'ex.kpi.revenue': 'Omzet',
  'ex.kpi.orders': 'Bestellingen',
  'ex.kpi.customers': 'Actieve klanten',
  'ex.kpi.units': 'Verkochte producten',
  'ex.vsPrevious': 'vs vorige periode',
  'ex.noComparison': 'Vergelijking niet beschikbaar',
  'ex.identifiedNote': 'Geïdentificeerde klanten · {0} van de bestellingen',
  'ex.salesTitle': 'Verkoop over de periode',
  'ex.granularity': 'Granulariteit',
  'ex.byDay': 'Per dag',
  'ex.byWeek': 'Per week',
  'ex.partialWeeks': 'De weken aan de randen van de periode zijn onvolledig.',
  'ex.categoryTitle': 'Verdeling per categorie',
  'cmp.insufficientHistory': 'Onvoldoende historische gegevens',
  'cmp.insufficientDetail': 'De vorige periode heeft slechts {0} dag(en) historiek op {1} (eerste verkoop op {2}): procentuele wijzigingen worden niet getoond.',
  'ex.ship.note': 'Verzending (netto na terugbetalingen, excl. btw): {0} · Totaal verkoop + verzending excl. btw: {1}. De productindicatoren hierboven omvatten geen verzending.',
  'ex.ship.partial': 'Verzending niet beschikbaar voor {0} bestelling(en).',
  'ex.uncategorised': 'Zonder categorie',
  'ex.others': 'Overige',
  'ex.total': 'Totaal',
  'ex.topProducts': 'Topproducten',
  'ex.topCustomers': 'Topklanten',
  'ex.col.product': 'Product',
  'ex.col.sales': 'Verkoop',
  'ex.col.revenue': 'Omzet',
  'ex.col.evolution': 'Evolutie',
  'ex.col.customer': 'Klant',
  'ex.col.orders': 'Bestellingen',
  'ex.customerLabel': 'Klant {0}',
  'ex.customerNote': 'Alleen geïdentificeerde klanten worden getoond ({0} van de bestellingen). Er wordt geen naam bewaard: klanten zijn gepseudonimiseerd.',
  'ex.insufficient': 'Onvoldoende gegevens',
  'ex.insufficientSub': 'Er zijn minstens 2 echte datapunten nodig om deze grafiek te tekenen.',
  'ex.noCategories': 'Geen gecategoriseerde verkoop in de periode.',
  'ex.noProducts': 'Geen productverkoop in de periode.',
  'ex.noCustomers': 'Geen geïdentificeerde klant in de periode: bestellingen zonder klantsleutel worden nooit aan een klant toegewezen.',
  'ex.noReport': 'Het rapport bevat nog geen Explorer-gegevens. Genereer het rapport opnieuw.',
  'ex.soonTitle': 'Binnenkort beschikbaar',
  'ex.soonSub': 'Deze weergave van Explorer is nog niet beschikbaar.',
  'period.fixed': 'Vast',
  'period.fixedNote': 'Deze pagina toont de laatste 30 dagen van het rapport. Kies een andere periode in Verkenner, Producten of Klanten.',
  'ex.trendTitle': 'Evolutie van de verkoop',
  'ex.kpi.aov': 'Gemiddeld winkelmandje',
  'ex.kpi.items': 'Verkochte artikelen',
  'ex.channelTitle': 'Verkoop per kanaal',
  'ex.channelUnknown': 'Kanaal onbekend',
  'ex.noChannels': 'Geen verkoop met een kanaal in de periode.',
  'ex.cmpTitle': 'Huidige vs vorige periode',
  'ex.cmpPrev': 'Vorige periode',
  'ex.cmpCur': 'Huidige periode',
  'ex.cmpNote': 'Blokken van 7 dagen vanaf het begin van elke periode, dag per dag in dezelfde volgorde vergeleken.',
  'ex.cmpPartial': 'Laatste blok: {0} dagen.',
  'ex.noPrevious': 'Er is verkoop in de vorige periode nodig om te vergelijken.',
  'ex.contribTitle': 'Bijdrage aan de omzet',
  'ex.contribNote': 'Totale omzetwijziging: {0} vs vorige periode.',
  'ex.noContrib': 'Er is een vorige periode met verkoop nodig om bijdragen te meten.',
  'ex.bestDay': 'Beste verkoopdag',
  'ex.weakDay': 'Zwakste dag',
  'ex.weakNote': 'Onder de dagen met minstens één verkoop.',
  'ex.daysNoSale': '{0} dagen zonder verkoop op {1}.',
  'ex.dayOrders1': '1 bestelling',
  'ex.dayOrdersN': '{0} bestellingen',
  'ex.noDays': 'Geen dag met verkoop in de periode.',
  'ex.kpi.productsSold': 'Verkochte producten',
  'ex.kpi.topProduct': 'Nr. 1 product in omzet',
  'ex.kpi.topCategory': 'Nr. 1 categorie',
  'ex.kpi.top3': 'Aandeel top 3 in de omzet',
  'ex.distinctProducts': '{0} verschillende producten verkocht',
  'ex.currentOnly': 'Alleen huidige periode',
  'ex.concentrationNote': 'Omzetconcentratie, geen prestatie',
  'ex.rankingTitle': 'Productranglijst',
  'ex.units': '{0} stuks',
  'ex.statusNew': 'Nieuw in de periode',
  'ex.statusNotBefore': 'Eerder niet verkocht',
  'ex.unmatched': 'Verwijderd catalogusproduct',
  'ex.growthTitle': 'Producten in stijging',
  'ex.declineTitle': 'Producten in daling',
  'ex.noGrowth': 'Geen product in stijging ten opzichte van een verkoop in de vorige periode.',
  'ex.noDecline': 'Geen product in daling ten opzichte van een verkoop in de vorige periode.',
  'ex.noSaleNow': 'Geen verkoop meer',
  'ex.contribChangeTitle': 'Bijdrage aan de omzetwijziging',
  'ex.catShareTitle': 'Omzetverdeling per categorie',
  'ex.concTitle': 'Omzetconcentratie',
  'ex.topN': 'Top {0}',
  'ex.concSentence': 'De eerste 3 producten vertegenwoordigen {0} van de omzet.',
  'ex.concNeutral': 'Beschrijvende indicator, zonder oordeel: te lezen volgens uw assortiment.',
  'ex.unitsVsRevenue': 'Verkochte eenheden vs omzet',
  'ex.unitsShare': 'Aandeel eenheden',
  'ex.revenueShare': 'Aandeel omzet',
  'ex.unitsNote': 'Markeringen #n = rang van het product in de ranglijst hierboven. Alleen eenheden tegenover omzet, zonder marge.',
  'ex.marginTitle': 'Marge per product',
  'ex.marginPartial': 'Onvolledige gegevens',
  'ex.marginSub': 'Marge per product niet getoond: kosten bekend voor {0} van de omzet, waarvan {1} geverifieerd. Een rangschikking op marge vereist volledige kosten.',
  'ex.unit1': '1 stuk',
  'ex.kpi.activeCustomers': 'Actieve klanten',
  'ex.kpi.newCustomers': 'Nieuwe klanten',
  'ex.kpi.returningCustomers': 'Terugkerende klanten',
  'ex.kpi.identifiedRevenue': 'Omzet van geïdentificeerde klanten',
  'ex.covNote': 'Geïdentificeerde klanten · {0} van de bestellingen',
  'ex.covNotePrev': 'Geïdentificeerde klanten · {0} van de bestellingen ({1} in de vorige periode)',
  'ex.newDef': 'Eerste bestelling uit hun geschiedenis in de periode',
  'ex.returningDef': 'Al bestellingen vóór de periode, of 2 of meer bestellingen',
  'ex.seg.new': 'Nieuwe klanten',
  'ex.seg.returning': 'Terugkerende klanten',
  'ex.seg.unknown': 'Onbekende geschiedenis',
  'ex.seg.newShort': 'Nieuw',
  'ex.seg.returningShort': 'Terugkerend',
  'ex.seg.unknownShort': 'Onbekend',
  'ex.nCustomers': '{0} klanten',
  'ex.identifiedShort': 'geïdentificeerd',
  'ex.newVsReturningTitle': 'Nieuwe vs terugkerende klanten',
  'ex.segDefs': 'Nieuw: eerste bestelling uit zijn geschiedenis in de periode (bestelindex van de bron). Terugkerend: eerdere bestelling al geregistreerd, of 2 of meer bestellingen. Onbekend: bestelindex niet betrouwbaar.',
  'ex.custRevenueTitle': 'Verdeling van de klantenomzet',
  'ex.custRevenueNote': 'Aandeel bestellingen met geïdentificeerde klant: {0}. Dit is niet de verdeling van alle klanten van de winkel.',
  'ex.custTrendTitle': 'Evolutie van geïdentificeerde klanten',
  'ex.seriesNew': 'Nieuwe klanten',
  'ex.seriesActive': 'Actieve klanten',
  'ex.custTrendNote': 'Per week (weken van de periode, de randen kunnen onvolledig zijn).',
  'ex.activityTitle': 'Klantenactiviteit',
  'ex.rec.d30': 'Laatste aankoop 30 dagen geleden of minder',
  'ex.rec.d60': 'Laatste aankoop 31 tot 60 dagen geleden',
  'ex.rec.d90': 'Laatste aankoop 61 tot 90 dagen geleden',
  'ex.rec.d90plus': 'Laatste aankoop meer dan 90 dagen geleden',
  'ex.recNote': 'Beschrijvende schijven over {0} dagen beschikbare geschiedenis. Nordla heeft geen goedgekeurde definitie van een “slapende” klant: er wordt er geen toegepast.',
  'ex.lastOrder': 'Laatste aankoop: {0}',
  'ex.basketShort': 'mandje',
  'ex.frequencyTitle': 'Aankoopfrequentie',
  'ex.freq.one': '1 bestelling',
  'ex.freq.two': '2 bestellingen',
  'ex.freq.three': '3 of meer bestellingen',
  'ex.freqNote': 'Bestellingen van de periode per geïdentificeerde klant.',
  'ex.avgOrders': 'Bestellingen per klant: gemiddeld {0}.',
  'ex.valueTitle': 'Klantwaarde',
  'ex.sampleTitle': 'Onvoldoende steekproef',
  'ex.gated': 'Gemiddelden niet getoond: {0} geïdentificeerde klanten, minimum {1} (bestaande Nordla-regel voor gemiddelden per klant).',
  'ex.noClv': 'Er wordt geen klantlevenswaarde (CLV) berekend: de nodige methode en geschiedenis ontbreken.',
  'ex.val.avgRevenue': 'Gemiddelde omzet per geïdentificeerde klant',
  'ex.val.median': 'Mediane omzet per geïdentificeerde klant',
  'ex.val.basket': 'Gemiddeld mandje van geïdentificeerde klanten',
  'ex.cohortTitle': 'Retentiecohorten',
  'ex.cohortSub': 'Er wordt geen cohort getekend: de huidige gegevens laten geen betrouwbare retentieberekening toe.',
  'ex.cohortReason.SHORT_HISTORY': 'Geschiedenis van {0} dagen, minder dan de vereiste {1} dagen.',
  'ex.cohortReason.TOO_FEW_RETURNING_CUSTOMERS': 'Te weinig geïdentificeerde terugkerende klanten.',
  'ex.cohortReason.NO_APPROVED_COHORT_DEFINITION': 'Er is nog geen cohortdefinitie goedgekeurd.',
  'ex.channelName.Point of Sale': 'Verkooppunt',
  'ex.channelName.Online Store': 'Webshop',
  'ex.noChannelData': 'Geen verkoop per kanaal in de periode.',
  'ex.metricLabel': 'Indicator',
  'ex.kpi.topChannel': 'Nr. 1 kanaal in omzet',
  'ex.kpi.topChannelShare': 'Aandeel van het hoofdkanaal',
  'ex.kpi.topChannelOrders': 'Bestellingen van het hoofdkanaal',
  'ex.kpi.topChannelAov': 'Gemiddeld mandje van het hoofdkanaal',
  'ex.prevShare': 'Vorige periode: {0}',
  'ex.chShareTitle': 'Omzetverdeling per kanaal',
  'ex.chPerfTitle': 'Prestatie per kanaal',
  'ex.chTrendTitle': 'Evolutie van de kanalen',
  'ex.chTrendNote': 'Omzet per week en per kanaal (weken van de periode, de randen kunnen onvolledig zijn).',
  'ex.chInsightTitle': 'Lezing van de cijfers',
  'ex.insShare': '{0} vertegenwoordigt {1} van de omzet van de periode.',
  'ex.insAov': 'Het gemiddelde mandje van kanaal {0} ligt {1} hoger dan dat van kanaal {2}.',
  'ex.insNeutral': 'Cijfermatige vaststellingen, zonder oordeel.',
  'ex.chVarTitle': 'Wijziging t.o.v. vorige periode',
  'ex.noSalesPeriod': 'Geen verkoop in de periode',
  'ex.chContribTitle': 'Bijdrage van de kanalen aan de omzetwijziging',
  'ex.chProductsTitle': 'Producten per kanaal',
  'ex.chCustomersTitle': 'Klanten per kanaal',
  'ex.chCustLine': '{0} geïdentificeerde klanten · {1} van de bestellingen van het kanaal',
  'ex.chCustSplit': '{0} nieuw · {1} terugkerend',
  'ex.chCustNote': 'Alleen geïdentificeerde klanten (pseudoniem). Bestellingen zonder geïdentificeerde klant worden aan niemand toegewezen.',
  'ex.geo.kpiCoverage': 'Geografische dekking',
  'ex.geo.covNote': '{0} bestelling(en) van {1} met een bruikbare plaats',
  'ex.geo.covNeutral': 'Geen extrapolatie van niet-gelokaliseerde bestellingen',
  'ex.geo.kpiSaleLoc': 'Verkooplocatie ingevuld',
  'ex.geo.saleLocNote': '{0} bestelling(en) van {1}',
  'ex.geo.saleLocNeutral': 'Locatie van de winkel, niet van de klant',
  'ex.geo.kpiZones': 'Bruikbare zones',
  'ex.geo.zonesNote': 'Plaats, postcode, provincie of land',
  'ex.geo.kpiOrders': 'Bestellingen in de periode',
  'ex.geo.blockedTitle': 'Geografische analyse niet beschikbaar',
  'ex.geo.blockedSub': 'Slechts {0} van de bestellingen heeft een bruikbare plaats. Liever geen grafiek of kaart dan misleidende cijfers.',
  'ex.geo.foundTitle': 'Aanwezige geografische gegevens',
  'ex.geo.colField': 'Gegeven',
  'ex.geo.colMeaning': 'Wat het is',
  'ex.geo.colOrders': 'Bestellingen',
  'ex.geo.colUsable': 'Bruikbaar',
  'ex.geo.saleLocation': 'Verkooplocatie: {0}',
  'ex.geo.saleLocMeaning': 'Verkooplocatie (winkel), niet de locatie van de klant',
  'ex.geo.noSaleLocation': 'Aan de bestellingen is geen verkooplocatie gekoppeld.',
  'ex.geo.no': 'Nee',
  'ex.geo.absentTitle': 'Ontbrekende gegevens',
  'ex.geo.absentLine': 'Leveringsadres of factuuradres (plaats, postcode, provincie, land): niet gesynchroniseerd. Online bestellingen hebben dus geen bekende bestemming.',
  'ex.geo.unlockTitle': 'Om deze analyse te ontgrendelen',
  'ex.geo.unlock1': 'Synchroniseer per bestelling minstens de plaats of postcode van bestemming (zonder straat, zonder naam).',
  'ex.geo.unlock2': 'Of vul de plaats van elk verkooppunt in, als er meerdere verkooplocaties bestaan.',
  'ex.geo.unlock3': 'Een voldoende dekking van gelokaliseerde bestellingen, over minstens twee verschillende zones (drempel te bepalen met de productverantwoordelijke).',
  'ex.geo.privacy': 'Privacy: er wordt geen adres opgeslagen. De analyse blijft geaggregeerd (plaats, provincie of land) en toont nooit een individuele klant.',
  'ex.geo.kpiOrdersNote': 'Geselecteerde periode',
  'ex.per.kpiCur': 'Omzet huidige periode',
  'ex.per.kpiPrev': 'Omzet vorige periode',
  'ex.per.kpiAbs': 'Absolute verandering',
  'ex.per.kpiPct': 'Verandering in %',
  'ex.per.last30': 'Geselecteerde periode',
  'ex.per.prev30': 'Voorgaande periode',
  'ex.per.noPrev': 'Geen vorige periode beschikbaar',
  'ex.per.pctInvalid': 'Niet beschikbaar: geen verkoop in de vorige periode',
  'ex.per.trendTitle': 'Evolutie over de periode',
  'ex.per.bestTitle': 'Sterkste periode',
  'ex.per.weakTitle': 'Zwakste periode',
  'ex.per.bestWeek': 'Sterkste volledige week: {0} ({1})',
  'ex.per.weakWeek': 'Zwakste volledige week: {0} ({1})',
  'ex.per.weekOf': 'week van {0}',
  'ex.per.activityTitle': 'Verdeling van de activiteit',
  'ex.per.daysWith': '{0} dagen met verkoop',
  'ex.per.daysWithout': '{0} dagen zonder verkoop',
  'ex.per.daysAbove': '{0} dagen boven het daggemiddelde',
  'ex.per.daysBelow': '{0} dagen onder het daggemiddelde',
  'ex.per.activityNote': 'Cijfermatige vaststellingen over {0} dagen; het gemiddelde telt dagen zonder verkoop mee.',
  'ex.per.weeksTitle': 'Bijdrage van de weken aan de omzet',
  'ex.per.weeksNote': 'Aandeel van elke week in de omzet van de periode. Weken aan de randen zijn gedeeltelijk ({0} dagen).',
  'ex.per.weekLabel': 'Wk. {0}',
  'ex.per.regTitle': 'Regelmaat van de verkoop',
  'ex.per.mean': 'Gemiddelde per dag',
  'ex.per.median': 'Mediaan per dag',
  'ex.per.sd': 'Standaardafwijking',
  'ex.per.cv': 'Variatiecoëfficiënt',
  'ex.per.regNote': 'Berekend over de {0} dagen van de periode, dagen zonder verkoop inbegrepen. De standaardafwijking meet de spreiding van de dagomzet rond het gemiddelde; de variatiecoëfficiënt zet die af tegen het gemiddelde. Hoe hoger, hoe meer de verkoop van dag tot dag varieert.',
  'ex.per.weekdayTitle': 'Prestatie per weekdag',
  'ex.per.weekdayNote': 'Gemiddelde per voorkomen: elke weekdag wordt gedeeld door het aantal keren dat hij in de periode voorkomt.',
  'ex.per.weekdayLine': '{0} bestelling(en) · {1}×',
  'ex.per.todTitle': 'Prestatie per moment van de dag',
  'ex.per.tod.night': 'Nacht (0–6 u)',
  'ex.per.tod.morning': 'Ochtend (6–12 u)',
  'ex.per.tod.midday': 'Middag (12–14 u)',
  'ex.per.tod.afternoon': 'Namiddag (14–18 u)',
  'ex.per.tod.evening': 'Avond (18–24 u)',
  'ex.per.todNote': 'Lokale tijd ({0}) van {1} bestelling(en) op {2}. Netto-omzet, terugbetalingen gekoppeld aan de bestelling.',
  'ex.per.orders': '{0} bestelling(en)',
  'ex.per.whyTitle': 'Waar komt de verandering vandaan?',
  'ex.per.whyOrders': 'Het aantal bestellingen verandert met {0} ({1} tegenover {2}).',
  'ex.per.whyAov': 'Het gemiddelde bestelbedrag verandert met {0} ({1} tegenover {2}).',
  'ex.per.whyNote': 'Rekenkundige lezing: omzet = bestellingen × gemiddeld bestelbedrag. Er is geen oorzaak vastgesteld.',
  'ex.per.noData': 'Te weinig dagen voor deze analyse.',
  'ex.cp.periodCur': 'Huidige periode',
  'ex.cp.periodPrev': 'Vorige periode',
  'ex.cp.range': '{0} – {1} ({2} dagen)',
  'ex.cp.previousValue': 'Vroeger: {0}',
  'ex.cp.change': 'Verschil: {0}',
  'ex.cp.blocksTitle': 'Huidige vs vorige periode',
  'ex.cp.blocksNote': 'Blokken van 7 dagen op positie uitgelijnd: blok 1 van elke periode, dan blok 2, enz. Het laatste blok is gedeeltelijk ({0} dagen).',
  'ex.cp.blocksNoteFull': 'Blokken van 7 dagen op positie uitgelijnd: blok 1 van elke periode, dan blok 2, enz.',
  'ex.cp.blockTip': '{0}: van {1} tot {2} tegenover van {3} tot {4}',
  'ex.cp.blockLabel': 'W{0}',
  'ex.cp.blockLabelPartial': 'W{0} ({1} d)',
  'ex.cp.trendTitle': 'Vergelijkende evolutie',
  'ex.cp.trendNote': 'Uitgelijnd op relatieve dag (dag 1 tot dag {0}): de kalenderdata van beide periodes zijn niet dezelfde.',
  'ex.cp.dayN': 'D{0}',
  'ex.cp.wfTitle': 'Ontleding van de omzetverandering',
  'ex.cp.wfPrev': 'Vorige omzet',
  'ex.cp.wfPrevShort': 'Voor',
  'ex.cp.wfCur': 'Huidige omzet',
  'ex.cp.wfCurShort': 'Nu',
  'ex.cp.wfOther': 'Overige categorieën ({0})',
  'ex.cp.wfOtherShort': 'Overig',
  'ex.cp.wfNote': 'Ontleding per cataloguscategorie (inclusief «Zonder categorie»): elke verkoop hoort bij één categorie, dus de som van de verschillen komt exact uit op de huidige omzet.',
  'ex.cp.productsTitle': 'Producten die de verandering verklaren',
  'ex.cp.channelsTitle': 'Evolutie per kanaal',
  'ex.cp.categoriesTitle': 'Evolutie per categorie',
  'ex.cp.shareOfChange': '{0} van de verandering',
  'ex.cp.statusNew': 'Nieuw in de periode',
  'ex.cp.statusAbsent': 'Geen verkoop in de periode',
  'ex.cp.noCategory': 'Zonder categorie',
  'ex.cp.volumeTitle': 'Volume vs gemiddeld bestelbedrag',
  'ex.cp.ordersLine': 'Bestellingen: {0}',
  'ex.cp.aovLine': 'Gemiddeld bestelbedrag: {0}',
  'ex.cp.up': 'stijging',
  'ex.cp.down': 'daling',
  'ex.cp.flat': 'stabiliteit',
  'ex.cp.volumeSentence': 'De omzet evolueert in een context van {0} van het aantal bestellingen en {1} van het gemiddelde bestelbedrag.',
  'ex.cp.unavailable': 'Niet beschikbaar',
  'ex.cp.customersTitle': 'Geïdentificeerde klanten',
  'ex.cp.custActive': 'Actieve geïdentificeerde klanten',
  'ex.cp.custRevenue': 'Omzet van geïdentificeerde klanten',
  'ex.cp.custNew': 'Nieuwe klanten',
  'ex.cp.custReturning': 'Terugkerende klanten',
  'ex.cp.coverage': '{0} van de bestellingen geïdentificeerd tegenover {1} eerder',
  'ex.cp.coverageWarn': 'De identificatiedekking is niet dezelfde in beide periodes: deze verschillen meten niet noodzakelijk een evolutie van de klantenbasis.',
  'ex.cp.coverageOk': 'De identificatiedekking ligt dicht bij elkaar in beide periodes.',
  'ex.cp.watchUp': 'Sterkste stijging',
  'ex.cp.watchDown': 'Sterkste daling',
  'ex.cp.watchNote': 'Product, in absoluut verschil in euro.',
  'ex.cp.noMove': 'Geen productbeweging om te tonen.',
  'ex.cp.mostTitle': 'Wat het meest veranderde',
  'ex.cp.mostRevenue': 'Omzet: {0}',
  'ex.cp.mostOrders': 'Bestellingen: {0}',
  'ex.cp.mostAov': 'Gemiddeld bestelbedrag: {0}',
  'ex.cp.mostProduct': 'Grootste productbijdrage: {0} ({1})',
  'ex.cp.mostChannel': 'Kanaal met de grootste verandering: {0} ({1})',
  'ex.cp.qualityTitle': 'Kwaliteit van de vergelijking',
  'ex.cp.q.comparable': 'Vergelijkbaar',
  'ex.cp.q.caution': 'Voorzichtig interpreteren',
  'ex.cp.q.partial': 'Gedeeltelijke gegevens',
  'ex.cp.q.days': 'Aantal dagen',
  'ex.cp.q.daysDetail': '{0} dagen tegenover {1} dagen.',
  'ex.cp.q.last_block': 'Laatste blok',
  'ex.cp.q.lastBlockPartial': 'Het laatste blok telt slechts {0} dagen, vergeleken met de {1} overeenkomstige dagen.',
  'ex.cp.q.lastBlockFull': 'Alle blokken tellen 7 dagen.',
  'ex.cp.q.customer_coverage': 'Identificatie van klanten',
  'ex.cp.q.coverageUnknown': 'Dekking niet meetbaar in een van de periodes.',
  'ex.cp.q.categories': 'Indeling in categorieën',
  'ex.cp.q.categoriesDetail': '{0} van de huidige omzet heeft geen categorie.',
  'ex.cp.q.costs': 'Kosten en marge',
  'ex.cp.q.costsDetail': 'Marge niet vergeleken: kosten ingevuld voor {0} van de producten, gecontroleerd voor {1}.',
  'ex.cp.qualityNote': 'Expliciete regels, geen algemene score.',
  'ex.cp.noPrevious': 'Geen vorige periode om mee te vergelijken.',
  'ex.cp.exportSection': 'vergelijking',
  'ex.days': 'dagen',
  'topbar.shopifySync': 'Shopify-synchronisatie {0}',
  'topbar.syncFailed': 'Shopify-synchronisatie mislukt · laatste gegevens {0}',
  'topbar.syncStale': 'Shopify-synchronisatie verouderd · {0}',
  'topbar.syncUnknown': 'Shopify-synchronisatie onbekend',
  'ask.title': 'Vraag het Nordla',
  'ask.placeholder': 'Stel een vraag over uw cijfers…',
  'ask.send': 'Vragen',
  'ask.close': 'Sluiten',
  'ask.examples': 'Voorbeelden',
  'ask.loading': 'Zoeken in uw gegevens…',
  'ask.q.revenue': 'Wat is mijn omzet van de laatste 30 dagen?',
  'ask.q.orders': 'Hoeveel bestellingen de laatste 7 dagen?',
  'ask.q.aov': 'Wat is mijn gemiddelde bestelwaarde over 30 dagen?',
  'ask.q.topProduct': 'Wat is mijn beste product?',
  'ask.q.channel': 'Wat is mijn belangrijkste kanaal?',
  'ask.f.net_sales_ex_tax': 'Omzet excl. btw (producten)',
  'ask.f.net_sales_incl_tax': 'Omzet incl. btw (producten)',
  'ask.f.shipping_net_ex_tax': 'Verzending excl. btw (apart, niet inbegrepen hierboven)',
  'ask.f.order_count': 'Bestellingen',
  'ask.f.units_sold': 'Verkochte stuks',
  'ask.f.aov_ex_tax': 'Gemiddelde bestelwaarde excl. btw',
  'ask.f.refunds_products': 'Terugbetalingen producten',
  'ask.f.refunds_total': 'Terugbetalingen totaal (producten + verzending)',
  'ask.f.active_customers': 'Actieve klanten (geïdentificeerd)',
  'ask.f.identified_share': 'Aandeel geïdentificeerde bestellingen',
  'ask.f.top_product': 'Beste product',
  'ask.f.top_channel': 'Belangrijkste kanaal',
  'ask.period': 'Periode: van {0} tot {1}',
  'ask.source': 'Bron: Nordla-rapport van {0} (cijfers berekend door Nordla, niet door AI)',
  'ask.explainBy': 'Uitleg ({0})',
  'ask.ai.notConfigured': 'AI-uitleg: er is geen AI-model ingesteld. De cijfers hierboven komen rechtstreeks uit uw Nordla-gegevens.',
  'ask.ai.misconfigured': 'AI-uitleg: de gevraagde aanbieder is niet correct ingesteld. De cijfers hierboven blijven juist.',
  'ask.ai.unavailable': 'AI-uitleg: de dienst is niet beschikbaar. De cijfers hierboven blijven juist.',
  'ask.ai.timeout': 'AI-uitleg: de dienst antwoordde niet op tijd. De cijfers hierboven blijven juist.',
  'ask.err.EMPTY_QUESTION': 'Schrijf een vraag.',
  'ask.err.QUESTION_TOO_LONG': 'De vraag is te lang (maximaal 500 tekens).',
  'ask.err.UNSUPPORTED_QUESTION': 'Ik kan deze vraag nog niet beantwoorden met betrouwbare gegevens. Ik kan antwoorden over: omzet, bestellingen, verkochte stuks, gemiddelde bestelwaarde, terugbetalingen, klanten, beste product en belangrijkste kanaal.',
  'ask.err.UNSUPPORTED_PERIOD': 'Deze periode is niet beschikbaar. Beschikbare periodes: gisteren, 7 dagen, 30 dagen.',
  'ask.err.ONLY_LAST_30_DAYS': 'Deze informatie is alleen beschikbaar voor de laatste 30 dagen.',
  'ask.err.NO_REPORT_AVAILABLE': 'Er is momenteel geen Nordla-rapport beschikbaar: de cijfers kunnen niet worden gelezen.',
  'ask.err.NO_DATA_FOR_QUESTION': 'Geen gegevens voor deze vraag in de periode.',
  'ask.err.PERIOD_NOT_IN_REPORT': 'Deze periode bestaat niet in het huidige rapport.',
  'ask.err.ASSISTANT_NOT_AVAILABLE': 'De assistent is niet beschikbaar op deze server.',
  'ask.err.TIMEOUT': 'Het antwoord duurde te lang. Probeer opnieuw.',
  'ask.err.GENERIC': 'De aanvraag is mislukt. Probeer het zo meteen opnieuw.',
  'period.p.last_7_days': 'Laatste 7 dagen',
  'period.p.last_30_days': 'Laatste 30 dagen',
  'period.p.last_90_days': 'Laatste 90 dagen',
  'period.p.this_week': 'Deze week',
  'period.p.this_month': 'Deze maand',
  'period.p.previous_month': 'Vorige maand',
  'period.p.this_year': 'Dit jaar',
  'period.p.custom': 'Aangepaste periode',
  'period.customRange': '{0} – {1}',
  'period.from': 'Begindatum',
  'period.to': 'Einddatum',
  'period.apply': 'Toepassen',
  'period.reset': 'Periode en filters herstellen',
  'period.range': 'Van {0} tot {1} ({2} dagen)',
  'period.todayIncluded': 'vandaag inbegrepen',
  'period.vsPrev': 'vergeleken met de periode van {0} tot {1}',
  'period.noPrevious': 'Geen voorgaande periode om mee te vergelijken',
  'period.empty': 'Geen bestellingen in deze periode.',
  'period.err.INVALID_DATE': 'Ongeldige datums: kies een begin- en einddatum.',
  'period.err.PERIOD_ORDER': 'De begindatum moet voor de einddatum liggen.',
  'period.err.PERIOD_IN_FUTURE': 'De einddatum mag niet in de toekomst liggen.',
  'period.err.PERIOD_TOO_LONG': 'De periode is te lang (maximaal 3 jaar).',
  'period.err.INVALID_PERIOD': 'Deze periode bestaat niet.',
  'period.err.DATASET_UNAVAILABLE': 'De gedetailleerde gegevens zijn nog niet klaar voor deze periode. Probeer het over enkele minuten opnieuw.',
  'period.err.GENERIC': 'De periode kon niet worden geladen. Probeer opnieuw.',
  'ex.money.note': 'Kortingen: {0} · Terugbetalingen producten: {1} · Btw producten: {2} (dezelfde berekeningen als het rapport, over de geselecteerde periode).',
  'ask.voice.start': 'Praat met Nordla',
  'ask.voice.short': 'Spreek',
  'ask.voice.stop': 'Stoppen',
  'ask.voice.listening': 'Ik luister…',
  'ask.voice.transcribing': 'Transcriberen…',
  'ask.voice.done': 'Dicteren klaar: controleer de tekst, verbeter ze indien nodig en klik op Vragen.',
  'ask.voice.denied': 'Toegang tot de microfoon is geweigerd. Sta de microfoon toe voor deze site in uw browser, of schrijf uw vraag.',
  'ask.voice.mic': 'Er kon geen microfoon worden gebruikt. Controleer of er een microfoon is aangesloten, of schrijf uw vraag.',
  'ask.voice.noSpeech': 'Ik heb niets gehoord. Probeer opnieuw of schrijf uw vraag.',
  'ask.voice.network': 'De spraakherkenning van uw browser is momenteel niet beschikbaar. Schrijf uw vraag.',
  'ask.voice.generic': 'Dicteren is niet gelukt. Schrijf uw vraag of probeer opnieuw.',
  'ask.voice.unsupported': 'Spraakdictaat is niet beschikbaar in deze browser (probeer Chrome of Edge). U kunt uw vraag schrijven.',
  'ask.voice.privacy': 'Nordla neemt uw audio niet op en slaat die niet op. De spraakherkenning wordt geleverd door uw browser en kan, afhankelijk van de browser, gebruikmaken van de diensten van de aanbieder van die browser. Alleen de getranscribeerde tekst wordt naar Nordla verzonden.',
  'topbar.reportGenerated': 'Rapport gegenereerd {0}',
  'kpi.costCoverageDetail': '{0} van de omzet gedekt · {1} van de kosten gecontroleerd',
  'watch.aovCompared': 'Gemiddeld bestelbedrag: {0} tegenover {1} in de voorgaande 30 dagen ({2}).',
  'wc.gainsLine': 'De producten met de sterkste stijging ({0}) voegen {1} toe.',
  'wc.lossesLine': 'De producten met de sterkste daling ({0}) halen {1} weg.',
  'wc.netLine': 'Netto verandering van de omzet: {0}.',
  'wc.marginCaveat': 'Kosten gedeeltelijk bekend: {0} van de omzet gedekt · {1} van de kosten gecontroleerd.',
  'ex.geo.pendingSub': 'Er bestaan bruikbare zones, maar de minimale dekkingsdrempel is nog niet bepaald: de analyse per zone is niet geactiveerd.',

  // ---- Clients (main customer workspace) ----
  'cl.title': 'Klanten',
  'cl.subtitle': 'Begrijp je klantenbestand en zie snel welke klanten je aandacht nodig hebben.',
  'cl.toExplorer': 'Klanten analyseren in Verkenner',
  'cl.coverageTitle': 'Klantdekking',
  'cl.coverageLine': '{0} van de bestellingen heeft een geïdentificeerde klant',
  'cl.coverageCounts': '({0} van {1} bestellingen, geselecteerde periode)',
  'cl.coveragePrev': '{0} in de vorige periode',
  'cl.scopePeriod': 'Indicatoren en statussen: geselecteerde periode',
  'cl.scopeHistory': 'Beschikbare historiek: sinds {0} ({1} dagen), {2} van de bestellingen geïdentificeerd',
  'cl.coverageShift': 'Het aandeel geïdentificeerde bestellingen ging van {0} naar {1}: een verandering in het aantal klanten weerspiegelt ook deze dekking, niet alleen de activiteit.',
  'cl.tag30': 'Geselecteerde periode',
  'cl.tagHistory': 'Beschikbare historiek',
  'cl.tagMixed': 'Periode + historiek',
  'cl.topTitle': 'Belangrijkste klanten per omzet',
  'cl.distTitle': 'Verdeling van de klanten',
  'cl.distNote': 'Actieve klanten in de periode, volgens de definities van Verkenner. Alleen bestellingen met een geïdentificeerde klant tellen mee ({0}).',
  'cl.watchHeading': 'Op te volgen',
  'cl.watch.lapsedTitle': 'Geen aankoop in de periode',
  'cl.watch.lapsedText': '{0} klant(en) kochten in de voorgaande periode, maar niet in de geselecteerde periode. Dit is een vaststelling over twee periodes, geen voorspelling.',
  'cl.watch.lapsedNone': 'Geen enkele geïdentificeerde klant kocht in de vorige periode zonder opnieuw te kopen in de huidige.',
  'cl.watch.bothTitle': 'Actief in beide periodes',
  'cl.watch.bothText': '{0} klant(en) kochten in beide periodes: hun evolutie is vergelijkbaar.',
  'cl.watch.bothNone': 'Geen enkele geïdentificeerde klant kocht zowel in de huidige als in de vorige periode: geen individuele evolutie is vergelijkbaar.',
  'cl.watch.rhythmTitle': 'Individueel aankoopritme',
  'cl.watch.rhythmInsufficient': 'De recentheid van een klant kan niet met het eigen ritme worden vergeleken: {0} interval(len) tussen bestellingen waargenomen, minimum {1}.',
  'cl.watch.rhythmNoRule': '{0} intervallen waargenomen, maar Nordla heeft geen goedgekeurde regel om een termijn ongewoon te noemen: er wordt geen klant gemarkeerd.',
  'cl.andMore': '+ {0} andere',
  'cl.listTitle': 'Klanten',
  'cl.searchPlaceholder': 'Klant zoeken (bv. #A4B7)',
  'cl.searchLabel': 'Een klant zoeken op kenmerk',
  'cl.filtersLabel': 'Klanten filteren',
  'cl.recencyLabel': 'Filteren op recentheid',
  'cl.sortLabel': 'Klanten sorteren',
  'cl.filter.all': 'Alle',
  'cl.filter.active': 'Actief',
  'cl.filter.new': 'Nieuw',
  'cl.filter.returning': 'Terugkerend',
  'cl.filter.unknown': 'Historiek onbekend',
  'cl.filter.inactive': 'Geen aankoop in de periode',
  'cl.recency.all': 'Elke recentheid',
  'cl.recency.d0_30': 'Laatste aankoop ≤ 30 dagen',
  'cl.recency.d31_60': 'Laatste aankoop 31–60 dagen',
  'cl.recency.d61_90': 'Laatste aankoop 61–90 dagen',
  'cl.recency.d90_plus': 'Laatste aankoop > 90 dagen',
  'cl.sort.recent': 'Sorteren: laatste aankoop',
  'cl.sort.revenue': 'Sorteren: omzet periode',
  'cl.sort.orders': 'Sorteren: bestellingen periode',
  'cl.sort.known': 'Sorteren: gekende bestellingen',
  'cl.col.customer': 'Klant',
  'cl.col.status': 'Status / activiteit',
  'cl.col.revenue': 'Omzet periode',
  'cl.col.orders': 'Bestellingen periode',
  'cl.col.aov': 'Gem. mandje periode',
  'cl.col.lastOrder': 'Laatste aankoop',
  'cl.col.recency': 'Recentheid',
  'cl.col.evolution': 'Evolutie',
  'cl.status.new': 'Nieuw',
  'cl.status.returning': 'Terugkerend',
  'cl.status.unknown': 'Historiek onbekend',
  'cl.status.inactive': 'Geen aankoop in de periode',
  'cl.evo.compared': 'Vergeleken met de voorgaande periode',
  'cl.evo.no_current_purchase': 'Geen aankoop in de huidige periode',
  'cl.evo.no_previous_purchase': 'Geen aankoop in de voorgaande periode: geen percentage berekenbaar',
  'cl.evo.no_previous_window': 'Geen vorige periode beschikbaar',
  'cl.evo.none': 'Geen aankoop in beide periodes',
  'cl.evo.newShort': 'Geen eerdere aankoop',
  'cl.today': 'vandaag',
  'cl.daysAgo': '{0} d geleden',
  'cl.count': '{0} klant(en) getoond van {1} geïdentificeerd',
  'cl.noIdentified': 'Geen geïdentificeerde klant in de beschikbare historiek: bestellingen zonder klant worden nooit toegewezen.',
  'cl.noMatchTitle': 'Geen overeenkomende klant',
  'cl.noMatch': 'Pas de zoekopdracht of de filters aan.',
  'cl.listNote': 'Omzet excl. btw, na terugbetalingen. Status, omzet, bestellingen en gemiddeld mandje: geselecteerde periode (definities van Verkenner). Laatste aankoop en recentheid: beschikbare historiek. Klanten zijn gepseudonimiseerd, er wordt geen naam opgeslagen.',
  'cl.openDetail': 'Details van {0} openen',
  'cl.close': 'Details sluiten',
  'cl.loading': 'Klant laden…',
  'cl.detailError': 'De details van deze klant zijn niet beschikbaar in het huidige rapport.',
  'cl.d.activeLine': 'Kocht in de geselecteerde periode',
  'cl.d.inactiveLine': 'Geen aankoop in de geselecteerde periode',
  'cl.d.periodTitle': 'Huidige periode',
  'cl.d.previous': 'Voorgaande periode: {0} · {1} bestelling(en)',
  'cl.d.historyTitle': 'Beschikbare historiek',
  'cl.d.firstKnown': 'Eerste gekende aankoop',
  'cl.d.lastKnown': 'Laatste gekende aankoop',
  'cl.d.knownOrders': 'Gekende bestellingen',
  'cl.d.knownRevenue': 'Gekende omzet (excl. btw)',
  'cl.d.earlierOutside': 'Volgens de bron had deze klant al {0} bestelling(en) geplaatst vóór het begin van de beschikbare historiek: die zijn hier niet opgenomen.',
  'cl.d.earlierNone': 'Volgens de bron ligt de eerste bestelling binnen de beschikbare historiek.',
  'cl.d.earlierUnknown': 'De bron laat niet toe te weten of deze klant vóór de beschikbare historiek bestelde.',
  'cl.d.trendTitle': 'Evolutie van de aankopen',
  'cl.d.trendOne': 'Eén gekende bestelling: geen curve, zie de historiek hieronder.',
  'cl.d.trendFew': '{0} gekende bestellingen: te weinig punten voor een curve, zie de historiek hieronder.',
  'cl.d.ordersTitle': 'Aankoophistoriek',
  'cl.d.inPeriod': 'Geselecteerde periode',
  'cl.d.refunded': 'Terugbetaling',
  'cl.d.ordersNote': 'Bedrag per bestelling: excl. btw, na geregistreerde terugbetalingen.',
  'cl.d.productsTitle': 'Gekochte producten',
  'cl.d.units': '× {0}',
  'cl.d.refundedUnits': 'waarvan {0} terugbetaald',

  // ---- Produits (main product workspace) ----
  'pr.title': 'Producten',
  'pr.subtitle': 'Volg je producten, zie de belangrijke bewegingen en focus op de producten die je aandacht verdienen.',
  'pr.toExplorer': 'Producten analyseren in Verkenner',
  'pr.scopeCurrent': 'Geselecteerde periode (sinds {0})',
  'pr.scopePrevious': 'vergeleken met de voorgaande periode (sinds {0})',
  'pr.scopeNoPrevious': 'geen vorige periode beschikbaar',
  'pr.scopeHistory': 'laatste verkoop: beschikbare historiek',
  'pr.catalogueLine': 'Omzet zonder categorie: {0} · omzet van artikelen buiten de catalogus: {1}',
  'pr.marginOmitted': 'Marge per product niet getoond: kosten gedeeltelijk ({0} van de omzet gedekt, {1} geverifieerd)',
  'pr.kpi.sold': 'Verkochte producten',
  'pr.kpi.soldPrev': 'Verschillende verkochte producten · {0} in de vorige periode',
  'pr.kpi.top': 'Product nr. 1 in omzet',
  'pr.shareOfRevenue': '{0} van de omzet',
  'pr.kpi.top3': 'Aandeel top 3 in de omzet',
  'pr.kpi.top3Note': 'Concentratie-indicator, geen prestatie',
  'pr.kpi.top3Prev': '{0} in de vorige periode ({1})',
  'pr.kpi.declining': 'Dalende producten',
  'pr.kpi.decliningNote': 'Waarvan {0} zonder verkoop in de periode',
  'pr.kpi.decliningScope': 'Ten opzichte van een verkoop in de voorgaande periode',
  'pr.status.compared': 'Vergelijkbaar',
  'pr.status.new': 'Nieuw in de periode',
  'pr.status.notBefore': 'Geen eerdere verkoop',
  'pr.status.absent': 'Geen verkoop meer in de periode',
  'pr.status.noPrevious': 'Geen vorige periode',
  'pr.status.partial': 'Gedeeltelijke gegevens',
  'pr.status.negative': 'Terugbetalingen > verkopen',
  'pr.partialTitle': 'Verkocht artikel dat niet meer overeenkomt met een product uit de catalogus: geen afbeelding, geen categorie, geen stabiele identiteit.',
  'pr.noSaleNowShort': 'Geen verkoop meer',
  'pr.evo.compared': 'Vergeleken met de voorgaande periode',
  'pr.evo.new': 'Nieuw in de periode: geen percentage',
  'pr.evo.not_sold_before': 'Geen verkoop in de voorgaande periode: geen percentage',
  'pr.evo.absent': 'Geen verkoop meer in de periode',
  'pr.evo.no_previous': 'Geen vorige periode beschikbaar',
  'pr.noImage': 'Geen afbeelding in de catalogus',
  'pr.noCatalogue': 'Buiten de catalogus',
  'pr.growthTitle': 'Stijgende producten',
  'pr.declineTitle': 'Dalende producten',
  'pr.tagCompare': 'Periode vs voorgaande',
  'pr.tag30': 'Geselecteerde periode',
  'pr.tagPrevious': 'Voorgaande periode',
  'pr.tagHistory': 'Beschikbare historiek',
  'pr.prevToCur': '{0} → {1}',
  'pr.newLine': 'Aangemaakt en verkocht in de periode: geen vergelijking',
  'pr.moversMore': '{0} getoond van {1}: zie de volledige lijst hieronder (filters Stijgend / Dalend).',
  'pr.moversNote': 'Alleen producten die in de vorige periode verkocht werden (echte vergelijkingsbasis), volgens Verkenner.',
  'pr.listTitle': 'Producten',
  'pr.searchPlaceholder': 'Product zoeken (naam of kenmerk)',
  'pr.searchLabel': 'Een product zoeken op naam of Shopify-kenmerk',
  'pr.sortLabel': 'Producten sorteren',
  'pr.filtersLabel': 'Producten filteren',
  'pr.filter.all': 'Alle',
  'pr.filter.up': 'Stijgend',
  'pr.filter.down': 'Dalend',
  'pr.filter.new': 'Nieuw in de periode',
  'pr.filter.absent': 'Geen verkoop in de periode',
  'pr.filter.uncategorised': 'Zonder categorie',
  'pr.sort.revenue': 'Sorteren: omzet periode',
  'pr.sort.units': 'Sorteren: eenheden periode',
  'pr.sort.gain': 'Sorteren: grootste stijging (€)',
  'pr.sort.loss': 'Sorteren: grootste daling (€)',
  'pr.sort.recent': 'Sorteren: laatste verkoop',
  'pr.sort.name': 'Sorteren: naam (A → Z)',
  'pr.col.product': 'Product',
  'pr.col.revenue': 'Omzet periode',
  'pr.col.units': 'Eenheden periode',
  'pr.col.share': 'Aandeel omzet',
  'pr.col.evolution': 'Evolutie',
  'pr.col.lastSale': 'Laatste verkoop',
  'pr.col.status': 'Status',
  'pr.count': '{0} product(en) getoond van {1}',
  'pr.noMatchTitle': 'Geen overeenkomend product',
  'pr.noMatch': 'Pas de zoekopdracht of de filters aan.',
  'pr.listNote': 'Producten verkocht in de geselecteerde periode of in de voorgaande periode. Omzet excl. btw, na terugbetalingen. Evolutie: alleen tegenover een echte verkoop in de vorige periode. Laatste verkoop: beschikbare historiek.',
  'pr.openDetail': 'Details van {0} openen',
  'pr.watchHeading': 'Op te volgen',
  'pr.watch.compareTitle': 'Vergelijking',
  'pr.watch.absentTitle': 'Geen verkoop meer in de periode',
  'pr.watch.absentText': '{0} product(en) verkocht in de voorgaande periode, werden niet verkocht in de geselecteerde periode.',
  'pr.watch.absentNone': 'Alle producten die in de vorige periode verkocht werden, werden ook in de huidige periode verkocht.',
  'pr.watch.lowerTitle': 'Dalend, nog steeds verkocht',
  'pr.watch.lowerText': '{0} product(en) worden nog verkocht, met een lagere omzet dan in de vorige periode.',
  'pr.watch.lowerNone': 'Geen enkel nog verkocht product heeft een lagere omzet dan in de vorige periode.',
  'pr.watch.catalogueTitle': 'Kwaliteit van de productgegevens',
  'pr.watch.uncat': '{0} verkocht(e) product(en) zonder categorie in de catalogus ({1} van de omzet).',
  'pr.watch.uncatNone': 'Alle verkochte producten hebben een categorie.',
  'pr.watch.unmatched': '{0} verkocht(e) artikel(en) komen niet meer overeen met de catalogus ({1} van de omzet).',
  'pr.watch.unmatchedNone': 'Alle verkochte artikelen komen overeen met een product uit de catalogus.',
  'pr.watch.negative': '{0} product(en) hebben meer terugbetalingen dan verkopen in de periode (negatieve bijdrage).',
  'pr.andMore': '+ {0} andere',
  'pr.catTitle': 'Verdeling per categorie',
  'pr.catNote': 'Categorie = producttype uit de catalogus. “Zonder categorie” blijft zichtbaar: die omzet is niet verdeeld.',
  'pr.concNote': '{0} producten verkocht in de periode. Aandeel in de omzet van de eerste 1, 3 en 5 producten.',
  'pr.loading': 'Product laden…',
  'pr.detailError': 'De details van dit product zijn niet beschikbaar in het huidige rapport.',
  'pr.close': 'Details sluiten',
  'pr.d.currentTitle': 'Huidige periode',
  'pr.d.perUnit': 'Omzet per eenheid',
  'pr.d.compareTitle': 'Vorige periode',
  'pr.d.prevRevenue': 'Vorige omzet',
  'pr.d.prevUnits': 'Vorige eenheden',
  'pr.d.change': 'Verschil',
  'pr.d.changePct': 'Verschil (%)',
  'pr.d.contribution': 'Bijdrage aan de verandering van de totale omzet: {0} op {1}.',
  'pr.d.trendTitle': 'Evolutie van de verkoop',
  'pr.d.trendFew': 'Verkoop op slechts {0} dag(en): geen curve, zie de recente verkopen hieronder.',
  'pr.d.trendNone': 'Geen verkoop in de periode: geen curve.',
  'pr.d.lastSale': 'Laatste gekende verkoop: {0}',
  'pr.d.recentTitle': 'Recente verkopen',
  'pr.d.refunded': '{0} terugbetaald',
  'pr.d.noRecent': 'Geen verkoop in de beschikbare historiek.',
  'pr.d.recentNote': 'Eén regel per bestelregel: bedrag excl. btw, na geregistreerde terugbetalingen.',

  // ---- Account control (top-right profile menu) ----
  'account.menuLabel': 'Accountmenu',
  'account.title': 'Account',
  'account.statusLocal': 'Lokaal voorbeeld · geen actieve sessie',
  'account.noSession': 'Analytics Premium heeft nog geen aanmelding: er is geen sessie om te sluiten en geen pagina met accountinstellingen. Deze acties verschijnen hier zodra ze echt bestaan.',
  'account.settings': 'Instellingen',
  'account.logout': 'Afmelden',
};
