'use strict';
// Français - langue source/par defaut de Nordla AI.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.fr = {
  'brand.name': 'Nordla AI',

  'nav.brief': 'Résumé',
  'nav.changed': 'Ce qui a changé',
  'nav.explore': 'Explorer',
  'nav.customers': 'Clients',
  'nav.products': 'Produits',
  'nav.askNordla': 'Demander à Nordla',

  'sidebar.askSubtitle': 'Obtenez des informations sur votre activité',

  'topbar.title': 'Analytics Premium',
  'topbar.lastSynced': 'Rapport généré {0}',

  'time.justNow': 'à l’instant',
  'time.minAgo': 'il y a {0} min',
  'time.hAgo': 'il y a {0} h',
  'time.dAgo': 'il y a {0} j',

  'period.last30Days': '30 derniers jours',

  'greeting.morning': 'Bonjour',
  'greeting.afternoon': 'Bon après-midi',
  'greeting.evening': 'Bonsoir',
  'hero.subtitle': 'Voici ce qui a changé cette semaine.',

  'kpi.netRevenue': 'Chiffre d’affaires net',
  'kpi.orders': 'Commandes',
  'kpi.aov': 'Panier moyen',
  'kpi.grossMargin': 'Marge brute',
  'kpi.thisPeriod': 'Cette période',
  'kpi.partialCostCoverage': 'Coûts partiellement connus',
  'kpi.infoTitle': 'Période en cours, données réelles',
  'kpi.noData': 'Aucune donnée de vente disponible pour cette période.',
  'kpi.insufficientHistory': 'Historique quotidien insuffisant pour un graphique.',

  'insight.badge': 'Meilleurs produits',
  'insight.title': 'Vos meilleurs produits par chiffre d’affaires',
  'insight.subtitle': '30 derniers jours, données de vente réelles.',
  'insight.body': 'Classement réel de la période en cours. La comparaison avec les 30 jours précédents est disponible dans « Ce qui a changé » et dans Explorer.',
  'insight.seeWhy': 'Voir pourquoi',
  'insight.seeWhyTitle': 'Cette action n’est pas encore disponible.',
  'insight.addToCommandCenter': 'Ajouter au Centre de commande',
  'insight.commandCenterTitle': 'Le Centre de commande n’est pas encore disponible',
  'insight.rankTitle': 'Chiffre d’affaires des meilleurs produits',
  'insight.noProducts': 'Aucune vente de produit sur cette période.',
  'insight.units': '{0} unités',
  'insight.shareNote': 'La part indiquée correspond au chiffre d’affaires combiné de ces {0} produits ({1}), et non au chiffre d’affaires total du magasin.',

  'watch.heading': 'Autres points à surveiller',
  'watch.aovTitle': 'Évolution du panier moyen',
  'watch.aovText': 'La comparaison du panier moyen avec la période précédente n’est pas disponible.',
  'watch.dormantTitle': 'Clients inactifs',
  'watch.dormantText': 'Cet indicateur n’est pas encore calculé - il nécessite une définition de l’inactivité et un historique client plus riche que celui disponible actuellement.',

  'health.title': 'État des données',
  'health.upToDate': 'Données à jour',
  'health.lastGenerated': 'Dernière génération',
  'health.viewSources': 'Voir les sources de données',

  'app.noReport': 'Aucun instantané de rapport trouvé pour le moment. Exécutez `npm run metrics:report` pour en générer un.',

  'common.dash': '—',
  'common.and': 'et',

  'wc.title': 'Ce qui a changé',
  'wc.subtitle': 'Voici les principaux changements de votre activité cette semaine, avec des explications simples et les prochaines actions possibles.',
  'wc.badgeUp': 'Bonne performance',
  'wc.badgeDown': 'À surveiller en priorité',
  'wc.badgeFlat': 'Stable',
  'wc.headlineUp': 'Le chiffre d’affaires net a augmenté de {0}.',
  'wc.headlineDown': 'Le chiffre d’affaires net a baissé de {0}.',
  'wc.headlineFlat': 'Le chiffre d’affaires net est resté stable ({0}).',
  'wc.noContributors': 'Aucun produit ne ressort clairement de cette variation.',
  'wc.bodyText': 'Comparé à la période précédente ({0} → {1}), le chiffre d’affaires net est passé de {2} à {3}.',
  'wc.noComparison': 'La comparaison avec la période précédente n’est pas encore disponible - il n’y a pas encore assez d’historique.',
  'wc.dataReliable': 'Le chiffre d’affaires de cette comparaison provient de commandes réelles et vérifiées.',
  'wc.contributorsTitle': 'Principaux contributeurs',
  'wc.vsPreviousPeriod': 'vs période précédente',
  'wc.watchlistLabel': 'À suivre',
  'wc.partialDataLabel': 'Données partielles',
  'wc.dismiss': 'Ignorer',
  'wc.dismissTitle': 'Cette action n’est pas encore disponible.',

  'wc.watchHeading': 'Autres éléments à surveiller',
  'wc.watchAovUp': 'Le panier moyen a augmenté de {0} %.',
  'wc.watchAovDown': 'Le panier moyen a diminué de {0} %.',
  'wc.watchAovDetail': 'Il est passé de {0} à {1}.',
  'wc.watchMoversUp': '{0} produit(s) ont porté la hausse.',
  'wc.watchMoversDown': '{0} produit(s) ont porté la baisse.',
  'wc.dqLabel': 'Coût d’achat connu (part du chiffre d’affaires)',
  'wc.watchCostCoverage': 'Coûts connus pour {0} % du chiffre d’affaires.',
  'wc.watchCostCoverageDetail': 'Le reste n’est pas encore classifié - la marge réelle peut différer.',

  'wc.otherChangesHeading': 'Autres changements ({0})',
  'wc.rowOrdersTitle': 'Commandes',
  'wc.rowOrdersDetail': 'Vous avez reçu {0} commandes, contre {1} précédemment.',
  'wc.rowGrossMarginTitle': 'Marge brute',
  'wc.rowGrossMarginDetail': 'Votre marge brute est de {0} %, contre {1} % précédemment.',
  'wc.rowActiveProductsTitle': 'Produits actifs vendus',
  'wc.rowActiveProductsDetail': '{0} produits vendus sur la période, contre {1} précédemment.',

  // ---------- Explorer ----------
  'ex.title': 'Explorer',
  'ex.subtitle': 'Analysez en profondeur vos données pour comprendre ce qui performe, où agir et quelles opportunités saisir.',
  'ex.export': 'Exporter',
  'ex.tab.overview': 'Vue d’ensemble',
  'ex.tab.sales': 'Ventes',
  'ex.tab.products': 'Produits',
  'ex.tab.customers': 'Clients',
  'ex.tab.channels': 'Canaux',
  'ex.tab.zones': 'Zones',
  'ex.tab.period': 'Période',
  'ex.tab.comparison': 'Comparaison',
  'ex.kpi.revenue': 'Chiffre d’affaires',
  'ex.kpi.orders': 'Commandes',
  'ex.kpi.customers': 'Clients actifs',
  'ex.kpi.units': 'Produits vendus',
  'ex.vsPrevious': 'vs période précédente',
  'ex.noComparison': 'Comparaison indisponible',
  'ex.identifiedNote': 'Clients identifiés · {0} des commandes',
  'ex.salesTitle': 'Ventes sur la période',
  'ex.granularity': 'Granularité',
  'ex.byDay': 'Par jour',
  'ex.byWeek': 'Par semaine',
  'ex.partialWeeks': 'Les semaines aux extrémités de la période sont partielles.',
  'ex.categoryTitle': 'Répartition par catégorie',
  'cmp.insufficientHistory': 'Données historiques insuffisantes',
  'cmp.insufficientDetail': 'La période précédente ne compte que {0} jour(s) d’historique sur {1} (premières ventes le {2}) : les variations en % ne sont pas affichées.',
  'ex.ship.note': 'Livraison (nette des remboursements, HTVA) : {0} · Total ventes + livraison HTVA : {1}. Les indicateurs produits ci-dessus n’incluent pas la livraison.',
  'ex.ship.partial': 'Livraison non disponible pour {0} commande(s).',
  'ex.uncategorised': 'Sans catégorie',
  'ex.others': 'Autres',
  'ex.total': 'Total',
  'ex.topProducts': 'Top produits',
  'ex.topCustomers': 'Top clients',
  'ex.col.product': 'Produit',
  'ex.col.sales': 'Ventes',
  'ex.col.revenue': 'CA',
  'ex.col.evolution': 'Évolution',
  'ex.col.customer': 'Client',
  'ex.col.orders': 'Commandes',
  'ex.customerLabel': 'Client {0}',
  'ex.customerNote': 'Seuls les clients identifiés sont listés ({0} des commandes). Aucun nom n’est stocké : les clients sont pseudonymisés.',
  'ex.insufficient': 'Données insuffisantes',
  'ex.insufficientSub': 'Il faut au moins 2 points de données réelles pour tracer ce graphique.',
  'ex.noCategories': 'Aucune vente catégorisée sur la période.',
  'ex.noProducts': 'Aucune vente de produit sur la période.',
  'ex.noCustomers': 'Aucun client identifié sur la période : les commandes sans clé client ne sont jamais attribuées à un client.',
  'ex.noReport': 'Le rapport ne contient pas encore les données Explorer. Régénérez le rapport.',
  'ex.soonTitle': 'Bientôt disponible',
  'ex.soonSub': 'Cette vue d’Explorer n’est pas encore disponible.',
  'period.fixed': 'Fixe',
  'period.fixedNote': 'Cette page affiche les 30 derniers jours du rapport. Choisissez une autre période dans Explorer, Produits ou Clients.',
  'ex.trendTitle': 'Évolution des ventes',
  'ex.kpi.aov': 'Panier moyen',
  'ex.kpi.items': 'Articles vendus',
  'ex.channelTitle': 'Ventes par canal',
  'ex.channelUnknown': 'Canal non renseigné',
  'ex.noChannels': 'Aucune vente avec un canal sur la période.',
  'ex.cmpTitle': 'Période actuelle vs précédente',
  'ex.cmpPrev': 'Période précédente',
  'ex.cmpCur': 'Période actuelle',
  'ex.cmpNote': 'Blocs de 7 jours à partir du début de chaque période, comparés jour par jour dans le même ordre.',
  'ex.cmpPartial': 'Dernier bloc : {0} jours.',
  'ex.noPrevious': 'Il faut des ventes sur la période précédente pour la comparer.',
  'ex.contribTitle': 'Contribution au chiffre d’affaires',
  'ex.contribNote': 'Variation totale du chiffre d’affaires : {0} vs période précédente.',
  'ex.noContrib': 'Il faut une période précédente avec des ventes pour mesurer les contributions.',
  'ex.bestDay': 'Meilleur jour de vente',
  'ex.weakDay': 'Jour le plus faible',
  'ex.weakNote': 'Parmi les jours avec au moins une vente.',
  'ex.daysNoSale': '{0} jours sans vente sur {1}.',
  'ex.dayOrders1': '1 commande',
  'ex.dayOrdersN': '{0} commandes',
  'ex.noDays': 'Aucun jour avec vente sur la période.',
  'ex.kpi.productsSold': 'Produits vendus',
  'ex.kpi.topProduct': 'Produit n°1 en CA',
  'ex.kpi.topCategory': 'Catégorie n°1',
  'ex.kpi.top3': 'Part du Top 3 dans le CA',
  'ex.distinctProducts': '{0} produits distincts vendus',
  'ex.currentOnly': 'Période actuelle uniquement',
  'ex.concentrationNote': 'Concentration du CA, pas une performance',
  'ex.rankingTitle': 'Classement des produits',
  'ex.units': '{0} unités',
  'ex.statusNew': 'Nouveau sur la période',
  'ex.statusNotBefore': 'Pas de vente avant',
  'ex.unmatched': 'Produit du catalogue supprimé',
  'ex.growthTitle': 'Produits en hausse',
  'ex.declineTitle': 'Produits en baisse',
  'ex.noGrowth': 'Aucun produit en hausse par rapport à une vente de la période précédente.',
  'ex.noDecline': 'Aucun produit en baisse par rapport à une vente de la période précédente.',
  'ex.noSaleNow': 'Plus de vente',
  'ex.contribChangeTitle': 'Contribution à la variation du chiffre d’affaires',
  'ex.catShareTitle': 'Répartition du CA par catégorie',
  'ex.concTitle': 'Concentration du chiffre d’affaires',
  'ex.topN': 'Top {0}',
  'ex.concSentence': 'Les 3 premiers produits représentent {0} du chiffre d’affaires.',
  'ex.concNeutral': 'Indicateur descriptif, sans jugement : à lire selon votre catalogue.',
  'ex.unitsVsRevenue': 'Unités vendues vs chiffre d’affaires',
  'ex.unitsShare': 'Part des unités',
  'ex.revenueShare': 'Part du CA',
  'ex.unitsNote': 'Repères #n = rang du produit dans le classement ci-dessus. Unités contre chiffre d’affaires uniquement, sans marge.',
  'ex.marginTitle': 'Marge par produit',
  'ex.marginPartial': 'Données partielles',
  'ex.marginSub': 'Marge par produit non affichée : coûts connus pour {0} du chiffre d’affaires, dont {1} vérifiés. Un classement par marge exigerait des coûts complets.',
  'ex.unit1': '1 unité',
  'ex.kpi.activeCustomers': 'Clients actifs',
  'ex.kpi.newCustomers': 'Nouveaux clients',
  'ex.kpi.returningCustomers': 'Clients récurrents',
  'ex.kpi.identifiedRevenue': 'CA des clients identifiés',
  'ex.covNote': 'Clients identifiés · {0} des commandes',
  'ex.covNotePrev': 'Clients identifiés · {0} des commandes ({1} la période précédente)',
  'ex.newDef': 'Première commande de leur historique dans la période',
  'ex.returningDef': 'Déjà des commandes avant la période, ou 2 commandes ou plus',
  'ex.seg.new': 'Nouveaux clients',
  'ex.seg.returning': 'Clients récurrents',
  'ex.seg.unknown': 'Historique inconnu',
  'ex.seg.newShort': 'Nouveau',
  'ex.seg.returningShort': 'Récurrent',
  'ex.seg.unknownShort': 'Inconnu',
  'ex.nCustomers': '{0} clients',
  'ex.identifiedShort': 'identifiés',
  'ex.newVsReturningTitle': 'Nouveaux vs clients récurrents',
  'ex.segDefs': 'Nouveau : première commande de son historique dans la période (index de commande de la source). Récurrent : commande précédente déjà enregistrée, ou 2 commandes ou plus. Inconnu : index de commande non fiable.',
  'ex.custRevenueTitle': 'Répartition du CA clients',
  'ex.custRevenueNote': 'Part des commandes avec client identifié : {0}. Ce n’est pas la répartition de tous les clients de la boutique.',
  'ex.custTrendTitle': 'Évolution des clients identifiés',
  'ex.seriesNew': 'Nouveaux clients',
  'ex.seriesActive': 'Clients actifs',
  'ex.custTrendNote': 'Par semaine (semaines de la période, les extrémités peuvent être partielles).',
  'ex.activityTitle': 'Activité des clients',
  'ex.rec.d30': 'Dernier achat il y a 30 jours ou moins',
  'ex.rec.d60': 'Dernier achat il y a 31 à 60 jours',
  'ex.rec.d90': 'Dernier achat il y a 61 à 90 jours',
  'ex.rec.d90plus': 'Dernier achat il y a plus de 90 jours',
  'ex.recNote': 'Tranches descriptives sur {0} jours d’historique disponible. Nordla n’a pas de définition approuvée d’un client « dormant » : aucune n’est appliquée.',
  'ex.lastOrder': 'Dernier achat : {0}',
  'ex.basketShort': 'panier',
  'ex.frequencyTitle': 'Fréquence d’achat',
  'ex.freq.one': '1 commande',
  'ex.freq.two': '2 commandes',
  'ex.freq.three': '3 commandes ou plus',
  'ex.freqNote': 'Commandes de la période par client identifié.',
  'ex.avgOrders': 'Commandes par client : {0} en moyenne.',
  'ex.valueTitle': 'Valeur client',
  'ex.sampleTitle': 'Échantillon insuffisant',
  'ex.gated': 'Moyennes non affichées : {0} clients identifiés, minimum requis {1} (règle Nordla existante pour les moyennes par client).',
  'ex.noClv': 'Aucune valeur vie client (CLV) n’est calculée : la méthode et l’historique nécessaires ne sont pas disponibles.',
  'ex.val.avgRevenue': 'CA moyen par client identifié',
  'ex.val.median': 'CA médian par client identifié',
  'ex.val.basket': 'Panier moyen des clients identifiés',
  'ex.cohortTitle': 'Cohortes de rétention',
  'ex.cohortSub': 'Aucune cohorte n’est tracée : les données actuelles ne permettent pas un calcul de rétention fiable.',
  'ex.cohortReason.SHORT_HISTORY': 'Historique de {0} jours, moins que les {1} jours requis.',
  'ex.cohortReason.TOO_FEW_RETURNING_CUSTOMERS': 'Trop peu de clients récurrents identifiés.',
  'ex.cohortReason.NO_APPROVED_COHORT_DEFINITION': 'Aucune définition de cohorte n’est encore approuvée.',
  'ex.channelName.Point of Sale': 'Point de vente',
  'ex.channelName.Online Store': 'Boutique en ligne',
  'ex.noChannelData': 'Aucune vente par canal sur la période.',
  'ex.metricLabel': 'Indicateur',
  'ex.kpi.topChannel': 'Canal n°1 en CA',
  'ex.kpi.topChannelShare': 'Part du canal principal',
  'ex.kpi.topChannelOrders': 'Commandes du canal principal',
  'ex.kpi.topChannelAov': 'Panier moyen du canal principal',
  'ex.prevShare': 'Période précédente : {0}',
  'ex.chShareTitle': 'Répartition du chiffre d’affaires par canal',
  'ex.chPerfTitle': 'Performance par canal',
  'ex.chTrendTitle': 'Évolution des canaux',
  'ex.chTrendNote': 'Chiffre d’affaires par semaine et par canal (semaines de la période, les extrémités peuvent être partielles).',
  'ex.chInsightTitle': 'Lecture des chiffres',
  'ex.insShare': '{0} représente {1} du chiffre d’affaires de la période.',
  'ex.insAov': 'Le panier moyen du canal {0} est supérieur de {1} à celui du canal {2}.',
  'ex.insNeutral': 'Constats chiffrés, sans jugement.',
  'ex.chVarTitle': 'Variation vs période précédente',
  'ex.noSalesPeriod': 'Aucune vente sur la période',
  'ex.chContribTitle': 'Contribution des canaux à la variation du CA',
  'ex.chProductsTitle': 'Produits par canal',
  'ex.chCustomersTitle': 'Clients par canal',
  'ex.chCustLine': '{0} clients identifiés · {1} des commandes du canal',
  'ex.chCustSplit': '{0} nouveaux · {1} récurrents',
  'ex.chCustNote': 'Clients identifiés uniquement (clé pseudonyme). Les commandes sans client identifié ne sont attribuées à personne.',
  'ex.geo.kpiCoverage': 'Couverture géographique',
  'ex.geo.covNote': '{0} commande(s) sur {1} avec une ville exploitable',
  'ex.geo.covNeutral': 'Aucune extrapolation des commandes non localisées',
  'ex.geo.kpiSaleLoc': 'Lieu de vente renseigné',
  'ex.geo.saleLocNote': '{0} commande(s) sur {1}',
  'ex.geo.saleLocNeutral': 'Lieu du magasin, pas celui du client',
  'ex.geo.kpiZones': 'Zones exploitables',
  'ex.geo.zonesNote': 'Ville, code postal, province ou pays',
  'ex.geo.kpiOrders': 'Commandes de la période',
  'ex.geo.blockedTitle': 'Analyse géographique non disponible',
  'ex.geo.blockedSub': 'Seulement {0} des commandes disposent d\'une ville exploitable. Aucun graphique ni carte n\'est affiché plutôt que des chiffres trompeurs.',
  'ex.geo.foundTitle': 'Données géographiques présentes',
  'ex.geo.colField': 'Donnée',
  'ex.geo.colMeaning': 'Ce que c\'est',
  'ex.geo.colOrders': 'Commandes',
  'ex.geo.colUsable': 'Utilisable',
  'ex.geo.saleLocation': 'Lieu de vente : {0}',
  'ex.geo.saleLocMeaning': 'Lieu de vente (magasin), pas la localisation du client',
  'ex.geo.noSaleLocation': 'Aucun lieu de vente n\'est associé aux commandes.',
  'ex.geo.no': 'Non',
  'ex.geo.absentTitle': 'Données absentes',
  'ex.geo.absentLine': 'Adresse de livraison ou de facturation (ville, code postal, province, pays) : non synchronisée. Les commandes en ligne n\'ont donc aucune destination connue.',
  'ex.geo.unlockTitle': 'Pour débloquer cette analyse',
  'ex.geo.unlock1': 'Synchroniser, pour chaque commande, au minimum la ville ou le code postal de destination (sans rue, sans nom).',
  'ex.geo.unlock2': 'Ou renseigner la ville de chaque point de vente, si plusieurs lieux de vente existent.',
  'ex.geo.unlock3': 'Une couverture suffisante des commandes localisées, sur au moins deux zones différentes (seuil à définir avec le responsable produit).',
  'ex.geo.privacy': 'Confidentialité : aucune adresse n\'est stockée. L\'analyse restera agrégée (ville, province ou pays) et ne montrera jamais de client individuel.',
  'ex.geo.kpiOrdersNote': 'Période sélectionnée',
  'ex.per.kpiCur': 'CA période actuelle',
  'ex.per.kpiPrev': 'CA période précédente',
  'ex.per.kpiAbs': 'Variation absolue',
  'ex.per.kpiPct': 'Variation en %',
  'ex.per.last30': 'Période sélectionnée',
  'ex.per.prev30': 'Période précédente',
  'ex.per.noPrev': 'Aucune période précédente disponible',
  'ex.per.pctInvalid': 'Indisponible : aucune vente sur la période précédente',
  'ex.per.trendTitle': 'Évolution sur la période',
  'ex.per.bestTitle': 'Meilleure période',
  'ex.per.weakTitle': 'Période la plus faible',
  'ex.per.bestWeek': 'Meilleure semaine complète : {0} ({1})',
  'ex.per.weakWeek': 'Semaine complète la plus faible : {0} ({1})',
  'ex.per.weekOf': 'semaine du {0}',
  'ex.per.activityTitle': 'Répartition de l\'activité',
  'ex.per.daysWith': '{0} jours avec ventes',
  'ex.per.daysWithout': '{0} jours sans vente',
  'ex.per.daysAbove': '{0} jours au-dessus de la moyenne journalière',
  'ex.per.daysBelow': '{0} jours sous la moyenne journalière',
  'ex.per.activityNote': 'Constats chiffrés sur {0} jours ; la moyenne compte les jours sans vente.',
  'ex.per.weeksTitle': 'Contribution des semaines au CA',
  'ex.per.weeksNote': 'Part de chaque semaine dans le CA de la période. Les semaines aux extrémités sont partielles ({0} jours).',
  'ex.per.weekLabel': 'Sem. {0}',
  'ex.per.regTitle': 'Régularité des ventes',
  'ex.per.mean': 'Moyenne par jour',
  'ex.per.median': 'Médiane par jour',
  'ex.per.sd': 'Écart-type',
  'ex.per.cv': 'Coefficient de variation',
  'ex.per.regNote': 'Calculé sur les {0} jours de la période, jours sans vente inclus. L\'écart-type mesure la dispersion des ventes journalières autour de la moyenne ; le coefficient de variation le rapporte à la moyenne. Plus ils sont élevés, plus les ventes varient d\'un jour à l\'autre.',
  'ex.per.weekdayTitle': 'Performance par jour de la semaine',
  'ex.per.weekdayNote': 'Moyenne par occurrence : chaque jour de la semaine est divisé par le nombre de fois où il apparaît dans la période.',
  'ex.per.weekdayLine': '{0} commande(s) · {1}×',
  'ex.per.todTitle': 'Performance par moment de la journée',
  'ex.per.tod.night': 'Nuit (0 h–6 h)',
  'ex.per.tod.morning': 'Matin (6 h–12 h)',
  'ex.per.tod.midday': 'Midi (12 h–14 h)',
  'ex.per.tod.afternoon': 'Après-midi (14 h–18 h)',
  'ex.per.tod.evening': 'Soirée (18 h–24 h)',
  'ex.per.todNote': 'Heure locale ({0}) de {1} commande(s) sur {2}. CA net, remboursements rattachés à la commande.',
  'ex.per.orders': '{0} commande(s)',
  'ex.per.whyTitle': 'D\'où vient la variation ?',
  'ex.per.whyOrders': 'Le nombre de commandes varie de {0} ({1} contre {2}).',
  'ex.per.whyAov': 'Le panier moyen varie de {0} ({1} contre {2}).',
  'ex.per.whyNote': 'Lecture arithmétique : CA = commandes × panier moyen. Aucune cause n\'est établie.',
  'ex.per.noData': 'Pas assez de jours pour cette analyse.',
  'ex.cp.periodCur': 'Période actuelle',
  'ex.cp.periodPrev': 'Période précédente',
  'ex.cp.range': '{0} – {1} ({2} jours)',
  'ex.cp.previousValue': 'Avant : {0}',
  'ex.cp.change': 'Écart : {0}',
  'ex.cp.blocksTitle': 'Période actuelle vs précédente',
  'ex.cp.blocksNote': 'Blocs de 7 jours alignés par position : le bloc 1 de chaque période, puis le bloc 2, etc. Le dernier bloc est partiel ({0} jours).',
  'ex.cp.blocksNoteFull': 'Blocs de 7 jours alignés par position : le bloc 1 de chaque période, puis le bloc 2, etc.',
  'ex.cp.blockTip': '{0} : du {1} au {2} contre du {3} au {4}',
  'ex.cp.blockLabel': 'S{0}',
  'ex.cp.blockLabelPartial': 'S{0} ({1} j)',
  'ex.cp.trendTitle': 'Évolution comparée',
  'ex.cp.trendNote': 'Alignement par jour relatif (jour 1 à jour {0}) : les dates calendaires des deux périodes ne sont pas les mêmes.',
  'ex.cp.dayN': 'J{0}',
  'ex.cp.wfTitle': 'Décomposition de la variation du chiffre d\'affaires',
  'ex.cp.wfPrev': 'CA précédent',
  'ex.cp.wfPrevShort': 'Avant',
  'ex.cp.wfCur': 'CA actuel',
  'ex.cp.wfCurShort': 'Actuel',
  'ex.cp.wfOther': 'Autres catégories ({0})',
  'ex.cp.wfOtherShort': 'Autres',
  'ex.cp.wfNote': 'Décomposition par catégorie du catalogue (« Sans catégorie » incluse) : chaque vente appartient à une seule catégorie, la somme des écarts rejoint donc exactement le CA actuel.',
  'ex.cp.productsTitle': 'Produits qui expliquent la variation',
  'ex.cp.channelsTitle': 'Évolution par canal',
  'ex.cp.categoriesTitle': 'Évolution par catégorie',
  'ex.cp.shareOfChange': '{0} de la variation',
  'ex.cp.statusNew': 'Nouveau sur la période',
  'ex.cp.statusAbsent': 'Aucune vente sur la période',
  'ex.cp.noCategory': 'Sans catégorie',
  'ex.cp.volumeTitle': 'Volume vs panier moyen',
  'ex.cp.ordersLine': 'Commandes : {0}',
  'ex.cp.aovLine': 'Panier moyen : {0}',
  'ex.cp.up': 'hausse',
  'ex.cp.down': 'baisse',
  'ex.cp.flat': 'stabilité',
  'ex.cp.volumeSentence': 'Le CA évolue dans un contexte de {0} du nombre de commandes et de {1} du panier moyen.',
  'ex.cp.unavailable': 'Indisponible',
  'ex.cp.customersTitle': 'Clients identifiés',
  'ex.cp.custActive': 'Clients identifiés actifs',
  'ex.cp.custRevenue': 'CA des clients identifiés',
  'ex.cp.custNew': 'Nouveaux clients',
  'ex.cp.custReturning': 'Clients récurrents',
  'ex.cp.coverage': '{0} des commandes identifiées vs {1} auparavant',
  'ex.cp.coverageWarn': 'La couverture d’identification n’est pas la même dans les deux périodes : ces écarts ne mesurent pas nécessairement une évolution de la clientèle.',
  'ex.cp.coverageOk': 'La couverture d\'identification est proche entre les deux périodes.',
  'ex.cp.watchUp': 'Plus forte progression',
  'ex.cp.watchDown': 'Plus forte baisse',
  'ex.cp.watchNote': 'Produit, en écart absolu en euros.',
  'ex.cp.noMove': 'Aucun mouvement de produit à afficher.',
  'ex.cp.mostTitle': 'Ce qui a le plus changé',
  'ex.cp.mostRevenue': 'CA : {0}',
  'ex.cp.mostOrders': 'Commandes : {0}',
  'ex.cp.mostAov': 'Panier moyen : {0}',
  'ex.cp.mostProduct': 'Principal contributeur produit : {0} ({1})',
  'ex.cp.mostChannel': 'Canal avec la plus forte variation : {0} ({1})',
  'ex.cp.qualityTitle': 'Qualité de comparaison',
  'ex.cp.q.comparable': 'Comparable',
  'ex.cp.q.caution': 'À interpréter avec prudence',
  'ex.cp.q.partial': 'Données partielles',
  'ex.cp.q.days': 'Nombre de jours',
  'ex.cp.q.daysDetail': '{0} jours contre {1} jours.',
  'ex.cp.q.last_block': 'Dernier bloc',
  'ex.cp.q.lastBlockPartial': 'Le dernier bloc ne compte que {0} jours, comparés aux {1} jours correspondants.',
  'ex.cp.q.lastBlockFull': 'Tous les blocs comptent 7 jours.',
  'ex.cp.q.customer_coverage': 'Identification des clients',
  'ex.cp.q.coverageUnknown': 'Couverture non mesurable sur l\'une des périodes.',
  'ex.cp.q.categories': 'Classement en catégories',
  'ex.cp.q.categoriesDetail': '{0} du CA actuel est sans catégorie.',
  'ex.cp.q.costs': 'Coûts et marge',
  'ex.cp.q.costsDetail': 'Marge non comparée : coûts renseignés pour {0} des produits, vérifiés pour {1}.',
  'ex.cp.qualityNote': 'Règles explicites, sans score global.',
  'ex.cp.noPrevious': 'Aucune période précédente à comparer.',
  'ex.cp.exportSection': 'comparaison',
  'ex.days': 'jours',
  'topbar.shopifySync': 'Synchro Shopify {0}',
  'topbar.syncFailed': 'Synchro Shopify en échec · dernières données {0}',
  'topbar.syncStale': 'Synchro Shopify ancienne · {0}',
  'topbar.syncUnknown': 'Synchro Shopify inconnue',
  'ask.title': 'Demander à Nordla',
  'ask.placeholder': 'Posez une question sur vos chiffres…',
  'ask.send': 'Demander',
  'ask.close': 'Fermer',
  'ask.examples': 'Exemples',
  'ask.loading': 'Recherche dans vos données…',
  'ask.q.revenue': 'Quel est mon chiffre d’affaires des 30 derniers jours ?',
  'ask.q.orders': 'Combien de commandes ces 7 derniers jours ?',
  'ask.q.aov': 'Quel est mon panier moyen sur 30 jours ?',
  'ask.q.topProduct': 'Quel est mon meilleur produit ?',
  'ask.q.channel': 'Quel est mon canal principal ?',
  'ask.f.net_sales_ex_tax': 'Chiffre d’affaires HTVA (produits)',
  'ask.f.net_sales_incl_tax': 'Chiffre d’affaires TVAC (produits)',
  'ask.f.shipping_net_ex_tax': 'Livraison HTVA (à part, non incluse ci-dessus)',
  'ask.f.order_count': 'Commandes',
  'ask.f.units_sold': 'Unités vendues',
  'ask.f.aov_ex_tax': 'Panier moyen HTVA',
  'ask.f.refunds_products': 'Remboursements produits',
  'ask.f.refunds_total': 'Remboursements total (produits + livraison)',
  'ask.f.active_customers': 'Clients actifs (identifiés)',
  'ask.f.identified_share': 'Part des commandes identifiées',
  'ask.f.top_product': 'Meilleur produit',
  'ask.f.top_channel': 'Canal principal',
  'ask.period': 'Période : du {0} au {1}',
  'ask.source': 'Source : rapport Nordla du {0} (chiffres calculés par Nordla, pas par l’IA)',
  'ask.explainBy': 'Explication ({0})',
  'ask.ai.notConfigured': 'Explication par l’IA : aucun modèle IA n’est configuré. Les chiffres ci-dessus viennent directement de vos données Nordla.',
  'ask.ai.misconfigured': 'Explication par l’IA : le fournisseur demandé n’est pas configuré correctement. Les chiffres ci-dessus restent exacts.',
  'ask.ai.unavailable': 'Explication par l’IA : le service est indisponible. Les chiffres ci-dessus restent exacts.',
  'ask.ai.timeout': 'Explication par l’IA : le service n’a pas répondu à temps. Les chiffres ci-dessus restent exacts.',
  'ask.err.EMPTY_QUESTION': 'Écrivez une question.',
  'ask.err.QUESTION_TOO_LONG': 'La question est trop longue (500 caractères maximum).',
  'ask.err.UNSUPPORTED_QUESTION': 'Je ne sais pas encore répondre à cette question avec des données fiables. Je peux répondre sur : chiffre d’affaires, commandes, unités vendues, panier moyen, remboursements, clients, meilleur produit et canal principal.',
  'ask.err.UNSUPPORTED_PERIOD': 'Cette période n’est pas disponible. Périodes disponibles : hier, 7 jours, 30 jours.',
  'ask.err.ONLY_LAST_30_DAYS': 'Cette information n’est disponible que sur les 30 derniers jours.',
  'ask.err.NO_REPORT_AVAILABLE': 'Aucun rapport Nordla n’est disponible pour le moment : les chiffres ne peuvent pas être lus.',
  'ask.err.NO_DATA_FOR_QUESTION': 'Aucune donnée pour cette question sur la période.',
  'ask.err.PERIOD_NOT_IN_REPORT': 'Cette période n’existe pas dans le rapport actuel.',
  'ask.err.ASSISTANT_NOT_AVAILABLE': 'L’assistant n’est pas disponible sur ce serveur.',
  'ask.err.TIMEOUT': 'La réponse a pris trop de temps. Réessayez.',
  'ask.err.GENERIC': 'La requête a échoué. Réessayez dans un instant.',
  'period.p.last_7_days': '7 derniers jours',
  'period.p.last_30_days': '30 derniers jours',
  'period.p.last_90_days': '90 derniers jours',
  'period.p.this_week': 'Cette semaine',
  'period.p.this_month': 'Ce mois',
  'period.p.previous_month': 'Mois précédent',
  'period.p.this_year': 'Cette année',
  'period.p.custom': 'Période personnalisée',
  'period.customRange': '{0} – {1}',
  'period.from': 'Date de début',
  'period.to': 'Date de fin',
  'period.apply': 'Appliquer',
  'period.reset': 'Réinitialiser la période et les filtres',
  'period.range': 'Du {0} au {1} ({2} jours)',
  'period.todayIncluded': 'aujourd’hui inclus',
  'period.vsPrev': 'comparée à la période du {0} au {1}',
  'period.noPrevious': 'Pas de période précédente à comparer',
  'period.empty': 'Aucune commande sur cette période.',
  'period.err.INVALID_DATE': 'Dates invalides : choisissez une date de début et une date de fin.',
  'period.err.PERIOD_ORDER': 'La date de début doit être avant la date de fin.',
  'period.err.PERIOD_IN_FUTURE': 'La date de fin ne peut pas être dans le futur.',
  'period.err.PERIOD_TOO_LONG': 'La période est trop longue (3 ans maximum).',
  'period.err.INVALID_PERIOD': 'Cette période n’existe pas.',
  'period.err.DATASET_UNAVAILABLE': 'Les données détaillées ne sont pas encore prêtes pour cette période. Réessayez dans quelques minutes.',
  'period.err.GENERIC': 'La période n’a pas pu être chargée. Réessayez.',
  'ex.money.note': 'Remises : {0} · Remboursements produits : {1} · TVA produits : {2} (mêmes calculs que le rapport, sur la période sélectionnée).',
  'ask.voice.start': 'Parler à Nordla',
  'ask.voice.short': 'Parler',
  'ask.voice.stop': 'Arrêter',
  'ask.voice.listening': 'Je vous écoute…',
  'ask.voice.transcribing': 'Transcription…',
  'ask.voice.done': 'Dictée terminée : vérifiez le texte, corrigez-le si besoin, puis cliquez sur Demander.',
  'ask.voice.denied': 'L’accès au micro est refusé. Autorisez le micro pour ce site dans votre navigateur, ou écrivez votre question.',
  'ask.voice.mic': 'Aucun micro n’a pu être utilisé. Vérifiez qu’un micro est branché, ou écrivez votre question.',
  'ask.voice.noSpeech': 'Je n’ai rien entendu. Réessayez ou écrivez votre question.',
  'ask.voice.network': 'La reconnaissance vocale de votre navigateur est indisponible pour le moment. Écrivez votre question.',
  'ask.voice.generic': 'La dictée n’a pas fonctionné. Écrivez votre question ou réessayez.',
  'ask.voice.unsupported': 'La dictée vocale n’est pas disponible dans ce navigateur (essayez Chrome ou Edge). Vous pouvez écrire votre question.',
  'ask.voice.privacy': 'Nordla n’enregistre ni ne stocke votre audio. La reconnaissance vocale est fournie par votre navigateur et peut, selon le navigateur, utiliser les services de son fournisseur. Seul le texte transcrit est envoyé à Nordla.',
  'topbar.reportGenerated': 'Rapport généré {0}',
  'kpi.costCoverageDetail': '{0} du CA couvert · {1} des coûts vérifiés',
  'watch.aovCompared': 'Panier moyen : {0} contre {1} sur les 30 jours précédents ({2}).',
  'wc.gainsLine': 'Les produits en plus forte hausse ({0}) ajoutent {1}.',
  'wc.lossesLine': 'Les produits en plus forte baisse ({0}) retirent {1}.',
  'wc.netLine': 'Variation nette du chiffre d’affaires : {0}.',
  'wc.marginCaveat': 'Coûts partiellement connus : {0} du CA couvert · {1} des coûts vérifiés.',
  'ex.geo.pendingSub': 'Des zones exploitables existent, mais le seuil de couverture minimal n’est pas encore défini : l’analyse par zone n’est pas activée.',

  // ---- Clients (main customer workspace) ----
  'cl.title': 'Clients',
  'cl.subtitle': 'Comprenez votre base clients et identifiez rapidement ceux qui nécessitent votre attention.',
  'cl.toExplorer': 'Analyser les clients dans Explorer',
  'cl.coverageTitle': 'Couverture clients',
  'cl.coverageLine': '{0} des commandes disposent d’un client identifié',
  'cl.coverageCounts': '({0} sur {1} commandes, période sélectionnée)',
  'cl.coveragePrev': '{0} sur la période précédente',
  'cl.scopePeriod': 'Indicateurs et statuts : période sélectionnée',
  'cl.scopeHistory': 'Historique disponible : depuis le {0} ({1} jours), {2} des commandes identifiées',
  'cl.coverageShift': 'La part de commandes identifiées est passée de {0} à {1} : une variation du nombre de clients reflète aussi ce changement de couverture, pas seulement une évolution de l’activité.',
  'cl.tag30': 'Période sélectionnée',
  'cl.tagHistory': 'Historique disponible',
  'cl.tagMixed': 'Période + historique',
  'cl.topTitle': 'Clients principaux par CA',
  'cl.distTitle': 'Répartition des clients',
  'cl.distNote': 'Clients actifs sur la période, selon les définitions d’Explorer. Seules les commandes avec un client identifié sont comptées ({0}).',
  'cl.watchHeading': 'À surveiller',
  'cl.watch.lapsedTitle': 'Sans achat sur la période',
  'cl.watch.lapsedText': '{0} client(s) ont acheté pendant la période précédente mais pas pendant la période sélectionnée. C’est un constat sur deux périodes, pas une prévision.',
  'cl.watch.lapsedNone': 'Aucun client identifié n’a acheté sur la période précédente sans racheter sur la période actuelle.',
  'cl.watch.bothTitle': 'Actifs sur les deux périodes',
  'cl.watch.bothText': '{0} client(s) ont acheté sur les deux périodes : leur évolution est comparable.',
  'cl.watch.bothNone': 'Aucun client identifié n’a acheté à la fois sur la période actuelle et sur la précédente : aucune évolution individuelle n’est comparable.',
  'cl.watch.rhythmTitle': 'Rythme d’achat individuel',
  'cl.watch.rhythmInsufficient': 'Impossible de comparer la récence d’un client à son propre rythme : {0} intervalle(s) entre commandes observé(s), minimum requis {1}.',
  'cl.watch.rhythmNoRule': '{0} intervalles observés, mais Nordla n’a pas de règle approuvée pour qualifier un délai d’inhabituel : aucun client n’est signalé.',
  'cl.andMore': '+ {0} autre(s)',
  'cl.listTitle': 'Clients',
  'cl.searchPlaceholder': 'Rechercher un client (ex. #A4B7)',
  'cl.searchLabel': 'Rechercher un client par son identifiant',
  'cl.filtersLabel': 'Filtrer les clients',
  'cl.recencyLabel': 'Filtrer par récence',
  'cl.sortLabel': 'Trier les clients',
  'cl.filter.all': 'Tous',
  'cl.filter.active': 'Actifs',
  'cl.filter.new': 'Nouveaux',
  'cl.filter.returning': 'Récurrents',
  'cl.filter.unknown': 'Historique inconnu',
  'cl.filter.inactive': 'Sans achat sur la période',
  'cl.recency.all': 'Toutes les récences',
  'cl.recency.d0_30': 'Dernier achat ≤ 30 jours',
  'cl.recency.d31_60': 'Dernier achat 31–60 jours',
  'cl.recency.d61_90': 'Dernier achat 61–90 jours',
  'cl.recency.d90_plus': 'Dernier achat > 90 jours',
  'cl.sort.recent': 'Tri : dernier achat',
  'cl.sort.revenue': 'Tri : CA période',
  'cl.sort.orders': 'Tri : commandes période',
  'cl.sort.known': 'Tri : commandes connues',
  'cl.col.customer': 'Client',
  'cl.col.status': 'Statut / activité',
  'cl.col.revenue': 'CA période',
  'cl.col.orders': 'Commandes période',
  'cl.col.aov': 'Panier moyen période',
  'cl.col.lastOrder': 'Dernier achat',
  'cl.col.recency': 'Récence',
  'cl.col.evolution': 'Évolution',
  'cl.status.new': 'Nouveau',
  'cl.status.returning': 'Récurrent',
  'cl.status.unknown': 'Historique inconnu',
  'cl.status.inactive': 'Sans achat sur la période',
  'cl.evo.compared': 'Comparé à la période précédente',
  'cl.evo.no_current_purchase': 'Aucun achat sur la période actuelle',
  'cl.evo.no_previous_purchase': 'Aucun achat sur la période précédente : pas de pourcentage calculable',
  'cl.evo.no_previous_window': 'Aucune période précédente disponible',
  'cl.evo.none': 'Aucun achat sur les deux périodes',
  'cl.evo.newShort': 'Pas d’achat avant',
  'cl.today': 'aujourd’hui',
  'cl.daysAgo': 'il y a {0} j',
  'cl.count': '{0} client(s) affiché(s) sur {1} identifié(s)',
  'cl.noIdentified': 'Aucun client identifié dans l’historique disponible : les commandes sans client ne sont jamais attribuées.',
  'cl.noMatchTitle': 'Aucun client ne correspond',
  'cl.noMatch': 'Modifiez la recherche ou les filtres.',
  'cl.listNote': 'CA hors TVA, net des remboursements. Statut, CA, commandes et panier moyen : période sélectionnée (définitions d’Explorer). Dernier achat et récence : historique disponible. Clients pseudonymisés, aucun nom n’est stocké.',
  'cl.openDetail': 'Ouvrir le détail de {0}',
  'cl.close': 'Fermer le détail',
  'cl.loading': 'Chargement du client…',
  'cl.detailError': 'Le détail de ce client n’est pas disponible dans le rapport actuel.',
  'cl.d.activeLine': 'A acheté sur la période sélectionnée',
  'cl.d.inactiveLine': 'Aucun achat sur la période sélectionnée',
  'cl.d.periodTitle': 'Période actuelle',
  'cl.d.previous': 'Période précédente : {0} · {1} commande(s)',
  'cl.d.historyTitle': 'Historique disponible',
  'cl.d.firstKnown': 'Premier achat connu',
  'cl.d.lastKnown': 'Dernier achat connu',
  'cl.d.knownOrders': 'Commandes connues',
  'cl.d.knownRevenue': 'CA connu (HT)',
  'cl.d.earlierOutside': 'Selon la source, ce client avait déjà passé {0} commande(s) avant le début de l’historique disponible : elles ne sont pas incluses ici.',
  'cl.d.earlierNone': 'Selon la source, sa première commande se trouve dans l’historique disponible.',
  'cl.d.earlierUnknown': 'La source ne permet pas de savoir si ce client a commandé avant l’historique disponible.',
  'cl.d.trendTitle': 'Évolution des achats',
  'cl.d.trendOne': 'Une seule commande connue : pas de courbe, voir l’historique ci-dessous.',
  'cl.d.trendFew': '{0} commandes connues : trop peu de points pour une courbe, voir l’historique ci-dessous.',
  'cl.d.ordersTitle': 'Historique des achats',
  'cl.d.inPeriod': 'Période sélectionnée',
  'cl.d.refunded': 'Remboursement',
  'cl.d.ordersNote': 'Montant par commande : hors TVA, net des remboursements enregistrés.',
  'cl.d.productsTitle': 'Produits achetés',
  'cl.d.units': '× {0}',
  'cl.d.refundedUnits': 'dont {0} remboursé(s)',

  // ---- Produits (main product workspace) ----
  'pr.title': 'Produits',
  'pr.subtitle': 'Suivez vos produits, repérez les mouvements importants et concentrez-vous sur ceux qui méritent votre attention.',
  'pr.toExplorer': 'Analyser les produits dans Explorer',
  'pr.scopeCurrent': 'Période sélectionnée (depuis le {0})',
  'pr.scopePrevious': 'comparée à la période précédente (depuis le {0})',
  'pr.scopeNoPrevious': 'aucune période précédente disponible',
  'pr.scopeHistory': 'dernière vente : historique disponible',
  'pr.catalogueLine': 'CA sans catégorie : {0} · CA d’articles hors catalogue : {1}',
  'pr.marginOmitted': 'Marge par produit non affichée : coûts partiels ({0} du CA couvert, {1} vérifiés)',
  'pr.kpi.sold': 'Produits vendus',
  'pr.kpi.soldPrev': 'Produits distincts vendus · {0} la période précédente',
  'pr.kpi.top': 'Produit n°1 en CA',
  'pr.shareOfRevenue': '{0} du CA',
  'pr.kpi.top3': 'Part du Top 3 dans le CA',
  'pr.kpi.top3Note': 'Indicateur de concentration, pas de performance',
  'pr.kpi.top3Prev': '{0} la période précédente ({1})',
  'pr.kpi.declining': 'Produits en baisse',
  'pr.kpi.decliningNote': 'Dont {0} sans vente sur la période',
  'pr.kpi.decliningScope': 'Par rapport à une vente de la période précédente',
  'pr.status.compared': 'Comparable',
  'pr.status.new': 'Nouveau sur la période',
  'pr.status.notBefore': 'Pas de vente avant',
  'pr.status.absent': 'Plus de vente sur la période',
  'pr.status.noPrevious': 'Sans période précédente',
  'pr.status.partial': 'Données partielles',
  'pr.status.negative': 'Remboursements > ventes',
  'pr.partialTitle': 'Article vendu qui ne correspond plus à un produit du catalogue : ni image, ni catégorie, identité non stable.',
  'pr.noSaleNowShort': 'Plus de vente',
  'pr.evo.compared': 'Comparé à la période précédente',
  'pr.evo.new': 'Nouveau sur la période : pas de pourcentage',
  'pr.evo.not_sold_before': 'Pas de vente sur la période précédente : pas de pourcentage',
  'pr.evo.absent': 'Plus de vente sur la période',
  'pr.evo.no_previous': 'Aucune période précédente disponible',
  'pr.noImage': 'Pas d’image dans le catalogue',
  'pr.noCatalogue': 'Hors catalogue',
  'pr.growthTitle': 'Produits en hausse',
  'pr.declineTitle': 'Produits en baisse',
  'pr.tagCompare': 'Période vs précédente',
  'pr.tag30': 'Période sélectionnée',
  'pr.tagPrevious': 'Période précédente',
  'pr.tagHistory': 'Historique disponible',
  'pr.prevToCur': '{0} → {1}',
  'pr.newLine': 'Créé et vendu sur la période : pas de comparaison',
  'pr.moversMore': '{0} affichés sur {1} : voir la liste complète ci-dessous (filtres En hausse / En baisse).',
  'pr.moversNote': 'Uniquement les produits vendus sur la période précédente (base de comparaison réelle), selon Explorer.',
  'pr.listTitle': 'Produits',
  'pr.searchPlaceholder': 'Rechercher un produit (nom ou identifiant)',
  'pr.searchLabel': 'Rechercher un produit par nom ou identifiant Shopify',
  'pr.sortLabel': 'Trier les produits',
  'pr.filtersLabel': 'Filtrer les produits',
  'pr.filter.all': 'Tous',
  'pr.filter.up': 'En hausse',
  'pr.filter.down': 'En baisse',
  'pr.filter.new': 'Nouveau sur la période',
  'pr.filter.absent': 'Sans vente sur la période',
  'pr.filter.uncategorised': 'Sans catégorie',
  'pr.sort.revenue': 'Tri : CA période',
  'pr.sort.units': 'Tri : unités période',
  'pr.sort.gain': 'Tri : plus forte hausse (€)',
  'pr.sort.loss': 'Tri : plus forte baisse (€)',
  'pr.sort.recent': 'Tri : dernière vente',
  'pr.sort.name': 'Tri : nom (A → Z)',
  'pr.col.product': 'Produit',
  'pr.col.revenue': 'CA période',
  'pr.col.units': 'Unités période',
  'pr.col.share': 'Part du CA',
  'pr.col.evolution': 'Évolution',
  'pr.col.lastSale': 'Dernière vente',
  'pr.col.status': 'Statut',
  'pr.count': '{0} produit(s) affiché(s) sur {1}',
  'pr.noMatchTitle': 'Aucun produit ne correspond',
  'pr.noMatch': 'Modifiez la recherche ou les filtres.',
  'pr.listNote': 'Produits vendus sur la période sélectionnée ou sur la période précédente. CA hors TVA, net des remboursements. Évolution : uniquement face à une vente réelle de la période précédente. Dernière vente : historique disponible.',
  'pr.openDetail': 'Ouvrir le détail de {0}',
  'pr.watchHeading': 'À surveiller',
  'pr.watch.compareTitle': 'Comparaison',
  'pr.watch.absentTitle': 'Plus de vente sur la période',
  'pr.watch.absentText': '{0} produit(s) vendus sur la période précédente ne se sont pas vendus sur la période sélectionnée.',
  'pr.watch.absentNone': 'Tous les produits vendus sur la période précédente se sont encore vendus sur la période actuelle.',
  'pr.watch.lowerTitle': 'En baisse, toujours vendus',
  'pr.watch.lowerText': '{0} produit(s) se vendent encore, pour un CA inférieur à la période précédente.',
  'pr.watch.lowerNone': 'Aucun produit encore vendu n’a un CA inférieur à la période précédente.',
  'pr.watch.catalogueTitle': 'Qualité des données produit',
  'pr.watch.uncat': '{0} produit(s) vendu(s) sans catégorie dans le catalogue ({1} du CA).',
  'pr.watch.uncatNone': 'Tous les produits vendus ont une catégorie.',
  'pr.watch.unmatched': '{0} article(s) vendu(s) ne correspondent plus au catalogue ({1} du CA).',
  'pr.watch.unmatchedNone': 'Tous les articles vendus correspondent à un produit du catalogue.',
  'pr.watch.negative': '{0} produit(s) ont plus de remboursements que de ventes sur la période (contribution négative).',
  'pr.andMore': '+ {0} autre(s)',
  'pr.catTitle': 'Répartition par catégorie',
  'pr.catNote': 'Catégorie = type de produit du catalogue. « Sans catégorie » reste visible : ce CA n’est pas réparti.',
  'pr.concNote': '{0} produits vendus sur la période. Part du CA des 1, 3 et 5 premiers produits.',
  'pr.loading': 'Chargement du produit…',
  'pr.detailError': 'Le détail de ce produit n’est pas disponible dans le rapport actuel.',
  'pr.close': 'Fermer le détail',
  'pr.d.currentTitle': 'Période actuelle',
  'pr.d.perUnit': 'CA par unité',
  'pr.d.compareTitle': 'Période précédente',
  'pr.d.prevRevenue': 'CA précédent',
  'pr.d.prevUnits': 'Unités précédentes',
  'pr.d.change': 'Variation',
  'pr.d.changePct': 'Variation (%)',
  'pr.d.contribution': 'Contribution à la variation du CA total : {0} sur {1}.',
  'pr.d.trendTitle': 'Évolution des ventes',
  'pr.d.trendFew': 'Ventes sur {0} jour(s) seulement : pas de courbe, voir les ventes récentes ci-dessous.',
  'pr.d.trendNone': 'Aucune vente sur la période : pas de courbe.',
  'pr.d.lastSale': 'Dernière vente connue : {0}',
  'pr.d.recentTitle': 'Ventes récentes',
  'pr.d.refunded': '{0} remboursé(s)',
  'pr.d.noRecent': 'Aucune vente dans l’historique disponible.',
  'pr.d.recentNote': 'Une ligne par ligne de commande : montant hors TVA, net des remboursements enregistrés.',

  // ---- Account control (top-right profile menu) ----
  'account.menuLabel': 'Menu du compte',
  'account.title': 'Compte',
  'account.statusLocal': 'Aperçu local · aucune session active',
  'account.noSession': 'Analytics Premium ne dispose pas encore de connexion : aucune session à fermer et aucune page de paramètres du compte. Ces actions apparaîtront ici dès qu’elles existeront réellement.',
  'account.settings': 'Paramètres',
  'account.logout': 'Se déconnecter',
};
