// EU rules as DATA. Each rule: appliesWhen (three-valued predicate over identity traits + case context), why text, required evidence, sources, version.
// A rule never says "compliant": it says whether the regime APPLIES, which evidence is expected, and what is still missing. Nordla is decision support only.
import { SRC } from './sources.js';

export const RULE_VERSION = '2026-10-03.1';
const LITHIUM = ['li_ion', 'li_po', 'li_metal', 'lithium'];
const isLithium = { trait: 'battery.chemistry', in: LITHIUM };
const R = (r) => ({ jurisdiction: 'EU', ruleVersion: RULE_VERSION, instrumentRefs: [], requiresAuthorityConfirmation: false, severity: 'NORMAL', requiredEvidence: [], ...r });
const doc = (id, label, docType, requirement = 'REQUIRED', extra = {}) => ({ id, label, docType, requirement, ...extra });
const own = (id, label, requirement = 'REQUIRED', extra = {}) => ({ id, label, docType: 'COMPANY_RECORD', requirement, ...extra });

const HARMONISED_ANY = { any: [{ trait: 'electrical.present', is: true }, { trait: 'radio.present', is: true }, { trait: 'toy', is: true }, { trait: 'ppe', is: true }] };

export const EU_RULES = [
  R({
    id: 'eu.gpsr', family: 'GPSR', title: 'General Product Safety Regulation (EU) 2023/988',
    appliesWhen: { all: [{ ctx: 'consumerSales', is: true }, { not: { trait: 'medical', is: true } }] },
    whyApplies: 'consumer product offered to EU consumers: GPSR applies in full to non-harmonised products and for the risks/aspects that sector law does not cover; for harmonised products the distance-sales, accident and online information duties still apply (Art. 2, 19-21)',
    whyNot: 'not a consumer product, or medical (separate regime)',
    requiredEvidence: [
      own('gpsr.risk_analysis', 'Internal risk analysis and technical documentation (kept 10 years)', 'REQUIRED', { when: { ctx: 'ownBrand', is: true } }),
      doc('gpsr.manual', 'Instructions and safety information in the consumer language of each target market', 'MANUAL', 'CONDITIONAL'),
      doc('gpsr.label', 'Label / packaging artwork showing manufacturer and responsible-person name and address, type or batch identifier', 'LABEL_ARTWORK', 'CONDITIONAL'),
      doc('gpsr.test', 'Safety test evidence supporting the risk analysis', 'TEST_REPORT', 'RECOMMENDED'),
    ],
    sources: [SRC.GPSR, SRC.GPSR_GUIDE, SRC.BE_GENERAL], instrumentRefs: ['2023/988'], requiresAuthorityConfirmation: false,
    notes: 'Art. 16: an EU-established responsible person must exist for non-harmonised products (importer, EU manufacturer, authorised representative or EU fulfilment provider); its name and contact go on the product, packaging, parcel or document. Art. 19: online offers must show manufacturer, responsible person, product identification with a picture, and warnings in the consumer language. Art. 22: the marketplace requires the same from you.',
  }),
  R({
    id: 'eu.nlf_operator', family: 'CE_FRAMEWORK', title: 'Economic operator duties for harmonised products (Reg. 2019/1020 Art. 4; Decision 768/2008)',
    appliesWhen: HARMONISED_ANY,
    whyApplies: 'the product falls under at least one Union harmonisation act: an EU-established economic operator (EU manufacturer, importer, authorised representative or EU fulfilment provider) must be named and verify that the EU declaration of conformity and the technical documentation exist; its details must be on the product, packaging or accompanying document and present at customs',
    whyNot: 'no harmonisation-act trait established',
    requiredEvidence: [
      own('nlf.eu_operator', 'Name an EU-established economic operator and have its name and address on the product / packaging / document', 'REQUIRED'),
      own('nlf.records', 'Keep a copy of the EU declaration of conformity and the technical documentation available for 10 years', 'REQUIRED'),
    ],
    sources: [SRC.MSR, SRC.NLF, SRC.BLUE_GUIDE], instrumentRefs: ['2019/1020'],
    notes: 'The Blue Guide (section 3.6) says the Art. 4 operator details must be present when the product is declared for free circulation at customs.',
  }),
  R({
    id: 'eu.ce', family: 'CE', title: 'CE marking',
    appliesWhen: HARMONISED_ANY,
    whyApplies: 'at least one harmonisation act that provides for CE marking applies, so the manufacturer (or its authorised representative) must affix it after the conformity assessment',
    whyNot: 'no harmonisation act providing for CE marking is established for this product: a CE mark must NOT be affixed to products that no act requires it for; the general product safety rules apply instead',
    requiredEvidence: [own('ce.assessment', 'Conformity assessment done by the manufacturer, CE marking affixed on the product by the manufacturer', 'REQUIRED')],
    sources: [SRC.CE765, SRC.CE_PAGE, SRC.BLUE_GUIDE],
    notes: 'CE is not a mark of origin, quality or safety approval, and a logo on a product or listing proves nothing: the EU declaration of conformity and its supporting evidence are what count. Cosmetics, food-contact materials, textiles (outside PPE/toys) and most household goods are NOT CE products, but they have their own regimes.',
  }),
  R({
    id: 'eu.lvd', family: 'LVD', title: 'Low Voltage Directive 2014/35/EU',
    appliesWhen: { all: [{ trait: 'electrical.present', is: true }, { trait: 'radio.present', is: false }, { any: [{ all: [{ trait: 'electrical.maxVoltageAc', gte: 50 }, { trait: 'electrical.maxVoltageAc', lte: 1000 }] }, { all: [{ trait: 'electrical.maxVoltageDc', gte: 75 }, { trait: 'electrical.maxVoltageDc', lte: 1500 }] }] }] },
    whyApplies: 'electrical equipment rated 50-1000 V AC or 75-1500 V DC, without radio function (radio equipment is covered by RED, which includes safety)',
    whyNot: 'outside 50-1000 V AC / 75-1500 V DC, or radio equipment (RED covers safety)',
    standardFamily: 'LVD', instrumentRefs: ['2014/35'],
    requiredEvidence: [doc('lvd.doc', 'EU declaration of conformity citing Directive 2014/35/EU', 'EU_DOC'), doc('lvd.test', 'Safety test report (e.g. EN 62368-1 / EN 60335 family) for the exact model', 'TEST_REPORT')],
    sources: [SRC.LVD, SRC.BE_ELECTRICAL],
    notes: 'The 50 V / 75 V lower limits are the voltage RATING of the equipment, not the voltage of what it plugs into. The category voltage defaults are PROBABLE only: confirm the rating from the rating label.',
  }),
  R({
    id: 'eu.emc', family: 'EMC', title: 'EMC Directive 2014/30/EU',
    appliesWhen: { all: [{ trait: 'electrical.present', is: true }, { trait: 'radio.present', is: false }] },
    whyApplies: 'electrical or electronic apparatus that can emit or be disturbed by electromagnetic interference, without radio function (radio equipment is covered by RED)',
    whyNot: 'no electrical function, or radio equipment (RED covers EMC)',
    standardFamily: 'EMC', instrumentRefs: ['2014/30'],
    requiredEvidence: [doc('emc.doc', 'EU declaration of conformity citing Directive 2014/30/EU', 'EU_DOC'), doc('emc.test', 'EMC test report (e.g. EN 55032 / EN 55035 / EN 61000 family) for the exact model', 'TEST_REPORT')],
    sources: [SRC.EMC],
  }),
  R({
    id: 'eu.red', family: 'RED', title: 'Radio Equipment Directive 2014/53/EU',
    appliesWhen: { trait: 'radio.present', is: true },
    whyApplies: 'the product intentionally emits or receives radio waves (Bluetooth, Wi-Fi, RF...): RED covers safety, EMC and radio spectrum use, with no voltage limit',
    whyNot: 'no radio function established',
    standardFamily: 'RED', instrumentRefs: ['2014/53'],
    requiredEvidence: [doc('red.doc', 'EU declaration of conformity citing Directive 2014/53/EU', 'EU_DOC'), doc('red.test', 'Radio / EMC / safety test reports for the exact model (ETSI EN 300/301, EN 62368-1...)', 'TEST_REPORT')],
    sources: [SRC.RED, SRC.BE_BIPT],
  }),
  R({
    id: 'eu.red_cyber', family: 'RED', title: 'RED cybersecurity requirements (Delegated Regulation (EU) 2022/30)',
    appliesWhen: { all: [{ trait: 'radio.present', is: true }, { any: [{ trait: 'radio.internetConnected', is: true }, { trait: 'radio.processesPersonalData', is: true }, { trait: 'childrenUse', is: true }] }] },
    whyApplies: 'radio equipment that is internet-connected, processes personal data (including childcare equipment, toys with radio, wearables) or handles money transfer must meet the RED cybersecurity requirements (Art. 3(3)(d)-(f)), applicable since 1 August 2025',
    whyNot: 'not internet-connected, no personal data processing and not for children',
    standardFamily: 'RED', instrumentRefs: ['2014/53'],
    requiredEvidence: [doc('redcyber.test', 'Cybersecurity assessment evidence (e.g. EN 18031 series) for the exact model', 'TEST_REPORT', 'CONDITIONAL')],
    sources: [SRC.RED_CYBER, SRC.CRA_NEWS], requiresAuthorityConfirmation: true,
    notes: 'Delegated Regulation 2026/339 repeals 2022/30 from 11 December 2027, when the Cyber Resilience Act applies in full (reporting duties from 11 September 2026). The CRA text itself was not opened: confirm with an expert.',
  }),
  R({
    id: 'eu.charger', family: 'COMMON_CHARGER', title: 'Common charger Directive (EU) 2022/2380 (USB Type-C)',
    appliesWhen: { all: [{ trait: 'category', in: ['bluetooth_speaker', 'bluetooth_earbuds'] }, { trait: 'battery.present', is: true }] },
    whyApplies: 'rechargeable portable speakers, headphones and earbuds must use USB Type-C for wired charging (applies since 28 December 2024), and the box must carry the charger-included pictogram information',
    whyNot: 'not a listed device category',
    requiredEvidence: [doc('charger.label', 'Packaging showing USB Type-C and the charger-included pictogram', 'PACKAGING_ARTWORK', 'CONDITIONAL')],
    sources: [SRC.CHARGER], instrumentRefs: ['2022/2380'],
    notes: 'Laptops: from 28 April 2026. Other product categories (phones, tablets, cameras, e-readers, keyboards, mice, game consoles, navigation) are listed in Annex Ia: check the exact product against it.',
  }),
  R({
    id: 'eu.rohs', family: 'ROHS', title: 'RoHS Directive 2011/65/EU (with Delegated Directive (EU) 2015/863)',
    appliesWhen: { trait: 'electrical.present', is: true },
    whyApplies: 'electrical and electronic equipment: lead, mercury, hexavalent chromium, PBB, PBDE, four phthalates (DEHP, BBP, DBP, DIBP) at 0.1% and cadmium at 0.01% by weight in homogeneous material are restricted',
    whyNot: 'no electrical or electronic function established',
    standardFamily: 'ROHS', instrumentRefs: ['2011/65'],
    requiredEvidence: [{ id: 'rohs.evidence', label: 'RoHS test report or material declaration for the exact model (EN IEC 63000 technical documentation)', docType: 'ROHS_EVIDENCE', docTypes: ['ROHS_EVIDENCE', 'TEST_REPORT'], requirement: 'REQUIRED' }],
    sources: [SRC.ROHS_PAGE, SRC.ROHS],
  }),
  R({
    id: 'eu.batteries', family: 'BATTERIES', title: 'Batteries Regulation (EU) 2023/1542',
    appliesWhen: { trait: 'battery.present', is: true },
    whyApplies: 'the product contains or is a battery: the importer of an imported battery has the manufacturer-type responsibilities (conformity, labelling, due diligence, extended producer responsibility)',
    whyNot: 'no battery established',
    standardFamily: 'BATTERIES', instrumentRefs: ['2023/1542'],
    requiredEvidence: [doc('batt.doc', 'Battery conformity and safety evidence (EN 62133 / IEC 62619 / UN 38.3) for the exact battery', 'BATTERY_DOC'), doc('batt.label', 'Battery labelling (capacity, separate-collection symbol, chemical symbols where required)', 'LABEL_ARTWORK', 'CONDITIONAL')],
    sources: [SRC.BATT_PAGE, SRC.BATT_FAQ, SRC.BATT], requiresAuthorityConfirmation: true, severity: 'HIGH',
    notes: 'The application dates of several obligations (CE marking, labelling, due diligence, battery passport) are staggered: confirm the obligations that apply on the date of import.',
  }),
  R({
    id: 'transport.lithium', family: 'BATTERIES', title: 'Lithium battery transport tests and dangerous-goods rules (UN 38.3)',
    appliesWhen: { all: [{ trait: 'battery.present', is: true }, isLithium] },
    whyApplies: 'lithium cells and batteries must have passed the UN Manual of Tests and Criteria 38.3 to be transported; air and sea shipments follow dangerous-goods rules (and Amazon reviews them)',
    whyNot: 'no lithium battery established',
    standardFamily: 'BATTERIES',
    requiredEvidence: [doc('un383.report', 'UN 38.3 test summary / report for the exact battery', 'UN383'), doc('un383.sds', 'Safety data sheet / dangerous-goods information', 'SDS', 'CONDITIONAL')],
    sources: [SRC.UN383], requiresAuthorityConfirmation: true,
    notes: 'The shipping rules (carrier, mode, packing instructions) are for the freight forwarder: ask the forwarder before booking.',
  }),
  R({
    id: 'eu.weee', family: 'WEEE', title: 'WEEE Directive 2012/19/EU (extended producer responsibility)',
    appliesWhen: { trait: 'electrical.present', is: true },
    whyApplies: 'electrical and electronic equipment: the producer or importer must register in each Member State where it sells and finance take-back and recycling',
    whyNot: 'no electrical or electronic function established',
    requiredEvidence: [own('weee.registration', 'WEEE producer registration in each sales country (in Belgium: Recupel)', 'REQUIRED')],
    sources: [SRC.WEEE_PAGE, SRC.WEEE_FAQ],
  }),
  R({
    id: 'eu.reach', family: 'REACH', title: 'REACH Regulation (EC) 1907/2006 (restricted substances in articles)',
    appliesWhen: { always: true },
    whyApplies: 'every article placed on the EU market must respect REACH restrictions (Annex XVII) and the importer must handle substances of very high concern (SVHC) above 0.1% by weight, including notification and information to customers',
    requiredEvidence: [{ id: 'reach.evidence', label: 'REACH / SVHC test evidence or supplier declaration for the exact product', docType: 'REACH_EVIDENCE', docTypes: ['REACH_EVIDENCE', 'TEST_REPORT', 'MATERIAL_DECL'], requirement: 'RECOMMENDED' }],
    sources: [SRC.REACH_PAGE, SRC.REACH], requiresAuthorityConfirmation: true,
    notes: 'Higher scrutiny for products worn, mouthed or used by children, jewellery, textiles and plastics. No single document proves REACH compliance: a supplier statement is only a claim.',
  }),
  R({
    id: 'eu.clp', family: 'CLP', title: 'CLP Regulation (EC) 1272/2008 and safety data sheet',
    appliesWhen: { trait: 'chemicalMixture', is: true },
    whyApplies: 'a chemical substance or mixture: classification, labelling, packaging and (for hazardous mixtures) a safety data sheet are required',
    whyNot: 'not a chemical substance or mixture',
    requiredEvidence: [doc('clp.sds', 'Safety data sheet (REACH Annex II format) and label artwork', 'SDS')],
    sources: [SRC.CLP], requiresAuthorityConfirmation: true,
  }),
  R({
    id: 'eu.toys', family: 'TOYS', title: 'Toy Safety Directive 2009/48/EC (Regulation (EU) 2025/2509 from 1 August 2030)',
    appliesWhen: { trait: 'toy', is: true },
    whyApplies: 'a product designed or intended, exclusively or not, for play by children under 14: CE marking, EN 71 testing, warnings, age grading and a safety assessment (chemical, physical, flammability, electrical) are required. The Toy Safety Regulation replaces the Directive from 1 August 2030 (digital product passport, new chemical rules)',
    whyNot: 'not established as a toy',
    standardFamily: 'TOYS', instrumentRefs: ['2009/48'],
    requiredEvidence: [doc('toys.doc', 'EU declaration of conformity citing Directive 2009/48/EC', 'EU_DOC'), doc('toys.test', 'EN 71 test reports (mechanical, flammability, chemical) for the exact model', 'TEST_REPORT'), doc('toys.label', 'Packaging with age warnings, CE marking and manufacturer/importer details', 'PACKAGING_ARTWORK', 'CONDITIONAL')],
    sources: [SRC.TOYS, SRC.TOYS_REG, SRC.TOYS_BE], requiresAuthorityConfirmation: true, severity: 'HIGH',
    notes: 'Toys are among the products most often found dangerous: expect a third-party laboratory report, not a supplier statement.',
  }),
  R({
    id: 'eu.fcm', family: 'FCM', title: 'Food-contact materials (Regulation (EC) 1935/2004 and specific measures)',
    appliesWhen: { trait: 'foodContact', is: true },
    whyApplies: 'material intended to touch food or drink: it must be safe, traceable and accompanied by a declaration of compliance; plastics follow Regulation (EU) 10/2011 and bisphenol restrictions apply (Regulation (EU) 2024/3190)',
    whyNot: 'not intended to touch food or drink',
    standardFamily: 'FCM',
    requiredEvidence: [doc('fcm.doc', 'Declaration of compliance for food contact for the exact product', 'FCM_DOC'), doc('fcm.test', 'Migration / material test report (e.g. specific and overall migration) from a laboratory', 'TEST_REPORT'), { id: 'fcm.material', label: 'Material declaration (material, additives, intended temperature and food types)', docType: 'MATERIAL_DECL', requirement: 'CONDITIONAL' }],
    sources: [SRC.FCM_PAGE, SRC.FCM_LEG, SRC.FCM_BPA, SRC.FCM_BE], requiresAuthorityConfirmation: true, severity: 'HIGH',
    notes: 'The "glass and fork" symbol and a supplier "food grade" statement are not a declaration of compliance.',
  }),
  R({
    id: 'eu.textiles', family: 'TEXTILES', title: 'Textile fibre labelling (Regulation (EU) 1007/2011) and children\'s textile safety',
    appliesWhen: { trait: 'textile', is: true },
    whyApplies: 'textile products must carry a fibre-composition label in the language of the market; children\'s clothing has extra safety requirements (drawstrings, small parts); REACH restrictions (azo dyes, formaldehyde, nickel on metal parts) apply. Textiles are not CE products unless PPE or toy law applies',
    whyNot: 'not a textile product',
    standardFamily: 'TEXTILES',
    requiredEvidence: [doc('text.label', 'Label artwork with fibre composition (and care) in the market language', 'LABEL_ARTWORK'), doc('text.test', 'Chemical / safety test report (azo, formaldehyde; drawstrings for children)', 'TEST_REPORT', 'CONDITIONAL', { when: { trait: 'childrenUse', is: true } })],
    sources: [SRC.TEXT_FAQ, SRC.ESPR],
    notes: 'Unsold apparel and footwear: ESPR Art. 25 prohibits destroying unsold stock from 19 July 2026 for large companies (micro and small enterprises are exempt; medium from 19 July 2030).',
  }),
  R({
    id: 'eu.cosmetics', family: 'COSMETICS', title: 'Cosmetics Regulation (EC) 1223/2009',
    appliesWhen: { trait: 'cosmetic', is: true },
    whyApplies: 'a cosmetic product: an EU responsible person, a product safety report by a qualified safety assessor, notification in the CPNP portal, GMP evidence, an ingredient list and compliant labelling are required before it is placed on the market',
    whyNot: 'not a cosmetic product',
    standardFamily: 'COSMETICS',
    requiredEvidence: [own('cosm.rp', 'EU responsible person named on the label and product information file (PIF) available', 'REQUIRED'), own('cosm.cpnp', 'Notification in the EU CPNP portal and cosmetic product safety report (CPSR) by a qualified assessor', 'REQUIRED'), doc('cosm.label', 'Label artwork: ingredients (INCI), batch, expiry/PAO, responsible person, function, warnings', 'LABEL_ARTWORK')],
    sources: [SRC.COSM_PAGE], requiresAuthorityConfirmation: true, severity: 'HIGH',
    notes: 'A cosmetic is NOT importable on a supplier certificate alone: the responsible person duty cannot be delegated to the factory for you.',
  }),
  R({
    id: 'eu.ppe', family: 'PPE', title: 'PPE Regulation (EU) 2016/425',
    appliesWhen: { trait: 'ppe', is: true },
    whyApplies: 'personal protective equipment: category I (minimal risks), II and III (serious / irreversible harm) determine the conformity route; category II and III need a notified-body EU type-examination certificate',
    whyNot: 'not personal protective equipment',
    standardFamily: 'PPE', instrumentRefs: ['2016/425'],
    requiredEvidence: [doc('ppe.doc', 'EU declaration of conformity citing Regulation (EU) 2016/425', 'EU_DOC'), doc('ppe.cert', 'Notified-body EU type-examination certificate (category II / III), with the notified-body number', 'CERTIFICATE', 'CONDITIONAL'), doc('ppe.test', 'Test report to the harmonised standard (EN 388, EN 374, EN 149, EN 166, ...)', 'TEST_REPORT')],
    sources: [SRC.PPE_PAGE, SRC.PPE_REG], requiresAuthorityConfirmation: true, severity: 'HIGH',
  }),
  R({
    id: 'eu.packaging', family: 'PACKAGING', title: 'Packaging and Packaging Waste Regulation (EU) 2025/40 (applies from 12 August 2026)',
    appliesWhen: { always: true },
    whyApplies: 'packaging placed on the EU market must comply with the PPWR (substances, recyclability, labelling, producer responsibility); the producer responsibility registration is national',
    requiredEvidence: [own('pack.producer', 'Packaging producer responsibility registration in each sales country (in Belgium: Fost Plus for household, Valipac for industrial packaging)', 'REQUIRED')],
    sources: [SRC.PACK_PAGE, SRC.PACK_NEWS, SRC.PPWR], requiresAuthorityConfirmation: true,
    notes: 'The detailed PPWR obligations phase in over several years: confirm those that apply on the date of import.',
  }),
  R({
    id: 'eu.medical_boundary', family: 'MEDICAL', title: 'Medical device boundary (Regulation (EU) 2017/745)',
    appliesWhen: { trait: 'medical', is: true },
    whyApplies: 'a medical purpose is claimed: the product may be a medical device (separate, much stricter regime). Nordla does NOT assess it',
    whyNot: 'no medical purpose claimed',
    requiredEvidence: [own('med.expert', 'Expert classification of the intended purpose before any import decision', 'REQUIRED')],
    sources: [], requiresAuthorityConfirmation: true, severity: 'HIGH',
    notes: 'The MDR text was not opened by Nordla. Whether a consumer item is a medical device depends on the purpose the supplier or the listing claims.',
  }),
  R({
    id: 'customs.eori', family: 'CUSTOMS', title: 'EORI number and customs import declaration',
    appliesWhen: { always: true },
    whyApplies: 'importing goods from China needs an EORI number, a customs declaration and a tariff classification; low-value consignments have no duty exemption for customs purposes: confirm the current rules with your customs broker',
    requiredEvidence: [own('customs.eori', 'EORI number and customs broker or forwarder arrangement', 'REQUIRED')],
    sources: [SRC.EORI, SRC.LOW_VALUE, SRC.TARIC, SRC.EBTI], requiresAuthorityConfirmation: true,
  }),
];
