import {EXECUTION_MODE,LICENSE_STATUS,MODEL_STATUS} from './constants.js';
export const CREATIVE_FIDELITY_CANDIDATES=Object.freeze([
{id:'hidream-o1',name:'HiDream-O1',provider:'HiDream.ai',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','REFERENCE_IMAGE'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.VERIFIED,license_name:'MIT',license_source:'https://github.com/HiDream-ai/HiDream-O1-Image/blob/main/LICENSE',commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:['Official README states both code and models use the MIT License. Exact downloaded artifact hash must still be recorded before execution.']},
{id:'qwen-image-edit',name:'Qwen Image / Edit candidate',provider:'Alibaba / Qwen',kind:'IMAGE_MODEL',version:'2511 candidate',version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','MULTI_REFERENCE'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:'Apache-2.0 badge on official model page; exact artifact LICENSE still required',license_source:'https://huggingface.co/Qwen/Qwen-Image-Edit-2511/tree/main',commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{storage_gb_reported:57.7},pricing:{software_license_eur:0},notes:['Version-specific exact LICENSE verification remains mandatory before execution.']},
{id:'flux2-klein-4b',name:'FLUX.2 Klein 4B',provider:'Black Forest Labs',kind:'IMAGE_MODEL',version:'4B',version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','REFERENCE_IMAGE'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.VERIFIED,license_name:'Apache-2.0',license_source:'https://github.com/black-forest-labs/flux2',commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{vram_gb_reported_approx:8,consumer_gpu:true},pricing:{software_license_eur:0},notes:['Only the 4B/4B Base line is treated as Apache-2.0 here; 9B/dev variants are not interchangeable for licensing.']},
{id:'sana-image',name:'SANA image candidate',provider:'NVIDIA',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:null,license_source:null,commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:[]},
{id:'z-image-turbo',name:'Z-Image-Turbo',provider:'Unknown until license audit',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION'],status:MODEL_STATUS.WATCH,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:null,license_source:null,commercial_use:false,eu_allowed:false,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:['Blocked from commercial benchmark execution until license and EU rights are verified.']},
{id:'gpt-image-reference',name:'GPT Image premium reference',provider:'OpenAI',kind:'IMAGE_API',version:null,version_hash:null,execution_mode:EXECUTION_MODE.API,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','REFERENCE_IMAGE'],status:MODEL_STATUS.REFERENCE,license_status:LICENSE_STATUS.VERIFIED,license_name:'Provider terms',license_source:'Provider API terms',commercial_use:true,eu_allowed:true,self_hostable:false,hardware:{},pricing:{basis:'PAY_AS_YOU_GO',exact_price_required_at_run_time:true},notes:['Reference only; no assumption that it should be the default production engine.']}
]);
