import {EXECUTION_MODE,LICENSE_STATUS,MODEL_STATUS} from './constants.js';
export const CREATIVE_FIDELITY_CANDIDATES=Object.freeze([
{id:'hidream-o1',name:'HiDream-O1',provider:'HiDream.ai',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','REFERENCE_IMAGE'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:'MIT (research finding; exact artifact review required)',license_source:null,commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:['Do not promote to APPROVED until exact weights LICENSE is archived and verified.']},
{id:'qwen-image-edit',name:'Qwen Image / Edit candidate',provider:'Alibaba / Qwen',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','MULTI_REFERENCE'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:null,license_source:null,commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:['Version-specific license review is mandatory.']},
{id:'flux2-klein-4b',name:'FLUX.2 Klein 4B',provider:'Black Forest Labs',kind:'IMAGE_MODEL',version:'4B',version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','REFERENCE_IMAGE'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:'Apache-2.0 (research finding; exact artifact review required)',license_source:null,commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:[]},
{id:'sana-image',name:'SANA image candidate',provider:'NVIDIA',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION'],status:MODEL_STATUS.BENCHMARK,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:null,license_source:null,commercial_use:true,eu_allowed:true,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:[]},
{id:'z-image-turbo',name:'Z-Image-Turbo',provider:'Unknown until license audit',kind:'IMAGE_MODEL',version:null,version_hash:null,execution_mode:EXECUTION_MODE.SELF_HOST,capabilities:['IMAGE_GENERATION'],status:MODEL_STATUS.WATCH,license_status:LICENSE_STATUS.NEEDS_REVIEW,license_name:null,license_source:null,commercial_use:false,eu_allowed:false,self_hostable:true,hardware:{},pricing:{software_license_eur:0},notes:['Blocked from commercial benchmark execution until license and EU rights are verified.']},
{id:'gpt-image-reference',name:'GPT Image premium reference',provider:'OpenAI',kind:'IMAGE_API',version:null,version_hash:null,execution_mode:EXECUTION_MODE.API,capabilities:['IMAGE_GENERATION','IMAGE_EDITING','REFERENCE_IMAGE'],status:MODEL_STATUS.REFERENCE,license_status:LICENSE_STATUS.VERIFIED,license_name:'Provider terms',license_source:'Provider API terms',commercial_use:true,eu_allowed:true,self_hostable:false,hardware:{},pricing:{basis:'PAY_AS_YOU_GO',exact_price_required_at_run_time:true},notes:['Reference only; no assumption that it should be the default production engine.']}
]);
