export const MODEL_STATUS = Object.freeze({
  BENCHMARK: 'BENCHMARK',
  APPROVED: 'APPROVED',
  REFERENCE: 'REFERENCE',
  WATCH: 'WATCH',
  REJECT: 'REJECT',
});

export const LICENSE_STATUS = Object.freeze({
  VERIFIED: 'VERIFIED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  RESTRICTED: 'RESTRICTED',
  REJECTED: 'REJECTED',
});

export const EXECUTION_MODE = Object.freeze({
  SELF_HOST: 'SELF_HOST',
  API: 'API',
  LOCAL_TOOL: 'LOCAL_TOOL',
});

export const BENCHMARK_TASK = Object.freeze({
  BACKGROUND_SWAP: 'BACKGROUND_SWAP',
  PREMIUM_AD: 'PREMIUM_AD',
  IN_CONTEXT: 'IN_CONTEXT',
  EXTERNAL_EDIT: 'EXTERNAL_EDIT',
  COHERENT_SET: 'COHERENT_SET',
});

export const FIDELITY_CHECK = Object.freeze({
  PRODUCT_IDENTITY: 'PRODUCT_IDENTITY',
  PRODUCT_GEOMETRY: 'PRODUCT_GEOMETRY',
  PIECE_COUNT: 'PIECE_COUNT',
  PRODUCT_COLOR: 'PRODUCT_COLOR',
  LOGO: 'LOGO',
  TEXT: 'TEXT',
  FACE: 'FACE',
});

// Backward-compatible names for the experimental V0 API.
export const FIDELITY_FATAL_DEFECT = Object.freeze({
  TEXT_MISMATCH: FIDELITY_CHECK.TEXT,
  LOGO_MISMATCH: FIDELITY_CHECK.LOGO,
  FACE_CHANGED: FIDELITY_CHECK.FACE,
  GEOMETRY_CHANGED: FIDELITY_CHECK.PRODUCT_GEOMETRY,
  PIECE_COUNT_MISMATCH: FIDELITY_CHECK.PIECE_COUNT,
  IDENTITY_COLOR_MISMATCH: FIDELITY_CHECK.PRODUCT_COLOR,
  PRODUCT_INVENTED: FIDELITY_CHECK.PRODUCT_IDENTITY,
});

export const FIDELITY_GATE_OUTCOME = Object.freeze({
  PASS: 'PASS',
  FAIL: 'FAIL',
  NOT_MEASURABLE: 'NOT_MEASURABLE',
});

export const BENCHMARK_VERDICT = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  UNDETERMINED: 'UNDETERMINED',
});

export const QUALITY_RATING = Object.freeze({
  UNACCEPTABLE: 'UNACCEPTABLE',
  WEAK: 'WEAK',
  ACCEPTABLE: 'ACCEPTABLE',
  STRONG: 'STRONG',
});
