export const MODEL_STATUS = Object.freeze({BENCHMARK:'BENCHMARK',APPROVED:'APPROVED',REFERENCE:'REFERENCE',WATCH:'WATCH',REJECT:'REJECT'});
export const LICENSE_STATUS = Object.freeze({VERIFIED:'VERIFIED',NEEDS_REVIEW:'NEEDS_REVIEW',RESTRICTED:'RESTRICTED',REJECTED:'REJECTED'});
export const EXECUTION_MODE = Object.freeze({SELF_HOST:'SELF_HOST',API:'API',LOCAL_TOOL:'LOCAL_TOOL'});
export const BENCHMARK_TASK = Object.freeze({BACKGROUND_SWAP:'BACKGROUND_SWAP',PREMIUM_AD:'PREMIUM_AD',IN_CONTEXT:'IN_CONTEXT',EXTERNAL_EDIT:'EXTERNAL_EDIT',COHERENT_SET:'COHERENT_SET'});
export const FIDELITY_FATAL_DEFECT = Object.freeze({TEXT_MISMATCH:'TEXT_MISMATCH',LOGO_MISMATCH:'LOGO_MISMATCH',FACE_CHANGED:'FACE_CHANGED',GEOMETRY_CHANGED:'GEOMETRY_CHANGED',PIECE_COUNT_MISMATCH:'PIECE_COUNT_MISMATCH',IDENTITY_COLOR_MISMATCH:'IDENTITY_COLOR_MISMATCH',PRODUCT_INVENTED:'PRODUCT_INVENTED'});
