// Activation & Channel Execution V1: closed vocabularies and stable error codes.
//
//   MARKETING PREPARES · SOCLE / POLICY / HUMAN AUTHORIZES · EXECUTION LAYER EXECUTES · M4 OBSERVES AND LEARNS
//
// This layer is NOT Marketing decision logic. It consumes an ActivationManifest that the Socle / Policy / a human already authorized,
// checks the capabilities of the connected account, executes ONE external call per delivery through a governed adapter, guarantees
// it never happens twice, follows the real provider status and returns proof. It never chooses what, where (which account) or when
// (best time) to publish, never edits the creative, and never stores a token.

export const ACTIVATION_VERSION = 'activation-channel-execution.v1';

// The connector `kind` IS the provider id (merchant_connectors is an open set, ADR 0003).
export const CHANNEL_PROVIDER = Object.freeze({
  INSTAGRAM: 'instagram',
  TIKTOK: 'tiktok',
  GOOGLE_BUSINESS_PROFILE: 'google_business_profile',
});
export const CHANNEL_PROVIDERS = Object.freeze(Object.values(CHANNEL_PROVIDER));

export const PUBLISH_MODE = Object.freeze({
  PUBLISH_NOW: 'PUBLISH_NOW',
  SCHEDULE_INTERNAL: 'SCHEDULE_INTERNAL',
  INTERACTIVE_CONFIRMATION: 'INTERACTIVE_CONFIRMATION',
});

export const PREFLIGHT_STATUS = Object.freeze({
  READY: 'READY',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  BLOCKED: 'BLOCKED',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const JOB_STATE = Object.freeze({
  PLANNED: 'PLANNED',
  READY: 'READY',
  SUBMITTING: 'SUBMITTING',
  PROCESSING: 'PROCESSING',
  PUBLISHED: 'PUBLISHED',
  FAILED_RETRYABLE: 'FAILED_RETRYABLE',
  FAILED_FINAL: 'FAILED_FINAL',
  CANCELLED: 'CANCELLED',
});

// Closed transitions. PUBLISHED, FAILED_FINAL and CANCELLED are terminal. SUBMITTING -> READY exists only to hand a claimed job
// back when the live preflight needs a human (nothing was sent to the provider).
export const JOB_TRANSITIONS = Object.freeze({
  PLANNED: ['READY', 'CANCELLED', 'FAILED_FINAL'],
  READY: ['SUBMITTING', 'CANCELLED', 'FAILED_FINAL'],
  SUBMITTING: ['PROCESSING', 'PUBLISHED', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'READY'],
  PROCESSING: ['PUBLISHED', 'FAILED_RETRYABLE', 'FAILED_FINAL'],
  FAILED_RETRYABLE: ['SUBMITTING', 'FAILED_FINAL', 'CANCELLED'],
  PUBLISHED: [],
  FAILED_FINAL: [],
  CANCELLED: [],
});
export const TERMINAL_JOB_STATES = Object.freeze(['PUBLISHED', 'FAILED_FINAL', 'CANCELLED']);

// Provider-normalized error codes (never a raw provider payload).
export const PROVIDER_ERROR = Object.freeze({
  RATE_LIMITED: 'RATE_LIMITED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',
  PROCESSING_TRANSIENT: 'PROCESSING_TRANSIENT',
  AUTH_INVALID: 'AUTH_INVALID',
  SCOPE_MISSING: 'SCOPE_MISSING',
  MEDIA_INVALID: 'MEDIA_INVALID',
  PRIVACY_MISMATCH: 'PRIVACY_MISMATCH',
  CAPABILITY_UNSUPPORTED: 'CAPABILITY_UNSUPPORTED',
  POLICY_VIOLATION: 'POLICY_VIOLATION',
  ACCOUNT_INVALID: 'ACCOUNT_INVALID',
  PRIVATE_ONLY_RESTRICTION: 'PRIVATE_ONLY_RESTRICTION',
  DAILY_LIMIT_REACHED: 'DAILY_LIMIT_REACHED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  PERMANENT_REJECTION: 'PERMANENT_REJECTION',
  PUBLISH_RESULT_UNKNOWN: 'PUBLISH_RESULT_UNKNOWN',
});
// ONLY these are retried. Everything else (permanent 4xx, auth, scope, media, privacy, policy, account...) is final.
export const RETRYABLE_PROVIDER_ERRORS = Object.freeze(['RATE_LIMITED', 'PROVIDER_UNAVAILABLE', 'TIMEOUT', 'PROCESSING_TRANSIENT']);

// Deterministic backoff 1m -> 5m -> 15m -> 60m, capped; Retry-After wins when later.
export const RETRY_BACKOFF_MS = Object.freeze([60_000, 300_000, 900_000, 3_600_000]);
export const MAX_ATTEMPTS = 5;
export const MAX_STATUS_POLLS = 12;
export const STATUS_POLL_INTERVAL_MS = 60_000;
export const SUBMISSION_LEASE_MS = 600_000;

export const READINESS_LEVEL = Object.freeze({
  CONTRACT_READY: 'CONTRACT_READY',
  ADAPTER_READY: 'ADAPTER_READY',
  SANDBOX_READY: 'SANDBOX_READY',
  PRODUCTION_READY: 'PRODUCTION_READY',
});

export const DEFAULT_TIMEOUT_MS = 15_000;

export const ACT_ERROR = Object.freeze({
  UNKNOWN_KEY: 'ACT_UNKNOWN_KEY',
  INVALID_FIELD: 'ACT_INVALID_FIELD',
  INVALID_TIMESTAMP: 'ACT_INVALID_TIMESTAMP',
  SECRET_LEAK: 'ACT_SECRET_LEAK',
  FORBIDDEN_FIELD: 'ACT_FORBIDDEN_FIELD',

  CONNECTOR_KIND_UNSUPPORTED: 'ACT_CONNECTOR_KIND_UNSUPPORTED',
  CONNECTOR_EXTERNAL_ID_REQUIRED: 'ACT_CONNECTOR_EXTERNAL_ID_REQUIRED',
  CONNECTOR_MERCHANT_MISMATCH: 'ACT_CONNECTOR_MERCHANT_MISMATCH',
  CONNECTOR_NOT_FOUND: 'ACT_CONNECTOR_NOT_FOUND',
  CONNECTOR_AMBIGUOUS: 'ACT_CONNECTOR_AMBIGUOUS',
  CREDENTIAL_PROVIDER_REQUIRED: 'ACT_CREDENTIAL_PROVIDER_REQUIRED',

  ORDER_SCOPE_MISMATCH: 'ACT_ORDER_SCOPE_MISMATCH',
  ORDER_INVALID_MODE: 'ACT_ORDER_INVALID_MODE',
  ORDER_INVALID_WINDOW: 'ACT_ORDER_PUBLISH_AT_OUTSIDE_WINDOW',
  ORDER_PUBLISH_AT_REQUIRED: 'ACT_ORDER_PUBLISH_AT_REQUIRED',
  ORDER_DUPLICATE_DELIVERY: 'ACT_ORDER_DUPLICATE_DELIVERY',
  ORDER_DELIVERY_MISSING: 'ACT_ORDER_DELIVERY_MISSING',
  ORDER_DELIVERY_UNKNOWN: 'ACT_ORDER_DELIVERY_UNKNOWN',
  ORDER_INVALID_EXPIRY: 'ACT_ORDER_INVALID_EXPIRY',
  ORDER_OUTLIVES_GOVERNING: 'ACT_ORDER_OUTLIVES_GOVERNING',
  ORDER_DERIVED_MISMATCH: 'ACT_ORDER_DERIVED_MISMATCH',
  ORDER_PROVIDER_MISMATCH: 'ACT_ORDER_PROVIDER_MISMATCH',
  PROVIDER_OPTIONS_INVALID: 'ACT_PROVIDER_OPTIONS_INVALID',
  PROVIDER_OPTION_NOT_APPROVED: 'ACT_PROVIDER_OPTION_NOT_APPROVED',

  JOB_INVALID_TRANSITION: 'ACT_JOB_INVALID_TRANSITION',
  JOB_STATE_CONFLICT: 'ACT_JOB_STATE_CONFLICT',
  JOB_NOT_FOUND: 'ACT_JOB_NOT_FOUND',
  JOB_SCOPE_MISMATCH: 'ACT_JOB_SCOPE_MISMATCH',
  IDEMPOTENCY_CONFLICT: 'ACT_IDEMPOTENCY_CONFLICT',
  STORE_FAILED: 'ACT_STORE_FAILED',

  RECEIPT_NOT_PUBLISHED: 'ACT_RECEIPT_NOT_PUBLISHED',
  RECEIPT_POST_ID_REQUIRED: 'ACT_RECEIPT_POST_ID_REQUIRED',
  RECEIPT_PUBLISHED_AT_REQUIRED: 'ACT_RECEIPT_PUBLISHED_AT_REQUIRED',
  M4_NOTHING_PUBLISHED: 'ACT_M4_NOTHING_PUBLISHED',
  M4_RECEIPT_SCOPE_MISMATCH: 'ACT_M4_RECEIPT_SCOPE_MISMATCH',

  MEDIA_TRANSPORT_MISSING: 'ACT_MEDIA_TRANSPORT_MISSING',
  MEDIA_NOT_COMPATIBLE: 'ACT_MEDIA_NOT_COMPATIBLE',
  MEDIA_LOCATION_REFUSED: 'ACT_MEDIA_LOCATION_REFUSED',
});

export class ActivationError extends Error {
  /** @param {string} code one of ACT_ERROR @param {string} message never contains submitted values @param {object} [detail] non-secret context */
  constructor(code, message, detail = {}) {
    super(message);
    this.name = 'ActivationError';
    this.code = code;
    this.detail = detail;
  }
}
