// Generates docs/CHINA-SOURCING-PHRASEBOOK-REVIEW.md: every Chinese sentence Nordla can show a supplier, with its French and English meaning and its REVIEW STATE, for a native speaker to check.
//   node tools/phrasebook-review.mjs
import { writeFileSync } from 'node:fs';
import { TEMPLATES } from '../src/sourcing/core/supplier.js';
import { SUGGESTED, REVIEW, NATIVE_REVIEW, conflictPhrases, frText } from '../src/sourcing/core/phrases.js';

const esc = (x) => String(x ?? '').replace(/\|/g, '\|').replace(/\n/g, ' ');
const state = (id, base) => (NATIVE_REVIEW[id] ? REVIEW.NATIVE_REVIEWED : base);
let md = `# China Sourcing - Chinese phrasebook for native review\n\nGenerated by \`node tools/phrasebook-review.mjs\`. **No sentence below is certified.** A sentence becomes NATIVE_REVIEWED only when a native speaker has checked it and an entry is added to \`NATIVE_REVIEW\` in \`src/sourcing/core/phrases.js\` (reviewer, date). Until then the app shows its state next to the Chinese text ("non relue" / "relecture par un locuteur natif à faire") and never calls it a certified translation. **Critical sentences must be validated before real commercial use.**\n\nHow to review: for each row read the Chinese, compare with the French/English meaning, and answer OK / FIX (with the corrected sentence). Check especially: trade terms (MOQ 起订量, Incoterms, 定金/尾款), politeness level for a first meeting, and that model numbers / standards are inserted unchanged. Placeholders in braces are replaced by the case's own values, copied verbatim.\n\n`;
md += '## A. Questions of the V0 phrasebook (state: TECHNICAL_ONLY = technically checked, native review pending)\n\n| id | English | Chinese | state |\n|---|---|---|---|\n';
for (const [id, t] of Object.entries(TEMPLATES)) md += `| ${id} | ${esc(t.en)} | ${esc(t.zh)} | ${state(id, REVIEW.TECHNICAL_ONLY)} |\n`;
md += '\n## B. Suggested commercial questions added in V1 (state: UNREVIEWED)\n\n| id | Français | English | Chinese | state |\n|---|---|---|---|---|\n';
for (const [id, t] of Object.entries(SUGGESTED)) md += `| s:${id} | ${esc(t.fr)} | ${esc(t.en)} | ${esc(t.zh)} | ${state(`s:${id}`, REVIEW.UNREVIEWED)} |\n`;
md += '\n## C. Clarification sentences for a contradiction (state: UNREVIEWED; the two values are inserted unchanged)\n\n| fact | Français (example values 50 / 100) | Chinese | state |\n|---|---|---|---|\n';
for (const key of ['quote.moq', 'quote.unitPrice', 'quote.incoterm', 'quote.leadTime', 'payment.depositPct', 'identifier.model']) { const p = conflictPhrases({ key, entries: [{ value: key === 'quote.incoterm' ? 'FOB' : key === 'identifier.model' ? 'PB-X200' : '50' }, { value: key === 'quote.incoterm' ? 'EXW' : key === 'identifier.model' ? 'PB-X180' : '100' }] }); md += `| ${key} | ${esc(p.fr)} | ${esc(p.zh)} | ${p.review} |\n`; }
const d = conflictPhrases({ key: 'docClaim.UN383', entries: [{ value: 'CLAIMED' }, { value: 'NOT_AVAILABLE' }] }); md += `| docClaim.* | ${esc(d.fr)} | ${esc(d.zh)} | ${d.review} |\n`;
md += `\n## D. French reading texts of the V0 questions (for the owner: validated during the physical checkpoints)\n\n| id | Français |\n|---|---|\n`;
for (const id of Object.keys(TEMPLATES)) md += `| ${id} | ${esc(frText(id, { model: '{model}', qty: '{qty}', docType: 'TEST_REPORT', refs: '{refs}' }) ?? '(none)')} |\n`;
writeFileSync(new URL('../docs/CHINA-SOURCING-PHRASEBOOK-REVIEW.md', import.meta.url), md); console.log('written');
