-- Finance CORE - ESSENTIAL BANK. Builds on 20261003090000 (P0 integrity) and 20261004090000 (essential payments); none of the three is applied to production yet: apply them in order.
-- ADDITIVE: nothing dropped, no row rewritten except two backfills of NEW columns (account links). Legacy columns of fin_bank_transactions (status, matched_*) stay but stop being authoritative.
--
-- THE MODEL
--   Bank account        fin_bank_accounts          identity of an account (provider id or the CSV pseudo-account), currency, MASKED iban, status. Never a credential.
--   Bank transaction    fin_bank_transactions      an OBSERVED bank movement. Immutable facts. NOT a Finance payment.
--   Reconciliation      fin_bank_reconciliations   append-only link  bank transaction <-> payment (kind MATCH) or "deliberately set aside" (kind IGNORE); N<->M, partial, reversible.
--   Payment truth       fin_payment_registry + allocations (unchanged, still the only authority on payments, allocations, refunds, reversals and document status).
--   Derived             reconciled / ignored / remaining of a transaction, and its reconciliation status, come ONLY from the reconciliation rows (fin_bank_tx_amounts).
--                       fin_bank_transactions.status and matched_amount_cents/matched_at are a MIRROR written by a trigger; matched_kind/matched_document_id/matched_payment_id are dead legacy.
--
-- AMOUNTS of a transaction T (integer cents, one currency):  abs = |amount|;  matched = net MATCH rows;  ignored = net IGNORE rows;  remaining = abs - matched - ignored
--   Invariants (PostgreSQL): remaining >= 0 ; a MATCH never exceeds the payment (amount - its reversals) ; direction (IN tx <-> IN payment, OUT <-> OUT) and currency agree ;
--   an unreconcile never exceeds what the reconciliation row still holds ; a payment that is reconciled cannot be voided (unreconcile first).
-- LOCKING ORDER (extends the payments order): document -> payment -> bank transaction. A reconciliation locks its payment, then its transaction.
-- ATOMICITY: fin_bank_reconcile_and_pay creates the payment AND the reconciliation in ONE transaction: a failed payment can never leave a claimed transaction behind.

-- ---------- accounts ----------
create table fin_bank_accounts (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references merchants(id),
  external_id text not null check (length(external_id) between 1 and 200),
  origin text not null check (origin in ('PROVIDER', 'CSV')),
  provider text,
  display_name text check (length(display_name) <= 120),
  iban_masked text check (iban_masked is null or (position('*' in iban_masked) > 0 and length(iban_masked) <= 40)), -- a full IBAN is never stored here
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'CLOSED')),
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  constraint fin_bank_accounts_external_uq unique (merchant_id, external_id),
  constraint fin_bank_accounts_id_merchant_uq unique (id, merchant_id)
);
alter table fin_bank_accounts enable row level security;
revoke all on fin_bank_accounts from anon, authenticated;

-- ---------- transactions: identity, provenance, counterparty, structured communication (stored here, generated by the Belgian chantier) ----------
alter table fin_bank_transactions add constraint fin_bank_tx_id_merchant_uq unique (id, merchant_id);
alter table fin_bank_transactions
  add column bank_account_id uuid,
  add column value_date date,
  add column fingerprint text check (length(fingerprint) <= 64),
  add column bank_reference text check (length(bank_reference) <= 200),
  add column counterparty_account_masked text check (counterparty_account_masked is null or position('*' in counterparty_account_masked) > 0),
  add column direction text generated always as (case when amount_cents >= 0 then 'IN' else 'OUT' end) stored,
  add constraint fin_bank_tx_account_fk foreign key (bank_account_id, merchant_id) references fin_bank_accounts (id, merchant_id),
  add constraint fin_bank_tx_currency_chk check (currency ~ '^[A-Z]{3}$') not valid,
  add constraint fin_bank_tx_amount_nonzero_chk check (amount_cents <> 0) not valid;
create index fin_bank_tx_account_idx on fin_bank_transactions (bank_account_id, date);

alter table fin_bank_balances
  add column bank_account_id uuid,
  add column source text not null default 'provider' check (source in ('provider', 'manual', 'csv')),
  add constraint fin_bank_balances_account_fk foreign key (bank_account_id, merchant_id) references fin_bank_accounts (id, merchant_id);
comment on column fin_bank_balances.as_of is 'observed_at: when the bank said so. A balance is never "current": its age is part of what is shown.';

-- backfill of the NEW columns for rows that predate accounts (production is expected to hold none)
insert into fin_bank_accounts (merchant_id, external_id, origin, currency)
  select t.merchant_id, t.account_id, case when t.account_id = 'csv-import' then 'CSV' else 'PROVIDER' end, (array_agg(t.currency order by t.imported_at))[1] from fin_bank_transactions t group by t.merchant_id, t.account_id
  on conflict (merchant_id, external_id) do nothing;
insert into fin_bank_accounts (merchant_id, external_id, origin, currency)
  select b.merchant_id, b.account_id, 'PROVIDER', b.currency from fin_bank_balances b on conflict (merchant_id, external_id) do nothing;
update fin_bank_transactions t set bank_account_id = a.id from fin_bank_accounts a where a.merchant_id = t.merchant_id and a.external_id = t.account_id and t.bank_account_id is null;
update fin_bank_balances b set bank_account_id = a.id from fin_bank_accounts a where a.merchant_id = b.merchant_id and a.external_id = b.account_id and b.bank_account_id is null;

-- every transaction/balance is attached to an account of the SAME merchant and the SAME currency (the account is created on first sight: old callers keep working)
create function fin_bank_account_link() returns trigger language plpgsql as $$
declare acc fin_bank_accounts%rowtype;
begin
  if new.bank_account_id is null then
    insert into fin_bank_accounts (merchant_id, external_id, origin, currency)
      values (new.merchant_id, new.account_id, case when new.account_id = 'csv-import' then 'CSV' else 'PROVIDER' end, new.currency) on conflict (merchant_id, external_id) do nothing;
    select * into acc from fin_bank_accounts where merchant_id = new.merchant_id and external_id = new.account_id;
    new.bank_account_id := acc.id;
  else
    select * into acc from fin_bank_accounts where id = new.bank_account_id and merchant_id = new.merchant_id;
    if not found then raise exception 'FIN_BANK_ACCOUNT_NOT_FOUND'; end if;
    if acc.external_id <> new.account_id then raise exception 'FIN_BANK_ACCOUNT_MISMATCH: % vs %', acc.external_id, new.account_id; end if;
  end if;
  if acc.currency <> new.currency then raise exception 'FIN_BANK_CURRENCY_MISMATCH: account %, row %', acc.currency, new.currency; end if;
  return new;
end $$;
create trigger fin_bank_tx_account_link_trg before insert on fin_bank_transactions for each row execute function fin_bank_account_link();
create trigger fin_bank_balances_account_link_trg before insert or update on fin_bank_balances for each row execute function fin_bank_account_link();

-- ---------- reconciliations ----------
create table fin_bank_reconciliations (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references merchants(id),
  bank_transaction_id uuid not null,
  payment_id uuid,
  kind text not null check (kind in ('MATCH', 'IGNORE')),
  amount_cents bigint not null check (amount_cents <> 0),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  reverses_id uuid,
  method text not null default 'MANUAL' check (method in ('MANUAL', 'SUGGESTION_CONFIRMED')),
  suggestion jsonb,
  idempotency_key text not null check (length(idempotency_key) between 1 and 300),
  reason text,
  actor jsonb,
  created_at timestamptz not null default now(),
  constraint fin_bank_reconciliations_id_merchant_uq unique (id, merchant_id),
  constraint fin_bank_reconciliations_idempotency_uq unique (merchant_id, idempotency_key),
  constraint fin_bank_reconciliations_tx_fk foreign key (bank_transaction_id, merchant_id) references fin_bank_transactions (id, merchant_id),
  constraint fin_bank_reconciliations_payment_fk foreign key (payment_id, merchant_id) references fin_payment_registry (id, merchant_id),
  constraint fin_bank_reconciliations_reverses_fk foreign key (reverses_id, merchant_id) references fin_bank_reconciliations (id, merchant_id),
  constraint fin_bank_reconciliations_kind_chk check ((kind = 'MATCH') = (payment_id is not null)),
  constraint fin_bank_reconciliations_reversal_negative check ((amount_cents < 0) = (reverses_id is not null))
);
create index fin_bank_reconciliations_tx_idx on fin_bank_reconciliations (bank_transaction_id);
create index fin_bank_reconciliations_payment_idx on fin_bank_reconciliations (payment_id) where payment_id is not null;
create index fin_bank_reconciliations_reverses_idx on fin_bank_reconciliations (reverses_id) where reverses_id is not null;
create trigger fin_bank_reconciliations_append_only_trg before update or delete on fin_bank_reconciliations for each row execute function fin_append_only();
alter table fin_bank_reconciliations enable row level security;
revoke all on fin_bank_reconciliations from anon, authenticated;

-- the ONE definition of what is reconciled / ignored / left of a bank transaction
create function fin_bank_tx_amounts(p_merchant uuid, p_tx uuid) returns jsonb language sql stable as $$
  with t as (select abs(amount_cents) as abs_cents from fin_bank_transactions where id = p_tx and merchant_id = p_merchant),
  r as (select coalesce(sum(amount_cents) filter (where kind = 'MATCH'), 0) as matched, coalesce(sum(amount_cents) filter (where kind = 'IGNORE'), 0) as ignored, max(created_at) as last_at
        from fin_bank_reconciliations where bank_transaction_id = p_tx and merchant_id = p_merchant)
  select jsonb_build_object('amount', t.abs_cents, 'matched', r.matched, 'ignored', r.ignored, 'remaining', t.abs_cents - r.matched - r.ignored, 'last_at', r.last_at,
    'status', case when r.matched = 0 and r.ignored = 0 then 'UNRECONCILED' when t.abs_cents - r.matched - r.ignored = 0 and r.matched > 0 then 'RECONCILED' when t.abs_cents - r.matched - r.ignored = 0 then 'IGNORED' else 'PARTIALLY_RECONCILED' end)
  from t, r
$$;

create function fin_bank_reconciliation_guard() returns trigger language plpgsql as $$
declare tx fin_bank_transactions%rowtype; pay fin_payment_registry%rowtype; orig fin_bank_reconciliations%rowtype; am jsonb; pay_net bigint; pay_reversed bigint; orig_left bigint;
begin
  if new.payment_id is not null then
    select * into pay from fin_payment_registry where id = new.payment_id and merchant_id = new.merchant_id for update; -- 2: the payment
    if not found then raise exception 'FIN_PAYMENT_NOT_FOUND'; end if;
    if pay.reversal_of_id is not null then raise exception 'FIN_BANK_PAYMENT_IS_A_REVERSAL'; end if;
  end if;
  select * into tx from fin_bank_transactions where id = new.bank_transaction_id and merchant_id = new.merchant_id for update; -- 3: the bank transaction
  if not found then raise exception 'FIN_BANK_TX_NOT_FOUND'; end if;
  if new.currency <> tx.currency or (new.payment_id is not null and pay.currency <> tx.currency) then raise exception 'FIN_BANK_CURRENCY_MISMATCH: transaction %, payment %, row %', tx.currency, pay.currency, new.currency; end if;
  if new.payment_id is not null and ((tx.amount_cents > 0 and pay.direction <> 'IN') or (tx.amount_cents < 0 and pay.direction <> 'OUT')) then raise exception 'FIN_BANK_DIRECTION_MISMATCH: a % transaction cannot be reconciled with a % payment', tx.direction, pay.direction; end if;
  if new.amount_cents > 0 then
    am := fin_bank_tx_amounts(tx.merchant_id, tx.id);
    if new.amount_cents > (am ->> 'remaining')::bigint then raise exception 'FIN_BANK_OVER_RECONCILED: % > remaining % (cents)', new.amount_cents, (am ->> 'remaining')::bigint; end if;
    if new.payment_id is not null then
      select coalesce(sum(amount_cents), 0) into pay_net from fin_bank_reconciliations where payment_id = pay.id and merchant_id = pay.merchant_id;
      select coalesce(sum(amount_cents), 0) into pay_reversed from fin_payment_registry where reversal_of_id = pay.id and merchant_id = pay.merchant_id;
      if pay_net + new.amount_cents > pay.amount_cents - pay_reversed then raise exception 'FIN_BANK_PAYMENT_OVER_RECONCILED: % > what is left of the payment % (cents)', new.amount_cents, pay.amount_cents - pay_reversed - pay_net; end if;
    end if;
  else
    select * into orig from fin_bank_reconciliations where id = new.reverses_id and merchant_id = new.merchant_id;
    if not found or orig.amount_cents <= 0 then raise exception 'FIN_BANK_RECONCILIATION_NOT_FOUND'; end if;
    if orig.bank_transaction_id <> new.bank_transaction_id or orig.payment_id is distinct from new.payment_id or orig.kind <> new.kind or orig.currency <> new.currency then raise exception 'FIN_BANK_UNRECONCILE_MISMATCH'; end if;
    select orig.amount_cents + coalesce(sum(amount_cents), 0) into orig_left from fin_bank_reconciliations where reverses_id = orig.id and merchant_id = orig.merchant_id;
    if orig_left + new.amount_cents < 0 then raise exception 'FIN_BANK_UNRECONCILE_EXCEEDS: % > still reconciled % (cents)', -new.amount_cents, orig_left; end if;
  end if;
  return new;
end $$;
create trigger fin_bank_reconciliation_guard_trg before insert on fin_bank_reconciliations for each row execute function fin_bank_reconciliation_guard();

-- the legacy columns follow the reconciliation rows (never the other way round)
create function fin_bank_reconciliation_mirror() returns trigger language plpgsql as $$
declare am jsonb; st text;
begin
  am := fin_bank_tx_amounts(new.merchant_id, new.bank_transaction_id);
  st := case am ->> 'status' when 'RECONCILED' then 'MATCHED' when 'IGNORED' then 'IGNORED' else 'NEW' end;
  update fin_bank_transactions set status = st, matched_amount_cents = nullif((am ->> 'matched')::bigint, 0), matched_at = case when st = 'NEW' then null else (am ->> 'last_at')::timestamptz end where id = new.bank_transaction_id and merchant_id = new.merchant_id;
  return new;
end $$;
create trigger fin_bank_reconciliation_mirror_trg after insert on fin_bank_reconciliations for each row execute function fin_bank_reconciliation_mirror();

-- bank transaction guard: content immutable; status / matched_* are DERIVED and can only take the value the reconciliation rows imply (no last-writer-wins, no hand-written claim)
create or replace function fin_bank_tx_guard() returns trigger language plpgsql as $$
declare am jsonb; st text;
begin
  if tg_op = 'DELETE' then raise exception 'bank transactions are append-only'; end if;
  if new.merchant_id is distinct from old.merchant_id or new.account_id is distinct from old.account_id or new.provider_tx_id is distinct from old.provider_tx_id
     or new.date is distinct from old.date or new.amount_cents is distinct from old.amount_cents or new.reference is distinct from old.reference
     or new.currency is distinct from old.currency or new.value_date is distinct from old.value_date or new.fingerprint is distinct from old.fingerprint then
    raise exception 'bank transaction content is immutable';
  end if;
  if new.bank_account_id is distinct from old.bank_account_id and old.bank_account_id is not null then raise exception 'bank transaction content is immutable'; end if;
  if new.status is distinct from old.status or new.matched_kind is distinct from old.matched_kind or new.matched_document_id is distinct from old.matched_document_id
     or new.matched_payment_id is distinct from old.matched_payment_id or new.matched_amount_cents is distinct from old.matched_amount_cents or new.matched_at is distinct from old.matched_at then
    am := fin_bank_tx_amounts(new.merchant_id, new.id);
    st := case am ->> 'status' when 'RECONCILED' then 'MATCHED' when 'IGNORED' then 'IGNORED' else 'NEW' end;
    if new.matched_kind is distinct from old.matched_kind or new.matched_document_id is distinct from old.matched_document_id or new.matched_payment_id is distinct from old.matched_payment_id
       or new.status <> st or new.matched_amount_cents is distinct from nullif((am ->> 'matched')::bigint, 0)
       or new.matched_at is distinct from (case when st = 'NEW' then null else (am ->> 'last_at')::timestamptz end) then
      raise exception 'FIN_BANK_STATUS_IS_DERIVED: the status of a bank transaction follows its reconciliations; use reconcile / unreconcile / ignore';
    end if;
  end if;
  return new;
end $$;

-- a payment that is reconciled with the bank cannot be voided: unreconcile first (the bank link would otherwise point at money that no longer exists)
create or replace function fin_payment_registry_guard() returns trigger language plpgsql as $$
declare orig fin_payment_registry%rowtype; reversed bigint; allocated bigint; reconciled bigint;
begin
  if new.refund_of_payment_id is not null then
    select * into orig from fin_payment_registry where id = new.refund_of_payment_id and merchant_id = new.merchant_id;
    if not found then raise exception 'FIN_PAYMENT_NOT_FOUND'; end if;
    if orig.direction <> 'IN' or orig.reversal_of_id is not null or new.direction <> 'OUT' then raise exception 'FIN_REFUND_MISMATCH: a refund is an OUT payment giving back an IN payment'; end if;
    if orig.currency <> new.currency then raise exception 'FIN_CURRENCY_MISMATCH: refund %, original %', new.currency, orig.currency; end if;
  end if;
  if new.reversal_of_id is null then return new; end if;
  select * into orig from fin_payment_registry where id = new.reversal_of_id and merchant_id = new.merchant_id for update;
  if not found then raise exception 'FIN_PAYMENT_NOT_FOUND'; end if;
  if orig.reversal_of_id is not null then raise exception 'FIN_REVERSAL_OF_REVERSAL: a reversal cannot be reversed'; end if;
  if orig.direction <> new.direction or orig.currency <> new.currency then raise exception 'FIN_REVERSAL_MISMATCH: direction or currency differs from the original'; end if;
  select coalesce(sum(amount_cents), 0) into reversed from fin_payment_registry where reversal_of_id = orig.id and merchant_id = orig.merchant_id;
  if reversed + new.amount_cents > orig.amount_cents then
    raise exception 'FIN_REVERSAL_EXCEEDS_PAYMENT: reversal % > remaining % (cents)', new.amount_cents, orig.amount_cents - reversed;
  end if;
  select coalesce(sum(amount_cents), 0) into allocated from fin_payment_allocations where payment_id = orig.id and merchant_id = orig.merchant_id;
  if orig.amount_cents - reversed - new.amount_cents < allocated then
    raise exception 'FIN_REVERSAL_PAYMENT_ALLOCATED: % cents of this payment are still allocated; reverse the allocations first', allocated;
  end if;
  select coalesce(sum(amount_cents), 0) into reconciled from fin_bank_reconciliations where payment_id = orig.id and merchant_id = orig.merchant_id;
  if orig.amount_cents - reversed - new.amount_cents < reconciled then
    raise exception 'FIN_REVERSAL_PAYMENT_RECONCILED: % cents of this payment are reconciled with the bank; unreconcile first', reconciled;
  end if;
  return new;
end $$;

-- ---------- RPCs: one operation = one transaction; callable by the service role only ----------
-- fin_bank_reconcile: link a bank transaction to payments that ALREADY exist (e.g. recorded by hand). p_items: [{ "paymentId": uuid, "amountCents": n }]. Idempotent per (key, payment).
create function fin_bank_reconcile(p_merchant uuid, p_key text, p_tx uuid, p_items jsonb, p_suggestion jsonb, p_actor jsonb, p_at timestamptz default null) returns jsonb language plpgsql as $$
declare it record; prior fin_bank_reconciliations%rowtype; r fin_bank_reconciliations%rowtype; rows jsonb := '[]'::jsonb; dup boolean := false; fresh boolean := false; idem text;
begin
  if p_key is null or length(p_key) = 0 then raise exception 'FIN_IDEMPOTENCY_KEY_REQUIRED'; end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then raise exception 'FIN_AMOUNT_INVALID: nothing to reconcile'; end if;
  perform pg_advisory_xact_lock(hashtextextended('fin_bank_rec:' || p_merchant::text || ':' || p_key, 0)); -- same-key retries wait for the first outcome (taken before any row lock)
  if not exists (select 1 from fin_bank_transactions where id = p_tx and merchant_id = p_merchant) then raise exception 'FIN_BANK_TX_NOT_FOUND'; end if;
  for it in select (x ->> 'paymentId')::uuid as pid, (x ->> 'amountCents')::bigint as cents from jsonb_array_elements(p_items) x order by 1 loop -- ascending payment id = deterministic lock order
    if it.cents is null or it.cents <= 0 then raise exception 'FIN_AMOUNT_INVALID'; end if;
    idem := p_key || ':' || it.pid::text;
    select * into prior from fin_bank_reconciliations where merchant_id = p_merchant and idempotency_key = idem;
    if found then
      if prior.bank_transaction_id <> p_tx or prior.amount_cents <> it.cents then raise exception 'FIN_IDEMPOTENCY_KEY_REUSED: key % was used for a different reconciliation', p_key; end if;
      dup := true; rows := rows || to_jsonb(prior); continue;
    end if;
    insert into fin_bank_reconciliations (merchant_id, bank_transaction_id, payment_id, kind, amount_cents, currency, method, suggestion, idempotency_key, actor, created_at)
      select p_merchant, p_tx, it.pid, 'MATCH', it.cents, t.currency, case when p_suggestion is null then 'MANUAL' else 'SUGGESTION_CONFIRMED' end, p_suggestion, idem, p_actor, coalesce(p_at, now()) from fin_bank_transactions t where t.id = p_tx and t.merchant_id = p_merchant returning * into r;
    fresh := true; rows := rows || to_jsonb(r);
    insert into fin_events (merchant_id, document_id, at, actor, action, from_status, to_status, detail)
      values (p_merchant, null, coalesce(p_at, now()), p_actor, 'BANK_RECONCILE', null, null, jsonb_build_object('transactionId', p_tx, 'paymentId', it.pid, 'reconciliationId', r.id, 'amountCents', it.cents, 'method', r.method, 'suggestion', p_suggestion));
  end loop;
  return jsonb_build_object('duplicate', dup and not fresh, 'reconciliations', rows, 'transaction', fin_bank_tx_amounts(p_merchant, p_tx));
end $$;

-- fin_bank_reconcile_and_pay: ATOMIC. Creates the payment (through fin_record_payment: same ceilings, same idempotency, same audit) and the reconciliation in ONE transaction.
--   If the payment is refused (ceiling, currency, closed document...) NOTHING is written: the transaction is never left "claimed". A retry with the same key returns the committed operation.
--   p_payment: { amountCents, method, reference, allocations: [{customerDocumentId|supplierInvoiceId, amountCents}], meta: {...} } ; the direction comes from the sign of the bank transaction.
create function fin_bank_reconcile_and_pay(p_merchant uuid, p_key text, p_tx uuid, p_payment jsonb, p_suggestion jsonb, p_actor jsonb, p_at timestamptz default null) returns jsonb language plpgsql as $$
declare tx fin_bank_transactions%rowtype; pay jsonb; pid uuid; cents bigint; rec fin_bank_reconciliations%rowtype; idem text; rec_json jsonb;
begin
  if p_key is null or length(p_key) = 0 then raise exception 'FIN_IDEMPOTENCY_KEY_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended('fin_bank_rec:' || p_merchant::text || ':' || p_key, 0));
  select * into tx from fin_bank_transactions where id = p_tx and merchant_id = p_merchant;
  if not found then raise exception 'FIN_BANK_TX_NOT_FOUND'; end if;
  cents := (p_payment ->> 'amountCents')::bigint;
  if cents is null or cents <= 0 then raise exception 'FIN_AMOUNT_INVALID'; end if;
  pay := fin_record_payment(p_merchant, p_key, case when tx.amount_cents > 0 then 'IN' else 'OUT' end, cents, tx.currency, tx.date, coalesce(p_payment ->> 'method', 'bank_transfer'), p_payment ->> 'reference', p_actor,
    coalesce(p_payment -> 'allocations', '[]'::jsonb), p_at,
    coalesce(p_payment -> 'meta', '{}'::jsonb) || jsonb_build_object('source', 'bank', 'bankReference', tx.provider_tx_id, 'structuredReference', tx.structured_reference));
  pid := (pay -> 'payment' ->> 'id')::uuid; idem := p_key || ':' || pid::text;
  select * into rec from fin_bank_reconciliations where merchant_id = p_merchant and idempotency_key = idem;
  if found then
    if rec.bank_transaction_id <> p_tx then raise exception 'FIN_IDEMPOTENCY_KEY_REUSED: key % was used for another bank transaction', p_key; end if;
    return jsonb_build_object('duplicate', true, 'payment', pay -> 'payment', 'allocations', pay -> 'allocations', 'reconciliation', to_jsonb(rec), 'transaction', fin_bank_tx_amounts(p_merchant, p_tx));
  end if;
  insert into fin_bank_reconciliations (merchant_id, bank_transaction_id, payment_id, kind, amount_cents, currency, method, suggestion, idempotency_key, actor, created_at)
    values (p_merchant, p_tx, pid, 'MATCH', cents, tx.currency, case when p_suggestion is null then 'MANUAL' else 'SUGGESTION_CONFIRMED' end, p_suggestion, idem, p_actor, coalesce(p_at, now())) returning * into rec;
  insert into fin_events (merchant_id, document_id, at, actor, action, from_status, to_status, detail)
    values (p_merchant, null, coalesce(p_at, now()), p_actor, 'BANK_RECONCILE', null, null, jsonb_build_object('transactionId', p_tx, 'paymentId', pid, 'reconciliationId', rec.id, 'amountCents', cents, 'method', rec.method, 'suggestion', p_suggestion, 'createdPayment', true));
  return jsonb_build_object('duplicate', false, 'payment', pay -> 'payment', 'allocations', pay -> 'allocations', 'reconciliation', to_jsonb(rec), 'transaction', fin_bank_tx_amounts(p_merchant, p_tx));
end $$;

-- fin_bank_unreconcile: take a reconciliation back (all or part). Appends a negative row linked to the original; never deletes; the PAYMENT is untouched (void it separately if it was wrong).
--   p_items: [{ "reconciliationId": uuid, "amountCents": n | null (= everything still reconciled) }]. Idempotent per (key, reconciliation).
create function fin_bank_unreconcile(p_merchant uuid, p_key text, p_items jsonb, p_reason text, p_actor jsonb, p_at timestamptz default null) returns jsonb language plpgsql as $$
declare it record; orig fin_bank_reconciliations%rowtype; prior fin_bank_reconciliations%rowtype; r fin_bank_reconciliations%rowtype; left_cents bigint; amt bigint; rows jsonb := '[]'::jsonb; dup boolean := false; fresh boolean := false; idem text; tx uuid;
begin
  if p_key is null or length(p_key) = 0 then raise exception 'FIN_IDEMPOTENCY_KEY_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended('fin_bank_rec:' || p_merchant::text || ':' || p_key, 0));
  for it in select (x ->> 'reconciliationId')::uuid as id, (x ->> 'amountCents')::bigint as cents from jsonb_array_elements(p_items) x
            order by (select o.payment_id from fin_bank_reconciliations o where o.id = (x ->> 'reconciliationId')::uuid and o.merchant_id = p_merchant) nulls last loop
    select * into orig from fin_bank_reconciliations where id = it.id and merchant_id = p_merchant;
    if not found or orig.amount_cents <= 0 then raise exception 'FIN_BANK_RECONCILIATION_NOT_FOUND'; end if;
    idem := p_key || ':' || it.id::text;
    select * into prior from fin_bank_reconciliations where merchant_id = p_merchant and idempotency_key = idem;
    if found then
      if it.cents is not null and -prior.amount_cents <> it.cents then raise exception 'FIN_IDEMPOTENCY_KEY_REUSED: key % was used for a different unreconcile', p_key; end if;
      dup := true; rows := rows || to_jsonb(prior); tx := orig.bank_transaction_id; continue;
    end if;
    select orig.amount_cents + coalesce(sum(amount_cents), 0) into left_cents from fin_bank_reconciliations where reverses_id = orig.id and merchant_id = p_merchant;
    amt := coalesce(it.cents, left_cents);
    if amt <= 0 or amt > left_cents then raise exception 'FIN_BANK_UNRECONCILE_EXCEEDS: % > still reconciled % (cents)', amt, left_cents; end if;
    insert into fin_bank_reconciliations (merchant_id, bank_transaction_id, payment_id, kind, amount_cents, currency, reverses_id, method, idempotency_key, reason, actor, created_at)
      values (p_merchant, orig.bank_transaction_id, orig.payment_id, orig.kind, -amt, orig.currency, orig.id, 'MANUAL', idem, p_reason, p_actor, coalesce(p_at, now())) returning * into r;
    fresh := true; rows := rows || to_jsonb(r); tx := orig.bank_transaction_id;
    insert into fin_events (merchant_id, document_id, at, actor, action, from_status, to_status, detail)
      values (p_merchant, null, coalesce(p_at, now()), p_actor, case when orig.kind = 'IGNORE' then 'BANK_UNIGNORE' else 'BANK_UNRECONCILE' end, null, null,
        jsonb_build_object('transactionId', orig.bank_transaction_id, 'paymentId', orig.payment_id, 'reconciliationId', orig.id, 'reversalId', r.id, 'amountCents', amt, 'reason', p_reason));
  end loop;
  return jsonb_build_object('duplicate', dup and not fresh, 'reversals', rows, 'transaction', case when tx is null then null else fin_bank_tx_amounts(p_merchant, tx) end);
end $$;

-- fin_bank_ignore: set a transaction (or part of it) aside on purpose (bank fee already booked elsewhere, internal transfer...). Reversible through fin_bank_unreconcile.
create function fin_bank_ignore(p_merchant uuid, p_key text, p_tx uuid, p_amount bigint, p_reason text, p_actor jsonb, p_at timestamptz default null) returns jsonb language plpgsql as $$
declare tx fin_bank_transactions%rowtype; prior fin_bank_reconciliations%rowtype; r fin_bank_reconciliations%rowtype; amt bigint; am jsonb;
begin
  if p_key is null or length(p_key) = 0 then raise exception 'FIN_IDEMPOTENCY_KEY_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended('fin_bank_rec:' || p_merchant::text || ':' || p_key, 0));
  select * into prior from fin_bank_reconciliations where merchant_id = p_merchant and idempotency_key = p_key;
  if found then
    if prior.bank_transaction_id <> p_tx or prior.kind <> 'IGNORE' or (p_amount is not null and prior.amount_cents <> p_amount) then raise exception 'FIN_IDEMPOTENCY_KEY_REUSED: key % was used for a different request', p_key; end if;
    return jsonb_build_object('duplicate', true, 'reconciliation', to_jsonb(prior), 'transaction', fin_bank_tx_amounts(p_merchant, p_tx));
  end if;
  select * into tx from fin_bank_transactions where id = p_tx and merchant_id = p_merchant for update;
  if not found then raise exception 'FIN_BANK_TX_NOT_FOUND'; end if;
  am := fin_bank_tx_amounts(p_merchant, p_tx); amt := coalesce(p_amount, (am ->> 'remaining')::bigint);
  if amt <= 0 then raise exception 'FIN_BANK_OVER_RECONCILED: nothing left to set aside'; end if;
  insert into fin_bank_reconciliations (merchant_id, bank_transaction_id, payment_id, kind, amount_cents, currency, method, idempotency_key, reason, actor, created_at)
    values (p_merchant, p_tx, null, 'IGNORE', amt, tx.currency, 'MANUAL', p_key, p_reason, p_actor, coalesce(p_at, now())) returning * into r;
  insert into fin_events (merchant_id, document_id, at, actor, action, from_status, to_status, detail)
    values (p_merchant, null, coalesce(p_at, now()), p_actor, 'BANK_IGNORE', null, null, jsonb_build_object('transactionId', p_tx, 'reconciliationId', r.id, 'amountCents', amt, 'reason', p_reason));
  return jsonb_build_object('duplicate', false, 'reconciliation', to_jsonb(r), 'transaction', fin_bank_tx_amounts(p_merchant, p_tx));
end $$;

revoke execute on function fin_bank_reconcile(uuid, text, uuid, jsonb, jsonb, jsonb, timestamptz), fin_bank_reconcile_and_pay(uuid, text, uuid, jsonb, jsonb, jsonb, timestamptz), fin_bank_unreconcile(uuid, text, jsonb, text, jsonb, timestamptz),
  fin_bank_ignore(uuid, text, uuid, bigint, text, jsonb, timestamptz), fin_bank_tx_amounts(uuid, uuid) from public, anon, authenticated;
grant execute on function fin_bank_reconcile(uuid, text, uuid, jsonb, jsonb, jsonb, timestamptz), fin_bank_reconcile_and_pay(uuid, text, uuid, jsonb, jsonb, jsonb, timestamptz), fin_bank_unreconcile(uuid, text, jsonb, text, jsonb, timestamptz),
  fin_bank_ignore(uuid, text, uuid, bigint, text, jsonb, timestamptz), fin_bank_tx_amounts(uuid, uuid) to service_role;
