'use strict';
// Nederlands - Nordla Growth.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.nl = Object.assign(window.NORDLA_DICTS.nl || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.vsPrevious': 'vs vorige periode',
  'gr.nav.aria': 'Growth-navigatie',
  'gr.nav.overview': 'Overzicht',
  'gr.nav.opportunities': 'Kansen',
  'gr.nav.campaigns': 'Campagnes',
  'gr.nav.content': 'Content',
  'gr.nav.storeGrowth': 'Winkelgroei',
  'gr.nav.audience': 'Doelgroep',
  'gr.nav.experiments': 'Experimenten',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Instellingen',
  'gr.nav.soon': 'Binnenkort beschikbaar',
  'gr.demo': 'Demogegevens',
  'gr.demoShort': 'Demo',
  'gr.demoTitle': 'Er is nog geen Growth-bron gekoppeld: alle cijfers op deze pagina zijn voorbeelden.',
  'gr.period.last30': 'Laatste 30 dagen',
  'gr.period.fixed': 'Vast',
  'gr.period.fixedNote': 'De Growth-weergave toont de laatste 30 dagen.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Zet uw bedrijfsgegevens om in meetbare groeikansen.',
  'gr.kpi.revenueInfluenced': 'Beïnvloede omzet',
  'gr.kpi.activeOpportunities': 'Actieve kansen',
  'gr.kpi.highPriority': 'hoge prioriteit',
  'gr.kpi.activeCampaigns': 'Actieve campagnes',
  'gr.kpi.performingWell': 'presteren goed',
  'gr.kpi.roas': 'ROAS',
  'gr.kpi.experimentsRunning': 'Lopende experimenten',
  'gr.kpi.endingThisWeek': 'eindigt deze week',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Getoonde indicator',
  'gr.pulse.revenue': 'Omzet',
  'gr.pulse.traffic': 'Winkelbezoek',
  'gr.pulse.total': 'Totale omzet',
  'gr.pulse.influenced': 'Omzet beïnvloed door Growth',
  'gr.pulse.visitors': 'Winkelbezoekers',
  'gr.pulse.share': '{0} % beïnvloed door Growth',
  'gr.pulse.foot': 'Per dag, van {0} tot {1}. Omzet en bezoek hebben andere eenheden en worden apart getoond.',
  'gr.ai.title': 'Nordla AI-inzichten',
  'gr.ai.badge': 'Nordla AI',
  'gr.ai.foot': 'Nordla AI verklaart; de cijfers komen uit de rekenmotor.',
  'gr.att.title': 'Vraagt uw aandacht',
  'gr.att.status.pending': 'Goed te keuren',
  'gr.att.status.new': 'Nieuw',
  'gr.att.status.endingSoon': 'Loopt bijna af',
  'gr.att.action.approve': 'Bekijken',
  'gr.att.action.review': 'Bekijken',
  'gr.att.action.results': 'Resultaten',
  'gr.att.soon': 'Beschikbaar met de pagina Approvals (binnenkort)',
  'gr.ch.title': 'Prestaties per kanaal',
  'gr.ch.channel': 'Kanaal',
  'gr.ch.revenue': 'Omzet',
  'gr.ch.reach': 'Bezoeken / bereik',
  'gr.ch.conversion': 'Conversie',
  'gr.ch.roas': 'ROAS',
  'gr.ch.unit.visits': 'bezoeken',
  'gr.ch.unit.reach': 'bereik',
  'gr.ch.unit.actions': 'acties',
  'gr.ch.organic': 'organisch',
  'gr.ch.foot': 'ROAS = toegewezen omzet ÷ advertentie-uitgaven. „organisch” = kanaal zonder uitgaven.',
  'gr.camp.title': 'Campagnes',
  'gr.camp.activeCount': '{0} actief',
  'gr.camp.spend': '{0} besteed van {1}',
  'gr.camp.noBudget': 'Geen budget (organisch)',
  'gr.camp.status.performing': 'Presteert',
  'gr.camp.status.active': 'Actief',
  'gr.camp.status.watch': 'Opvolgen',
  'gr.camp.roas': 'ROAS {0}',
  'gr.camp.conversions': '{0} conversies',
  'gr.camp.actions': '{0} acties',
  'gr.content.title': 'Contentprestaties',
  'gr.content.kind.reel': 'Reel',
  'gr.content.kind.video': 'Video',
  'gr.content.kind.carousel': 'Carrousel',
  'gr.content.kind.post': 'Post',
  'gr.content.views': '{0} weergaven',
  'gr.content.perf.best': 'Best presterend',
  'gr.content.perf.good': 'Goed',
  'gr.content.perf.below': 'Onder gemiddeld',
  'gr.store.title': 'Winkelgroei',
  'gr.store.traffic': 'Winkelbezoek',
  'gr.store.conversion': 'Conversiegraad',
  'gr.store.revenue': 'Winkelomzet',
  'gr.store.pts': '{0} ptn',
  'gr.opp.title': 'Belangrijkste kansen',
  'gr.opp.source': 'Bron: {0}',
  'gr.opp.priority.high': 'Hoge prioriteit',
  'gr.opp.priority.medium': 'Gemiddelde prioriteit',
  'gr.opp.status.recommended': 'Aanbevolen',
  'gr.opp.status.review': 'Te bekijken',
  'gr.opp.status.planned': 'Gepland',
  'gr.opp.estimate': 'Geschatte omzet',
  'gr.opp.foot': 'Schattingen over 30 dagen, te valideren vóór elke actie.',
  'gr.exp.title': 'Experimenten',
  'gr.exp.kpi': 'Geteste KPI: {0}',
  'gr.exp.status.running': 'Loopt',
  'gr.exp.status.endingSoon': 'Loopt bijna af',
  'gr.exp.duration': '{0} dagen',
  'gr.exp.ends': 'Einde',
  'gr.noData': 'Gegevens niet beschikbaar',
  'gr.loadError': 'De Growth-weergave kon niet worden geladen.',
  'gr.op.title': 'Kansen',
  'gr.op.subtitle': 'Identificeer en prioriteer de meest veelbelovende groeihefbomen voor uw activiteit.',
  'gr.op.kpi.priority': 'Prioritaire kansen',
  'gr.op.kpi.highPriority': '{0} hoge prioriteit',
  'gr.op.kpi.potential': 'Potentiële omzet',
  'gr.op.kpi.active': '{0} actieve kansen',
  'gr.op.kpi.ready': 'Klaar voor goedkeuring',
  'gr.op.kpi.readyNote': 'Acties die kunnen starten',
  'gr.op.kpi.inProgress': 'Lopend',
  'gr.op.kpi.inProgressNote': 'Kansen in uitvoering',
  'gr.op.kpi.wins': 'Successen deze maand',
  'gr.op.kpi.winsNote': '{0} gegenereerd',
  'gr.op.pipe.title': 'Pijplijn van kansen',
  'gr.op.pipe.desc': 'Identificeer, prioriteer en volg de groeikansen die Nordla detecteert.',
  'gr.op.pipe.foot': '{0} kansen getoond · {1} potentiële omzet. Schattingen, te valideren vóór elke actie.',
  'gr.op.f.source': 'Bron',
  'gr.op.f.allSources': 'Alle bronnen',
  'gr.op.f.status': 'Status',
  'gr.op.f.allStatuses': 'Alle statussen',
  'gr.op.f.sort': 'Sortering',
  'gr.op.f.sort.priority': 'Sorteren op prioriteit',
  'gr.op.f.sort.revenue': 'Sorteren op potentiële omzet',
  'gr.op.f.sort.confidence': 'Sorteren op betrouwbaarheid',
  'gr.op.col.name': 'Kans',
  'gr.op.col.source': 'Bron',
  'gr.op.col.priority': 'Prioriteit',
  'gr.op.col.revenue': 'Potentiële omzet',
  'gr.op.col.confidence': 'Betrouwbaarheid',
  'gr.op.col.effort': 'Inspanning',
  'gr.op.col.status': 'Status',
  'gr.op.col.actions': 'Acties',
  'gr.op.actionsSoon': 'Acties binnenkort beschikbaar',
  'gr.op.noMatch': 'Geen kans komt overeen met deze filters.',
  'gr.op.src.store': 'Winkelanalyse',
  'gr.op.src.stock': 'Voorraad',
  'gr.op.src.market': 'Markttrend',
  'gr.op.src.ai': 'Nordla AI',
  'gr.op.src.customers': 'Klantgedrag',
  'gr.op.src.experiment': 'Winkelexperiment',
  'gr.op.src.seasonality': 'Seizoensgebondenheid',
  'gr.op.src.sales': 'Verkoop',
  'gr.op.src.local': 'Lokale gegevens',
  'gr.op.src.margin': 'Marges',
  'gr.op.status.ready': 'Klaar voor goedkeuring',
  'gr.op.status.inProgress': 'Lopend',
  'gr.op.status.analysis': 'Te analyseren',
  'gr.op.status.planned': 'Gepland',
  'gr.op.priority.high': 'Hoog',
  'gr.op.priority.medium': 'Gemiddeld',
  'gr.op.priority.low': 'Laag',
  'gr.op.effort.low': 'Laag',
  'gr.op.effort.medium': 'Gemiddeld',
  'gr.op.effort.high': 'Hoog',
  'gr.op.ai.title': 'Aanbevelingen Nordla AI',
  'gr.op.ai.potential': 'Potentiële omzet',
  'gr.op.ai.confidence': 'betrouwbaarheid {0}',
  'gr.op.mx.title': 'Impact vs inspanning',
  'gr.op.mx.impact': 'Impact',
  'gr.op.mx.effortLow': 'Lage inspanning',
  'gr.op.mx.effortHigh': 'Gemiddelde tot hoge inspanning',
  'gr.op.mx.highLow': 'Hoge impact · lage inspanning',
  'gr.op.mx.highHigh': 'Hoge impact · hoge inspanning',
  'gr.op.mx.lowLow': 'Lage impact · lage inspanning',
  'gr.op.mx.lowHigh': 'Lage impact · hoge inspanning',
  'gr.op.mx.foot': 'De {0} prioritaire kansen, geplaatst volgens geschatte impact en inspanning.',
  'gr.op.appr.title': 'Vraagt uw goedkeuring',
  'gr.op.appr.budget': 'Voorgesteld budget {0}',
  'gr.op.appr.expected': 'verwachte omzet {0}',
  'gr.op.appr.approve': 'Goedkeuren',
  'gr.op.appr.soon': 'De goedkeuringsworkflow is nog niet beschikbaar',
  'gr.op.appr.foot': 'Er wordt geen actie gestart zonder uw beslissing.',
  'gr.op.seg.title': 'Segmenten met hoog potentieel',
  'gr.op.seg.foot': 'Geschatte groei van het potentieel per segment.',
  'gr.op.wins.title': 'Recente successen',
  'gr.op.wins.target': 'Doel {0} · {1} behaald',
  'gr.op.bySource.title': 'Potentiële omzet per bron',
  'gr.op.bySource.total': 'potentieel',
  'gr.op.bySource.others': 'Overige ({0})',
  'gr.op.bySource.foot': '{0} verdeeld over {1} bronnen; de kleinste zijn gegroepeerd.',
  'gr.op.byStatus.title': 'Pijplijn per status',
  'gr.op.byStatus.count': '{0} kansen',
  'gr.op.byStatus.foot': '{0} kansen · {1} potentiële omzet.',
  'gr.cp.title': 'Campagnes',
  'gr.cp.subtitle': 'Maak, volg en optimaliseer uw marketingcampagnes op al uw kanalen.',
  'gr.cp.kpi.revenue': 'Gegenereerde omzet',
  'gr.cp.kpi.clicks': 'Klikken',
  'gr.cp.kpi.newCustomers': 'Nieuwe klanten',
  'gr.cp.kpi.roas': 'Gemiddelde ROAS',
  'gr.cp.table.title': 'Campagnes ({0})',
  'gr.cp.table.foot': '{0} van {1} campagnes getoond. Prestatie = resultaat ten opzichte van het campagnedoel.',
  'gr.cp.search': 'Een campagne zoeken…',
  'gr.cp.f.channel': 'Kanaal',
  'gr.cp.f.allChannels': 'Alle kanalen',
  'gr.cp.f.status': 'Status',
  'gr.cp.f.allStatuses': 'Alle statussen',
  'gr.cp.new': '+ Nieuwe campagne',
  'gr.cp.newSoon': 'Campagnes aanmaken is nog niet beschikbaar',
  'gr.cp.noMatch': 'Geen campagne komt overeen met deze zoekopdracht.',
  'gr.cp.col.campaign': 'Campagne',
  'gr.cp.col.channel': 'Kanaal',
  'gr.cp.col.objective': 'Doel',
  'gr.cp.col.period': 'Periode',
  'gr.cp.col.budget': 'Budget',
  'gr.cp.col.status': 'Status',
  'gr.cp.col.performance': 'Prestatie',
  'gr.cp.status.running': 'Lopend',
  'gr.cp.status.ready': 'Klaar om te starten',
  'gr.cp.status.planned': 'Gepland',
  'gr.cp.objective.sales': 'Verkoop',
  'gr.cp.objective.awareness': 'Naamsbekendheid',
  'gr.cp.objective.storeTraffic': 'Winkelbezoek',
  'gr.cp.objective.retention': 'Klantbehoud',
  'gr.cp.objective.recruitment': 'Rekrutering',
  'gr.cp.actions.title': 'Prioritaire acties',
  'gr.cp.channels.title': 'Prestaties per kanaal',
  'gr.cp.channels.foot': 'Aandeel van de gegenereerde omzet ({0}) per kanaal.',
  'gr.cp.trend.title': 'Omzet vs uitgaven — laatste 30 dagen',
  'gr.cp.trend.revenue': 'Omzet',
  'gr.cp.trend.spend': 'Uitgaven',
  'gr.cp.trend.roas': 'ROAS {0}',
  'gr.cp.trend.foot': 'Per dag, van {0} tot {1}: omzet toegewezen aan campagnes en advertentie-uitgaven.',
  'gr.cp.f.sort': 'Sortering',
  'gr.cp.f.sort.default': 'Standaardvolgorde',
  'gr.cp.f.sort.budget': 'Sorteren op budget',
  'gr.cp.f.sort.performance': 'Sorteren op prestatie',
  'gr.cp.perfNone': 'Nog niet gestart: geen prestatie gemeten',
  'gr.cp.channels.spendRoas': '{0} uitgegeven · ROAS {1}',
  'gr.cp.channels.noSpend': 'Zonder uitgaven',
  // Potentiel produits
  'gr.nav.potential': 'Productpotentieel',
  'gr.period.lastWeeks': 'Laatste {0} weken',
  'gr.period.weeksNote': 'Analyse over de laatste {0} volledige weken.',
  'gr.pp.title': 'Productpotentieel',
  'gr.pp.subtitle': 'Zie welke producten u kunt pushen, opvolgen of beschermen op basis van vraag, voorraad en rendabiliteit.',
  'gr.pp.days': '{0} d',
  'gr.pp.unit1': '{0} eenheid verkocht',
  'gr.pp.uN': '{0} eenheden',
  'gr.pp.u1': '{0} eenheid',
  'gr.pp.units': '{0} eenheden verkocht',
  'gr.pp.noImage': 'Geen gesynchroniseerde afbeelding',
  'gr.pp.noCategory': 'Zonder categorie',
  'gr.pp.openDetail': 'Details bekijken: {0}',
  'gr.pp.close': 'Sluiten',
  'gr.pp.kpi.active': 'Actieve producten',
  'gr.pp.kpi.activeNote': 'Verkocht in de laatste {0} weken',
  'gr.pp.kpi.push': 'Te pushen producten',
  'gr.pp.kpi.pushNote': '{0} van de verkoop in de periode',
  'gr.pp.kpi.pushNone': 'Geen enkel voldoet aan alle voorwaarden',
  'gr.pp.kpi.watch': 'Op te volgen',
  'gr.pp.kpi.watchNote': 'Daling, lage marge, retouren of tegenstrijdig signaal',
  'gr.pp.kpi.restock': 'Eerst aanvullen, dan promoten',
  'gr.pp.kpi.restockNote': 'Goede vraag, te weinig voorraad',
  'gr.pp.list.title': 'Producten',
  'gr.pp.list.desc': 'Elk product verkocht in de laatste {0} weken, met zijn Growth-status en het signaal dat die verklaart.',
  'gr.pp.list.foot': '{0} van {1} producten getoond',
  'gr.pp.quality.stock': 'Laatste voorraadmeting: {0} (gebruikt als ze jonger is dan {1} u)',
  'gr.pp.quality.noStock': 'Geen gesynchroniseerde voorraadmeting',
  'gr.pp.search': 'Product zoeken',
  'gr.pp.noMatch': 'Geen enkel product komt overeen met deze filters.',
  'gr.pp.empty.title': 'Geen product verkocht in de periode',
  'gr.pp.empty.text': 'Geen gesynchroniseerde verkoop in de laatste {0} weken: voorlopig niets aan te bevelen.',
  'gr.pp.f.aria': 'Filteren op Growth-status',
  'gr.pp.f.all': 'Alle',
  'gr.pp.f.push': 'Pushen',
  'gr.pp.f.growth': 'Sterke groei',
  'gr.pp.f.top': 'Bestsellers',
  'gr.pp.f.watch': 'Op te volgen',
  'gr.pp.f.restock': 'Eerst aanvullen',
  'gr.pp.f.lowMargin': 'Lage marge',
  'gr.pp.f.insufficient': 'Onvoldoende gegevens',
  'gr.pp.f.category': 'Categorie',
  'gr.pp.f.allCategories': 'Alle categorieën',
  'gr.pp.f.sort': 'Sorteren',
  'gr.pp.f.sort.sales': 'Sorteren op verkoop',
  'gr.pp.f.sort.evolution': 'Sorteren op evolutie',
  'gr.pp.f.sort.cover': 'Sorteren op dekking',
  'gr.pp.f.sort.margin': 'Sorteren op marge',
  'gr.pp.col.product': 'Product',
  'gr.pp.col.sales': 'Verkoop',
  'gr.pp.col.evolution': 'Evolutie',
  'gr.pp.col.margin': 'Marge',
  'gr.pp.col.stock': 'Voorraad',
  'gr.pp.col.cover': 'Dekking',
  'gr.pp.col.status': 'Status · signaal',
  'gr.pp.evo.insufficient': 'Onvoldoende historiek',
  'gr.pp.trend.UP': 'Stijgend',
  'gr.pp.trend.DOWN': 'Dalend',
  'gr.pp.trend.FLAT': 'Stabiel',
  'gr.pp.margin.MISSING': 'Kostprijs ontbreekt',
  'gr.pp.margin.PARTIAL': 'Gedeeltelijke marge',
  'gr.pp.margin.UNVERIFIED': 'Kostprijs niet geverifieerd',
  'gr.pp.margin.RELIABLE': 'Kostprijs geverifieerd',
  'gr.pp.stock.stale': 'Oude meting',
  'gr.pp.stock.unavailable': 'Voorraad onbekend',
  'gr.pp.cover.OUT': 'Uitverkocht',
  'gr.pp.cover.STOCK_UNUSABLE': 'Dekking niet berekend: voorraad onbekend of meting te oud.',
  'gr.pp.cover.INSUFFICIENT_HISTORY': 'Dekking niet berekend: onvoldoende verkoophistoriek.',
  'gr.pp.cover.INSUFFICIENT_SALES_SAMPLE': 'Dekking niet berekend: te weinig verkoop om een ritme te schatten.',
  'gr.pp.cover.NO_DEMAND_OBSERVED': 'Dekking niet berekend: geen vraag waargenomen.',
  'gr.pp.cover.NO_STOCK': 'Voorraad op.',
  'gr.pp.cover.UNKNOWN': 'Dekking niet berekend.',
  'gr.pp.status.push': 'Pushen',
  'gr.pp.status.restock': 'Eerst aanvullen',
  'gr.pp.status.topSeller': 'Topverkoper',
  'gr.pp.status.watch': 'Opvolgen',
  'gr.pp.status.declining': 'Dalend',
  'gr.pp.status.lowMargin': 'Lage marge',
  'gr.pp.status.returns': 'Te veel retouren',
  'gr.pp.status.insufficient': 'Onvoldoende gegevens',
  'gr.pp.status.stable': 'Stabiel',
  'gr.pp.signal.newProduct': 'Nieuw product: minder dan {0} weken verkoop',
  'gr.pp.signal.thinSample': '{0}: te kleine steekproef',
  'gr.pp.signal.outOfStock': 'Vraag aanwezig, voorraad op',
  'gr.pp.signal.coverDays': 'Voorraad voor slechts {0} dagen',
  'gr.pp.signal.returnRate': '{0} van de eenheden terugbetaald',
  'gr.pp.signal.margin': 'Geverifieerde marge van {0}',
  'gr.pp.signal.evolution': '{0} t.o.v. vorige {1} w.',
  'gr.pp.signal.topRank': 'Nr. {0} in verkoop over de periode',
  'gr.pp.signal.none': 'Geen bijzonder signaal',
  'gr.pp.action.increaseVisibility': 'Zichtbaarheid verhogen',
  'gr.pp.action.restockFirst': 'Eerst aanvullen',
  'gr.pp.action.doNotPromote': 'Niet promoten',
  'gr.pp.action.reviewReturns': 'Retouren analyseren',
  'gr.pp.action.checkCost': 'Kostprijs controleren',
  'gr.pp.action.checkStock': 'Voorraad controleren',
  'gr.pp.action.watch': 'Opvolgen',
  'gr.pp.action.keep': 'Beschikbaar houden',
  'gr.pp.action.none': 'Geen actie',
  'gr.pp.actionText.increaseVisibility': 'Geef het meer zichtbaarheid: in de webshop, in de etalage of in een volgende campagne. Voorraad en marge kunnen volgen.',
  'gr.pp.actionText.restockFirst': 'Vul eerst aan vóór elke promotie: nu promoten zou vooral tot tekorten leiden.',
  'gr.pp.actionText.doNotPromote': 'Geen geld aan zichtbaarheid voor dit product zolang marge of retouren niet opgelost zijn.',
  'gr.pp.actionText.reviewReturns': 'Bekijk de redenen van terugbetaling (kwaliteit, maat, beschrijving) voordat u het meer zichtbaarheid geeft.',
  'gr.pp.actionText.checkCost': 'De vraag stijgt maar de marge is niet betrouwbaar: vul de aankoopprijs in of controleer ze om te weten of pushen rendabel is.',
  'gr.pp.actionText.checkStock': 'De vraag stijgt maar de voorraad is niet zeker gekend: controleer ze vóór elke promotie.',
  'gr.pp.actionText.watch': 'Geen onmiddellijke actie: volg de evolutie de komende weken op.',
  'gr.pp.actionText.keep': 'Houd het beschikbaar en zichtbaar zoals nu; extra promotie is niet nodig.',
  'gr.pp.actionText.none': 'Niet genoeg gegevens om een actie aan te bevelen: Nordla wacht op meer verkoop.',
  'gr.pp.reason.COST_MISSING': 'Kostprijs ontbreekt',
  'gr.pp.reason.MARGIN_PARTIAL': 'Gedeeltelijke marge',
  'gr.pp.reason.COST_UNVERIFIED': 'Kostprijs niet geverifieerd',
  'gr.pp.reason.STOCK_STALE': 'Oude voorraadmeting',
  'gr.pp.reason.STOCK_UNAVAILABLE': 'Voorraad onbekend',
  'gr.pp.reason.COVER_UNKNOWN': 'Dekking niet berekenbaar',
  'gr.pp.reason.HIGH_RETURNS': 'Te veel retouren',
  'gr.pp.reason.RETURNS_ELEVATED': 'Hoge retouren',
  'gr.pp.reason.TREND_INSUFFICIENT': 'Onvoldoende historiek',
  'gr.pp.push.title': 'Te pushen producten',
  'gr.pp.push.none': 'Geen enkel product voldoet vandaag aan de vier voorwaarden om te pushen:',
  'gr.pp.push.cond.demand': 'stijgende vraag;',
  'gr.pp.push.cond.cover': 'gekende voorraad voor minstens {0} weken;',
  'gr.pp.push.cond.cost': 'geverifieerde aankoopprijs (betrouwbare marge);',
  'gr.pp.push.cond.returns': 'retouren hoogstens {0}.',
  'gr.pp.push.foot': 'Stijgende vraag, voldoende voorraad, geverifieerde kostprijs en normale retouren.',
  'gr.pp.protect.title': 'Beschermen / niet pushen',
  'gr.pp.protect.none': 'Voorlopig geen product om te beschermen.',
  'gr.pp.protect.foot': 'Aanvullen, retouren, lage marge, tegenstrijdige signalen of daling.',
  'gr.pp.byStatus.title': 'Producten per Growth-status',
  'gr.pp.byStatus.foot': '{0} actieve producten ingedeeld',
  'gr.pp.d.why': 'Waarom deze status',
  'gr.pp.d.evidence': 'Bewijzen (laatste {0} weken)',
  'gr.pp.d.action': 'Aanbevolen actie',
  'gr.pp.d.opportunity': 'Kans aanmaken',
  'gr.pp.d.opportunitySoon': 'Binnenkort: dit product toevoegen aan de Growth-kansen.',
  'gr.pp.d.method': 'Status berekend op basis van de in Nordla gesynchroniseerde verkoop, voorraad, kostprijzen en terugbetalingen. Onbekende gegevens tellen nooit als nul.',
  'gr.pp.ev.sales': 'Netto verkoop excl. btw',
  'gr.pp.ev.salesNote': 'Nr. {0} van de periode',
  'gr.pp.ev.units': 'Verkochte eenheden',
  'gr.pp.ev.velocity': 'gemiddeld {0} per week',
  'gr.pp.ev.evoNote': '{0} st. tegen {1} st. ({2} w. vs {2} w.)',
  'gr.pp.ev.evoNone': 'Minstens {0} weken verkoop nodig om te vergelijken.',
  'gr.pp.ev.snapshot': 'Meting van {0}',
  'gr.pp.ev.snapshotOld': 'Laatste meting op {0}: te oud om te beslissen',
  'gr.pp.ev.noSnapshot': 'Geen gesynchroniseerde voorraadmeting',
  'gr.pp.ev.coverNote': 'Aanvuldrempel: {0} weken',
  'gr.pp.ev.refunds': 'Terugbetalingen',
  'gr.pp.ev.refundNote': 'Terugbetaalde eenheden: {0}',
  'gr.pp.ev.history': 'Waargenomen historiek',
  'gr.pp.ev.weeks': '{0} w.',
  'gr.pp.rule.NEW_PRODUCT': 'Dit product heeft slechts {0} weken waargenomen verkoop; er zijn er minstens {1} nodig voor een aanbeveling.',
  'gr.pp.rule.THIN_SAMPLE': '{0} in {2} weken: er zijn er minstens {1} nodig om te besluiten.',
  'gr.pp.rule.DEMAND_BUT_OUT_OF_STOCK': 'De vraag is goed maar de voorraad is op: promoten zou klanten naar een tekort sturen.',
  'gr.pp.rule.DEMAND_BUT_LOW_COVER': 'De vraag is goed maar de voorraad dekt slechts {0} dagen (minder dan {1} weken): eerst aanvullen vóór elke promotie.',
  'gr.pp.rule.DEMAND_BUT_HIGH_RETURNS': 'De vraag is goed, maar {0} van de verkochte eenheden werd terugbetaald: eerst begrijpen, dan pushen.',
  'gr.pp.rule.HIGH_RETURNS': '{0} van de verkochte eenheden werd terugbetaald (drempel: {1}).',
  'gr.pp.rule.LOW_RELIABLE_MARGIN': 'Betrouwbare marge van {0}, onder de drempel van {1}: elke extra verkoop levert weinig op.',
  'gr.pp.rule.TREND_DOWN': 'De verkoop van de laatste {0} weken daalt ten opzichte van de {0} vorige ({1} st. tegen {2} st.).',
  'gr.pp.rule.PUSH': 'Stijgende vraag ({0} st. tegen {1} st. over {2} weken), voldoende voorraad, geverifieerde kostprijs en normale retouren: het product kan meer zichtbaarheid aan.',
  'gr.pp.rule.BLOCKED': 'De vraag stijgt ({0} st. tegen {1} st. over {2} weken), maar er ontbreekt een voorwaarde om te pushen: {3}.',
  'gr.pp.blocked.checkStock': 'voorraad onbekend of meting te oud',
  'gr.pp.blocked.checkCost': 'aankoopprijs niet geverifieerd',
  'gr.pp.blocked.reviewReturns': 'retouren boven {0}',
  'gr.pp.blocked.watch': 'voorraaddekking niet berekenbaar',
  'gr.pp.rule.TOP_SELLER': 'Nr. {0} in verkoop over de periode, zonder nieuw stijgend signaal: beschikbaar houden volstaat.',
  'gr.pp.rule.TOP_SELLER_RETURNS': 'Topverkoper, maar {0} van de verkochte eenheden werd terugbetaald (meer dan {1}): begrijp deze retouren vóór elke aanvulling of promotie.',
  'gr.pp.rule.NO_SIGNAL': 'Regelmatige verkoop, zonder signaal van stijging, daling of risico.',
});
