'use strict';
// English - Nordla Growth.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.en = Object.assign(window.NORDLA_DICTS.en || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.vsPrevious': 'vs previous period',
  'gr.nav.aria': 'Growth navigation',
  'gr.nav.overview': 'Overview',
  'gr.nav.opportunities': 'Opportunities',
  'gr.nav.campaigns': 'Campaigns',
  'gr.nav.content': 'Content',
  'gr.nav.storeGrowth': 'Store Growth',
  'gr.nav.audience': 'Audience',
  'gr.nav.experiments': 'Experiments',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Settings',
  'gr.nav.soon': 'Coming soon',
  'gr.demo': 'Demo data',
  'gr.demoShort': 'Demo',
  'gr.demoTitle': 'No Growth source is connected yet: every figure on this page is an example.',
  'gr.period.last30': 'Last 30 days',
  'gr.period.fixed': 'Fixed',
  'gr.period.fixedNote': 'The Growth view shows the last 30 days.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Turn your business data into measurable growth opportunities.',
  'gr.kpi.revenueInfluenced': 'Revenue influenced',
  'gr.kpi.activeOpportunities': 'Active opportunities',
  'gr.kpi.highPriority': 'high priority',
  'gr.kpi.activeCampaigns': 'Active campaigns',
  'gr.kpi.performingWell': 'performing well',
  'gr.kpi.roas': 'ROAS',
  'gr.kpi.experimentsRunning': 'Experiments running',
  'gr.kpi.endingThisWeek': 'ends this week',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Metric shown',
  'gr.pulse.revenue': 'Revenue',
  'gr.pulse.traffic': 'Store traffic',
  'gr.pulse.total': 'Total revenue',
  'gr.pulse.influenced': 'Revenue influenced by Growth',
  'gr.pulse.visitors': 'Store visitors',
  'gr.pulse.share': '{0}% influenced by Growth',
  'gr.pulse.foot': 'Daily, {0} to {1}. Revenue and traffic have different units, so they are shown separately.',
  'gr.ai.title': 'Nordla AI insights',
  'gr.ai.badge': 'Nordla AI',
  'gr.ai.foot': 'Nordla AI explains; the figures come from the calculation engine.',
  'gr.att.title': 'Needs your attention',
  'gr.att.status.pending': 'To approve',
  'gr.att.status.new': 'New',
  'gr.att.status.endingSoon': 'Ending soon',
  'gr.att.action.approve': 'Review',
  'gr.att.action.review': 'Review',
  'gr.att.action.results': 'Results',
  'gr.att.soon': 'Available with the Approvals page (coming soon)',
  'gr.ch.title': 'Channel performance',
  'gr.ch.channel': 'Channel',
  'gr.ch.revenue': 'Revenue',
  'gr.ch.reach': 'Visits / reach',
  'gr.ch.conversion': 'Conversion',
  'gr.ch.roas': 'ROAS',
  'gr.ch.unit.visits': 'visits',
  'gr.ch.unit.reach': 'reach',
  'gr.ch.unit.actions': 'actions',
  'gr.ch.organic': 'organic',
  'gr.ch.foot': 'ROAS = attributed revenue ÷ ad spend. “organic” = channel with no spend.',
  'gr.camp.title': 'Campaigns',
  'gr.camp.activeCount': '{0} active',
  'gr.camp.spend': '{0} spent of {1}',
  'gr.camp.noBudget': 'No budget (organic)',
  'gr.camp.status.performing': 'Performing',
  'gr.camp.status.active': 'Active',
  'gr.camp.status.watch': 'Watch',
  'gr.camp.roas': 'ROAS {0}',
  'gr.camp.conversions': '{0} conversions',
  'gr.camp.actions': '{0} actions',
  'gr.content.title': 'Content performance',
  'gr.content.kind.reel': 'Reel',
  'gr.content.kind.video': 'Video',
  'gr.content.kind.carousel': 'Carousel',
  'gr.content.kind.post': 'Post',
  'gr.content.views': '{0} views',
  'gr.content.perf.best': 'Best performer',
  'gr.content.perf.good': 'Good',
  'gr.content.perf.below': 'Below average',
  'gr.store.title': 'Store growth',
  'gr.store.traffic': 'Store traffic',
  'gr.store.conversion': 'Conversion rate',
  'gr.store.revenue': 'In-store revenue',
  'gr.store.pts': '{0} pts',
  'gr.opp.title': 'Top opportunities',
  'gr.opp.source': 'Source: {0}',
  'gr.opp.priority.high': 'High priority',
  'gr.opp.priority.medium': 'Medium priority',
  'gr.opp.status.recommended': 'Recommended',
  'gr.opp.status.review': 'To review',
  'gr.opp.status.planned': 'Planned',
  'gr.opp.estimate': 'Estimated revenue',
  'gr.opp.foot': '30-day estimates, to be validated before any action.',
  'gr.exp.title': 'Experiments',
  'gr.exp.kpi': 'KPI tested: {0}',
  'gr.exp.status.running': 'Running',
  'gr.exp.status.endingSoon': 'Ending soon',
  'gr.exp.duration': '{0} days',
  'gr.exp.ends': 'Ends',
  'gr.noData': 'Data unavailable',
  'gr.loadError': 'The Growth view could not be loaded.',
  'gr.op.title': 'Opportunities',
  'gr.op.subtitle': 'Identify and prioritise the most promising growth levers for your business.',
  'gr.op.kpi.priority': 'Priority opportunities',
  'gr.op.kpi.highPriority': '{0} high priority',
  'gr.op.kpi.potential': 'Potential revenue',
  'gr.op.kpi.active': '{0} active opportunities',
  'gr.op.kpi.ready': 'Ready to approve',
  'gr.op.kpi.readyNote': 'Actions that can be launched',
  'gr.op.kpi.inProgress': 'In progress',
  'gr.op.kpi.inProgressNote': 'Opportunities being executed',
  'gr.op.kpi.wins': 'Wins this month',
  'gr.op.kpi.winsNote': '{0} generated',
  'gr.op.pipe.title': 'Opportunity pipeline',
  'gr.op.pipe.desc': 'Identify, prioritise and track the growth opportunities Nordla detects.',
  'gr.op.pipe.foot': '{0} opportunities shown · {1} potential revenue. Estimates, to be validated before any action.',
  'gr.op.f.source': 'Source',
  'gr.op.f.allSources': 'All sources',
  'gr.op.f.status': 'Status',
  'gr.op.f.allStatuses': 'All statuses',
  'gr.op.f.sort': 'Sort',
  'gr.op.f.sort.priority': 'Sort by priority',
  'gr.op.f.sort.revenue': 'Sort by potential revenue',
  'gr.op.f.sort.confidence': 'Sort by confidence',
  'gr.op.col.name': 'Opportunity',
  'gr.op.col.source': 'Source',
  'gr.op.col.priority': 'Priority',
  'gr.op.col.revenue': 'Potential revenue',
  'gr.op.col.confidence': 'Confidence',
  'gr.op.col.effort': 'Effort',
  'gr.op.col.status': 'Status',
  'gr.op.col.actions': 'Actions',
  'gr.op.actionsSoon': 'Actions coming soon',
  'gr.op.noMatch': 'No opportunity matches these filters.',
  'gr.op.src.store': 'Store analysis',
  'gr.op.src.stock': 'Stock',
  'gr.op.src.market': 'Market trend',
  'gr.op.src.ai': 'Nordla AI',
  'gr.op.src.customers': 'Customer behaviour',
  'gr.op.src.experiment': 'Store experiment',
  'gr.op.src.seasonality': 'Seasonality',
  'gr.op.src.sales': 'Sales',
  'gr.op.src.local': 'Local data',
  'gr.op.src.margin': 'Margins',
  'gr.op.status.ready': 'Ready to approve',
  'gr.op.status.inProgress': 'In progress',
  'gr.op.status.analysis': 'Analysis',
  'gr.op.status.planned': 'Planned',
  'gr.op.priority.high': 'High',
  'gr.op.priority.medium': 'Medium',
  'gr.op.priority.low': 'Low',
  'gr.op.effort.low': 'Low',
  'gr.op.effort.medium': 'Medium',
  'gr.op.effort.high': 'High',
  'gr.op.ai.title': 'Nordla AI recommendations',
  'gr.op.ai.potential': 'Potential revenue',
  'gr.op.ai.confidence': 'confidence {0}',
  'gr.op.mx.title': 'Impact vs effort',
  'gr.op.mx.impact': 'Impact',
  'gr.op.mx.effortLow': 'Low effort',
  'gr.op.mx.effortHigh': 'Medium to high effort',
  'gr.op.mx.highLow': 'High impact · low effort',
  'gr.op.mx.highHigh': 'High impact · high effort',
  'gr.op.mx.lowLow': 'Low impact · low effort',
  'gr.op.mx.lowHigh': 'Low impact · high effort',
  'gr.op.mx.foot': 'The {0} priority opportunities, placed by estimated impact and effort.',
  'gr.op.appr.title': 'Needs your approval',
  'gr.op.appr.budget': 'Proposed budget {0}',
  'gr.op.appr.expected': 'expected revenue {0}',
  'gr.op.appr.approve': 'Approve',
  'gr.op.appr.soon': 'The approval workflow is not available yet',
  'gr.op.appr.foot': 'No action is launched without your decision.',
  'gr.op.seg.title': 'High-potential segments',
  'gr.op.seg.foot': 'Estimated potential growth per segment.',
  'gr.op.wins.title': 'Recent wins',
  'gr.op.wins.target': 'Target {0} · {1} reached',
});
