'use strict';
// Français - langue par défaut de Nordla Growth (même runtime NORDLA_I18N qu'Analytics Premium).
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.fr = Object.assign(window.NORDLA_DICTS.fr || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.vsPrevious': 'vs période précédente',
  'gr.nav.aria': 'Navigation Growth',
  'gr.nav.overview': 'Vue d’ensemble',
  'gr.nav.opportunities': 'Opportunités',
  'gr.nav.campaigns': 'Campagnes',
  'gr.nav.content': 'Contenu',
  'gr.nav.storeGrowth': 'Croissance magasin',
  'gr.nav.audience': 'Audience',
  'gr.nav.experiments': 'Expériences',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Paramètres',
  'gr.nav.soon': 'Bientôt disponible',
  'gr.demo': 'Données de démonstration',
  'gr.demoShort': 'Démo',
  'gr.demoTitle': 'Aucune source Growth n’est encore connectée : tous les chiffres de cette page sont des exemples.',
  'gr.period.last30': '30 derniers jours',
  'gr.period.fixed': 'Fixe',
  'gr.period.fixedNote': 'La vue Growth affiche les 30 derniers jours.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Transformez les données de votre entreprise en opportunités de croissance mesurables.',
  'gr.kpi.revenueInfluenced': 'CA influencé',
  'gr.kpi.activeOpportunities': 'Opportunités actives',
  'gr.kpi.highPriority': 'haute priorité',
  'gr.kpi.activeCampaigns': 'Campagnes actives',
  'gr.kpi.performingWell': 'performantes',
  'gr.kpi.roas': 'ROAS',
  'gr.kpi.experimentsRunning': 'Expériences en cours',
  'gr.kpi.endingThisWeek': 'se termine cette semaine',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Indicateur affiché',
  'gr.pulse.revenue': 'Chiffre d’affaires',
  'gr.pulse.traffic': 'Trafic magasin',
  'gr.pulse.total': 'CA total',
  'gr.pulse.influenced': 'CA influencé par Growth',
  'gr.pulse.visitors': 'Visiteurs en magasin',
  'gr.pulse.share': '{0} % influencé par Growth',
  'gr.pulse.foot': 'Par jour, du {0} au {1}. Chiffre d’affaires et trafic ont des unités différentes : ils sont affichés séparément.',
  'gr.ai.title': 'Insights Nordla AI',
  'gr.ai.badge': 'Nordla AI',
  'gr.ai.foot': 'Nordla AI explique ; les chiffres viennent du moteur de calcul.',
  'gr.att.title': 'Nécessite votre attention',
  'gr.att.status.pending': 'À approuver',
  'gr.att.status.new': 'Nouveau',
  'gr.att.status.endingSoon': 'Se termine bientôt',
  'gr.att.action.approve': 'Examiner',
  'gr.att.action.review': 'Examiner',
  'gr.att.action.results': 'Résultats',
  'gr.att.soon': 'Disponible avec la page Approvals (bientôt)',
  'gr.ch.title': 'Performance par canal',
  'gr.ch.channel': 'Canal',
  'gr.ch.revenue': 'CA',
  'gr.ch.reach': 'Visites / portée',
  'gr.ch.conversion': 'Conversion',
  'gr.ch.roas': 'ROAS',
  'gr.ch.unit.visits': 'visites',
  'gr.ch.unit.reach': 'portée',
  'gr.ch.unit.actions': 'actions',
  'gr.ch.organic': 'organique',
  'gr.ch.foot': 'ROAS = CA attribué ÷ dépense publicitaire. « organique » = canal sans dépense.',
  'gr.camp.title': 'Campagnes',
  'gr.camp.activeCount': '{0} actives',
  'gr.camp.spend': '{0} dépensés sur {1}',
  'gr.camp.noBudget': 'Sans budget (organique)',
  'gr.camp.status.performing': 'Performante',
  'gr.camp.status.active': 'Active',
  'gr.camp.status.watch': 'À surveiller',
  'gr.camp.roas': 'ROAS {0}',
  'gr.camp.conversions': '{0} conversions',
  'gr.camp.actions': '{0} actions',
  'gr.content.title': 'Performance du contenu',
  'gr.content.kind.reel': 'Reel',
  'gr.content.kind.video': 'Vidéo',
  'gr.content.kind.carousel': 'Carrousel',
  'gr.content.kind.post': 'Post',
  'gr.content.views': '{0} vues',
  'gr.content.perf.best': 'Meilleur contenu',
  'gr.content.perf.good': 'Bon',
  'gr.content.perf.below': 'Sous la moyenne',
  'gr.store.title': 'Croissance magasin',
  'gr.store.traffic': 'Trafic magasin',
  'gr.store.conversion': 'Taux de conversion',
  'gr.store.revenue': 'CA magasin',
  'gr.store.pts': '{0} pts',
  'gr.opp.title': 'Opportunités prioritaires',
  'gr.opp.source': 'Source : {0}',
  'gr.opp.priority.high': 'Priorité haute',
  'gr.opp.priority.medium': 'Priorité moyenne',
  'gr.opp.status.recommended': 'Recommandée',
  'gr.opp.status.review': 'À examiner',
  'gr.opp.status.planned': 'Planifiée',
  'gr.opp.estimate': 'CA estimé',
  'gr.opp.foot': 'Estimations sur 30 jours, à valider avant toute action.',
  'gr.exp.title': 'Expériences',
  'gr.exp.kpi': 'KPI testé : {0}',
  'gr.exp.status.running': 'En cours',
  'gr.exp.status.endingSoon': 'Se termine bientôt',
  'gr.exp.duration': '{0} jours',
  'gr.exp.ends': 'Fin',
  'gr.noData': 'Données indisponibles',
  'gr.loadError': 'La vue Growth n’a pas pu être chargée.',
  'gr.op.title': 'Opportunités',
  'gr.op.subtitle': 'Identifiez et priorisez les leviers de croissance les plus prometteurs pour votre activité.',
  'gr.op.kpi.priority': 'Opportunités prioritaires',
  'gr.op.kpi.highPriority': '{0} priorité élevée',
  'gr.op.kpi.potential': 'Revenu potentiel',
  'gr.op.kpi.active': '{0} opportunités actives',
  'gr.op.kpi.ready': 'Prêtes à approuver',
  'gr.op.kpi.readyNote': 'Actions pouvant être lancées',
  'gr.op.kpi.inProgress': 'En cours',
  'gr.op.kpi.inProgressNote': 'Opportunités en exécution',
  'gr.op.kpi.wins': 'Gains ce mois',
  'gr.op.kpi.winsNote': '{0} générés',
  'gr.op.pipe.title': 'Pipeline des opportunités',
  'gr.op.pipe.desc': 'Identifiez, priorisez et suivez les opportunités de croissance détectées par Nordla.',
  'gr.op.pipe.foot': '{0} opportunités affichées · {1} de revenu potentiel. Estimations à valider avant toute action.',
  'gr.op.f.source': 'Source',
  'gr.op.f.allSources': 'Toutes les sources',
  'gr.op.f.status': 'Statut',
  'gr.op.f.allStatuses': 'Tous les statuts',
  'gr.op.f.sort': 'Tri',
  'gr.op.f.sort.priority': 'Trier par priorité',
  'gr.op.f.sort.revenue': 'Trier par revenu potentiel',
  'gr.op.f.sort.confidence': 'Trier par confiance',
  'gr.op.col.name': 'Opportunité',
  'gr.op.col.source': 'Source',
  'gr.op.col.priority': 'Priorité',
  'gr.op.col.revenue': 'Revenu potentiel',
  'gr.op.col.confidence': 'Confiance',
  'gr.op.col.effort': 'Effort',
  'gr.op.col.status': 'Statut',
  'gr.op.col.actions': 'Actions',
  'gr.op.actionsSoon': 'Actions bientôt disponibles',
  'gr.op.noMatch': 'Aucune opportunité ne correspond à ces filtres.',
  'gr.op.src.store': 'Analyse magasin',
  'gr.op.src.stock': 'Stock',
  'gr.op.src.market': 'Tendance marché',
  'gr.op.src.ai': 'Nordla AI',
  'gr.op.src.customers': 'Comportement client',
  'gr.op.src.experiment': 'Expérience magasin',
  'gr.op.src.seasonality': 'Saisonnalité',
  'gr.op.src.sales': 'Ventes',
  'gr.op.src.local': 'Données locales',
  'gr.op.src.margin': 'Marges',
  'gr.op.status.ready': 'Prête à approuver',
  'gr.op.status.inProgress': 'En cours',
  'gr.op.status.analysis': 'À analyser',
  'gr.op.status.planned': 'Planifiée',
  'gr.op.priority.high': 'Élevée',
  'gr.op.priority.medium': 'Moyenne',
  'gr.op.priority.low': 'Faible',
  'gr.op.effort.low': 'Faible',
  'gr.op.effort.medium': 'Moyen',
  'gr.op.effort.high': 'Élevé',
  'gr.op.ai.title': 'Recommandations Nordla AI',
  'gr.op.ai.potential': 'Revenu potentiel',
  'gr.op.ai.confidence': 'confiance {0}',
  'gr.op.mx.title': 'Impact vs effort',
  'gr.op.mx.impact': 'Impact',
  'gr.op.mx.effortLow': 'Effort faible',
  'gr.op.mx.effortHigh': 'Effort moyen à élevé',
  'gr.op.mx.highLow': 'Impact élevé · faible effort',
  'gr.op.mx.highHigh': 'Impact élevé · effort élevé',
  'gr.op.mx.lowLow': 'Impact faible · faible effort',
  'gr.op.mx.lowHigh': 'Impact faible · effort élevé',
  'gr.op.mx.foot': 'Les {0} opportunités prioritaires, placées selon l’impact et l’effort estimés.',
  'gr.op.appr.title': 'Nécessite votre approbation',
  'gr.op.appr.budget': 'Budget proposé {0}',
  'gr.op.appr.expected': 'revenu attendu {0}',
  'gr.op.appr.approve': 'Approuver',
  'gr.op.appr.soon': 'Le workflow d’approbation n’est pas encore disponible',
  'gr.op.appr.foot': 'Aucune action n’est lancée sans votre décision.',
  'gr.op.seg.title': 'Segments à fort potentiel',
  'gr.op.seg.foot': 'Croissance estimée du potentiel par segment.',
  'gr.op.wins.title': 'Succès récents',
  'gr.op.wins.target': 'Objectif {0} · {1} atteint',
  'gr.op.bySource.title': 'Revenu potentiel par source',
  'gr.op.bySource.total': 'potentiel',
  'gr.op.bySource.others': 'Autres ({0})',
  'gr.op.bySource.foot': '{0} répartis entre {1} sources ; les plus petites sont regroupées.',
  'gr.op.byStatus.title': 'Pipeline par statut',
  'gr.op.byStatus.count': '{0} opportunités',
  'gr.op.byStatus.foot': '{0} opportunités · {1} de revenu potentiel.',
  'gr.cp.title': 'Campagnes',
  'gr.cp.subtitle': 'Créez, suivez et optimisez vos campagnes marketing sur tous vos canaux.',
  'gr.cp.kpi.revenue': 'Revenu généré',
  'gr.cp.kpi.clicks': 'Clics',
  'gr.cp.kpi.newCustomers': 'Nouveaux clients',
  'gr.cp.kpi.roas': 'ROAS moyen',
  'gr.cp.table.title': 'Campagnes ({0})',
  'gr.cp.table.foot': '{0} campagnes affichées sur {1}. Performance = résultat par rapport à l’objectif de la campagne.',
  'gr.cp.search': 'Rechercher une campagne…',
  'gr.cp.f.channel': 'Canal',
  'gr.cp.f.allChannels': 'Tous les canaux',
  'gr.cp.f.status': 'Statut',
  'gr.cp.f.allStatuses': 'Tous les statuts',
  'gr.cp.new': '+ Nouvelle campagne',
  'gr.cp.newSoon': 'La création de campagne n’est pas encore disponible',
  'gr.cp.noMatch': 'Aucune campagne ne correspond à cette recherche.',
  'gr.cp.col.campaign': 'Campagne',
  'gr.cp.col.channel': 'Canal',
  'gr.cp.col.objective': 'Objectif',
  'gr.cp.col.period': 'Période',
  'gr.cp.col.budget': 'Budget',
  'gr.cp.col.status': 'Statut',
  'gr.cp.col.performance': 'Performance',
  'gr.cp.status.running': 'En cours',
  'gr.cp.status.ready': 'Prête à lancer',
  'gr.cp.status.planned': 'Planifiée',
  'gr.cp.objective.sales': 'Ventes',
  'gr.cp.objective.awareness': 'Notoriété',
  'gr.cp.objective.storeTraffic': 'Trafic magasin',
  'gr.cp.objective.retention': 'Rétention',
  'gr.cp.objective.recruitment': 'Recrutement',
  'gr.cp.actions.title': 'Actions prioritaires',
  'gr.cp.channels.title': 'Performances par canal',
  'gr.cp.channels.foot': 'Part du revenu généré ({0}) par canal.',
  'gr.cp.trend.title': 'Revenu vs dépense — 30 derniers jours',
  'gr.cp.trend.revenue': 'Revenu',
  'gr.cp.trend.spend': 'Dépense',
  'gr.cp.trend.roas': 'ROAS {0}',
  'gr.cp.trend.foot': 'Par jour, du {0} au {1} : revenu attribué aux campagnes et dépense publicitaire.',
  'gr.cp.f.sort': 'Tri',
  'gr.cp.f.sort.default': 'Ordre par défaut',
  'gr.cp.f.sort.budget': 'Trier par budget',
  'gr.cp.f.sort.performance': 'Trier par performance',
  'gr.cp.perfNone': 'Pas encore lancée : aucune performance mesurée',
  'gr.cp.channels.spendRoas': '{0} dépensés · ROAS {1}',
  'gr.cp.channels.noSpend': 'Sans dépense',
  // Potentiel produits
  'gr.nav.potential': 'Produits Potentiels',
  'gr.period.lastWeeks': '{0} dernières semaines',
  'gr.period.weeksNote': 'Analyse sur les {0} dernières semaines complètes.',
  'gr.pp.title': 'Produits Potentiels',
  'gr.pp.subtitle': 'Identifiez les produits à pousser, à surveiller ou à protéger selon la demande, le stock et la rentabilité.',
  'gr.pp.days': '{0} j',
  'gr.pp.unit1': '{0} unité vendue',
  'gr.pp.uN': '{0} unités',
  'gr.pp.u1': '{0} unité',
  'gr.pp.units': '{0} unités vendues',
  'gr.pp.noImage': 'Pas d’image synchronisée',
  'gr.pp.noCategory': 'Sans catégorie',
  'gr.pp.openDetail': 'Voir le détail : {0}',
  'gr.pp.close': 'Fermer',
  'gr.pp.kpi.active': 'Produits actifs',
  'gr.pp.kpi.activeNote': 'Vendus sur les {0} dernières semaines',
  'gr.pp.kpi.push': 'Produits à pousser',
  'gr.pp.kpi.pushNote': '{0} des ventes de la période',
  'gr.pp.kpi.pushNone': 'Aucun ne réunit toutes les conditions',
  'gr.pp.kpi.watch': 'À surveiller',
  'gr.pp.kpi.watchNote': 'Baisse, marge faible, retours ou signal contradictoire',
  'gr.pp.kpi.restock': 'Réassort avant promotion',
  'gr.pp.kpi.restockNote': 'Bonne demande, stock trop court',
  'gr.pp.list.title': 'Produits',
  'gr.pp.list.desc': 'Chaque produit vendu sur les {0} dernières semaines, avec son statut Growth et le signal qui le justifie.',
  'gr.pp.list.foot': '{0} produits affichés sur {1}',
  'gr.pp.quality.stock': 'Dernier relevé de stock : {0} (utilisé s’il date de moins de {1} h)',
  'gr.pp.quality.noStock': 'Aucun relevé de stock synchronisé',
  'gr.pp.search': 'Rechercher un produit',
  'gr.pp.noMatch': 'Aucun produit ne correspond à ces filtres.',
  'gr.pp.empty.title': 'Aucun produit vendu sur la période',
  'gr.pp.empty.text': 'Aucune vente synchronisée sur les {0} dernières semaines : rien à recommander pour l’instant.',
  'gr.pp.f.aria': 'Filtrer par statut Growth',
  'gr.pp.f.all': 'Tous',
  'gr.pp.f.push': 'À pousser',
  'gr.pp.f.growth': 'Forte croissance',
  'gr.pp.f.top': 'Meilleures ventes',
  'gr.pp.f.watch': 'À surveiller',
  'gr.pp.f.restock': 'Réassort avant promotion',
  'gr.pp.f.lowMargin': 'Marge faible',
  'gr.pp.f.insufficient': 'Données insuffisantes',
  'gr.pp.f.category': 'Catégorie',
  'gr.pp.f.allCategories': 'Toutes les catégories',
  'gr.pp.f.sort': 'Trier',
  'gr.pp.f.sort.sales': 'Trier par ventes',
  'gr.pp.f.sort.evolution': 'Trier par évolution',
  'gr.pp.f.sort.cover': 'Trier par couverture',
  'gr.pp.f.sort.margin': 'Trier par marge',
  'gr.pp.col.product': 'Produit',
  'gr.pp.col.sales': 'Ventes',
  'gr.pp.col.evolution': 'Évolution',
  'gr.pp.col.margin': 'Marge',
  'gr.pp.col.stock': 'Stock',
  'gr.pp.col.cover': 'Couverture',
  'gr.pp.col.status': 'Statut · signal',
  'gr.pp.evo.insufficient': 'Historique insuffisant',
  'gr.pp.trend.UP': 'En hausse',
  'gr.pp.trend.DOWN': 'En baisse',
  'gr.pp.trend.FLAT': 'Stable',
  'gr.pp.margin.MISSING': 'Coût manquant',
  'gr.pp.margin.PARTIAL': 'Marge partielle',
  'gr.pp.margin.UNVERIFIED': 'Coût non vérifié',
  'gr.pp.margin.RELIABLE': 'Coût vérifié',
  'gr.pp.stock.stale': 'Relevé ancien',
  'gr.pp.stock.unavailable': 'Stock indisponible',
  'gr.pp.cover.OUT': 'Rupture',
  'gr.pp.cover.STOCK_UNUSABLE': 'Couverture non calculée : stock indisponible ou relevé trop ancien.',
  'gr.pp.cover.INSUFFICIENT_HISTORY': 'Couverture non calculée : historique de ventes insuffisant.',
  'gr.pp.cover.INSUFFICIENT_SALES_SAMPLE': 'Couverture non calculée : trop peu de ventes pour estimer un rythme.',
  'gr.pp.cover.NO_DEMAND_OBSERVED': 'Couverture non calculée : aucune demande observée.',
  'gr.pp.cover.NO_STOCK': 'Stock épuisé.',
  'gr.pp.cover.UNKNOWN': 'Couverture non calculée.',
  'gr.pp.status.push': 'À pousser',
  'gr.pp.status.restock': 'Réassort avant promotion',
  'gr.pp.status.topSeller': 'Top vente',
  'gr.pp.status.watch': 'À surveiller',
  'gr.pp.status.declining': 'En baisse',
  'gr.pp.status.lowMargin': 'Marge faible',
  'gr.pp.status.returns': 'Trop de retours',
  'gr.pp.status.insufficient': 'Données insuffisantes',
  'gr.pp.status.stable': 'Stable',
  'gr.pp.signal.newProduct': 'Produit récent : moins de {0} semaines de ventes',
  'gr.pp.signal.thinSample': '{0} : échantillon trop faible',
  'gr.pp.signal.outOfStock': 'Demande présente, stock épuisé',
  'gr.pp.signal.coverDays': 'Stock pour {0} jours seulement',
  'gr.pp.signal.returnRate': '{0} des unités remboursées',
  'gr.pp.signal.margin': 'Marge vérifiée de {0}',
  'gr.pp.signal.evolution': '{0} vs {1} sem. précédentes',
  'gr.pp.signal.topRank': 'N°{0} des ventes de la période',
  'gr.pp.signal.none': 'Aucun signal particulier',
  'gr.pp.action.increaseVisibility': 'Augmenter la visibilité',
  'gr.pp.action.restockFirst': 'Réassortir d’abord',
  'gr.pp.action.doNotPromote': 'Ne pas promouvoir',
  'gr.pp.action.reviewReturns': 'Analyser les retours',
  'gr.pp.action.checkCost': 'Vérifier le coût',
  'gr.pp.action.checkStock': 'Vérifier le stock',
  'gr.pp.action.watch': 'Surveiller',
  'gr.pp.action.keep': 'Maintenir disponible',
  'gr.pp.action.none': 'Aucune action',
  'gr.pp.actionText.increaseVisibility': 'Donnez-lui plus de place : mise en avant sur la boutique, en vitrine ou dans une prochaine campagne. Le stock et la marge peuvent suivre.',
  'gr.pp.actionText.restockFirst': 'Réassortez avant toute mise en avant : une promotion maintenant créerait surtout des ruptures.',
  'gr.pp.actionText.doNotPromote': 'Ne pas dépenser en visibilité sur ce produit tant que la marge ou les retours ne sont pas corrigés.',
  'gr.pp.actionText.reviewReturns': 'Regardez les motifs de remboursement (qualité, taille, description) avant de lui donner plus de visibilité.',
  'gr.pp.actionText.checkCost': 'La demande monte mais la marge n’est pas fiable : renseignez ou vérifiez le coût d’achat pour savoir si le pousser est rentable.',
  'gr.pp.actionText.checkStock': 'La demande monte mais le stock n’est pas connu avec certitude : vérifiez-le avant toute mise en avant.',
  'gr.pp.actionText.watch': 'Pas d’action immédiate : suivez l’évolution des prochaines semaines.',
  'gr.pp.actionText.keep': 'Gardez-le disponible et visible comme aujourd’hui ; une promotion supplémentaire n’est pas nécessaire.',
  'gr.pp.actionText.none': 'Pas assez d’éléments pour recommander une action : Nordla attend plus de ventes.',
  'gr.pp.reason.COST_MISSING': 'Coût manquant',
  'gr.pp.reason.MARGIN_PARTIAL': 'Marge partielle',
  'gr.pp.reason.COST_UNVERIFIED': 'Coût non vérifié',
  'gr.pp.reason.STOCK_STALE': 'Relevé de stock ancien',
  'gr.pp.reason.STOCK_UNAVAILABLE': 'Stock indisponible',
  'gr.pp.reason.COVER_UNKNOWN': 'Couverture non calculable',
  'gr.pp.reason.HIGH_RETURNS': 'Trop de retours',
  'gr.pp.reason.RETURNS_ELEVATED': 'Retours élevés',
  'gr.pp.reason.TREND_INSUFFICIENT': 'Historique insuffisant',
  'gr.pp.push.title': 'Produits à pousser',
  'gr.pp.push.none': 'Aucun produit ne réunit aujourd’hui les quatre conditions pour être poussé :',
  'gr.pp.push.cond.demand': 'demande en hausse ;',
  'gr.pp.push.cond.cover': 'stock connu couvrant au moins {0} semaines ;',
  'gr.pp.push.cond.cost': 'coût d’achat vérifié (marge fiable) ;',
  'gr.pp.push.cond.returns': 'retours au plus de {0}.',
  'gr.pp.push.foot': 'Demande en hausse, stock suffisant, coût vérifié et retours normaux.',
  'gr.pp.protect.title': 'À protéger / ne pas pousser',
  'gr.pp.protect.none': 'Aucun produit à protéger pour l’instant.',
  'gr.pp.protect.foot': 'Réassort, retours, marge faible, signaux contradictoires ou baisse.',
  'gr.pp.byStatus.title': 'Produits par statut Growth',
  'gr.pp.byStatus.foot': '{0} produits actifs classés',
  'gr.pp.d.why': 'Pourquoi ce statut',
  'gr.pp.d.evidence': 'Preuves ({0} dernières semaines)',
  'gr.pp.d.action': 'Action recommandée',
  'gr.pp.d.opportunity': 'Créer une opportunité',
  'gr.pp.d.opportunitySoon': 'Bientôt : ajouter ce produit aux Opportunités Growth.',
  'gr.pp.d.method': 'Statut calculé à partir des ventes, du stock, des coûts et des remboursements synchronisés dans Nordla. Une donnée inconnue n’est jamais comptée comme zéro.',
  'gr.pp.ev.sales': 'Ventes nettes HT',
  'gr.pp.ev.salesNote': 'N°{0} de la période',
  'gr.pp.ev.units': 'Unités vendues',
  'gr.pp.ev.velocity': '{0} par semaine en moyenne',
  'gr.pp.ev.evoNote': '{0} u. contre {1} u. ({2} sem. vs {2} sem.)',
  'gr.pp.ev.evoNone': 'Il faut au moins {0} semaines de ventes pour comparer.',
  'gr.pp.ev.snapshot': 'Relevé du {0}',
  'gr.pp.ev.snapshotOld': 'Dernier relevé le {0} : trop ancien pour décider',
  'gr.pp.ev.noSnapshot': 'Aucun relevé de stock synchronisé',
  'gr.pp.ev.coverNote': 'Seuil de réassort : {0} semaines',
  'gr.pp.ev.refunds': 'Remboursements',
  'gr.pp.ev.refundNote': 'Unités remboursées : {0}',
  'gr.pp.ev.history': 'Historique observé',
  'gr.pp.ev.weeks': '{0} sem.',
  'gr.pp.rule.NEW_PRODUCT': 'Ce produit n’a que {0} semaines de ventes observées ; il en faut au moins {1} avant de recommander quoi que ce soit.',
  'gr.pp.rule.THIN_SAMPLE': '{0} en {2} semaines : il en faut au moins {1} pour conclure.',
  'gr.pp.rule.DEMAND_BUT_OUT_OF_STOCK': 'La demande est bonne mais le stock est épuisé : le promouvoir enverrait des clients vers une rupture.',
  'gr.pp.rule.DEMAND_BUT_LOW_COVER': 'La demande est bonne mais le stock ne couvre que {0} jours (moins de {1} semaines) : réassortir avant toute promotion.',
  'gr.pp.rule.DEMAND_BUT_HIGH_RETURNS': 'La demande est bonne, mais {0} des unités vendues ont été remboursées : à comprendre avant de le pousser.',
  'gr.pp.rule.HIGH_RETURNS': '{0} des unités vendues ont été remboursées (seuil : {1}).',
  'gr.pp.rule.LOW_RELIABLE_MARGIN': 'Marge fiable de {0}, sous le seuil de {1} : chaque vente supplémentaire rapporte peu.',
  'gr.pp.rule.TREND_DOWN': 'Les ventes des {0} dernières semaines sont en baisse par rapport aux {0} précédentes ({1} u. contre {2} u.).',
  'gr.pp.rule.PUSH': 'Demande en hausse ({0} u. contre {1} u. sur {2} semaines), stock suffisant, coût vérifié et retours normaux : le produit peut absorber plus de visibilité.',
  'gr.pp.rule.BLOCKED': 'La demande est en hausse ({0} u. contre {1} u. sur {2} semaines), mais une condition manque pour le pousser : {3}.',
  'gr.pp.blocked.checkStock': 'stock inconnu ou relevé trop ancien',
  'gr.pp.blocked.checkCost': 'coût d’achat non vérifié',
  'gr.pp.blocked.reviewReturns': 'retours au-dessus de {0}',
  'gr.pp.blocked.watch': 'couverture de stock non calculable',
  'gr.pp.rule.TOP_SELLER': 'N°{0} des ventes de la période, sans nouveau signal de hausse : le garder disponible suffit.',
  'gr.pp.rule.TOP_SELLER_RETURNS': 'Top vente, mais {0} des unités vendues ont été remboursées (au-delà de {1}) : comprendre ces retours avant tout réassort ou promotion.',
  'gr.pp.rule.NO_SIGNAL': 'Ventes régulières, sans signal de hausse, de baisse ni de risque.',
  // Audience
  'gr.period.lastDays': '{0} derniers jours',
  'gr.period.daysNote': 'Analyse sur les {0} derniers jours complets, comparés aux {0} jours précédents.',
  'gr.au.title': 'Audience',
  'gr.au.subtitle': 'Identifiez les segments clients qui représentent une opportunité de croissance.',
  'gr.au.vsPrevious': 'vs période précédente',
  'gr.au.pts': '{0} pts',
  'gr.au.daysAgo': 'il y a {0} j',
  'gr.au.open': 'Ouvrir',
  'gr.au.openSegment': 'Voir le segment : {0}',
  'gr.au.kpi.active': 'Clients actifs',
  'gr.au.kpi.new': 'Nouveaux clients',
  'gr.au.kpi.repeatRate': 'Taux de réachat',
  'gr.au.kpi.aov': 'Panier moyen',
  'gr.au.kpi.toReactivate': 'Clients à réactiver',
  'gr.au.kpi.orders': 'Commandes',
  'gr.au.kpi.netSales': 'CA HT',
  'gr.au.kpi.returningOrders': 'Commandes de clients récurrents',
  'gr.au.kpi.multiProduct': 'Paniers multi-produits',
  'gr.au.kpi.noPrevious': 'Pas de période précédente comparable',
  'gr.au.kpi.notComputable': 'Non calculable',
  'gr.au.kpi.fromZero': '0 sur la période précédente',
  'gr.au.kpi.sampleGate': 'Moins de {0} clients actifs : non calculé',
  'gr.au.kpi.historyGate': 'Historique de moins de {0} jours : non calculé',
  'gr.au.kpi.indexMissing': 'Ordre d’achat client non transmis par la source',
  'gr.au.dist.title': 'Répartition des segments',
  'gr.au.dist.ordersTitle': 'Répartition des commandes',
  'gr.au.dist.value': '{0} ({1})',
  'gr.au.dist.revenue': '{0} du CA',
  'gr.au.dist.foot': '{0} clients identifiés. Chaque client appartient à un seul segment (total 100 %). Part du CA : achats des {1} derniers jours.',
  'gr.au.dist.ordersFoot': 'Commandes des {0} derniers jours selon l’ordre d’achat transmis par la source. Chaque commande est comptée une fois.',
  'gr.au.dist.noIndex': 'Aucune des {0} commandes de la période ne porte d’ordre d’achat client transmis par la source : impossible de distinguer premiers achats et achats répétés.',
  'gr.au.orderGroup.new': 'Premier achat (en ligne)',
  'gr.au.orderGroup.returning': 'Client récurrent',
  'gr.au.orderGroup.first_recorded_pos': '1er achat enregistré en magasin',
  'gr.au.orderGroup.unknown': 'Ordre d’achat inconnu',
  'gr.au.seg.loyal': 'Clients fidèles',
  'gr.au.seg.returning': 'Clients récurrents',
  'gr.au.seg.newReturned': 'Nouveaux clients prometteurs',
  'gr.au.seg.new': 'Nouveaux clients',
  'gr.au.seg.reactivate': 'Clients à réactiver',
  'gr.au.seg.occasional': 'Occasionnels à convertir',
  'gr.au.seg.unknown': 'Historique non établi',
  'gr.au.segDef.loyal': '≥ 3 achats, dont un récent',
  'gr.au.segDef.returning': '2 achats, dont un récent',
  'gr.au.segDef.newReturned': 'Nouveaux, déjà revenus',
  'gr.au.segDef.new': '1er achat récent',
  'gr.au.segDef.reactivate': '≥ 2 achats, aucun récent',
  'gr.au.segDef.occasional': '1 achat ancien, pas revenu',
  'gr.au.segDef.unknown': '1 achat récent, 1er achat non prouvé',
  'gr.au.segRule.loyal': 'Client identifié avec au moins 3 commandes connues (ou un numéro de commande source ≥ 3), dont au moins une dans les {0} derniers jours.',
  'gr.au.segRule.returning': 'Client identifié avec exactement 2 commandes connues, dont au moins une dans les {0} derniers jours, et dont le premier achat n’est pas récent.',
  'gr.au.segRule.newReturned': 'Premier achat prouvé (numéro de commande source = 1) dans les {0} derniers jours, et au moins une autre commande depuis : le client est déjà revenu.',
  'gr.au.segRule.new': 'Premier achat prouvé (numéro de commande source = 1) dans les {0} derniers jours, sans autre commande pour l’instant.',
  'gr.au.segRule.reactivate': 'Client identifié avec au moins 2 commandes (acheteur répété prouvé) mais aucune commande dans les {0} derniers jours.',
  'gr.au.segRule.occasional': 'Client identifié avec une seule commande connue, passée il y a plus de {0} jours, et pas revenu depuis.',
  'gr.au.segRule.unknown': 'Une seule commande dans les {0} derniers jours, sans numéro de commande source fiable (ex. vente en magasin) : impossible de savoir si c’est un premier achat. Ce groupe n’est pas qualifié.',
  'gr.au.status.priority': 'Prioritaire',
  'gr.au.status.activate': 'À activer',
  'gr.au.status.develop': 'À développer',
  'gr.au.status.watch': 'À surveiller',
  'gr.au.status.insufficient': 'Données insuffisantes',
  'gr.au.rule.INSUFFICIENT': 'Pas assez de données pour une recommandation fiable : Growth ne tire aucune conclusion de ce segment pour l’instant.',
  'gr.au.rule.REPEAT_BUYERS_WITHOUT_RECENT_ORDER': 'Ces clients ont prouvé qu’ils rachètent (au moins 2 commandes) mais n’ont plus commandé récemment : c’est un groupe identifiable à recontacter.',
  'gr.au.rule.REVENUE_SHARE_ABOVE_CUSTOMER_SHARE': 'Ce segment pèse {0} du CA récent pour {1} des clients actifs : il contribue plus que son poids.',
  'gr.au.rule.SMALLER_THAN_PREVIOUS_WINDOW': 'Ce segment compte moins de clients que sur la période précédente ({2}).',
  'gr.au.rule.ONE_ORDER_NOT_REPEATED': 'Ces clients ont acheté une fois il y a plus longtemps que la période et ne sont pas revenus : une deuxième commande reste à obtenir.',
  'gr.au.rule.ACTIVE_SEGMENT': 'Segment actif et suffisamment grand, sans signal particulier de sur-contribution ni de baisse.',
  'gr.au.reason.SAMPLE_BELOW_MIN_CUSTOMERS': 'Moins de {0} clients identifiés au total',
  'gr.au.reason.SEGMENT_BELOW_MIN_GROUP': 'Segment de moins de {1} clients',
  'gr.au.reason.SHORT_HISTORY': 'Historique trop court',
  'gr.au.reason.FIRST_ORDER_NOT_PROVEN': 'Premier achat non prouvé',
  'gr.au.action.reactivation': 'Préparer une campagne de réactivation',
  'gr.au.action.loyalty': 'Renforcer la fidélisation',
  'gr.au.action.secondPurchase': 'Préparer une offre de deuxième achat',
  'gr.au.action.targetedOffer': 'Tester une offre ciblée',
  'gr.au.action.none': 'Aucune action pour l’instant',
  'gr.au.actionText.reactivation': 'Recontacter ce groupe avec un message ou une offre simple, puis mesurer combien de clients reviennent. À tester à petite échelle d’abord.',
  'gr.au.actionText.loyalty': 'Reconnaître et récompenser ces clients (avantage fidélité, accès anticipé) pour entretenir leur rythme d’achat.',
  'gr.au.actionText.secondPurchase': 'Donner une raison de revenir après le premier achat (suggestion de produit, offre limitée dans le temps).',
  'gr.au.actionText.targetedOffer': 'Tester une offre adaptée à ce qu’ils ont acheté la première fois, sur un petit groupe, avant de l’élargir.',
  'gr.au.actionText.none': 'Growth ne recommande rien sur ce segment tant que les données sont insuffisantes.',
  'gr.au.prio.title': 'Segments prioritaires',
  'gr.au.prio.foot': 'Classés par statut puis par taille. Statuts issus de règles explicites, sans score.',
  'gr.au.col.segment': 'Segment',
  'gr.au.col.size': 'Taille',
  'gr.au.col.revenueShare': 'Part du CA',
  'gr.au.col.status': 'Statut',
  'gr.au.col.action': 'Action recommandée',
  'gr.au.col.customers': 'Clients',
  'gr.au.col.frequency': 'Commandes / client',
  'gr.au.col.revenue': 'CA {0} j',
  'gr.au.col.aov': 'Panier moyen',
  'gr.au.col.recency': 'Dernier achat',
  'gr.au.col.statusAction': 'Statut · action',
  'gr.au.sig.title': 'Signaux d’audience',
  'gr.au.sig.foot': 'Faits observés, comparés à une référence. Aucune prédiction.',
  'gr.au.sig.none': 'Aucun signal fiable : il faut au moins {0} clients identifiés.',
  'gr.au.sig.repeatRevenueShare.title': 'Les clients qui rachètent génèrent {0} du CA',
  'gr.au.sig.repeatRevenueShare.text': 'Ils représentent {0} des clients actifs mais {1} du CA des {2} derniers jours : ils pèsent plus que leur nombre.',
  'gr.au.sig.reactivation.title': '{0} acheteurs répétés sans achat depuis {1} jours',
  'gr.au.sig.reactivation.text': 'Ils ont généré {0} sur l’historique observé : un groupe identifiable à recontacter.',
  'gr.au.sig.repeatRateUp.title': 'Le taux de réachat progresse',
  'gr.au.sig.repeatRateDown.title': 'Le taux de réachat recule',
  'gr.au.sig.repeatRateChange.text': '{0} des clients actifs ont déjà acheté au moins deux fois, contre {1} sur les {2} jours précédents.',
  'gr.au.sig.aovGap.title': 'Panier moyen : clients récurrents vs nouveaux',
  'gr.au.sig.aovGap.text': '{0} pour les clients qui rachètent contre {1} pour les nouveaux clients (commandes observées).',
  'gr.au.sig.coverage.title': '{0} des commandes sont rattachées à un client',
  'gr.au.sig.coverage.text': '{0} commandes anonymes (souvent en magasin) ne sont dans aucun segment : les segments décrivent les clients identifiés uniquement.',
  'gr.au.sig.returningOrders.title': '{0} des commandes viennent de clients récurrents',
  'gr.au.sig.returningOrders.text': 'Sur {0} commandes dont l’ordre d’achat est connu (minimum, l’historique source peut être incomplet).',
  'gr.au.sig.aovUp.title': 'Le panier moyen augmente',
  'gr.au.sig.aovDown.title': 'Le panier moyen baisse',
  'gr.au.sig.aovChange.text': '{0} contre {1} sur les {2} jours précédents.',
  'gr.au.sig.multiProduct.title': '{0} des commandes contiennent plusieurs produits',
  'gr.au.sig.multiProduct.text': 'Sur {0} commandes : indique la part d’achats groupés, utile pour les offres associées.',
  'gr.au.sig.customerLevelMissing.title': 'Segments clients indisponibles',
  'gr.au.sig.customerLevelMissing.text': 'Aucune commande ne porte d’identifiant client pseudonymisé : Nordla ne peut pas regrouper les achats par client. Les indicateurs restent au niveau des commandes.',
  'gr.au.list.title': 'Segments clients ({0})',
  'gr.au.list.desc': 'Groupes exclusifs de clients identifiés, définis par leurs achats observés. « Récent » = dans les {0} derniers jours.',
  'gr.au.list.foot': '{0} clients identifiés · {1} des commandes de la période rattachées à un client · Aucun client n’est affiché individuellement.',
  'gr.au.newSegment': '+ Nouveau segment',
  'gr.au.newSegmentSoon': 'Bientôt disponible : les segments personnalisés ne sont pas encore enregistrés dans Nordla.',
  'gr.au.act.title': 'Actions recommandées ({0})',
  'gr.au.act.target': 'Cible : {0} ({1} clients)',
  'gr.au.act.toTest': 'À tester',
  'gr.au.act.prerequisite': 'Prérequis',
  'gr.au.act.none': 'Aucune action recommandée : aucun segment suffisamment grand ou établi.',
  'gr.au.act.foot': 'Bénéfices qualitatifs uniquement : aucun CRM ni outil e-mail n’est connecté, aucun résultat n’est promis.',
  'gr.au.actTitle.reactivation': 'Préparer une campagne de réactivation',
  'gr.au.actTitle.loyalty': 'Renforcer la fidélisation',
  'gr.au.actTitle.secondPurchase': 'Préparer une offre de deuxième achat',
  'gr.au.actTitle.targetedOffer': 'Tester une offre ciblée',
  'gr.au.actTitle.growSample': 'Attendre un échantillon suffisant',
  'gr.au.actTitle.enableCustomerKey': 'Activer l’identification client pseudonymisée',
  'gr.au.actWhy.growSample': 'Trop peu de clients identifiés pour qualifier des segments.',
  'gr.au.actWhy.enableCustomerKey': 'Aucune commande synchronisée ne porte de clé client pseudonymisée.',
  'gr.au.actBenefit.reactivation': 'Réactivation possible d’acheteurs qui ont déjà prouvé leur intérêt.',
  'gr.au.actBenefit.loyalty': 'Protéger le segment qui pèse le plus dans le CA.',
  'gr.au.actBenefit.secondPurchase': 'Transformer un premier achat en habitude.',
  'gr.au.actBenefit.targetedOffer': 'Obtenir une deuxième commande de clients déjà acquis.',
  'gr.au.actBenefit.growSample': 'Des segments fiables dès que l’échantillon est atteint.',
  'gr.au.actBenefit.enableCustomerKey': 'Débloque les segments (fidèles, à réactiver, nouveaux) sans stocker d’identité : seule une empreinte chiffrée est conservée.',
  'gr.au.noKey.banner': 'Niveau client indisponible : aucune commande ne porte d’identifiant client pseudonymisé. La page reste au niveau des commandes et ne cible aucun client individuellement.',
  'gr.au.noKey.text': 'Ces segments nécessitent l’identification client pseudonymisée, qui n’est pas active pour cette boutique :',
  'gr.au.d.window': 'Référence : {0} derniers jours',
  'gr.au.d.definition': 'Définition',
  'gr.au.d.sizeValue': 'Taille et valeur',
  'gr.au.d.size': 'Clients',
  'gr.au.d.sizeNote': '{0} des clients identifiés',
  'gr.au.d.evolution': 'Période précédente',
  'gr.au.d.noPrevious': 'Pas de période comparable',
  'gr.au.d.same': 'Stable : {0} clients',
  'gr.au.d.previous': '{0} clients sur la période précédente',
  'gr.au.d.noWindowPurchase': 'Aucun achat sur la période, par définition',
  'gr.au.d.revenueShare': '{0} du CA des clients actifs',
  'gr.au.d.historyRevenue': 'CA observé (historique)',
  'gr.au.d.historyNote': 'Sur {0} jours d’historique chargé',
  'gr.au.d.aovNote': 'Toutes leurs commandes observées',
  'gr.au.d.frequencyNote': 'Commandes connues par client',
  'gr.au.d.recencyNote': 'Médiane du segment',
  'gr.au.d.why': 'Pourquoi Growth le signale',
  'gr.au.d.action': 'Action suggérée',
  'gr.au.d.method': 'Segment calculé à partir des commandes synchronisées dans Nordla, regroupées par identifiant client pseudonymisé. Aucune donnée personnelle n’est lue ni affichée. Observation, pas prédiction.',
  'gr.au.empty.title': 'Aucune commande sur la période',
  'gr.au.empty.text': 'Aucune commande synchronisée : Audience n’a rien à analyser pour l’instant.',
  'gr.au.empty.window': 'Aucune donnée sur les {0} derniers jours.',
  // Contenu
  'gr.ct.title': 'Contenu',
  'gr.ct.subtitle': 'Repérez les fiches produits incomplètes et les améliorations à apporter en priorité.',
  'gr.ct.status.priority': 'Prioritaire',
  'gr.ct.status.improve': 'À améliorer',
  'gr.ct.status.insufficient': 'Données insuffisantes',
  'gr.ct.status.correct': 'Correct',
  'gr.ct.problem.noImage': 'Sans image',
  'gr.ct.problem.noAltText': 'Sans texte alternatif',
  'gr.ct.problem.noType': 'Sans catégorie',
  'gr.ct.problem.noCollection': 'Hors collection',
  'gr.ct.problem.missingSku': 'SKU manquant',
  'gr.ct.problem.duplicateTitle': 'Nom en double',
  'gr.ct.kpi.toImprove': 'Produits à améliorer',
  'gr.ct.kpi.toImproveNote': 'Au moins un problème, sur {0} produits actifs',
  'gr.ct.kpi.noImage': 'Sans image',
  'gr.ct.kpi.noImageNote': 'Aucune image principale',
  'gr.ct.kpi.noAltText': 'Sans texte alternatif',
  'gr.ct.kpi.noAltTextNote': 'Image sans description',
  'gr.ct.kpi.noType': 'Sans catégorie',
  'gr.ct.kpi.noTypeNote': 'Type de produit vide',
  'gr.ct.kpi.missingSku': 'SKU manquant',
  'gr.ct.kpi.missingSkuNote': 'Au moins une variante sans SKU',
  'gr.ct.kpi.unavailable': 'Non vérifiable avec les données actuelles',
  'gr.ct.prio.title': 'Produits par priorité',
  'gr.ct.prio.total': 'produits',
  'gr.ct.prio.foot': '{0} produits actifs analysés, chacun compté une fois.',
  'gr.ct.problems.title': 'Principaux problèmes de contenu',
  'gr.ct.problems.none': 'Aucun problème détecté parmi les contrôles possibles.',
  'gr.ct.problems.notChecked': 'Non contrôlé avec les données actuelles : {0}.',
  'gr.ct.na.description': 'description',
  'gr.ct.na.reviews': 'avis clients',
  'gr.ct.na.multipleImages': 'images multiples',
  'gr.ct.na.seo': 'titre et méta SEO',
  'gr.ct.na.attributes': 'attributs produit',
  'gr.ct.search': 'Rechercher un produit ou un SKU',
  'gr.ct.f.status': 'Statut',
  'gr.ct.f.allStatuses': 'Tous les statuts',
  'gr.ct.f.problem': 'Problème',
  'gr.ct.f.allProblems': 'Tous les problèmes',
  'gr.ct.f.category': 'Catégorie',
  'gr.ct.f.allCategories': 'Toutes les catégories',
  'gr.ct.noSku': 'Sans SKU',
  'gr.ct.col.product': 'Produit',
  'gr.ct.col.category': 'Catégorie',
  'gr.ct.col.problems': 'Problèmes',
  'gr.ct.col.status': 'Statut',
  'gr.ct.col.sales': 'Ventes ({0} sem.)',
  'gr.ct.col.action': 'Action',
  'gr.ct.noProblemYet': 'Aucun problème détecté (image non vérifiable)',
  'gr.ct.noProblem': 'Aucun problème détecté',
  'gr.ct.seeReco': 'Voir les recommandations',
  'gr.ct.seeDetail': 'Voir le détail',
  'gr.ct.list.title': 'Produits',
  'gr.ct.list.foot': '{0} produits affichés sur {1} actifs ({2} au catalogue, brouillons et archivés exclus). Triés par priorité puis par ventes.',
  'gr.ct.empty.noProducts': 'Aucun produit actif à analyser.',
  'gr.ct.empty.clearTitle': 'Aucun problème de contenu détecté avec les données actuellement disponibles.',
  'gr.ct.empty.clearText': 'Nordla continuera à surveiller la qualité des informations produits.',
  'gr.ct.empty.insufficientTitle': 'Données insuffisantes',
  'gr.ct.empty.insufficientText': 'Certaines dimensions du contenu produit ne sont pas encore disponibles dans Nordla : aucun produit n’est déclaré correct sans pouvoir le vérifier.',
  'gr.ct.banner.noImage': 'Images non vérifiables : aucune image produit n’est encore synchronisée pour cette boutique. Nordla ne peut donc pas distinguer un produit sans image d’une image non transmise ; ces produits sont en « Données insuffisantes », jamais « Correct ».',
  'gr.ct.d.problems': 'Problèmes détectés',
  'gr.ct.d.none': 'Aucun problème détectable avec les données disponibles.',
  'gr.ct.d.noneInsufficient': 'Aucun problème détecté, mais l’image ne peut pas être vérifiée : le produit n’est pas déclaré correct.',
  'gr.ct.d.why': 'Pourquoi c’est important',
  'gr.ct.d.sold': 'Ce produit s’est vendu {0} fois sur les {1} dernières semaines : ses informations sont réellement vues par des clients, il mérite d’être traité parmi les premiers.',
  'gr.ct.d.notSold': 'Aucune vente sur les {0} dernières semaines : moins urgent, mais sa fiche reste incomplète pour une utilisation future dans Growth ou d’autres canaux.',
  'gr.ct.d.reco': 'Recommandations',
  'gr.ct.d.unverified': 'Non vérifiable avec les données actuelles',
  'gr.ct.d.improve': 'Améliorer ce produit',
  'gr.ct.d.improveSoon': 'Bientôt disponible : Nordla ne modifie pas encore les fiches produits.',
  'gr.ct.d.method': 'Contrôles déterministes sur les données produit synchronisées dans Nordla. Aucun impact chiffré n’est promis : l’effet d’une meilleure fiche n’est pas mesuré.',
  'gr.ct.rule.MAJOR_PROBLEM': 'Le produit n’a pas d’image : il est difficile à comprendre ou à présenter sans visuel.',
  'gr.ct.rule.MANY_PROBLEMS': 'Au moins {0} problèmes à la fois : la fiche est incomplète sur plusieurs points.',
  'gr.ct.rule.MINOR_PROBLEMS': 'Problèmes non bloquants : le produit reste présentable mais sa fiche peut être complétée.',
  'gr.ct.rule.ESSENTIAL_CHECK_UNAVAILABLE': 'Aucun problème détecté, mais un contrôle essentiel (l’image) n’est pas vérifiable avec les données actuelles.',
  'gr.ct.rule.NO_DETECTABLE_PROBLEM': 'Aucun problème détectable avec les données que Nordla possède. Cela ne garantit pas un contenu parfait.',
  'gr.ct.fact.noImage': 'Aucune image principale n’est disponible pour ce produit.',
  'gr.ct.fact.noAltText': 'L’image principale n’a pas de texte alternatif.',
  'gr.ct.fact.noType': 'Le type de produit est vide dans la source.',
  'gr.ct.fact.noCollection': 'Le produit n’appartient à aucune collection actuelle.',
  'gr.ct.fact.missingSku': '{0} variante(s) sur {1} sans SKU.',
  'gr.ct.fact.duplicateTitle': '{0} autre(s) produit(s) actif(s) portent exactement le même nom.',
  'gr.ct.explain.noImage': 'Sans visuel, le client ne voit pas ce qu’il achète.',
  'gr.ct.explain.noAltText': 'Le texte alternatif décrit l’image pour l’accessibilité et les moteurs de recherche.',
  'gr.ct.explain.noType': 'Sans catégorie, le produit est mal classé dans la boutique et dans les analyses Nordla.',
  'gr.ct.explain.noCollection': 'Hors collection, le produit est plus difficile à trouver en navigation.',
  'gr.ct.explain.missingSku': 'Sans SKU, la variante est difficile à identifier en stock, en caisse ou sur d’autres canaux.',
  'gr.ct.explain.duplicateTitle': 'Deux produits au même nom se confondent pour le client et dans les rapports.',
  'gr.ct.reco.noImage': 'Ajouter une image produit de qualité.',
  'gr.ct.reco.noAltText': 'Ajouter un texte alternatif descriptif.',
  'gr.ct.reco.noType': 'Classer le produit dans une catégorie exploitable.',
  'gr.ct.reco.noCollection': 'Ajouter le produit à une collection pertinente.',
  'gr.ct.reco.missingSku': 'Attribuer un SKU unique à chaque variante.',
  'gr.ct.reco.duplicateTitle': 'Donner un nom distinctif à chaque produit.',
  'gr.ct.recoHow.noImage': 'Photo nette du produit réel, sur fond neutre, dans l’outil de la boutique.',
  'gr.ct.recoHow.noAltText': 'Décrire en quelques mots ce que montre l’image (produit, couleur, usage).',
  'gr.ct.recoHow.noType': 'Renseigner le type de produit dans la fiche de la boutique.',
  'gr.ct.recoHow.noCollection': 'Choisir la collection où un client le chercherait.',
  'gr.ct.recoHow.missingSku': 'Compléter le champ SKU de chaque variante concernée.',
  'gr.ct.recoHow.duplicateTitle': 'Ajouter ce qui les distingue (modèle, taille, couleur) dans le nom.',
});
