'use strict';
// English - Nordla Growth.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.en = Object.assign(window.NORDLA_DICTS.en || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.src.notConnected': 'Source not connected',
  'gr.src.unavailable': 'Data not available',
  'gr.ov.nc.influenced': 'Revenue influenced by Growth requires attributing sales to marketing actions. No attribution source is connected.',
  'gr.ov.nc.ai': 'No recommendation engine is connected to this card yet.',
  'gr.ov.nc.content': 'No social account is connected: content performance is not available.',
  'gr.vsPrevious': 'vs previous period',
  'gr.nav.aria': 'Growth navigation',
  'gr.nav.overview': 'Overview',
  'gr.nav.opportunities': 'Opportunities',
  'gr.nav.content': 'Content',
  'gr.nav.storeGrowth': 'Store Growth',
  'gr.nav.audience': 'Audience',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Settings',
  'gr.nav.soon': 'Coming soon',
  'gr.nav.more': 'More',
  'gr.nav.moreTitle': 'Other Growth pages',
  'gr.period.last30': 'Last 30 days',
  'gr.period.fixed': 'Fixed',
  'gr.period.fixedNote': 'The Growth view shows the last 30 days.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Nordla checks the quality of your product listings and data, tells you what to fix first, and will flag the products or moments to promote as soon as sales and purchase costs are reliable enough.',
  'gr.kpi.revenueInfluenced': 'Revenue influenced',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Metric shown',
  'gr.pulse.revenue': 'Revenue',
  'gr.pulse.traffic': 'Store traffic',
  'gr.ai.title': 'Nordla AI insights',
  'gr.ai.badge': 'Nordla AI',
  'gr.att.title': 'Needs your attention',
  'gr.content.title': 'Content performance',
  'gr.store.title': 'Store growth',
  'gr.store.traffic': 'Store traffic',
  'gr.store.conversion': 'Conversion rate',
  'gr.store.revenue': 'In-store revenue',
  'gr.store.pts': '{0} pts',
  'gr.opp.title': 'Commercial opportunities',
  'gr.noData': 'Data unavailable',
  'gr.loadError': 'The Growth view could not be loaded.',
  'gr.op.title': 'Opportunities',
  'gr.op.subtitle': 'What to fix first, the opportunities your data confirms, and the signals still too weak to act on.',
  // Potentiel produits
  'gr.nav.potential': 'Product potential',
  'gr.period.lastWeeks': 'Last {0} weeks',
  'gr.period.weeksNote': 'Analysis over the last {0} complete weeks.',
  'gr.pp.title': 'Product potential',
  'gr.pp.subtitle': 'See which products to push, watch or protect based on demand, stock and profitability.',
  'gr.pp.days': '{0} d',
  'gr.pp.unit1': '{0} unit sold',
  'gr.pp.uN': '{0} units',
  'gr.pp.u1': '{0} unit',
  'gr.pp.units': '{0} units sold',
  'gr.pp.noImage': 'No synced image',
  'gr.pp.noCategory': 'No category',
  'gr.pp.openDetail': 'View details: {0}',
  'gr.pp.close': 'Close',
  'gr.pp.kpi.active': 'Active products',
  'gr.pp.kpi.activeNote': 'Sold in the last {0} weeks',
  'gr.pp.kpi.push': 'Products to push',
  'gr.pp.kpi.pushNote': '{0} of the period’s sales',
  'gr.pp.kpi.pushNone': 'None meets every condition',
  'gr.pp.kpi.watch': 'To watch',
  'gr.pp.kpi.watchNote': 'Decline, low margin, returns or a mixed signal',
  'gr.pp.kpi.restock': 'Restock before promotion',
  'gr.pp.kpi.restockNote': 'Good demand, stock too short',
  'gr.pp.list.title': 'Products',
  'gr.pp.list.desc': 'Every product sold in the last {0} weeks, with its Growth status and the signal behind it.',
  'gr.pp.list.foot': '{0} of {1} products shown',
  'gr.pp.quality.stock': 'Latest stock snapshot: {0} (used when under {1} h old)',
  'gr.pp.quality.noStock': 'No synced stock snapshot',
  'gr.pp.search': 'Search a product',
  'gr.pp.noMatch': 'No product matches these filters.',
  'gr.pp.empty.title': 'No product sold in the period',
  'gr.pp.empty.text': 'No synced sales in the last {0} weeks: nothing to recommend yet.',
  'gr.pp.f.aria': 'Filter by Growth status',
  'gr.pp.f.all': 'All',
  'gr.pp.f.push': 'To push',
  'gr.pp.f.growth': 'Strong growth',
  'gr.pp.f.top': 'Best sellers',
  'gr.pp.f.watch': 'To watch',
  'gr.pp.f.restock': 'Restock first',
  'gr.pp.f.lowMargin': 'Low margin',
  'gr.pp.f.insufficient': 'Insufficient data',
  'gr.pp.f.category': 'Category',
  'gr.pp.f.allCategories': 'All categories',
  'gr.pp.f.sort': 'Sort',
  'gr.pp.f.sort.sales': 'Sort by sales',
  'gr.pp.f.sort.evolution': 'Sort by change',
  'gr.pp.f.sort.cover': 'Sort by cover',
  'gr.pp.f.sort.margin': 'Sort by margin',
  'gr.pp.col.product': 'Product',
  'gr.pp.col.sales': 'Sales',
  'gr.pp.col.evolution': 'Change',
  'gr.pp.col.margin': 'Margin',
  'gr.pp.col.stock': 'Stock',
  'gr.pp.col.cover': 'Cover',
  'gr.pp.col.status': 'Status · signal',
  'gr.pp.evo.insufficient': 'Insufficient history',
  'gr.pp.trend.UP': 'Rising',
  'gr.pp.trend.DOWN': 'Falling',
  'gr.pp.trend.FLAT': 'Steady',
  'gr.pp.margin.MISSING': 'Cost missing',
  'gr.pp.margin.PARTIAL': 'Partial margin',
  'gr.pp.margin.UNVERIFIED': 'Cost not verified',
  'gr.pp.margin.RELIABLE': 'Cost verified',
  'gr.pp.stock.stale': 'Old snapshot',
  'gr.pp.stock.unavailable': 'Stock unavailable',
  'gr.pp.cover.OUT': 'Out of stock',
  'gr.pp.cover.STOCK_UNUSABLE': 'Cover not calculated: stock unavailable or snapshot too old.',
  'gr.pp.cover.INSUFFICIENT_HISTORY': 'Cover not calculated: not enough sales history.',
  'gr.pp.cover.INSUFFICIENT_SALES_SAMPLE': 'Cover not calculated: too few sales to estimate a pace.',
  'gr.pp.cover.NO_DEMAND_OBSERVED': 'Cover not calculated: no demand observed.',
  'gr.pp.cover.NO_STOCK': 'Out of stock.',
  'gr.pp.cover.UNKNOWN': 'Cover not calculated.',
  'gr.pp.status.push': 'Push',
  'gr.pp.status.restock': 'Restock before promotion',
  'gr.pp.status.topSeller': 'Top seller',
  'gr.pp.status.watch': 'Watch',
  'gr.pp.status.declining': 'Declining',
  'gr.pp.status.lowMargin': 'Low margin',
  'gr.pp.status.returns': 'Too many returns',
  'gr.pp.status.insufficient': 'Insufficient data',
  'gr.pp.status.stable': 'Steady',
  'gr.pp.signal.newProduct': 'New product: under {0} weeks of sales',
  'gr.pp.signal.thinSample': '{0}: sample too small',
  'gr.pp.signal.outOfStock': 'Demand present, out of stock',
  'gr.pp.signal.coverDays': 'Stock for only {0} days',
  'gr.pp.signal.returnRate': '{0} of units refunded',
  'gr.pp.signal.margin': 'Verified margin of {0}',
  'gr.pp.signal.evolution': '{0} vs previous {1} wk',
  'gr.pp.signal.topRank': 'No. {0} in sales over the period',
  'gr.pp.signal.none': 'No particular signal',
  'gr.pp.action.increaseVisibility': 'Increase visibility',
  'gr.pp.action.restockFirst': 'Restock first',
  'gr.pp.action.doNotPromote': 'Do not promote',
  'gr.pp.action.reviewReturns': 'Review returns',
  'gr.pp.action.checkCost': 'Check the cost',
  'gr.pp.action.checkStock': 'Check the stock',
  'gr.pp.action.watch': 'Watch',
  'gr.pp.action.keep': 'Keep available',
  'gr.pp.action.none': 'No action',
  'gr.pp.actionText.increaseVisibility': 'Give it more visibility: in the online store, the shop window or a next campaign. Stock and margin can keep up.',
  'gr.pp.actionText.restockFirst': 'Restock before any promotion: promoting now would mostly create stock-outs.',
  'gr.pp.actionText.doNotPromote': 'Do not spend on visibility for this product until the margin or returns are fixed.',
  'gr.pp.actionText.reviewReturns': 'Look at the refund reasons (quality, size, description) before giving it more visibility.',
  'gr.pp.actionText.checkCost': 'Demand is rising but the margin is not reliable: enter or verify the purchase cost to know whether pushing it pays.',
  'gr.pp.actionText.checkStock': 'Demand is rising but stock is not known for sure: check it before any promotion.',
  'gr.pp.actionText.watch': 'No immediate action: follow the trend over the coming weeks.',
  'gr.pp.actionText.keep': 'Keep it available and visible as today; no extra promotion is needed.',
  'gr.pp.actionText.none': 'Not enough evidence to recommend an action: Nordla waits for more sales.',
  'gr.pp.reason.COST_MISSING': 'Cost missing',
  'gr.pp.reason.MARGIN_PARTIAL': 'Partial margin',
  'gr.pp.reason.COST_UNVERIFIED': 'Cost not verified',
  'gr.pp.reason.STOCK_STALE': 'Old stock snapshot',
  'gr.pp.reason.STOCK_UNAVAILABLE': 'Stock unavailable',
  'gr.pp.reason.COVER_UNKNOWN': 'Cover not computable',
  'gr.pp.reason.HIGH_RETURNS': 'Too many returns',
  'gr.pp.reason.RETURNS_ELEVATED': 'High returns',
  'gr.pp.reason.TREND_INSUFFICIENT': 'Insufficient history',
  'gr.pp.push.title': 'Products to push',
  'gr.pp.push.none': 'No product meets the four conditions to be pushed today:',
  'gr.pp.push.cond.demand': 'rising demand;',
  'gr.pp.push.cond.cover': 'known stock covering at least {0} weeks;',
  'gr.pp.push.cond.cost': 'verified purchase cost (reliable margin);',
  'gr.pp.push.cond.returns': 'returns at most {0}.',
  'gr.pp.push.foot': 'Rising demand, enough stock, verified cost and normal returns.',
  'gr.pp.protect.title': 'Protect / do not push',
  'gr.pp.protect.none': 'No product to protect for now.',
  'gr.pp.protect.foot': 'Restock, returns, low margin, mixed signals or decline.',
  'gr.pp.byStatus.title': 'Products by Growth status',
  'gr.pp.byStatus.foot': '{0} active products classified',
  'gr.pp.d.why': 'Why this status',
  'gr.pp.d.evidence': 'Evidence (last {0} weeks)',
  'gr.pp.d.action': 'Recommended action',
  'gr.pp.d.method': 'Status computed from the sales, stock, costs and refunds synced into Nordla. An unknown value is never counted as zero.',
  'gr.pp.ev.sales': 'Net sales excl. VAT',
  'gr.pp.ev.salesNote': 'No. {0} of the period',
  'gr.pp.ev.units': 'Units sold',
  'gr.pp.ev.velocity': '{0} per week on average',
  'gr.pp.ev.evoNote': '{0} u. vs {1} u. ({2} wk vs {2} wk)',
  'gr.pp.ev.evoNone': 'At least {0} weeks of sales are needed to compare.',
  'gr.pp.ev.snapshot': 'Snapshot of {0}',
  'gr.pp.ev.snapshotOld': 'Last snapshot on {0}: too old to decide',
  'gr.pp.ev.noSnapshot': 'No synced stock snapshot',
  'gr.pp.ev.coverNote': 'Restock threshold: {0} weeks',
  'gr.pp.ev.refunds': 'Refunds',
  'gr.pp.ev.refundNote': 'Units refunded: {0}',
  'gr.pp.ev.history': 'Observed history',
  'gr.pp.ev.weeks': '{0} wk',
  'gr.pp.rule.NEW_PRODUCT': 'This product has only {0} weeks of observed sales; at least {1} are needed before recommending anything.',
  'gr.pp.rule.THIN_SAMPLE': '{0} in {2} weeks: at least {1} are needed to conclude.',
  'gr.pp.rule.DEMAND_BUT_OUT_OF_STOCK': 'Demand is good but the product is out of stock: promoting it would send customers to a stock-out.',
  'gr.pp.rule.DEMAND_BUT_LOW_COVER': 'Demand is good but stock covers only {0} days (under {1} weeks): restock before any promotion.',
  'gr.pp.rule.DEMAND_BUT_HIGH_RETURNS': 'Demand is good, but {0} of the units sold were refunded: understand why before pushing it.',
  'gr.pp.rule.HIGH_RETURNS': '{0} of the units sold were refunded (threshold: {1}).',
  'gr.pp.rule.LOW_RELIABLE_MARGIN': 'Reliable margin of {0}, below the {1} threshold: each extra sale earns little.',
  'gr.pp.rule.TREND_DOWN': 'Sales in the last {0} weeks are down on the previous {0} ({1} u. vs {2} u.).',
  'gr.pp.rule.PUSH': 'Rising demand ({0} u. vs {1} u. over {2} weeks), enough stock, verified cost and normal returns: the product can absorb more visibility.',
  'gr.pp.rule.BLOCKED': 'Demand is rising ({0} u. vs {1} u. over {2} weeks), but one condition to push it is missing: {3}.',
  'gr.pp.blocked.checkStock': 'stock unknown or snapshot too old',
  'gr.pp.blocked.checkCost': 'purchase cost not verified',
  'gr.pp.blocked.reviewReturns': 'returns above {0}',
  'gr.pp.blocked.watch': 'stock cover not computable',
  'gr.pp.rule.TOP_SELLER': 'No. {0} in sales over the period, with no new rising signal: keeping it available is enough.',
  'gr.pp.rule.TOP_SELLER_RETURNS': 'Top seller, but {0} of the units sold were refunded (above {1}): understand these returns before any restock or promotion.',
  'gr.pp.rule.NO_SIGNAL': 'Regular sales, with no rising, falling or risk signal.',
  // Audience
  'gr.period.lastDays': 'Last {0} days',
  'gr.period.daysNote': 'Analysis over the last {0} complete days, compared with the {0} days before.',
  'gr.au.title': 'Audience',
  'gr.au.subtitle': 'See which customer segments are a growth opportunity.',
  'gr.au.vsPrevious': 'vs previous period',
  'gr.au.pts': '{0} pts',
  'gr.au.daysAgo': '{0} d ago',
  'gr.au.open': 'Open',
  'gr.au.openSegment': 'View segment: {0}',
  'gr.au.kpi.active': 'Active customers',
  'gr.au.kpi.new': 'New customers',
  'gr.au.kpi.repeatRate': 'Repeat rate',
  'gr.au.kpi.aov': 'Average order',
  'gr.au.kpi.toReactivate': 'Customers to reactivate',
  'gr.au.kpi.orders': 'Orders',
  'gr.au.kpi.netSales': 'Net sales excl. VAT',
  'gr.au.kpi.returningOrders': 'Orders from returning customers',
  'gr.au.kpi.multiProduct': 'Multi-product orders',
  'gr.au.kpi.noPrevious': 'No comparable previous period',
  'gr.au.kpi.notComputable': 'Not computable',
  'gr.au.kpi.fromZero': '0 in the previous period',
  'gr.au.kpi.sampleGate': 'Fewer than {0} active customers: not computed',
  'gr.au.kpi.historyGate': 'History shorter than {0} days: not computed',
  'gr.au.kpi.indexMissing': 'Customer order index not provided by the source',
  'gr.au.dist.title': 'Segment breakdown',
  'gr.au.dist.ordersTitle': 'Order breakdown',
  'gr.au.dist.value': '{0} ({1})',
  'gr.au.dist.revenue': '{0} of sales',
  'gr.au.dist.foot': '{0} identified customers. Each customer belongs to one segment only (total 100 %). Share of sales: purchases of the last {1} days.',
  'gr.au.dist.ordersFoot': 'Orders of the last {0} days by the order index provided by the source. Each order is counted once.',
  'gr.au.dist.noIndex': 'None of the period’s {0} orders carries a customer order index from the source: first and repeat purchases cannot be told apart.',
  'gr.au.orderGroup.new': 'First purchase (online)',
  'gr.au.orderGroup.returning': 'Returning customer',
  'gr.au.orderGroup.first_recorded_pos': 'First recorded in-store purchase',
  'gr.au.orderGroup.unknown': 'Order index unknown',
  'gr.au.seg.loyal': 'Loyal customers',
  'gr.au.seg.returning': 'Returning customers',
  'gr.au.seg.newReturned': 'Promising new customers',
  'gr.au.seg.new': 'New customers',
  'gr.au.seg.reactivate': 'Customers to reactivate',
  'gr.au.seg.occasional': 'One-time buyers to convert',
  'gr.au.seg.unknown': 'History not established',
  'gr.au.segDef.loyal': '≥ 3 orders, one of them recent',
  'gr.au.segDef.returning': '2 orders, one of them recent',
  'gr.au.segDef.newReturned': 'New, already came back',
  'gr.au.segDef.new': 'Recent first order',
  'gr.au.segDef.reactivate': '≥ 2 orders, none recent',
  'gr.au.segDef.occasional': '1 old order, did not come back',
  'gr.au.segDef.unknown': '1 recent order, first not proven',
  'gr.au.segRule.loyal': 'Identified customer with at least 3 known orders (or a source order number ≥ 3), at least one in the last {0} days.',
  'gr.au.segRule.returning': 'Identified customer with exactly 2 known orders, at least one in the last {0} days, whose first order is not recent.',
  'gr.au.segRule.newReturned': 'Proven first order (source order number = 1) in the last {0} days, and at least one more order since: the customer already came back.',
  'gr.au.segRule.new': 'Proven first order (source order number = 1) in the last {0} days, with no other order yet.',
  'gr.au.segRule.reactivate': 'Identified customer with at least 2 orders (proven repeat buyer) but no order in the last {0} days.',
  'gr.au.segRule.occasional': 'Identified customer with a single known order, more than {0} days ago, who has not come back since.',
  'gr.au.segRule.unknown': 'A single order in the last {0} days without a reliable source order number (e.g. in-store sale): it cannot be known whether it is a first order. This group is not qualified.',
  'gr.au.status.priority': 'Priority',
  'gr.au.status.activate': 'To activate',
  'gr.au.status.develop': 'To develop',
  'gr.au.status.watch': 'Watch',
  'gr.au.status.insufficient': 'Insufficient data',
  'gr.au.rule.INSUFFICIENT': 'Not enough data for a reliable recommendation: Growth draws no conclusion from this segment for now.',
  'gr.au.rule.REPEAT_BUYERS_WITHOUT_RECENT_ORDER': 'These customers proved they buy again (at least 2 orders) but have not ordered recently: an identifiable group to reach again.',
  'gr.au.rule.REVENUE_SHARE_ABOVE_CUSTOMER_SHARE': 'This segment weighs {0} of recent sales for {1} of active customers: it contributes more than its weight.',
  'gr.au.rule.SMALLER_THAN_PREVIOUS_WINDOW': 'This segment has fewer customers than in the previous period ({2}).',
  'gr.au.rule.ONE_ORDER_NOT_REPEATED': 'These customers bought once, before the period, and did not come back: a second order is still to be won.',
  'gr.au.rule.ACTIVE_SEGMENT': 'Active, large enough segment, with no particular over-contribution or decline signal.',
  'gr.au.reason.SAMPLE_BELOW_MIN_CUSTOMERS': 'Fewer than {0} identified customers in total',
  'gr.au.reason.SEGMENT_BELOW_MIN_GROUP': 'Segment below {1} customers',
  'gr.au.reason.SHORT_HISTORY': 'History too short',
  'gr.au.reason.FIRST_ORDER_NOT_PROVEN': 'First order not proven',
  'gr.au.action.reactivation': 'Prepare a reactivation campaign',
  'gr.au.action.loyalty': 'Strengthen loyalty',
  'gr.au.action.secondPurchase': 'Prepare a second-purchase offer',
  'gr.au.action.targetedOffer': 'Test a targeted offer',
  'gr.au.action.none': 'No action for now',
  'gr.au.actionText.reactivation': 'Reach this group with a simple message or offer, then measure how many come back. Test small first.',
  'gr.au.actionText.loyalty': 'Recognise and reward these customers (loyalty perk, early access) to keep their buying pace.',
  'gr.au.actionText.secondPurchase': 'Give a reason to come back after the first order (product suggestion, time-limited offer).',
  'gr.au.actionText.targetedOffer': 'Test an offer matched to what they first bought, on a small group, before widening it.',
  'gr.au.actionText.none': 'Growth recommends nothing for this segment while the data is insufficient.',
  'gr.au.prio.title': 'Priority segments',
  'gr.au.prio.foot': 'Ranked by status, then size. Statuses come from explicit rules, no score.',
  'gr.au.col.segment': 'Segment',
  'gr.au.col.size': 'Size',
  'gr.au.col.revenueShare': 'Share of sales',
  'gr.au.col.status': 'Status',
  'gr.au.col.action': 'Recommended action',
  'gr.au.col.customers': 'Customers',
  'gr.au.col.frequency': 'Orders / customer',
  'gr.au.col.revenue': 'Sales {0} d',
  'gr.au.col.aov': 'Average order',
  'gr.au.col.recency': 'Last order',
  'gr.au.col.statusAction': 'Status · action',
  'gr.au.sig.title': 'Audience signals',
  'gr.au.sig.foot': 'Observed facts, compared with a reference. No prediction.',
  'gr.au.sig.none': 'No reliable signal: at least {0} identified customers are needed.',
  'gr.au.sig.repeatRevenueShare.title': 'Repeat buyers bring {0} of sales',
  'gr.au.sig.repeatRevenueShare.text': 'They are {0} of active customers but {1} of sales over the last {2} days: they weigh more than their number.',
  'gr.au.sig.reactivation.title': '{0} repeat buyers with no order for {1} days',
  'gr.au.sig.reactivation.text': 'They generated {0} over the observed history: an identifiable group to reach again.',
  'gr.au.sig.repeatRateUp.title': 'The repeat rate is rising',
  'gr.au.sig.repeatRateDown.title': 'The repeat rate is falling',
  'gr.au.sig.repeatRateChange.text': '{0} of active customers have bought at least twice, vs {1} in the previous {2} days.',
  'gr.au.sig.aovGap.title': 'Average order: returning vs new',
  'gr.au.sig.aovGap.text': '{0} for repeat buyers vs {1} for new customers (observed orders).',
  'gr.au.sig.coverage.title': '{0} of orders are linked to a customer',
  'gr.au.sig.coverage.text': '{0} anonymous orders (often in-store) are in no segment: segments describe identified customers only.',
  'gr.au.sig.returningOrders.title': '{0} of orders come from returning customers',
  'gr.au.sig.returningOrders.text': 'Out of {0} orders with a known order index (a lower bound, the source history may be incomplete).',
  'gr.au.sig.aovUp.title': 'The average order is rising',
  'gr.au.sig.aovDown.title': 'The average order is falling',
  'gr.au.sig.aovChange.text': '{0} vs {1} in the previous {2} days.',
  'gr.au.sig.multiProduct.title': '{0} of orders contain several products',
  'gr.au.sig.multiProduct.text': 'Out of {0} orders: shows the share of combined purchases, useful for bundle offers.',
  'gr.au.sig.customerLevelMissing.title': 'Customer segments unavailable',
  'gr.au.sig.customerLevelMissing.text': 'No order carries a pseudonymous customer id: Nordla cannot group purchases by customer. Indicators stay at order level.',
  'gr.au.list.title': 'Customer segments ({0})',
  'gr.au.list.desc': 'Exclusive groups of identified customers, defined by their observed orders. “Recent” = within the last {0} days.',
  'gr.au.list.foot': '{0} identified customers · {1} of the period’s orders linked to a customer · No customer is shown individually.',
  'gr.au.act.title': 'Recommended actions ({0})',
  'gr.au.act.target': 'Target: {0} ({1} customers)',
  'gr.au.act.toTest': 'To test',
  'gr.au.act.prerequisite': 'Prerequisite',
  'gr.au.act.none': 'No recommended action: no segment is large or established enough.',
  'gr.au.act.foot': 'Qualitative benefits only: no CRM or e-mail tool is connected, no result is promised.',
  'gr.au.actTitle.reactivation': 'Prepare a reactivation campaign',
  'gr.au.actTitle.loyalty': 'Strengthen loyalty',
  'gr.au.actTitle.secondPurchase': 'Prepare a second-purchase offer',
  'gr.au.actTitle.targetedOffer': 'Test a targeted offer',
  'gr.au.actTitle.growSample': 'Wait for a sufficient sample',
  'gr.au.actTitle.enableCustomerKey': 'Enable pseudonymous customer identification',
  'gr.au.actWhy.growSample': 'Too few identified customers to qualify segments.',
  'gr.au.actWhy.enableCustomerKey': 'No synced order carries a pseudonymous customer key.',
  'gr.au.actBenefit.reactivation': 'Possible reactivation of buyers who already proved their interest.',
  'gr.au.actBenefit.loyalty': 'Protect the segment that weighs most in sales.',
  'gr.au.actBenefit.secondPurchase': 'Turn a first order into a habit.',
  'gr.au.actBenefit.targetedOffer': 'Win a second order from customers already acquired.',
  'gr.au.actBenefit.growSample': 'Reliable segments once the sample is reached.',
  'gr.au.actBenefit.enableCustomerKey': 'Unlocks the segments (loyal, to reactivate, new) without storing any identity: only a keyed fingerprint is kept.',
  'gr.au.noKey.banner': 'Customer level unavailable: no order carries a pseudonymous customer id. The page stays at order level and targets no individual customer.',
  'gr.au.noKey.text': 'These segments need pseudonymous customer identification, which is not active for this store:',
  'gr.au.d.window': 'Reference: last {0} days',
  'gr.au.d.definition': 'Definition',
  'gr.au.d.sizeValue': 'Size and value',
  'gr.au.d.size': 'Customers',
  'gr.au.d.sizeNote': '{0} of identified customers',
  'gr.au.d.evolution': 'Previous period',
  'gr.au.d.noPrevious': 'No comparable period',
  'gr.au.d.same': 'Unchanged: {0} customers',
  'gr.au.d.previous': '{0} customers in the previous period',
  'gr.au.d.noWindowPurchase': 'No order in the period, by definition',
  'gr.au.d.revenueShare': '{0} of active customers’ sales',
  'gr.au.d.historyRevenue': 'Observed sales (history)',
  'gr.au.d.historyNote': 'Over {0} days of loaded history',
  'gr.au.d.aovNote': 'All their observed orders',
  'gr.au.d.frequencyNote': 'Known orders per customer',
  'gr.au.d.recencyNote': 'Segment median',
  'gr.au.d.why': 'Why Growth flags it',
  'gr.au.d.action': 'Suggested action',
  'gr.au.d.method': 'Segment computed from the orders synced into Nordla, grouped by pseudonymous customer id. No personal data is read or shown. Observation, not prediction.',
  'gr.au.empty.title': 'No orders in the period',
  'gr.au.empty.text': 'No synced orders: Audience has nothing to analyse yet.',
  'gr.au.empty.window': 'No data over the last {0} days.',
  // Contenu
  'gr.ct.title': 'Content',
  'gr.ct.subtitle': 'Spot incomplete product pages and the improvements to make first.',
  'gr.ct.status.priority': 'High priority',
  'gr.ct.status.improve': 'Needs improvement',
  'gr.ct.status.insufficient': 'Insufficient data',
  'gr.ct.status.correct': 'No issue found',
  'gr.ct.problem.noImage': 'No image',
  'gr.ct.problem.noAltText': 'No alt text',
  'gr.ct.problem.noType': 'No category',
  'gr.ct.problem.noCollection': 'In no collection',
  'gr.ct.problem.missingSku': 'Missing SKU',
  'gr.ct.problem.duplicateTitle': 'Duplicate name',
  'gr.ct.kpi.toImprove': 'Products to improve',
  'gr.ct.kpi.toImproveNote': 'At least one issue, out of {0} active products',
  'gr.ct.kpi.noImage': 'No image',
  'gr.ct.kpi.noImageNote': 'No main image',
  'gr.ct.kpi.noAltText': 'No alt text',
  'gr.ct.kpi.noAltTextNote': 'Image without description',
  'gr.ct.kpi.noType': 'No category',
  'gr.ct.kpi.noTypeNote': 'Empty product type',
  'gr.ct.kpi.missingSku': 'Missing SKU',
  'gr.ct.kpi.missingSkuNote': 'At least one variant without SKU',
  'gr.ct.kpi.unavailable': 'Not verifiable with current data',
  'gr.ct.prio.title': 'Products by priority',
  'gr.ct.prio.total': 'products',
  'gr.ct.prio.foot': '{0} active products analysed, each counted once.',
  'gr.ct.problems.title': 'Main content issues',
  'gr.ct.problems.none': 'No issue found among the checks that can run.',
  'gr.ct.problems.notChecked': 'Not checked with current data: {0}.',
  'gr.ct.na.description': 'description',
  'gr.ct.na.reviews': 'customer reviews',
  'gr.ct.na.multipleImages': 'multiple images',
  'gr.ct.na.seo': 'SEO title and meta',
  'gr.ct.na.attributes': 'product attributes',
  'gr.ct.search': 'Search a product or SKU',
  'gr.ct.f.status': 'Status',
  'gr.ct.f.allStatuses': 'All statuses',
  'gr.ct.f.problem': 'Issue',
  'gr.ct.f.allProblems': 'All issues',
  'gr.ct.f.category': 'Category',
  'gr.ct.f.allCategories': 'All categories',
  'gr.ct.noSku': 'No SKU',
  'gr.ct.col.product': 'Product',
  'gr.ct.col.category': 'Category',
  'gr.ct.col.problems': 'Issues',
  'gr.ct.col.status': 'Status',
  'gr.ct.col.sales': 'Sales ({0} wk)',
  'gr.ct.col.action': 'Action',
  'gr.ct.noProblemYet': 'No issue found (image not verifiable)',
  'gr.ct.noProblem': 'No issue found',
  'gr.ct.seeReco': 'See recommendations',
  'gr.ct.seeDetail': 'View details',
  'gr.ct.list.title': 'Products',
  'gr.ct.list.foot': '{0} of {1} active products shown ({2} in the catalogue, drafts and archived excluded). Sorted by priority, then sales.',
  'gr.ct.empty.noProducts': 'No active product to analyse.',
  'gr.ct.empty.clearTitle': 'No content issue found with the data currently available.',
  'gr.ct.empty.clearText': 'Nordla will keep monitoring the quality of product information.',
  'gr.ct.empty.insufficientTitle': 'Insufficient data',
  'gr.ct.empty.insufficientText': 'Some dimensions of product content are not available in Nordla yet: no product is declared fine without being checked.',
  'gr.ct.banner.noImage': 'Images not verifiable: no product image is synced for this store yet. Nordla therefore cannot tell a product without an image from an image that was not sent; these products are “Insufficient data”, never “No issue found”.',
  'gr.ct.d.problems': 'Issues found',
  'gr.ct.d.none': 'No detectable issue with the available data.',
  'gr.ct.d.noneInsufficient': 'No issue found, but the image cannot be checked: the product is not declared fine.',
  'gr.ct.d.why': 'Why it matters',
  'gr.ct.d.sold': 'This product sold {0} times over the last {1} weeks: its information is really seen by customers, it deserves to be handled early.',
  'gr.ct.d.notSold': 'No sale over the last {0} weeks: less urgent, but its page stays incomplete for future use in Growth or other channels.',
  'gr.ct.d.reco': 'Recommendations',
  'gr.ct.d.unverified': 'Not verifiable with current data',
  'gr.ct.d.method': 'Deterministic checks on the product data synced into Nordla. No figure is promised: the effect of a better page is not measured.',
  'gr.ct.rule.MAJOR_PROBLEM': 'The product has no image: it is hard to understand or present without a visual.',
  'gr.ct.rule.MANY_PROBLEMS': 'At least {0} issues at once: the page is incomplete on several points.',
  'gr.ct.rule.MINOR_PROBLEMS': 'Non-blocking issues: the product stays presentable but its page can be completed.',
  'gr.ct.rule.ESSENTIAL_CHECK_UNAVAILABLE': 'No issue found, but an essential check (the image) cannot run with current data.',
  'gr.ct.rule.NO_DETECTABLE_PROBLEM': 'No detectable issue with the data Nordla has. This does not guarantee perfect content.',
  'gr.ct.fact.noImage': 'No main image is available for this product.',
  'gr.ct.fact.noAltText': 'The main image has no alt text.',
  'gr.ct.fact.noType': 'The product type is empty in the source.',
  'gr.ct.fact.noCollection': 'The product belongs to no current collection.',
  'gr.ct.fact.missingSku': '{0} of {1} variant(s) without SKU.',
  'gr.ct.fact.duplicateTitle': '{0} other active product(s) carry exactly the same name.',
  'gr.ct.explain.noImage': 'Without a visual, the customer does not see what they buy.',
  'gr.ct.explain.noAltText': 'Alt text describes the image for accessibility and search engines.',
  'gr.ct.explain.noType': 'Without a category, the product is poorly classified in the store and in Nordla analyses.',
  'gr.ct.explain.noCollection': 'Outside any collection, the product is harder to find when browsing.',
  'gr.ct.explain.missingSku': 'Without a SKU, the variant is hard to identify in stock, at the till or on other channels.',
  'gr.ct.explain.duplicateTitle': 'Two products with the same name get confused by customers and in reports.',
  'gr.ct.reco.noImage': 'Add a quality product image.',
  'gr.ct.reco.noAltText': 'Add a descriptive alt text.',
  'gr.ct.reco.noType': 'Put the product in a usable category.',
  'gr.ct.reco.noCollection': 'Add the product to a relevant collection.',
  'gr.ct.reco.missingSku': 'Give each variant a unique SKU.',
  'gr.ct.reco.duplicateTitle': 'Give each product a distinctive name.',
  'gr.ct.recoHow.noImage': 'Sharp photo of the real product, on a neutral background, in the store tool.',
  'gr.ct.recoHow.noAltText': 'Describe in a few words what the image shows (product, colour, use).',
  'gr.ct.recoHow.noType': 'Fill in the product type in the store product page.',
  'gr.ct.recoHow.noCollection': 'Pick the collection where a customer would look for it.',
  'gr.ct.recoHow.missingSku': 'Complete the SKU field of each variant concerned.',
  'gr.ct.recoHow.duplicateTitle': 'Add what sets them apart (model, size, colour) to the name.',
  // Croissance magasin
  'gr.st.title': 'Store Growth',
  'gr.st.subtitle': 'Analyse your physical store’s sales and the local actions worth considering.',
  'gr.st.vsPrevious': 'vs previous 8 weeks',
  'gr.st.kpi.storeNet': 'Store sales (excl. VAT)',
  'gr.st.kpi.storeOrders': 'Store orders',
  'gr.st.kpi.storeAov': 'Store average order',
  'gr.st.kpi.storeShare': 'Store share',
  'gr.st.kpi.locations': 'Active stores',
  'gr.st.kpi.locationsNote': 'With sales in the period ({0} known location(s))',
  'gr.st.kpi.locationsUnknown': '{0} order(s) without a location',
  'gr.st.kpi.noPrevious': 'No comparable previous period',
  'gr.st.kpi.notComputable': 'Not computable',
  'gr.st.kpi.fromZero': '0 in the previous period',
  'gr.st.banner.footfall': 'Footfall not connected: the figures below are sales, not visitors. No conversion rate or visitor count is computed.',
  'gr.st.perf.title': 'Store performance',
  'gr.st.perf.metric': 'Metric',
  'gr.st.perf.sales': 'Store sales per week',
  'gr.st.perf.orders': 'Store orders per week',
  'gr.st.perf.channels': 'Store vs online (sales)',
  'gr.st.perf.store': 'Store',
  'gr.st.perf.online': 'Online',
  'gr.st.perf.current': 'Last 8 weeks',
  'gr.st.perf.previous': 'Previous 8 weeks',
  'gr.st.perf.foot': 'Complete weeks; each week is compared with the same position in the previous {0} weeks.',
  'gr.st.perf.footNoPrev': 'Complete weeks. No comparison: the history does not cover the previous {0} weeks.',
  'gr.st.days.title': 'Sales activity by day',
  'gr.st.days.orders': '{0} orders',
  'gr.st.days.foot': '{0} store orders in the period. Sales by weekday, not footfall; no finding below {1} orders.',
  'gr.st.products.title': 'Top store products',
  'gr.st.products.detail': '{0} · {1} of store sales',
  'gr.st.products.guard': 'Not highlighted: {0}',
  'gr.st.products.unknown': 'Product not linked to the catalogue',
  'gr.st.products.foot': 'Ranked by store sales over 8 weeks. Product potential guards (stock, margin, returns, decline) apply.',
  'gr.st.diff.title': 'Store / online differences',
  'gr.st.diff.aov': 'Average order: {0} in store vs {1} online.',
  'gr.st.diff.product': '{0} of store sales vs {1} of online sales',
  'gr.st.diff.none': 'No product weighs at least twice as much in store as online in the period.',
  'gr.st.diff.gated': 'Comparison available from {0} orders on each side (store: {1}, online: {2}).',
  'gr.st.diff.foot': 'Observed facts, with no assumed explanation.',
  'gr.st.loc.title': 'All stores ({0})',
  'gr.st.loc.store': 'Store',
  'gr.st.loc.orders': 'Orders',
  'gr.st.loc.net': 'Sales (excl. VAT)',
  'gr.st.loc.aov': 'Average order',
  'gr.st.loc.share': 'Share',
  'gr.st.loc.unnamed': 'Unnamed location',
  'gr.st.loc.unknown': 'Location not provided',
  'gr.st.loc.foot': 'KPIs add up all stores; no location is picked for you.',
  'gr.st.sig.title': 'Store signals',
  'gr.st.sig.none': 'No reliable signal: at least {0} store orders per compared period are needed (currently {1}).',
  'gr.st.sig.foot': 'Observed sales facts, compared with a reference. No assumed cause.',
  'gr.st.sig.storeFaster.title': 'The store grows faster than online',
  'gr.st.sig.onlineFaster.title': 'Online grows faster than the store',
  'gr.st.sig.storeVsOnline.text': 'Store sales {0} vs {1} online, over the last {2} weeks vs the previous ones.',
  'gr.st.sig.ordersUpAovDown.title': 'More orders, lower average order',
  'gr.st.sig.ordersDownAovUp.title': 'Fewer orders, higher average order',
  'gr.st.sig.ordersAov.text': 'Store orders {0}, average order {1} vs the previous 8 weeks.',
  'gr.st.sig.strongWeekday.title': '{0} accounts for {1} of store sales',
  'gr.st.sig.strongWeekday.text': 'Spread evenly, each day would hold {0}: this day weighs at least twice that.',
  'gr.st.sig.productGap.title': '{0} weighs more in store',
  'gr.st.sig.productGap.text': '{0} of store sales vs {1} of online sales.',
  'gr.st.sig.refundsUp.title': 'Store refunds rising',
  'gr.st.sig.refundsUp.text': '{0} of units sold refunded vs {1} in the previous 8 weeks.',
  'gr.st.act.title': 'Recommended local actions ({0})',
  'gr.st.act.none': 'No recommended action: at least {0} store orders in the period are needed.',
  'gr.st.act.foot': 'Based on observed sales only; none assumes store traffic.',
  'gr.st.act.restockFirst.title': 'Restock before any in-store animation',
  'gr.st.act.restockFirst.text': '{0} sells well in store but its stock covers too few weeks (Product potential).',
  'gr.st.act.highlightProduct.title': 'Highlight a store product more',
  'gr.st.act.highlightProduct.text': '{0} makes {1} of store sales and is blocked by no guard.',
  'gr.st.act.weekdayHighlight.title': 'Test a highlight on {0}',
  'gr.st.act.weekdayHighlight.text': 'This day makes {0} of store sales.',
  'gr.st.act.checkAov.title': 'Look into the lower average order',
  'gr.st.act.checkAov.text': 'More orders but a smaller basket: look at discounts and product mix.',
  'gr.st.future.title': 'Going further',
  'gr.st.future.footfall': 'Store footfall',
  'gr.st.future.googleBusiness': 'Google Business Profile',
  'gr.st.future.posEnriched': 'Enriched POS',
  'gr.st.future.unlocks': 'Would unlock: {0}',
  'gr.st.future.u.conversion': 'store conversion rate',
  'gr.st.future.u.visitors': 'visitors',
  'gr.st.future.u.salesPerVisitor': 'sales per visitor',
  'gr.st.future.u.directions': 'direction requests',
  'gr.st.future.u.calls': 'calls',
  'gr.st.future.u.localVisibility': 'local visibility',
  'gr.st.future.u.staff': 'sales per staff member',
  'gr.st.future.u.paymentMethods': 'payment methods',
  'gr.st.future.u.hours': 'reliable hours',
  'gr.st.future.notConnected': 'Source not connected',
  'gr.st.future.audience': 'Store audience',
  'gr.st.future.audienceNone': 'Store audience not identifiable: store orders carry no pseudonymous customer id.',
  'gr.st.future.audienceShare': '{0} of store orders linked to a customer (aggregated, see Audience).',
  'gr.st.future.partial': 'Partial',
  'gr.st.future.notIdentifiable': 'Not identifiable',
  'gr.st.future.foot': 'None of these sources is connected: coming soon. Nothing is simulated meanwhile.',
  'gr.st.empty.noStoreTitle': 'No identifiable store sale in this period.',
  'gr.st.empty.noStoreText': 'Growth can analyse the point of sale once a physical sales source is available. No order comes from a store channel: this is not “zero sales”, it is a missing source.',
  'gr.st.empty.window': 'No store sale in the last {0} weeks.',
  // Shared page states
  'gr.state.loading': 'Loading data…',
  'gr.state.errorTitle': 'Data unavailable',
  'gr.state.error.TENANT_NOT_CONFIGURED': 'No store is configured for Growth on this server.',
  'gr.state.error.DATA_UNAVAILABLE': 'The store data could not be read right now.',
  'gr.state.error.NETWORK': 'The Growth server is not responding. Check the connection.',
  'gr.state.error.UNKNOWN': 'An unexpected error prevented this page from loading.',
  'gr.state.retry': 'Try again',
  // Overview: capabilities not connected (deep audit P1-2)
  'gr.pulse.visitorsNotConnected': 'Footfall not connected',
  'gr.pulse.visitorsNotConnectedText': 'No footfall source is connected: Nordla does not know the store’s visitor count.',
  'gr.store.notConnected': 'Not connected',
  'gr.store.footfallNote': 'No footfall source',
  'gr.store.realRevenue': 'Store sales (last {0} wk)',
  'gr.store.realChip': 'Real data',
  'gr.store.noStore': 'No identifiable store sale',
  'gr.store.unavailable': 'Data unavailable',
  // Opportunités - priorities aggregated from the four real engines (2026-09-28).
  'gr.opp.emptyText': 'Nordla is waiting for more sales, more history or verified purchase costs before recommending a commercial action.',
  'gr.kpi.fix': 'To fix now',
  'gr.kpi.fixNote': '{0} items affected',
  'gr.kpi.commercial': 'Commercial opportunities',
  'gr.kpi.commercialNote': 'Confirmed by your data',
  'gr.kpi.watch': 'To watch',
  'gr.kpi.watchNote': 'Signals still too weak',
  'gr.ov.toOpportunities': 'See all priorities',
  'gr.ov.prioritiesUnavailable': 'Priorities unavailable right now.',
  'gr.op.kpi.fix': 'To fix now',
  'gr.op.kpi.fixNote': '{0} items affected',
  'gr.op.kpi.commercial': 'Commercial opportunities',
  'gr.op.kpi.commercialNote': 'Confirmed by the current thresholds',
  'gr.op.kpi.watch': 'To watch',
  'gr.op.kpi.watchNote': 'Signals still too weak',
  'gr.op.link.potential': 'See in Product potential',
  'gr.op.link.content': 'See in Content',
  'gr.op.link.storeGrowth': 'See in Store Growth',
  'gr.op.link.audience': 'See in Audience',
  'gr.op.fix.title': 'To fix now',
  'gr.op.fix.intro': 'Reliable problems in your data, grouped by problem. Fixing them makes the recommendations safer.',
  'gr.op.fix.empty': 'Nothing to fix in the analysed data.',
  'gr.op.fix.examples': 'Examples:',
  'gr.op.fix.soldAffected': '{0} among the products sold',
  'gr.op.fix.purchaseCost.title': 'Purchase costs to verify: {0} products sold',
  'gr.op.fix.purchaseCost.why': 'Nordla only recommends “Push” and only reports “Low margin” when the purchase cost is verified. These costs come from your shop without verification: those recommendations stay blocked.',
  'gr.op.fix.purchaseCost.detail': '{0} not verified · {1} missing',
  'gr.op.fix.purchaseCost.blocked': '{0} blocked recommendation(s)',
  'gr.op.fix.purchaseCost.pending': 'Purchase cost verification is not available in Nordla yet.',
  'gr.op.fix.content.missingSku.title': '{0} products without a SKU',
  'gr.op.fix.content.missingSku.why': 'Without a SKU, a product is harder to track in stock and to match with your supplier invoices.',
  'gr.op.fix.content.noType.title': '{0} products without a type',
  'gr.op.fix.content.noType.why': 'Without a product type, the product cannot be grouped by category in your analyses.',
  'gr.op.fix.content.noAltText.title': '{0} images without alt text',
  'gr.op.fix.content.noAltText.why': 'Without alt text, the image is described neither for screen readers nor for search engines.',
  'gr.op.fix.content.noImage.title': '{0} products without an image',
  'gr.op.fix.content.noImage.why': 'Without an image, the product is hard to recognise online.',
  'gr.op.fix.content.noCollection.title': '{0} products outside any collection',
  'gr.op.fix.content.noCollection.why': 'Outside a collection, the product is harder to find in the online shop.',
  'gr.op.fix.content.duplicateTitle.title': '{0} products with a duplicate title',
  'gr.op.fix.content.duplicateTitle.why': 'Two products with the same title are hard to tell apart, for you and for your customers.',
  'gr.op.com.title': 'Commercial opportunities',
  'gr.op.com.intro': 'Only what Nordla’s engines confirm with their current thresholds.',
  'gr.op.com.emptyTitle': 'No reliable commercial opportunity yet',
  'gr.op.com.emptyText': 'Nordla only recommends a commercial action when sales, history and purchase costs are reliable enough. It is waiting for:',
  'gr.op.wait.productSales': 'more sales per product: {0} of {1} products have too few sales over {2} weeks (fewer than {3} units);',
  'gr.op.wait.verifiedCosts': 'verified purchase costs: {0} of {1} products sold have none;',
  'gr.op.wait.identifiedCustomers': 'more identified customers: {0} of the {1} needed to form customer groups;',
  'gr.op.wait.storeHistory': 'a longer store history: Nordla compares the last {0} weeks with the {0} weeks before, not fully covered yet;',
  'gr.op.wait.onlineOrders': 'more online orders: {0} of the {1} needed to compare store and online;',
  'gr.op.wait.storeOrders': 'more store orders: {0} of the {1} needed;',
  'gr.op.item.product.push.title': 'Feature “{0}”',
  'gr.op.item.product.push.why': 'Rising demand, enough stock and a verified purchase cost, according to Product potential.',
  'gr.op.item.product.restock.title': 'Restock “{0}” before any promotion',
  'gr.op.item.product.restock.why': 'Good demand but stock too short, according to Product potential.',
  'gr.op.item.store.weekday.title': 'Prepare the store for {0}',
  'gr.op.item.store.weekday.why': 'This day makes {0} of your store sales, clearly more than the others, according to Store Growth.',
  'gr.op.item.segment.title': '{0}: {1} customers',
  'gr.op.item.segment.commercial.why': 'Customer group flagged as an opportunity by Audience.',
  'gr.op.item.segment.watch.why': 'Customer group to watch according to Audience.',
  'gr.op.watch.title': 'To watch',
  'gr.op.watch.intro': 'Interesting signals that are too weak, or blocked by a safeguard: Nordla does not recommend acting yet.',
  'gr.op.watch.empty': 'No signal to watch for now.',
  'gr.op.volume': '{0} sales in {1} weeks',
  'gr.op.volumeStore': 'no. {0} in the store ({1} of store sales)',
  'gr.op.why.risingBlocked': 'Demand is rising, but the purchase cost is not verified: Nordla does not recommend pushing this product until its margin is reliable.',
  'gr.op.why.watch': 'Product potential reports a point to check before any promotion.',
  'gr.op.why.declining': 'Sales are falling: Nordla does not recommend featuring it.',
  'gr.op.why.lowMargin': 'The verified margin is too low for a promotion.',
  'gr.op.why.returns': 'Returns are high: to be examined before any promotion.',
  'gr.op.why.storeSuggestionThin': 'Well placed in the store, but with so few sales Nordla cannot recommend featuring it yet.',
  'gr.op.why.notValidated': 'Signal not confirmed by Product potential.',
  'gr.op.why.noProductEngine': 'Store signal without enough product data.',
  'gr.op.f.potential.push': 'Push',
  'gr.op.f.potential.restock': 'Restock before promotion',
  'gr.op.f.potential.topSeller': 'Among your best sellers',
  'gr.op.f.potential.watch': 'To watch',
  'gr.op.f.potential.declining': 'Falling sales',
  'gr.op.f.potential.lowMargin': 'Low margin',
  'gr.op.f.potential.returns': 'High returns',
  'gr.op.f.potential.stable': 'Stable sales',
  'gr.op.f.potential.insufficient': 'Insufficient data',
  'gr.op.f.risingDemand': 'Rising demand',
  'gr.op.f.storeTop': 'No. {0} in the store',
  'gr.op.f.storeTopBlocked': 'No. {0} in the store, kept out of the highlight',
  'gr.op.f.storeSuggested': 'Store highlight suggested',
  'gr.op.f.storeSuggestedNotRecommended': 'Suggested in store, not recommended',
  'gr.op.f.costUnverified': 'Purchase cost not verified',
  'gr.op.f.costMissing': 'Purchase cost missing',
  'gr.op.f.contentIncomplete': 'Product listing incomplete',
  'gr.op.missing': 'Missing:',
  'gr.op.m.verifiedCost': 'a verified purchase cost',
  'gr.op.m.moreWeeks': 'more weeks of sales (at least {0} weeks and {1} sales)',
  'gr.op.m.risingDemand': 'rising demand',
  'gr.op.m.fewerReturns': 'fewer returns',
  'gr.op.m.productHistory': 'sales data for this product',
  'gr.op.rel.reliable': 'Reliable',
  'gr.op.rel.limited': 'Weak signal',
  'gr.op.foot': 'Facts observed in your data and recomputed on every visit. No assumed causality, no automatic action.',
  'gr.op.srcUnavailable': 'Source unavailable right now: {0}. The other sources are taken into account.',
});
