'use strict';
// Français - langue par défaut de Nordla Growth (même runtime NORDLA_I18N qu'Analytics Premium).
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.fr = Object.assign(window.NORDLA_DICTS.fr || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.src.unavailable': 'Donnée non disponible',
  'gr.vsPrevious': 'vs période précédente',
  'gr.nav.aria': 'Navigation Développement des ventes',
  'gr.nav.overview': 'Vue d’ensemble',
  'gr.nav.opportunities': 'Opportunités',
  'gr.nav.content': 'Contenu',
  'gr.nav.storeGrowth': 'Croissance magasin',
  'gr.nav.audience': 'Audience',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Paramètres',
  'gr.nav.soon': 'Bientôt disponible',
  'gr.nav.more': 'Plus',
  'gr.nav.moreTitle': 'Autres pages',
  'gr.period.last30': '30 derniers jours',
  'gr.period.fixed': 'Fixe',
  'gr.period.fixedNote': 'Cette vue affiche les 30 derniers jours.',
  'gr.title': 'Développement des ventes',
  'gr.subtitle': 'Nordla vérifie la qualité de vos fiches produit et de vos données, vous indique quoi corriger en premier et vous signalera les produits ou moments à pousser dès que les ventes et les coûts d’achat seront suffisamment fiables.',
  'gr.att.title': 'Nécessite votre attention',
  'gr.store.title': 'Croissance magasin',
  'gr.store.revenue': 'CA magasin',
  'gr.store.pts': '{0} pts',
  'gr.opp.title': 'Opportunités commerciales',
  'gr.noData': 'Données indisponibles',
  'gr.loadError': 'Le développement des ventes n’a pas pu être chargé.',
  'gr.op.title': 'Opportunités',
  'gr.op.subtitle': 'Ce qu’il faut corriger en premier, les opportunités confirmées par vos données et les signaux encore trop faibles pour agir.',
  // Potentiel produits
  'gr.nav.potential': 'Produits Potentiels',
  'gr.period.lastWeeks': '{0} dernières semaines',
  'gr.period.weeksNote': 'Analyse sur les {0} dernières semaines complètes.',
  'gr.pp.title': 'Produits Potentiels',
  'gr.pp.subtitle': 'Identifiez les produits à pousser, à surveiller ou à protéger selon la demande, le stock et la rentabilité.',
  'gr.pp.days': '{0} j',
  'gr.pp.unit1': '{0} unité vendue',
  'gr.pp.uN': '{0} unités',
  'gr.pp.u1': '{0} unité',
  'gr.pp.units': '{0} unités vendues',
  'gr.pp.noImage': 'Pas d’image synchronisée',
  'gr.pp.noCategory': 'Sans catégorie',
  'gr.pp.openDetail': 'Voir le détail : {0}',
  'gr.pp.close': 'Fermer',
  'gr.pp.kpi.active': 'Produits actifs',
  'gr.pp.kpi.activeNote': 'Vendus sur les {0} dernières semaines',
  'gr.pp.kpi.push': 'Produits à pousser',
  'gr.pp.kpi.pushNote': '{0} des ventes de la période',
  'gr.pp.kpi.pushNone': 'Aucun ne réunit toutes les conditions',
  'gr.pp.kpi.watch': 'À surveiller',
  'gr.pp.kpi.watchNote': 'Baisse, marge faible, retours ou signal contradictoire',
  'gr.pp.kpi.restock': 'Réassort avant promotion',
  'gr.pp.kpi.restockNote': 'Bonne demande, stock trop court',
  'gr.pp.list.title': 'Produits',
  'gr.pp.list.desc': 'Chaque produit vendu sur les {0} dernières semaines, avec son statut et le signal qui le justifie.',
  'gr.pp.list.foot': '{0} produits affichés sur {1}',
  'gr.pp.quality.stock': 'Dernier relevé de stock : {0} (utilisé s’il date de moins de {1} h)',
  'gr.pp.quality.noStock': 'Aucun relevé de stock synchronisé',
  'gr.pp.search': 'Rechercher un produit',
  'gr.pp.noMatch': 'Aucun produit ne correspond à ces filtres.',
  'gr.pp.empty.title': 'Aucun produit vendu sur la période',
  'gr.pp.empty.text': 'Aucune vente synchronisée sur les {0} dernières semaines : rien à recommander pour l’instant.',
  'gr.pp.f.aria': 'Filtrer par statut',
  'gr.pp.f.all': 'Tous',
  'gr.pp.f.push': 'À pousser',
  'gr.pp.f.growth': 'Forte croissance',
  'gr.pp.f.top': 'Meilleures ventes',
  'gr.pp.f.watch': 'À surveiller',
  'gr.pp.f.restock': 'Réassort avant promotion',
  'gr.pp.f.lowMargin': 'Marge faible',
  'gr.pp.f.insufficient': 'Données insuffisantes',
  'gr.pp.f.category': 'Catégorie',
  'gr.pp.f.allCategories': 'Toutes les catégories',
  'gr.pp.f.sort': 'Trier',
  'gr.pp.f.sort.sales': 'Trier par ventes',
  'gr.pp.f.sort.evolution': 'Trier par évolution',
  'gr.pp.f.sort.cover': 'Trier par couverture',
  'gr.pp.f.sort.margin': 'Trier par marge',
  'gr.pp.col.product': 'Produit',
  'gr.pp.col.sales': 'Ventes',
  'gr.pp.col.evolution': 'Évolution',
  'gr.pp.col.margin': 'Marge',
  'gr.pp.col.stock': 'Stock',
  'gr.pp.col.cover': 'Couverture',
  'gr.pp.col.status': 'Statut · signal',
  'gr.pp.evo.insufficient': 'Historique insuffisant',
  'gr.pp.trend.UP': 'En hausse',
  'gr.pp.trend.DOWN': 'En baisse',
  'gr.pp.trend.FLAT': 'Stable',
  'gr.pp.margin.MISSING': 'Coût manquant',
  'gr.pp.margin.PARTIAL': 'Marge partielle',
  'gr.pp.margin.UNVERIFIED': 'Coût non vérifié',
  'gr.pp.margin.RELIABLE': 'Coût vérifié',
  'gr.pp.stock.stale': 'Relevé ancien',
  'gr.pp.stock.unavailable': 'Stock indisponible',
  'gr.pp.cover.OUT': 'Rupture',
  'gr.pp.cover.STOCK_UNUSABLE': 'Couverture non calculée : stock indisponible ou relevé trop ancien.',
  'gr.pp.cover.INSUFFICIENT_HISTORY': 'Couverture non calculée : historique de ventes insuffisant.',
  'gr.pp.cover.INSUFFICIENT_SALES_SAMPLE': 'Couverture non calculée : trop peu de ventes pour estimer un rythme.',
  'gr.pp.cover.NO_DEMAND_OBSERVED': 'Couverture non calculée : aucune demande observée.',
  'gr.pp.cover.NO_STOCK': 'Stock épuisé.',
  'gr.pp.cover.UNKNOWN': 'Couverture non calculée.',
  'gr.pp.status.push': 'À pousser',
  'gr.pp.status.restock': 'Réassort avant promotion',
  'gr.pp.status.topSeller': 'Top vente',
  'gr.pp.status.watch': 'À surveiller',
  'gr.pp.status.declining': 'En baisse',
  'gr.pp.status.lowMargin': 'Marge faible',
  'gr.pp.status.returns': 'Trop de retours',
  'gr.pp.status.insufficient': 'Données insuffisantes',
  'gr.pp.status.stable': 'Stable',
  'gr.pp.signal.newProduct': 'Produit récent : moins de {0} semaines de ventes',
  'gr.pp.signal.thinSample': '{0} : échantillon trop faible',
  'gr.pp.signal.outOfStock': 'Demande présente, stock épuisé',
  'gr.pp.signal.coverDays': 'Stock pour {0} jours seulement',
  'gr.pp.signal.returnRate': '{0} des unités remboursées',
  'gr.pp.signal.margin': 'Marge vérifiée de {0}',
  'gr.pp.signal.evolution': '{0} vs {1} sem. précédentes',
  'gr.pp.signal.topRank': 'N°{0} des ventes de la période',
  'gr.pp.signal.none': 'Aucun signal particulier',
  'gr.pp.action.increaseVisibility': 'Augmenter la visibilité',
  'gr.pp.action.restockFirst': 'Réassortir d’abord',
  'gr.pp.action.doNotPromote': 'Ne pas promouvoir',
  'gr.pp.action.reviewReturns': 'Analyser les retours',
  'gr.pp.action.checkCost': 'Vérifier le coût',
  'gr.pp.action.checkStock': 'Vérifier le stock',
  'gr.pp.action.watch': 'Surveiller',
  'gr.pp.action.keep': 'Maintenir disponible',
  'gr.pp.action.none': 'Aucune action',
  'gr.pp.actionText.increaseVisibility': 'Donnez-lui plus de place : mise en avant sur la boutique, en vitrine ou dans une prochaine campagne. Le stock et la marge peuvent suivre.',
  'gr.pp.actionText.restockFirst': 'Réassortez avant toute mise en avant : une promotion maintenant créerait surtout des ruptures.',
  'gr.pp.actionText.doNotPromote': 'Ne pas dépenser en visibilité sur ce produit tant que la marge ou les retours ne sont pas corrigés.',
  'gr.pp.actionText.reviewReturns': 'Regardez les motifs de remboursement (qualité, taille, description) avant de lui donner plus de visibilité.',
  'gr.pp.actionText.checkCost': 'La demande monte mais la marge n’est pas fiable : renseignez ou vérifiez le coût d’achat pour savoir si le pousser est rentable.',
  'gr.pp.actionText.checkStock': 'La demande monte mais le stock n’est pas connu avec certitude : vérifiez-le avant toute mise en avant.',
  'gr.pp.actionText.watch': 'Pas d’action immédiate : suivez l’évolution des prochaines semaines.',
  'gr.pp.actionText.keep': 'Gardez-le disponible et visible comme aujourd’hui ; une promotion supplémentaire n’est pas nécessaire.',
  'gr.pp.actionText.none': 'Pas assez d’éléments pour recommander une action : Nordla attend plus de ventes.',
  'gr.pp.reason.COST_MISSING': 'Coût manquant',
  'gr.pp.reason.MARGIN_PARTIAL': 'Marge partielle',
  'gr.pp.reason.COST_UNVERIFIED': 'Coût non vérifié',
  'gr.pp.reason.STOCK_STALE': 'Relevé de stock ancien',
  'gr.pp.reason.STOCK_UNAVAILABLE': 'Stock indisponible',
  'gr.pp.reason.COVER_UNKNOWN': 'Couverture non calculable',
  'gr.pp.reason.HIGH_RETURNS': 'Trop de retours',
  'gr.pp.reason.RETURNS_ELEVATED': 'Retours élevés',
  'gr.pp.reason.TREND_INSUFFICIENT': 'Historique insuffisant',
  'gr.pp.push.title': 'Produits à pousser',
  'gr.pp.push.none': 'Aucun produit ne réunit aujourd’hui les quatre conditions pour être poussé :',
  'gr.pp.push.cond.demand': 'demande en hausse ;',
  'gr.pp.push.cond.cover': 'stock connu couvrant au moins {0} semaines ;',
  'gr.pp.push.cond.cost': 'coût d’achat vérifié (marge fiable) ;',
  'gr.pp.push.cond.returns': 'retours au plus de {0}.',
  'gr.pp.push.foot': 'Demande en hausse, stock suffisant, coût vérifié et retours normaux.',
  'gr.pp.protect.title': 'À protéger / ne pas pousser',
  'gr.pp.protect.none': 'Aucun produit à protéger pour l’instant.',
  'gr.pp.protect.foot': 'Réassort, retours, marge faible, signaux contradictoires ou baisse.',
  'gr.pp.byStatus.title': 'Produits par statut',
  'gr.pp.byStatus.foot': '{0} produits actifs classés',
  'gr.pp.d.why': 'Pourquoi ce statut',
  'gr.pp.d.evidence': 'Preuves ({0} dernières semaines)',
  'gr.pp.d.action': 'Action recommandée',
  'gr.pp.d.method': 'Statut calculé à partir des ventes, du stock, des coûts et des remboursements synchronisés dans Nordla. Une donnée inconnue n’est jamais comptée comme zéro.',
  'gr.pp.ev.sales': 'Ventes nettes HT',
  'gr.pp.ev.salesNote': 'N°{0} de la période',
  'gr.pp.ev.units': 'Unités vendues',
  'gr.pp.ev.velocity': '{0} par semaine en moyenne',
  'gr.pp.ev.evoNote': '{0} u. contre {1} u. ({2} sem. vs {2} sem.)',
  'gr.pp.ev.evoNone': 'Il faut au moins {0} semaines de ventes pour comparer.',
  'gr.pp.ev.snapshot': 'Relevé du {0}',
  'gr.pp.ev.snapshotOld': 'Dernier relevé le {0} : trop ancien pour décider',
  'gr.pp.ev.noSnapshot': 'Aucun relevé de stock synchronisé',
  'gr.pp.ev.coverNote': 'Seuil de réassort : {0} semaines',
  'gr.pp.ev.refunds': 'Remboursements',
  'gr.pp.ev.refundNote': 'Unités remboursées : {0}',
  'gr.pp.ev.history': 'Historique observé',
  'gr.pp.ev.weeks': '{0} sem.',
  'gr.pp.rule.NEW_PRODUCT': 'Ce produit n’a que {0} semaines de ventes observées ; il en faut au moins {1} avant de recommander quoi que ce soit.',
  'gr.pp.rule.THIN_SAMPLE': '{0} en {2} semaines : il en faut au moins {1} pour conclure.',
  'gr.pp.rule.DEMAND_BUT_OUT_OF_STOCK': 'La demande est bonne mais le stock est épuisé : le promouvoir enverrait des clients vers une rupture.',
  'gr.pp.rule.DEMAND_BUT_LOW_COVER': 'La demande est bonne mais le stock ne couvre que {0} jours (moins de {1} semaines) : réassortir avant toute promotion.',
  'gr.pp.rule.DEMAND_BUT_HIGH_RETURNS': 'La demande est bonne, mais {0} des unités vendues ont été remboursées : à comprendre avant de le pousser.',
  'gr.pp.rule.HIGH_RETURNS': '{0} des unités vendues ont été remboursées (seuil : {1}).',
  'gr.pp.rule.LOW_RELIABLE_MARGIN': 'Marge fiable de {0}, sous le seuil de {1} : chaque vente supplémentaire rapporte peu.',
  'gr.pp.rule.TREND_DOWN': 'Les ventes des {0} dernières semaines sont en baisse par rapport aux {0} précédentes ({1} u. contre {2} u.).',
  'gr.pp.rule.PUSH': 'Demande en hausse ({0} u. contre {1} u. sur {2} semaines), stock suffisant, coût vérifié et retours normaux : le produit peut absorber plus de visibilité.',
  'gr.pp.rule.BLOCKED': 'La demande est en hausse ({0} u. contre {1} u. sur {2} semaines), mais une condition manque pour le pousser : {3}.',
  'gr.pp.blocked.checkStock': 'stock inconnu ou relevé trop ancien',
  'gr.pp.blocked.checkCost': 'coût d’achat non vérifié',
  'gr.pp.blocked.reviewReturns': 'retours au-dessus de {0}',
  'gr.pp.blocked.watch': 'couverture de stock non calculable',
  'gr.pp.rule.TOP_SELLER': 'N°{0} des ventes de la période, sans nouveau signal de hausse : le garder disponible suffit.',
  'gr.pp.rule.TOP_SELLER_RETURNS': 'Top vente, mais {0} des unités vendues ont été remboursées (au-delà de {1}) : comprendre ces retours avant tout réassort ou promotion.',
  'gr.pp.rule.NO_SIGNAL': 'Ventes régulières, sans signal de hausse, de baisse ni de risque.',
  // Audience
  'gr.period.lastDays': '{0} derniers jours',
  'gr.period.daysNote': 'Analyse sur les {0} derniers jours complets, comparés aux {0} jours précédents.',
  'gr.au.title': 'Audience',
  'gr.au.subtitle': 'Identifiez les segments clients qui représentent une opportunité de croissance.',
  'gr.au.vsPrevious': 'vs période précédente',
  'gr.au.pts': '{0} pts',
  'gr.au.daysAgo': 'il y a {0} j',
  'gr.au.open': 'Ouvrir',
  'gr.au.openSegment': 'Voir le segment : {0}',
  'gr.au.kpi.active': 'Clients actifs',
  'gr.au.kpi.new': 'Nouveaux clients',
  'gr.au.kpi.repeatRate': 'Taux de réachat',
  'gr.au.kpi.aov': 'Panier moyen',
  'gr.au.kpi.toReactivate': 'Clients à réactiver',
  'gr.au.kpi.orders': 'Commandes',
  'gr.au.kpi.netSales': 'CA HT',
  'gr.au.kpi.returningOrders': 'Commandes de clients récurrents',
  'gr.au.kpi.multiProduct': 'Paniers multi-produits',
  'gr.au.kpi.noPrevious': 'Pas de période précédente comparable',
  'gr.au.kpi.notComputable': 'Non calculable',
  'gr.au.kpi.fromZero': '0 sur la période précédente',
  'gr.au.kpi.sampleGate': 'Moins de {0} clients actifs : non calculé',
  'gr.au.kpi.historyGate': 'Historique de moins de {0} jours : non calculé',
  'gr.au.kpi.indexMissing': 'Ordre d’achat client non transmis par la source',
  'gr.au.dist.title': 'Répartition des segments',
  'gr.au.dist.ordersTitle': 'Répartition des commandes',
  'gr.au.dist.value': '{0} ({1})',
  'gr.au.dist.revenue': '{0} du CA',
  'gr.au.dist.foot': '{0} clients identifiés. Chaque client appartient à un seul segment (total 100 %). Part du CA : achats des {1} derniers jours.',
  'gr.au.dist.ordersFoot': 'Commandes des {0} derniers jours selon l’ordre d’achat transmis par la source. Chaque commande est comptée une fois.',
  'gr.au.dist.noIndex': 'Aucune des {0} commandes de la période ne porte d’ordre d’achat client transmis par la source : impossible de distinguer premiers achats et achats répétés.',
  'gr.au.orderGroup.new': 'Premier achat (en ligne)',
  'gr.au.orderGroup.returning': 'Client récurrent',
  'gr.au.orderGroup.first_recorded_pos': '1er achat enregistré en magasin',
  'gr.au.orderGroup.unknown': 'Ordre d’achat inconnu',
  'gr.au.seg.loyal': 'Clients fidèles',
  'gr.au.seg.returning': 'Clients récurrents',
  'gr.au.seg.newReturned': 'Nouveaux clients prometteurs',
  'gr.au.seg.new': 'Nouveaux clients',
  'gr.au.seg.reactivate': 'Clients à réactiver',
  'gr.au.seg.occasional': 'Occasionnels à convertir',
  'gr.au.seg.unknown': 'Historique non établi',
  'gr.au.segDef.loyal': '≥ 3 achats, dont un récent',
  'gr.au.segDef.returning': '2 achats, dont un récent',
  'gr.au.segDef.newReturned': 'Nouveaux, déjà revenus',
  'gr.au.segDef.new': '1er achat récent',
  'gr.au.segDef.reactivate': '≥ 2 achats, aucun récent',
  'gr.au.segDef.occasional': '1 achat ancien, pas revenu',
  'gr.au.segDef.unknown': '1 achat récent, 1er achat non prouvé',
  'gr.au.segRule.loyal': 'Client identifié avec au moins 3 commandes connues (ou un numéro de commande source ≥ 3), dont au moins une dans les {0} derniers jours.',
  'gr.au.segRule.returning': 'Client identifié avec exactement 2 commandes connues, dont au moins une dans les {0} derniers jours, et dont le premier achat n’est pas récent.',
  'gr.au.segRule.newReturned': 'Premier achat prouvé (numéro de commande source = 1) dans les {0} derniers jours, et au moins une autre commande depuis : le client est déjà revenu.',
  'gr.au.segRule.new': 'Premier achat prouvé (numéro de commande source = 1) dans les {0} derniers jours, sans autre commande pour l’instant.',
  'gr.au.segRule.reactivate': 'Client identifié avec au moins 2 commandes (acheteur répété prouvé) mais aucune commande dans les {0} derniers jours.',
  'gr.au.segRule.occasional': 'Client identifié avec une seule commande connue, passée il y a plus de {0} jours, et pas revenu depuis.',
  'gr.au.segRule.unknown': 'Une seule commande dans les {0} derniers jours, sans numéro de commande source fiable (ex. vente en magasin) : impossible de savoir si c’est un premier achat. Ce groupe n’est pas qualifié.',
  'gr.au.status.priority': 'Prioritaire',
  'gr.au.status.activate': 'À activer',
  'gr.au.status.develop': 'À développer',
  'gr.au.status.watch': 'À surveiller',
  'gr.au.status.insufficient': 'Données insuffisantes',
  'gr.au.rule.INSUFFICIENT': 'Pas assez de données pour une recommandation fiable : Nordla ne tire aucune conclusion de ce segment pour l’instant.',
  'gr.au.rule.REPEAT_BUYERS_WITHOUT_RECENT_ORDER': 'Ces clients ont prouvé qu’ils rachètent (au moins 2 commandes) mais n’ont plus commandé récemment : c’est un groupe identifiable à recontacter.',
  'gr.au.rule.REVENUE_SHARE_ABOVE_CUSTOMER_SHARE': 'Ce segment pèse {0} du CA récent pour {1} des clients actifs : il contribue plus que son poids.',
  'gr.au.rule.SMALLER_THAN_PREVIOUS_WINDOW': 'Ce segment compte moins de clients que sur la période précédente ({2}).',
  'gr.au.rule.ONE_ORDER_NOT_REPEATED': 'Ces clients ont acheté une fois il y a plus longtemps que la période et ne sont pas revenus : une deuxième commande reste à obtenir.',
  'gr.au.rule.ACTIVE_SEGMENT': 'Segment actif et suffisamment grand, sans signal particulier de sur-contribution ni de baisse.',
  'gr.au.reason.SAMPLE_BELOW_MIN_CUSTOMERS': 'Moins de {0} clients identifiés au total',
  'gr.au.reason.SEGMENT_BELOW_MIN_GROUP': 'Segment de moins de {1} clients',
  'gr.au.reason.SHORT_HISTORY': 'Historique trop court',
  'gr.au.reason.FIRST_ORDER_NOT_PROVEN': 'Premier achat non prouvé',
  'gr.au.action.reactivation': 'Préparer une campagne de réactivation',
  'gr.au.action.loyalty': 'Renforcer la fidélisation',
  'gr.au.action.secondPurchase': 'Préparer une offre de deuxième achat',
  'gr.au.action.targetedOffer': 'Tester une offre ciblée',
  'gr.au.action.none': 'Aucune action pour l’instant',
  'gr.au.actionText.reactivation': 'Recontacter ce groupe avec un message ou une offre simple, puis mesurer combien de clients reviennent. À tester à petite échelle d’abord.',
  'gr.au.actionText.loyalty': 'Reconnaître et récompenser ces clients (avantage fidélité, accès anticipé) pour entretenir leur rythme d’achat.',
  'gr.au.actionText.secondPurchase': 'Donner une raison de revenir après le premier achat (suggestion de produit, offre limitée dans le temps).',
  'gr.au.actionText.targetedOffer': 'Tester une offre adaptée à ce qu’ils ont acheté la première fois, sur un petit groupe, avant de l’élargir.',
  'gr.au.actionText.none': 'Nordla ne recommande rien sur ce segment tant que les données sont insuffisantes.',
  'gr.au.prio.title': 'Segments prioritaires',
  'gr.au.prio.foot': 'Classés par statut puis par taille. Statuts issus de règles explicites, sans score.',
  'gr.au.col.segment': 'Segment',
  'gr.au.col.size': 'Taille',
  'gr.au.col.revenueShare': 'Part du CA',
  'gr.au.col.status': 'Statut',
  'gr.au.col.action': 'Action recommandée',
  'gr.au.col.customers': 'Clients',
  'gr.au.col.frequency': 'Commandes / client',
  'gr.au.col.revenue': 'CA {0} j',
  'gr.au.col.aov': 'Panier moyen',
  'gr.au.col.recency': 'Dernier achat',
  'gr.au.col.statusAction': 'Statut · action',
  'gr.au.sig.title': 'Signaux d’audience',
  'gr.au.sig.foot': 'Faits observés, comparés à une référence. Aucune prédiction.',
  'gr.au.sig.none': 'Aucun signal fiable : il faut au moins {0} clients identifiés.',
  'gr.au.sig.repeatRevenueShare.title': 'Les clients qui rachètent génèrent {0} du CA',
  'gr.au.sig.repeatRevenueShare.text': 'Ils représentent {0} des clients actifs mais {1} du CA des {2} derniers jours : ils pèsent plus que leur nombre.',
  'gr.au.sig.reactivation.title': '{0} acheteurs répétés sans achat depuis {1} jours',
  'gr.au.sig.reactivation.text': 'Ils ont généré {0} sur l’historique observé : un groupe identifiable à recontacter.',
  'gr.au.sig.repeatRateUp.title': 'Le taux de réachat progresse',
  'gr.au.sig.repeatRateDown.title': 'Le taux de réachat recule',
  'gr.au.sig.repeatRateChange.text': '{0} des clients actifs ont déjà acheté au moins deux fois, contre {1} sur les {2} jours précédents.',
  'gr.au.sig.aovGap.title': 'Panier moyen : clients récurrents vs nouveaux',
  'gr.au.sig.aovGap.text': '{0} pour les clients qui rachètent contre {1} pour les nouveaux clients (commandes observées).',
  'gr.au.sig.coverage.title': '{0} des commandes sont rattachées à un client',
  'gr.au.sig.coverage.text': '{0} commandes anonymes (souvent en magasin) ne sont dans aucun segment : les segments décrivent les clients identifiés uniquement.',
  'gr.au.sig.returningOrders.title': '{0} des commandes viennent de clients récurrents',
  'gr.au.sig.returningOrders.text': 'Sur {0} commandes dont l’ordre d’achat est connu (minimum, l’historique source peut être incomplet).',
  'gr.au.sig.aovUp.title': 'Le panier moyen augmente',
  'gr.au.sig.aovDown.title': 'Le panier moyen baisse',
  'gr.au.sig.aovChange.text': '{0} contre {1} sur les {2} jours précédents.',
  'gr.au.sig.multiProduct.title': '{0} des commandes contiennent plusieurs produits',
  'gr.au.sig.multiProduct.text': 'Sur {0} commandes : indique la part d’achats groupés, utile pour les offres associées.',
  'gr.au.sig.customerLevelMissing.title': 'Segments clients indisponibles',
  'gr.au.sig.customerLevelMissing.text': 'Aucune commande ne porte d’identifiant client pseudonymisé : Nordla ne peut pas regrouper les achats par client. Les indicateurs restent au niveau des commandes.',
  'gr.au.list.title': 'Segments clients ({0})',
  'gr.au.list.desc': 'Groupes exclusifs de clients identifiés, définis par leurs achats observés. « Récent » = dans les {0} derniers jours.',
  'gr.au.list.foot': '{0} clients identifiés · {1} des commandes de la période rattachées à un client · Aucun client n’est affiché individuellement.',
  'gr.au.act.title': 'Actions recommandées ({0})',
  'gr.au.act.target': 'Cible : {0} ({1} clients)',
  'gr.au.act.toTest': 'À tester',
  'gr.au.act.prerequisite': 'Prérequis',
  'gr.au.act.none': 'Aucune action recommandée : aucun segment suffisamment grand ou établi.',
  'gr.au.act.foot': 'Bénéfices qualitatifs uniquement : aucun CRM ni outil e-mail n’est connecté, aucun résultat n’est promis.',
  'gr.au.actTitle.reactivation': 'Préparer une campagne de réactivation',
  'gr.au.actTitle.loyalty': 'Renforcer la fidélisation',
  'gr.au.actTitle.secondPurchase': 'Préparer une offre de deuxième achat',
  'gr.au.actTitle.targetedOffer': 'Tester une offre ciblée',
  'gr.au.actTitle.growSample': 'Attendre un échantillon suffisant',
  'gr.au.actTitle.enableCustomerKey': 'Activer l’identification client pseudonymisée',
  'gr.au.actWhy.growSample': 'Trop peu de clients identifiés pour qualifier des segments.',
  'gr.au.actWhy.enableCustomerKey': 'Aucune commande synchronisée ne porte de clé client pseudonymisée.',
  'gr.au.actBenefit.reactivation': 'Réactivation possible d’acheteurs qui ont déjà prouvé leur intérêt.',
  'gr.au.actBenefit.loyalty': 'Protéger le segment qui pèse le plus dans le CA.',
  'gr.au.actBenefit.secondPurchase': 'Transformer un premier achat en habitude.',
  'gr.au.actBenefit.targetedOffer': 'Obtenir une deuxième commande de clients déjà acquis.',
  'gr.au.actBenefit.growSample': 'Des segments fiables dès que l’échantillon est atteint.',
  'gr.au.actBenefit.enableCustomerKey': 'Débloque les segments (fidèles, à réactiver, nouveaux) sans stocker d’identité : seule une empreinte chiffrée est conservée.',
  'gr.au.noKey.banner': 'Niveau client indisponible : aucune commande ne porte d’identifiant client pseudonymisé. La page reste au niveau des commandes et ne cible aucun client individuellement.',
  'gr.au.noKey.text': 'Ces segments nécessitent l’identification client pseudonymisée, qui n’est pas active pour cette boutique :',
  'gr.au.d.window': 'Référence : {0} derniers jours',
  'gr.au.d.definition': 'Définition',
  'gr.au.d.sizeValue': 'Taille et valeur',
  'gr.au.d.size': 'Clients',
  'gr.au.d.sizeNote': '{0} des clients identifiés',
  'gr.au.d.evolution': 'Période précédente',
  'gr.au.d.noPrevious': 'Pas de période comparable',
  'gr.au.d.same': 'Stable : {0} clients',
  'gr.au.d.previous': '{0} clients sur la période précédente',
  'gr.au.d.noWindowPurchase': 'Aucun achat sur la période, par définition',
  'gr.au.d.revenueShare': '{0} du CA des clients actifs',
  'gr.au.d.historyRevenue': 'CA observé (historique)',
  'gr.au.d.historyNote': 'Sur {0} jours d’historique chargé',
  'gr.au.d.aovNote': 'Toutes leurs commandes observées',
  'gr.au.d.frequencyNote': 'Commandes connues par client',
  'gr.au.d.recencyNote': 'Médiane du segment',
  'gr.au.d.why': 'Pourquoi Nordla le signale',
  'gr.au.d.action': 'Action suggérée',
  'gr.au.d.method': 'Segment calculé à partir des commandes synchronisées dans Nordla, regroupées par identifiant client pseudonymisé. Aucune donnée personnelle n’est lue ni affichée. Observation, pas prédiction.',
  'gr.au.empty.title': 'Aucune commande sur la période',
  'gr.au.empty.text': 'Aucune commande synchronisée : Audience n’a rien à analyser pour l’instant.',
  'gr.au.empty.window': 'Aucune donnée sur les {0} derniers jours.',
  // Contenu
  'gr.ct.title': 'Contenu',
  'gr.ct.subtitle': 'Repérez les fiches produits incomplètes et les améliorations à apporter en priorité.',
  'gr.ct.status.priority': 'Prioritaire',
  'gr.ct.status.improve': 'À améliorer',
  'gr.ct.status.insufficient': 'Données insuffisantes',
  'gr.ct.status.correct': 'Correct',
  'gr.ct.problem.noImage': 'Sans image',
  'gr.ct.problem.noAltText': 'Sans texte alternatif',
  'gr.ct.problem.noType': 'Sans catégorie',
  'gr.ct.problem.noCollection': 'Hors collection',
  'gr.ct.problem.missingSku': 'SKU manquant',
  'gr.ct.problem.duplicateTitle': 'Nom en double',
  'gr.ct.kpi.toImprove': 'Produits à améliorer',
  'gr.ct.kpi.toImproveNote': 'Au moins un problème, sur {0} produits actifs',
  'gr.ct.kpi.noImage': 'Sans image',
  'gr.ct.kpi.noImageNote': 'Aucune image principale',
  'gr.ct.kpi.noAltText': 'Sans texte alternatif',
  'gr.ct.kpi.noAltTextNote': 'Image sans description',
  'gr.ct.kpi.noType': 'Sans catégorie',
  'gr.ct.kpi.noTypeNote': 'Type de produit vide',
  'gr.ct.kpi.missingSku': 'SKU manquant',
  'gr.ct.kpi.missingSkuNote': 'Au moins une variante sans SKU',
  'gr.ct.kpi.unavailable': 'Non vérifiable avec les données actuelles',
  'gr.ct.prio.title': 'Produits par priorité',
  'gr.ct.prio.total': 'produits',
  'gr.ct.prio.foot': '{0} produits actifs analysés, chacun compté une fois.',
  'gr.ct.problems.title': 'Principaux problèmes de contenu',
  'gr.ct.problems.none': 'Aucun problème détecté parmi les contrôles possibles.',
  'gr.ct.problems.notChecked': 'Non contrôlé avec les données actuelles : {0}.',
  'gr.ct.na.description': 'description',
  'gr.ct.na.reviews': 'avis clients',
  'gr.ct.na.multipleImages': 'images multiples',
  'gr.ct.na.seo': 'titre et méta SEO',
  'gr.ct.na.attributes': 'attributs produit',
  'gr.ct.search': 'Rechercher un produit ou un SKU',
  'gr.ct.f.status': 'Statut',
  'gr.ct.f.allStatuses': 'Tous les statuts',
  'gr.ct.f.problem': 'Problème',
  'gr.ct.f.allProblems': 'Tous les problèmes',
  'gr.ct.f.category': 'Catégorie',
  'gr.ct.f.allCategories': 'Toutes les catégories',
  'gr.ct.noSku': 'Sans SKU',
  'gr.ct.col.product': 'Produit',
  'gr.ct.col.category': 'Catégorie',
  'gr.ct.col.problems': 'Problèmes',
  'gr.ct.col.status': 'Statut',
  'gr.ct.col.sales': 'Ventes ({0} sem.)',
  'gr.ct.col.action': 'Action',
  'gr.ct.noProblemYet': 'Aucun problème détecté (image non vérifiable)',
  'gr.ct.noProblem': 'Aucun problème détecté',
  'gr.ct.seeReco': 'Voir les recommandations',
  'gr.ct.seeDetail': 'Voir le détail',
  'gr.ct.list.title': 'Produits',
  'gr.ct.list.foot': '{0} produits affichés sur {1} actifs ({2} au catalogue, brouillons et archivés exclus). Triés par priorité puis par ventes.',
  'gr.ct.empty.noProducts': 'Aucun produit actif à analyser.',
  'gr.ct.empty.clearTitle': 'Aucun problème de contenu détecté avec les données actuellement disponibles.',
  'gr.ct.empty.clearText': 'Nordla continuera à surveiller la qualité des informations produits.',
  'gr.ct.empty.insufficientTitle': 'Données insuffisantes',
  'gr.ct.empty.insufficientText': 'Certaines dimensions du contenu produit ne sont pas encore disponibles dans Nordla : aucun produit n’est déclaré correct sans pouvoir le vérifier.',
  'gr.ct.banner.noImage': 'Images non vérifiables : aucune image produit n’est encore synchronisée pour cette boutique. Nordla ne peut donc pas distinguer un produit sans image d’une image non transmise ; ces produits sont en « Données insuffisantes », jamais « Correct ».',
  'gr.ct.d.problems': 'Problèmes détectés',
  'gr.ct.d.none': 'Aucun problème détectable avec les données disponibles.',
  'gr.ct.d.noneInsufficient': 'Aucun problème détecté, mais l’image ne peut pas être vérifiée : le produit n’est pas déclaré correct.',
  'gr.ct.d.why': 'Pourquoi c’est important',
  'gr.ct.d.sold': 'Ce produit s’est vendu {0} fois sur les {1} dernières semaines : ses informations sont réellement vues par des clients, il mérite d’être traité parmi les premiers.',
  'gr.ct.d.notSold': 'Aucune vente sur les {0} dernières semaines : moins urgent, mais sa fiche reste incomplète pour une utilisation future dans le développement des ventes ou d’autres canaux.',
  'gr.ct.d.reco': 'Recommandations',
  'gr.ct.d.unverified': 'Non vérifiable avec les données actuelles',
  'gr.ct.d.method': 'Contrôles déterministes sur les données produit synchronisées dans Nordla. Aucun impact chiffré n’est promis : l’effet d’une meilleure fiche n’est pas mesuré.',
  'gr.ct.rule.MAJOR_PROBLEM': 'Le produit n’a pas d’image : il est difficile à comprendre ou à présenter sans visuel.',
  'gr.ct.rule.MANY_PROBLEMS': 'Au moins {0} problèmes à la fois : la fiche est incomplète sur plusieurs points.',
  'gr.ct.rule.MINOR_PROBLEMS': 'Problèmes non bloquants : le produit reste présentable mais sa fiche peut être complétée.',
  'gr.ct.rule.ESSENTIAL_CHECK_UNAVAILABLE': 'Aucun problème détecté, mais un contrôle essentiel (l’image) n’est pas vérifiable avec les données actuelles.',
  'gr.ct.rule.NO_DETECTABLE_PROBLEM': 'Aucun problème détectable avec les données que Nordla possède. Cela ne garantit pas un contenu parfait.',
  'gr.ct.fact.noImage': 'Aucune image principale n’est disponible pour ce produit.',
  'gr.ct.fact.noAltText': 'L’image principale n’a pas de texte alternatif.',
  'gr.ct.fact.noType': 'Le type de produit est vide dans la source.',
  'gr.ct.fact.noCollection': 'Le produit n’appartient à aucune collection actuelle.',
  'gr.ct.fact.missingSku': '{0} variante(s) sur {1} sans SKU.',
  'gr.ct.fact.duplicateTitle': '{0} autre(s) produit(s) actif(s) portent exactement le même nom.',
  'gr.ct.explain.noImage': 'Sans visuel, le client ne voit pas ce qu’il achète.',
  'gr.ct.explain.noAltText': 'Le texte alternatif décrit l’image pour l’accessibilité et les moteurs de recherche.',
  'gr.ct.explain.noType': 'Sans catégorie, le produit est mal classé dans la boutique et dans les analyses Nordla.',
  'gr.ct.explain.noCollection': 'Hors collection, le produit est plus difficile à trouver en navigation.',
  'gr.ct.explain.missingSku': 'Sans SKU, la variante est difficile à identifier en stock, en caisse ou sur d’autres canaux.',
  'gr.ct.explain.duplicateTitle': 'Deux produits au même nom se confondent pour le client et dans les rapports.',
  'gr.ct.reco.noImage': 'Ajouter une image produit de qualité.',
  'gr.ct.reco.noAltText': 'Ajouter un texte alternatif descriptif.',
  'gr.ct.reco.noType': 'Classer le produit dans une catégorie exploitable.',
  'gr.ct.reco.noCollection': 'Ajouter le produit à une collection pertinente.',
  'gr.ct.reco.missingSku': 'Attribuer un SKU unique à chaque variante.',
  'gr.ct.reco.duplicateTitle': 'Donner un nom distinctif à chaque produit.',
  'gr.ct.recoHow.noImage': 'Photo nette du produit réel, sur fond neutre, dans l’outil de la boutique.',
  'gr.ct.recoHow.noAltText': 'Décrire en quelques mots ce que montre l’image (produit, couleur, usage).',
  'gr.ct.recoHow.noType': 'Renseigner le type de produit dans la fiche de la boutique.',
  'gr.ct.recoHow.noCollection': 'Choisir la collection où un client le chercherait.',
  'gr.ct.recoHow.missingSku': 'Compléter le champ SKU de chaque variante concernée.',
  'gr.ct.recoHow.duplicateTitle': 'Ajouter ce qui les distingue (modèle, taille, couleur) dans le nom.',
  // Croissance magasin
  'gr.st.title': 'Croissance magasin',
  'gr.st.subtitle': 'Analysez les ventes de votre point de vente physique et les actions locales à envisager.',
  'gr.st.vsPrevious': 'vs 8 semaines précédentes',
  'gr.st.kpi.storeNet': 'CA magasin (HT)',
  'gr.st.kpi.storeOrders': 'Commandes magasin',
  'gr.st.kpi.storeAov': 'Panier moyen magasin',
  'gr.st.kpi.storeShare': 'Part du magasin',
  'gr.st.kpi.locations': 'Magasins actifs',
  'gr.st.kpi.locationsNote': 'Avec des ventes sur la période ({0} emplacement(s) connus)',
  'gr.st.kpi.locationsUnknown': '{0} commande(s) sans emplacement renseigné',
  'gr.st.kpi.noPrevious': 'Pas de période précédente comparable',
  'gr.st.kpi.notComputable': 'Non calculable',
  'gr.st.kpi.fromZero': '0 sur la période précédente',
  'gr.st.banner.footfall': 'Fréquentation non connectée : les chiffres ci-dessous sont des ventes, pas des visiteurs. Aucun taux de conversion ni nombre de visiteurs n’est calculé.',
  'gr.st.perf.title': 'Performance magasin',
  'gr.st.perf.metric': 'Indicateur',
  'gr.st.perf.sales': 'CA magasin par semaine',
  'gr.st.perf.orders': 'Commandes magasin par semaine',
  'gr.st.perf.channels': 'Magasin vs en ligne (CA)',
  'gr.st.perf.store': 'Magasin',
  'gr.st.perf.online': 'En ligne',
  'gr.st.perf.current': '8 dernières semaines',
  'gr.st.perf.previous': '8 semaines précédentes',
  'gr.st.perf.foot': 'Semaines complètes ; chaque semaine est comparée à la même position sur les {0} semaines précédentes.',
  'gr.st.perf.footNoPrev': 'Semaines complètes. Pas de comparaison : l’historique ne couvre pas les {0} semaines précédentes.',
  'gr.st.days.title': 'Activité des ventes par jour',
  'gr.st.days.orders': '{0} cmd',
  'gr.st.days.foot': '{0} commandes magasin sur la période. Ventes par jour de la semaine, pas de fréquentation ; aucun constat sous {1} commandes.',
  'gr.st.products.title': 'Produits moteurs en magasin',
  'gr.st.products.detail': '{0} · {1} des ventes magasin',
  'gr.st.products.guard': 'Pas de mise en avant : {0}',
  'gr.st.products.unknown': 'Produit non rattaché au catalogue',
  'gr.st.products.foot': 'Classés par CA magasin sur 8 semaines. Les garde-fous de Produits Potentiels (stock, marge, retours, baisse) s’appliquent.',
  'gr.st.diff.title': 'Différences magasin / online',
  'gr.st.diff.aov': 'Panier moyen : {0} en magasin contre {1} en ligne.',
  'gr.st.diff.product': '{0} des ventes magasin contre {1} des ventes en ligne',
  'gr.st.diff.none': 'Aucun produit ne pèse au moins deux fois plus en magasin qu’en ligne sur la période.',
  'gr.st.diff.gated': 'Comparaison disponible à partir de {0} commandes de chaque côté (magasin : {1}, en ligne : {2}).',
  'gr.st.diff.foot': 'Faits observés, sans explication supposée.',
  'gr.st.loc.title': 'Tous les magasins ({0})',
  'gr.st.loc.store': 'Magasin',
  'gr.st.loc.orders': 'Commandes',
  'gr.st.loc.net': 'CA (HT)',
  'gr.st.loc.aov': 'Panier moyen',
  'gr.st.loc.share': 'Part',
  'gr.st.loc.unnamed': 'Emplacement sans nom',
  'gr.st.loc.unknown': 'Emplacement non renseigné',
  'gr.st.loc.foot': 'Les KPI additionnent tous les magasins ; aucun emplacement n’est choisi à votre place.',
  'gr.st.sig.title': 'Signaux magasin',
  'gr.st.sig.none': 'Aucun signal fiable : il faut au moins {0} commandes magasin sur chaque période comparée (actuellement {1}).',
  'gr.st.sig.foot': 'Faits observés sur les ventes, comparés à une référence. Aucune causalité supposée.',
  'gr.st.sig.storeFaster.title': 'Le magasin progresse plus vite que l’online',
  'gr.st.sig.onlineFaster.title': 'L’online progresse plus vite que le magasin',
  'gr.st.sig.storeVsOnline.text': 'CA magasin {0} contre {1} en ligne, sur les {2} dernières semaines vs les précédentes.',
  'gr.st.sig.ordersUpAovDown.title': 'Plus de commandes, panier moyen en baisse',
  'gr.st.sig.ordersDownAovUp.title': 'Moins de commandes, panier moyen en hausse',
  'gr.st.sig.ordersAov.text': 'Commandes magasin {0}, panier moyen {1} par rapport aux 8 semaines précédentes.',
  'gr.st.sig.strongWeekday.title': 'Le {0} concentre {1} des ventes magasin',
  'gr.st.sig.strongWeekday.text': 'Réparties également, chaque jour en ferait {0} : ce jour pèse au moins le double.',
  'gr.st.sig.productGap.title': '{0} pèse plus en magasin',
  'gr.st.sig.productGap.text': '{0} des ventes magasin contre {1} des ventes en ligne.',
  'gr.st.sig.refundsUp.title': 'Remboursements magasin en hausse',
  'gr.st.sig.refundsUp.text': '{0} des unités vendues remboursées contre {1} sur les 8 semaines précédentes.',
  'gr.st.act.title': 'Actions locales recommandées ({0})',
  'gr.st.act.none': 'Aucune action recommandée : il faut au moins {0} commandes magasin sur la période.',
  'gr.st.act.foot': 'Basées uniquement sur les ventes observées ; aucune ne suppose un trafic en magasin.',
  'gr.st.act.restockFirst.title': 'Réassortir avant toute animation',
  'gr.st.act.restockFirst.text': '{0} se vend bien en magasin mais son stock ne couvre pas assez de semaines (Produits Potentiels).',
  'gr.st.act.highlightProduct.title': 'Mettre davantage en avant un produit magasin',
  'gr.st.act.highlightProduct.text': '{0} représente {1} des ventes magasin et n’est bloqué par aucun garde-fou.',
  'gr.st.act.weekdayHighlight.title': 'Tester une mise en avant le {0}',
  'gr.st.act.weekdayHighlight.text': 'Ce jour réalise {0} des ventes magasin.',
  'gr.st.act.checkAov.title': 'Vérifier la baisse du panier moyen',
  'gr.st.act.checkAov.text': 'Plus de commandes mais un panier plus petit : regarder les remises et le mix produits.',
  'gr.st.future.title': 'Pour aller plus loin',
  'gr.st.future.footfall': 'Fréquentation magasin',
  'gr.st.future.googleBusiness': 'Google Business Profile',
  'gr.st.future.posEnriched': 'Caisse enrichie',
  'gr.st.future.unlocks': 'Débloquerait : {0}',
  'gr.st.future.u.conversion': 'taux de conversion magasin',
  'gr.st.future.u.visitors': 'visiteurs',
  'gr.st.future.u.salesPerVisitor': 'ventes par visiteur',
  'gr.st.future.u.directions': 'demandes d’itinéraire',
  'gr.st.future.u.calls': 'appels',
  'gr.st.future.u.localVisibility': 'visibilité locale',
  'gr.st.future.u.staff': 'ventes par vendeur',
  'gr.st.future.u.paymentMethods': 'moyens de paiement',
  'gr.st.future.u.hours': 'heures fiables',
  'gr.st.future.notConnected': 'Source non connectée',
  'gr.st.future.audience': 'Audience magasin',
  'gr.st.future.audienceNone': 'Audience magasin non identifiable : les commandes magasin ne portent pas d’identifiant client pseudonymisé.',
  'gr.st.future.audienceShare': '{0} des commandes magasin rattachées à un client (agrégé, voir Audience).',
  'gr.st.future.partial': 'Partielle',
  'gr.st.future.notIdentifiable': 'Non identifiable',
  'gr.st.future.foot': 'Aucune de ces sources n’est connectée : bientôt disponible. Rien n’est simulé en attendant.',
  'gr.st.empty.noStoreTitle': 'Aucune vente magasin identifiable sur cette période.',
  'gr.st.empty.noStoreText': 'Nordla peut analyser le point de vente lorsqu’une source de ventes physiques est disponible. Aucune commande de cette boutique ne provient d’un canal magasin : ce n’est pas « zéro vente », c’est une source absente.',
  'gr.st.empty.window': 'Aucune vente magasin sur les {0} dernières semaines.',
  // Shared page states
  'gr.state.loading': 'Chargement des données…',
  'gr.state.errorTitle': 'Données indisponibles',
  'gr.state.error.TENANT_NOT_CONFIGURED': 'Aucune boutique n’est configurée pour le développement des ventes sur ce serveur.',
  'gr.state.error.DATA_UNAVAILABLE': 'Les données de la boutique n’ont pas pu être lues pour le moment.',
  'gr.state.error.NETWORK': 'Le serveur du développement des ventes ne répond pas. Vérifiez la connexion.',
  'gr.state.error.UNKNOWN': 'Une erreur inattendue a empêché le chargement de cette page.',
  'gr.state.retry': 'Réessayer',
  // Overview: capabilities not connected (deep audit P1-2)
  'gr.store.realRevenue': 'CA magasin ({0} dern. sem.)',
  'gr.store.realChip': 'Données réelles',
  'gr.store.noStore': 'Aucune vente magasin identifiable',
  'gr.store.unavailable': 'Donnée indisponible',
  // Opportunités - priorities aggregated from the four real engines (2026-09-28).
  'gr.opp.emptyText': 'Nordla attend plus de ventes, d’historique ou de coûts d’achat vérifiés avant de recommander une action commerciale.',
  'gr.kpi.fix': 'À corriger maintenant',
  'gr.kpi.fixHint': 'Un même produit peut nécessiter plusieurs corrections.',
  'gr.kpi.fixNote': '{0} corrections détectées',
  'gr.kpi.commercial': 'Opportunités commerciales',
  'gr.kpi.commercialNote': 'Confirmées par vos données',
  'gr.kpi.watch': 'À surveiller',
  'gr.kpi.watchNote': 'Signaux encore trop faibles',
  'gr.ov.toOpportunities': 'Voir toutes les priorités',
  'gr.ov.prioritiesUnavailable': 'Priorités indisponibles pour le moment.',
  'gr.op.kpi.fix': 'À corriger maintenant',
  'gr.op.kpi.fixNote': '{0} corrections détectées',
  'gr.op.kpi.commercial': 'Opportunités commerciales',
  'gr.op.kpi.commercialNote': 'Confirmées par les seuils actuels',
  'gr.op.kpi.watch': 'À surveiller',
  'gr.op.kpi.watchNote': 'Signaux encore trop faibles',
  'gr.op.link.potential': 'Voir dans Produits Potentiels',
  'gr.op.link.content': 'Voir dans Contenu',
  'gr.op.link.storeGrowth': 'Voir dans Croissance magasin',
  'gr.op.link.audience': 'Voir dans Audience',
  'gr.op.fix.title': 'À corriger maintenant',
  'gr.op.fix.intro': 'Problèmes fiables dans vos données, regroupés par problème. Les corriger rend les recommandations plus sûres.',
  'gr.op.fix.empty': 'Rien à corriger dans les données analysées.',
  'gr.op.fix.examples': 'Exemples :',
  'gr.op.fix.soldAffected': '{0} parmi les produits vendus',
  'gr.op.fix.purchaseCost.title': 'Coûts d’achat à vérifier : {0} produits vendus',
  'gr.op.fix.purchaseCost.why': 'Nordla ne recommande « À pousser » et ne signale « Marge faible » que si le coût d’achat est vérifié. Ces coûts viennent de votre boutique sans vérification : ces recommandations restent bloquées.',
  'gr.op.fix.purchaseCost.detail': '{0} non vérifiés · {1} absents',
  'gr.op.fix.purchaseCost.blocked': '{0} recommandation(s) bloquée(s)',
  'gr.op.fix.purchaseCost.pending': 'La vérification des coûts d’achat n’est pas encore disponible dans Nordla.',
  'gr.op.fix.content.missingSku.title': '{0} produits sans SKU',
  'gr.op.fix.content.missingSku.why': 'Sans SKU, un produit est plus difficile à suivre en stock et à rapprocher de vos factures fournisseurs.',
  'gr.op.fix.content.noType.title': '{0} produits sans type',
  'gr.op.fix.content.noType.why': 'Sans type de produit, le produit ne peut pas être classé par catégorie dans vos analyses.',
  'gr.op.fix.content.noAltText.title': '{0} images sans texte alternatif',
  'gr.op.fix.content.noAltText.why': 'Sans texte alternatif, l’image n’est décrite ni pour les lecteurs d’écran ni pour les moteurs de recherche.',
  'gr.op.fix.content.noImage.title': '{0} produits sans image',
  'gr.op.fix.content.noImage.why': 'Sans image, le produit est difficile à reconnaître en ligne.',
  'gr.op.fix.content.noCollection.title': '{0} produits hors collection',
  'gr.op.fix.content.noCollection.why': 'Hors collection, le produit est plus difficile à trouver dans la boutique en ligne.',
  'gr.op.fix.content.duplicateTitle.title': '{0} produits au titre en double',
  'gr.op.fix.content.duplicateTitle.why': 'Deux produits au même titre sont difficiles à distinguer, pour vous comme pour vos clients.',
  'gr.op.com.title': 'Opportunités commerciales',
  'gr.op.com.intro': 'Uniquement ce que les moteurs Nordla confirment avec leurs seuils actuels.',
  'gr.op.com.emptyTitle': 'Aucune opportunité commerciale fiable pour l’instant',
  'gr.op.com.emptyText': 'Nordla ne recommande une action commerciale que lorsque les ventes, l’historique et les coûts d’achat sont assez fiables. Il attend :',
  'gr.op.wait.productSales': 'plus de ventes par produit : {0} produits sur {1} ont trop peu de ventes sur {2} semaines (moins de {3} unités) ;',
  'gr.op.wait.verifiedCosts': 'des coûts d’achat vérifiés : {0} produits vendus sur {1} n’en ont pas ;',
  'gr.op.wait.identifiedCustomers': 'plus de clients identifiés : {0} sur les {1} nécessaires pour former des groupes de clients ;',
  'gr.op.wait.storeHistory': 'un historique magasin plus long : Nordla compare les {0} dernières semaines aux {0} précédentes, pas encore entièrement couvertes ;',
  'gr.op.wait.onlineOrders': 'plus de commandes en ligne : {0} sur les {1} nécessaires pour comparer magasin et en ligne ;',
  'gr.op.wait.storeOrders': 'plus de commandes en magasin : {0} sur les {1} nécessaires ;',
  'gr.op.item.product.push.title': 'Mettre en avant « {0} »',
  'gr.op.item.product.push.why': 'Demande en hausse, stock suffisant et coût d’achat vérifié, selon Produits Potentiels.',
  'gr.op.item.product.restock.title': 'Réassortir « {0} » avant toute promotion',
  'gr.op.item.product.restock.why': 'Bonne demande mais stock trop court, selon Produits Potentiels.',
  'gr.op.item.store.weekday.title': 'Préparer le magasin pour le {0}',
  'gr.op.item.store.weekday.why': 'Ce jour réalise {0} de vos ventes en magasin, nettement plus que les autres, selon Croissance magasin.',
  'gr.op.item.segment.title': '{0} : {1} clients',
  'gr.op.item.segment.commercial.why': 'Groupe de clients signalé comme opportunité par Audience.',
  'gr.op.item.segment.watch.why': 'Groupe de clients à surveiller selon Audience.',
  'gr.op.watch.title': 'À surveiller',
  'gr.op.watch.intro': 'Signaux intéressants mais trop faibles, ou bloqués par un garde-fou : Nordla ne recommande pas encore d’agir.',
  'gr.op.watch.empty': 'Aucun signal à surveiller pour l’instant.',
  'gr.op.volume': '{0} ventes en {1} semaines',
  'gr.op.volumeStore': 'n° {0} du magasin ({1} des ventes en magasin)',
  'gr.op.why.risingBlocked': 'La demande monte, mais le coût d’achat n’est pas vérifié : Nordla ne recommande pas de pousser ce produit tant que sa marge n’est pas fiable.',
  'gr.op.why.watch': 'Produits Potentiels signale un point à vérifier avant toute promotion.',
  'gr.op.why.declining': 'Les ventes baissent : Nordla ne recommande pas de le mettre en avant.',
  'gr.op.why.lowMargin': 'La marge vérifiée est trop faible pour une promotion.',
  'gr.op.why.returns': 'Les retours sont élevés : à examiner avant toute promotion.',
  'gr.op.why.storeSuggestionThin': 'Bien placé en magasin, mais avec si peu de ventes Nordla ne peut pas encore recommander de le mettre en avant.',
  'gr.op.why.notValidated': 'Signal non confirmé par Produits Potentiels.',
  'gr.op.why.noProductEngine': 'Signal du magasin sans données produit suffisantes.',
  'gr.op.f.potential.push': 'À pousser',
  'gr.op.f.potential.restock': 'Réassort avant promotion',
  'gr.op.f.potential.topSeller': 'Parmi vos meilleures ventes',
  'gr.op.f.potential.watch': 'À surveiller',
  'gr.op.f.potential.declining': 'Ventes en baisse',
  'gr.op.f.potential.lowMargin': 'Marge faible',
  'gr.op.f.potential.returns': 'Retours élevés',
  'gr.op.f.potential.stable': 'Ventes stables',
  'gr.op.f.potential.insufficient': 'Données insuffisantes',
  'gr.op.f.risingDemand': 'Demande en hausse',
  'gr.op.f.storeTop': 'N° {0} du magasin',
  'gr.op.f.storeTopBlocked': 'N° {0} du magasin, écarté de la mise en avant',
  'gr.op.f.storeSuggested': 'Mise en avant suggérée en magasin',
  'gr.op.f.storeSuggestedNotRecommended': 'Suggéré en magasin, non recommandé',
  'gr.op.f.costUnverified': 'Coût d’achat non vérifié',
  'gr.op.f.costMissing': 'Coût d’achat absent',
  'gr.op.f.contentIncomplete': 'Fiche produit incomplète',
  'gr.op.missing': 'Il manque :',
  'gr.op.m.verifiedCost': 'un coût d’achat vérifié',
  'gr.op.m.moreWeeks': 'plus de semaines de ventes (au moins {0} semaines et {1} ventes)',
  'gr.op.m.risingDemand': 'une demande en hausse',
  'gr.op.m.fewerReturns': 'moins de retours',
  'gr.op.m.productHistory': 'des données de ventes pour ce produit',
  'gr.op.rel.reliable': 'Fiable',
  'gr.op.rel.limited': 'Signal faible',
  'gr.op.foot': 'Faits observés dans vos données et recalculés à chaque visite. Aucune causalité supposée, aucune action automatique.',
  'gr.op.srcUnavailable': 'Source indisponible pour le moment : {0}. Les autres sources sont prises en compte.',
});
