'use strict';
// Français - langue par défaut de Nordla Growth (même runtime NORDLA_I18N qu'Analytics Premium).
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.fr = Object.assign(window.NORDLA_DICTS.fr || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.vsPrevious': 'vs période précédente',
  'gr.nav.aria': 'Navigation Growth',
  'gr.nav.overview': 'Vue d’ensemble',
  'gr.nav.opportunities': 'Opportunités',
  'gr.nav.campaigns': 'Campagnes',
  'gr.nav.content': 'Contenu',
  'gr.nav.storeGrowth': 'Croissance magasin',
  'gr.nav.audience': 'Audience',
  'gr.nav.experiments': 'Expériences',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Paramètres',
  'gr.nav.soon': 'Bientôt disponible',
  'gr.demo': 'Données de démonstration',
  'gr.demoShort': 'Démo',
  'gr.demoTitle': 'Aucune source Growth n’est encore connectée : tous les chiffres de cette page sont des exemples.',
  'gr.period.last30': '30 derniers jours',
  'gr.period.fixed': 'Fixe',
  'gr.period.fixedNote': 'La vue Growth affiche les 30 derniers jours.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Transformez les données de votre entreprise en opportunités de croissance mesurables.',
  'gr.kpi.revenueInfluenced': 'CA influencé',
  'gr.kpi.activeOpportunities': 'Opportunités actives',
  'gr.kpi.highPriority': 'haute priorité',
  'gr.kpi.activeCampaigns': 'Campagnes actives',
  'gr.kpi.performingWell': 'performantes',
  'gr.kpi.roas': 'ROAS',
  'gr.kpi.experimentsRunning': 'Expériences en cours',
  'gr.kpi.endingThisWeek': 'se termine cette semaine',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Indicateur affiché',
  'gr.pulse.revenue': 'Chiffre d’affaires',
  'gr.pulse.traffic': 'Trafic magasin',
  'gr.pulse.total': 'CA total',
  'gr.pulse.influenced': 'CA influencé par Growth',
  'gr.pulse.visitors': 'Visiteurs en magasin',
  'gr.pulse.share': '{0} % influencé par Growth',
  'gr.pulse.foot': 'Par jour, du {0} au {1}. Chiffre d’affaires et trafic ont des unités différentes : ils sont affichés séparément.',
  'gr.ai.title': 'Insights Nordla AI',
  'gr.ai.badge': 'Nordla AI',
  'gr.ai.foot': 'Nordla AI explique ; les chiffres viennent du moteur de calcul.',
  'gr.att.title': 'Nécessite votre attention',
  'gr.att.status.pending': 'À approuver',
  'gr.att.status.new': 'Nouveau',
  'gr.att.status.endingSoon': 'Se termine bientôt',
  'gr.att.action.approve': 'Examiner',
  'gr.att.action.review': 'Examiner',
  'gr.att.action.results': 'Résultats',
  'gr.att.soon': 'Disponible avec la page Approvals (bientôt)',
  'gr.ch.title': 'Performance par canal',
  'gr.ch.channel': 'Canal',
  'gr.ch.revenue': 'CA',
  'gr.ch.reach': 'Visites / portée',
  'gr.ch.conversion': 'Conversion',
  'gr.ch.roas': 'ROAS',
  'gr.ch.unit.visits': 'visites',
  'gr.ch.unit.reach': 'portée',
  'gr.ch.unit.actions': 'actions',
  'gr.ch.organic': 'organique',
  'gr.ch.foot': 'ROAS = CA attribué ÷ dépense publicitaire. « organique » = canal sans dépense.',
  'gr.camp.title': 'Campagnes',
  'gr.camp.activeCount': '{0} actives',
  'gr.camp.spend': '{0} dépensés sur {1}',
  'gr.camp.noBudget': 'Sans budget (organique)',
  'gr.camp.status.performing': 'Performante',
  'gr.camp.status.active': 'Active',
  'gr.camp.status.watch': 'À surveiller',
  'gr.camp.roas': 'ROAS {0}',
  'gr.camp.conversions': '{0} conversions',
  'gr.camp.actions': '{0} actions',
  'gr.content.title': 'Performance du contenu',
  'gr.content.kind.reel': 'Reel',
  'gr.content.kind.video': 'Vidéo',
  'gr.content.kind.carousel': 'Carrousel',
  'gr.content.kind.post': 'Post',
  'gr.content.views': '{0} vues',
  'gr.content.perf.best': 'Meilleur contenu',
  'gr.content.perf.good': 'Bon',
  'gr.content.perf.below': 'Sous la moyenne',
  'gr.store.title': 'Croissance magasin',
  'gr.store.traffic': 'Trafic magasin',
  'gr.store.conversion': 'Taux de conversion',
  'gr.store.revenue': 'CA magasin',
  'gr.store.pts': '{0} pts',
  'gr.opp.title': 'Opportunités prioritaires',
  'gr.opp.source': 'Source : {0}',
  'gr.opp.priority.high': 'Priorité haute',
  'gr.opp.priority.medium': 'Priorité moyenne',
  'gr.opp.status.recommended': 'Recommandée',
  'gr.opp.status.review': 'À examiner',
  'gr.opp.status.planned': 'Planifiée',
  'gr.opp.estimate': 'CA estimé',
  'gr.opp.foot': 'Estimations sur 30 jours, à valider avant toute action.',
  'gr.exp.title': 'Expériences',
  'gr.exp.kpi': 'KPI testé : {0}',
  'gr.exp.status.running': 'En cours',
  'gr.exp.status.endingSoon': 'Se termine bientôt',
  'gr.exp.duration': '{0} jours',
  'gr.exp.ends': 'Fin',
  'gr.noData': 'Données indisponibles',
  'gr.loadError': 'La vue Growth n’a pas pu être chargée.',
});
