'use strict';
// Nederlands - Nordla Growth.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.nl = Object.assign(window.NORDLA_DICTS.nl || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.ov.demoTitle': 'Campagnecijfers overgenomen van de pagina Campagnes (demonstratiegegevens). Winkelverkopen zijn echt. De andere bronnen zijn niet gekoppeld.',
  'gr.src.notConnected': 'Bron niet gekoppeld',
  'gr.src.unavailable': 'Gegevens niet beschikbaar',
  'gr.ov.nc.influenced': 'Door Growth beïnvloede omzet vereist een toewijzing van verkopen aan marketingacties. Er is geen attributiebron gekoppeld.',
  'gr.ov.nc.ai': 'Er is nog geen aanbevelingsmotor aan deze kaart gekoppeld.',
  'gr.ov.nc.attention': 'Er is nog geen bron voor meldingen gekoppeld.',
  'gr.ov.nc.content': 'Er is geen sociaal account gekoppeld: contentprestaties zijn niet beschikbaar.',
  'gr.ov.nc.opportunities': 'Er is nog geen kansenpijplijn gekoppeld.',
  'gr.ov.fromCampaigns': 'Bron: Campagnes (demo)',
  'gr.ov.chFoot': 'Omzet en ROAS overgenomen van de pagina Campagnes (demonstratiegegevens). Bereik en conversie: bron niet gekoppeld.',
  'gr.op.nc.pipeline': 'Geen enkele Nordla-motor levert nog een kansenpijplijn (prioriteit, potentiële omzet, betrouwbaarheid, status).',
  'gr.op.nc.revenue': 'Potentiële omzet per bron vereist een gekoppelde kansenpijplijn.',
  'gr.op.nc.segments': 'Segmenten met hoog potentieel vereisen een gekoppelde kansenpijplijn.',
  'gr.op.nc.effort': 'Impact en inspanning worden niet geschat zolang er geen kans gekoppeld is.',
  'gr.op.nc.approvals': 'Niets goed te keuren: er is geen kansenbron gekoppeld.',
  'gr.op.nc.wins': 'Geen gemeten successen: er is geen kansenbron gekoppeld.',
  'gr.vsPrevious': 'vs vorige periode',
  'gr.nav.aria': 'Growth-navigatie',
  'gr.nav.overview': 'Overzicht',
  'gr.nav.opportunities': 'Kansen',
  'gr.nav.campaigns': 'Campagnes',
  'gr.nav.content': 'Content',
  'gr.nav.storeGrowth': 'Winkelgroei',
  'gr.nav.audience': 'Doelgroep',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Instellingen',
  'gr.nav.soon': 'Binnenkort beschikbaar',
  'gr.nav.more': 'Meer',
  'gr.nav.moreTitle': 'Andere Growth-pagina’s',
  'gr.demo': 'Demogegevens',
  'gr.demoShort': 'Demo',
  'gr.demoTitle': 'Er is nog geen Growth-bron gekoppeld: alle cijfers op deze pagina zijn voorbeelden.',
  'gr.period.last30': 'Laatste 30 dagen',
  'gr.period.fixed': 'Vast',
  'gr.period.fixedNote': 'De Growth-weergave toont de laatste 30 dagen.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Zet uw bedrijfsgegevens om in meetbare groeikansen.',
  'gr.kpi.revenueInfluenced': 'Beïnvloede omzet',
  'gr.kpi.activeOpportunities': 'Actieve kansen',
  'gr.kpi.highPriority': 'hoge prioriteit',
  'gr.kpi.activeCampaigns': 'Actieve campagnes',
  'gr.kpi.performingWell': 'presteren goed',
  'gr.kpi.roas': 'ROAS',
  'gr.kpi.endingThisWeek': 'eindigt deze week',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Getoonde indicator',
  'gr.pulse.revenue': 'Omzet',
  'gr.pulse.traffic': 'Winkelbezoek',
  'gr.pulse.total': 'Totale omzet',
  'gr.pulse.influenced': 'Omzet beïnvloed door Growth',
  'gr.pulse.visitors': 'Winkelbezoekers',
  'gr.pulse.share': '{0} % beïnvloed door Growth',
  'gr.pulse.foot': 'Per dag, van {0} tot {1}. Omzet en bezoek hebben andere eenheden en worden apart getoond.',
  'gr.ai.title': 'Nordla AI-inzichten',
  'gr.ai.badge': 'Nordla AI',
  'gr.ai.foot': 'Nordla AI verklaart; de cijfers komen uit de rekenmotor.',
  'gr.att.title': 'Vraagt uw aandacht',
  'gr.att.status.pending': 'Goed te keuren',
  'gr.att.status.new': 'Nieuw',
  'gr.att.status.endingSoon': 'Loopt bijna af',
  'gr.att.action.approve': 'Bekijken',
  'gr.att.action.review': 'Bekijken',
  'gr.att.action.results': 'Resultaten',
  'gr.att.soon': 'Beschikbaar met de pagina Approvals (binnenkort)',
  'gr.ch.title': 'Prestaties per kanaal',
  'gr.ch.channel': 'Kanaal',
  'gr.ch.revenue': 'Omzet',
  'gr.ch.reach': 'Bezoeken / bereik',
  'gr.ch.conversion': 'Conversie',
  'gr.ch.roas': 'ROAS',
  'gr.ch.unit.visits': 'bezoeken',
  'gr.ch.unit.reach': 'bereik',
  'gr.ch.unit.actions': 'acties',
  'gr.ch.organic': 'organisch',
  'gr.ch.foot': 'ROAS = toegewezen omzet ÷ advertentie-uitgaven. „organisch” = kanaal zonder uitgaven.',
  'gr.camp.title': 'Campagnes',
  'gr.camp.activeCount': '{0} actief',
  'gr.camp.spend': '{0} besteed van {1}',
  'gr.camp.noBudget': 'Geen budget (organisch)',
  'gr.camp.status.performing': 'Presteert',
  'gr.camp.status.active': 'Actief',
  'gr.camp.status.watch': 'Opvolgen',
  'gr.camp.roas': 'ROAS {0}',
  'gr.camp.conversions': '{0} conversies',
  'gr.camp.actions': '{0} acties',
  'gr.content.title': 'Contentprestaties',
  'gr.content.kind.reel': 'Reel',
  'gr.content.kind.video': 'Video',
  'gr.content.kind.carousel': 'Carrousel',
  'gr.content.kind.post': 'Post',
  'gr.content.views': '{0} weergaven',
  'gr.content.perf.best': 'Best presterend',
  'gr.content.perf.good': 'Goed',
  'gr.content.perf.below': 'Onder gemiddeld',
  'gr.store.title': 'Winkelgroei',
  'gr.store.traffic': 'Winkelbezoek',
  'gr.store.conversion': 'Conversiegraad',
  'gr.store.revenue': 'Winkelomzet',
  'gr.store.pts': '{0} ptn',
  'gr.opp.title': 'Belangrijkste kansen',
  'gr.opp.source': 'Bron: {0}',
  'gr.opp.priority.high': 'Hoge prioriteit',
  'gr.opp.priority.medium': 'Gemiddelde prioriteit',
  'gr.opp.status.recommended': 'Aanbevolen',
  'gr.opp.status.review': 'Te bekijken',
  'gr.opp.status.planned': 'Gepland',
  'gr.opp.estimate': 'Geschatte omzet',
  'gr.opp.foot': 'Schattingen over 30 dagen, te valideren vóór elke actie.',
  'gr.noData': 'Gegevens niet beschikbaar',
  'gr.loadError': 'De Growth-weergave kon niet worden geladen.',
  'gr.op.title': 'Kansen',
  'gr.op.subtitle': 'Identificeer en prioriteer de meest veelbelovende groeihefbomen voor uw activiteit.',
  'gr.op.kpi.priority': 'Prioritaire kansen',
  'gr.op.kpi.highPriority': '{0} hoge prioriteit',
  'gr.op.kpi.potential': 'Potentiële omzet',
  'gr.op.kpi.active': '{0} actieve kansen',
  'gr.op.kpi.ready': 'Klaar voor goedkeuring',
  'gr.op.kpi.readyNote': 'Acties die kunnen starten',
  'gr.op.kpi.inProgress': 'Lopend',
  'gr.op.kpi.inProgressNote': 'Kansen in uitvoering',
  'gr.op.kpi.wins': 'Successen deze maand',
  'gr.op.kpi.winsNote': '{0} gegenereerd',
  'gr.op.pipe.title': 'Pijplijn van kansen',
  'gr.op.pipe.desc': 'Identificeer, prioriteer en volg de groeikansen die Nordla detecteert.',
  'gr.op.pipe.foot': '{0} kansen getoond · {1} potentiële omzet. Schattingen, te valideren vóór elke actie.',
  'gr.op.f.source': 'Bron',
  'gr.op.f.allSources': 'Alle bronnen',
  'gr.op.f.status': 'Status',
  'gr.op.f.allStatuses': 'Alle statussen',
  'gr.op.f.sort': 'Sortering',
  'gr.op.f.sort.priority': 'Sorteren op prioriteit',
  'gr.op.f.sort.revenue': 'Sorteren op potentiële omzet',
  'gr.op.f.sort.confidence': 'Sorteren op betrouwbaarheid',
  'gr.op.col.name': 'Kans',
  'gr.op.col.source': 'Bron',
  'gr.op.col.priority': 'Prioriteit',
  'gr.op.col.revenue': 'Potentiële omzet',
  'gr.op.col.confidence': 'Betrouwbaarheid',
  'gr.op.col.effort': 'Inspanning',
  'gr.op.col.status': 'Status',
  'gr.op.col.actions': 'Acties',
  'gr.op.actionsSoon': 'Acties binnenkort beschikbaar',
  'gr.op.noMatch': 'Geen kans komt overeen met deze filters.',
  'gr.op.src.store': 'Winkelanalyse',
  'gr.op.src.stock': 'Voorraad',
  'gr.op.src.market': 'Markttrend',
  'gr.op.src.ai': 'Nordla AI',
  'gr.op.src.customers': 'Klantgedrag',
  'gr.op.src.experiment': 'Winkelexperiment',
  'gr.op.src.seasonality': 'Seizoensgebondenheid',
  'gr.op.src.sales': 'Verkoop',
  'gr.op.src.local': 'Lokale gegevens',
  'gr.op.src.margin': 'Marges',
  'gr.op.status.ready': 'Klaar voor goedkeuring',
  'gr.op.status.inProgress': 'Lopend',
  'gr.op.status.analysis': 'Te analyseren',
  'gr.op.status.planned': 'Gepland',
  'gr.op.priority.high': 'Hoog',
  'gr.op.priority.medium': 'Gemiddeld',
  'gr.op.priority.low': 'Laag',
  'gr.op.effort.low': 'Laag',
  'gr.op.effort.medium': 'Gemiddeld',
  'gr.op.effort.high': 'Hoog',
  'gr.op.ai.title': 'Aanbevelingen Nordla AI',
  'gr.op.ai.potential': 'Potentiële omzet',
  'gr.op.ai.confidence': 'betrouwbaarheid {0}',
  'gr.op.mx.title': 'Impact vs inspanning',
  'gr.op.mx.impact': 'Impact',
  'gr.op.mx.effortLow': 'Lage inspanning',
  'gr.op.mx.effortHigh': 'Gemiddelde tot hoge inspanning',
  'gr.op.mx.highLow': 'Hoge impact · lage inspanning',
  'gr.op.mx.highHigh': 'Hoge impact · hoge inspanning',
  'gr.op.mx.lowLow': 'Lage impact · lage inspanning',
  'gr.op.mx.lowHigh': 'Lage impact · hoge inspanning',
  'gr.op.mx.foot': 'De {0} prioritaire kansen, geplaatst volgens geschatte impact en inspanning.',
  'gr.op.appr.title': 'Vraagt uw goedkeuring',
  'gr.op.appr.budget': 'Voorgesteld budget {0}',
  'gr.op.appr.expected': 'verwachte omzet {0}',
  'gr.op.appr.approve': 'Goedkeuren',
  'gr.op.appr.soon': 'De goedkeuringsworkflow is nog niet beschikbaar',
  'gr.op.appr.foot': 'Er wordt geen actie gestart zonder uw beslissing.',
  'gr.op.seg.title': 'Segmenten met hoog potentieel',
  'gr.op.seg.foot': 'Geschatte groei van het potentieel per segment.',
  'gr.op.wins.title': 'Recente successen',
  'gr.op.wins.target': 'Doel {0} · {1} behaald',
  'gr.op.bySource.title': 'Potentiële omzet per bron',
  'gr.op.bySource.total': 'potentieel',
  'gr.op.bySource.others': 'Overige ({0})',
  'gr.op.bySource.foot': '{0} verdeeld over {1} bronnen; de kleinste zijn gegroepeerd.',
  'gr.op.byStatus.title': 'Pijplijn per status',
  'gr.op.byStatus.count': '{0} kansen',
  'gr.op.byStatus.foot': '{0} kansen · {1} potentiële omzet.',
  'gr.cp.title': 'Campagnes',
  'gr.cp.subtitle': 'Maak, volg en optimaliseer uw marketingcampagnes op al uw kanalen.',
  'gr.cp.kpi.revenue': 'Gegenereerde omzet',
  'gr.cp.kpi.clicks': 'Klikken',
  'gr.cp.kpi.newCustomers': 'Nieuwe klanten',
  'gr.cp.kpi.roas': 'Gemiddelde ROAS',
  'gr.cp.table.title': 'Campagnes ({0})',
  'gr.cp.table.foot': '{0} van {1} campagnes getoond. Prestatie = resultaat ten opzichte van het campagnedoel.',
  'gr.cp.search': 'Een campagne zoeken…',
  'gr.cp.f.channel': 'Kanaal',
  'gr.cp.f.allChannels': 'Alle kanalen',
  'gr.cp.f.status': 'Status',
  'gr.cp.f.allStatuses': 'Alle statussen',
  'gr.cp.new': '+ Nieuwe campagne',
  'gr.cp.newSoon': 'Campagnes aanmaken is nog niet beschikbaar',
  'gr.cp.noMatch': 'Geen campagne komt overeen met deze zoekopdracht.',
  'gr.cp.col.campaign': 'Campagne',
  'gr.cp.col.channel': 'Kanaal',
  'gr.cp.col.objective': 'Doel',
  'gr.cp.col.period': 'Periode',
  'gr.cp.col.budget': 'Budget',
  'gr.cp.col.status': 'Status',
  'gr.cp.col.performance': 'Prestatie',
  'gr.cp.status.running': 'Lopend',
  'gr.cp.status.ready': 'Klaar om te starten',
  'gr.cp.status.planned': 'Gepland',
  'gr.cp.objective.sales': 'Verkoop',
  'gr.cp.objective.awareness': 'Naamsbekendheid',
  'gr.cp.objective.storeTraffic': 'Winkelbezoek',
  'gr.cp.objective.retention': 'Klantbehoud',
  'gr.cp.objective.recruitment': 'Rekrutering',
  'gr.cp.actions.title': 'Prioritaire acties',
  'gr.cp.channels.title': 'Prestaties per kanaal',
  'gr.cp.channels.foot': 'Aandeel van de gegenereerde omzet ({0}) per kanaal.',
  'gr.cp.trend.title': 'Omzet vs uitgaven — laatste 30 dagen',
  'gr.cp.trend.revenue': 'Omzet',
  'gr.cp.trend.spend': 'Uitgaven',
  'gr.cp.trend.roas': 'ROAS {0}',
  'gr.cp.trend.foot': 'Per dag, van {0} tot {1}: omzet toegewezen aan campagnes en advertentie-uitgaven.',
  'gr.cp.f.sort': 'Sortering',
  'gr.cp.f.sort.default': 'Standaardvolgorde',
  'gr.cp.f.sort.budget': 'Sorteren op budget',
  'gr.cp.f.sort.performance': 'Sorteren op prestatie',
  'gr.cp.perfNone': 'Nog niet gestart: geen prestatie gemeten',
  'gr.cp.channels.spendRoas': '{0} uitgegeven · ROAS {1}',
  'gr.cp.channels.noSpend': 'Zonder uitgaven',
  // Potentiel produits
  'gr.nav.potential': 'Productpotentieel',
  'gr.period.lastWeeks': 'Laatste {0} weken',
  'gr.period.weeksNote': 'Analyse over de laatste {0} volledige weken.',
  'gr.pp.title': 'Productpotentieel',
  'gr.pp.subtitle': 'Zie welke producten u kunt pushen, opvolgen of beschermen op basis van vraag, voorraad en rendabiliteit.',
  'gr.pp.days': '{0} d',
  'gr.pp.unit1': '{0} eenheid verkocht',
  'gr.pp.uN': '{0} eenheden',
  'gr.pp.u1': '{0} eenheid',
  'gr.pp.units': '{0} eenheden verkocht',
  'gr.pp.noImage': 'Geen gesynchroniseerde afbeelding',
  'gr.pp.noCategory': 'Zonder categorie',
  'gr.pp.openDetail': 'Details bekijken: {0}',
  'gr.pp.close': 'Sluiten',
  'gr.pp.kpi.active': 'Actieve producten',
  'gr.pp.kpi.activeNote': 'Verkocht in de laatste {0} weken',
  'gr.pp.kpi.push': 'Te pushen producten',
  'gr.pp.kpi.pushNote': '{0} van de verkoop in de periode',
  'gr.pp.kpi.pushNone': 'Geen enkel voldoet aan alle voorwaarden',
  'gr.pp.kpi.watch': 'Op te volgen',
  'gr.pp.kpi.watchNote': 'Daling, lage marge, retouren of tegenstrijdig signaal',
  'gr.pp.kpi.restock': 'Eerst aanvullen, dan promoten',
  'gr.pp.kpi.restockNote': 'Goede vraag, te weinig voorraad',
  'gr.pp.list.title': 'Producten',
  'gr.pp.list.desc': 'Elk product verkocht in de laatste {0} weken, met zijn Growth-status en het signaal dat die verklaart.',
  'gr.pp.list.foot': '{0} van {1} producten getoond',
  'gr.pp.quality.stock': 'Laatste voorraadmeting: {0} (gebruikt als ze jonger is dan {1} u)',
  'gr.pp.quality.noStock': 'Geen gesynchroniseerde voorraadmeting',
  'gr.pp.search': 'Product zoeken',
  'gr.pp.noMatch': 'Geen enkel product komt overeen met deze filters.',
  'gr.pp.empty.title': 'Geen product verkocht in de periode',
  'gr.pp.empty.text': 'Geen gesynchroniseerde verkoop in de laatste {0} weken: voorlopig niets aan te bevelen.',
  'gr.pp.f.aria': 'Filteren op Growth-status',
  'gr.pp.f.all': 'Alle',
  'gr.pp.f.push': 'Pushen',
  'gr.pp.f.growth': 'Sterke groei',
  'gr.pp.f.top': 'Bestsellers',
  'gr.pp.f.watch': 'Op te volgen',
  'gr.pp.f.restock': 'Eerst aanvullen',
  'gr.pp.f.lowMargin': 'Lage marge',
  'gr.pp.f.insufficient': 'Onvoldoende gegevens',
  'gr.pp.f.category': 'Categorie',
  'gr.pp.f.allCategories': 'Alle categorieën',
  'gr.pp.f.sort': 'Sorteren',
  'gr.pp.f.sort.sales': 'Sorteren op verkoop',
  'gr.pp.f.sort.evolution': 'Sorteren op evolutie',
  'gr.pp.f.sort.cover': 'Sorteren op dekking',
  'gr.pp.f.sort.margin': 'Sorteren op marge',
  'gr.pp.col.product': 'Product',
  'gr.pp.col.sales': 'Verkoop',
  'gr.pp.col.evolution': 'Evolutie',
  'gr.pp.col.margin': 'Marge',
  'gr.pp.col.stock': 'Voorraad',
  'gr.pp.col.cover': 'Dekking',
  'gr.pp.col.status': 'Status · signaal',
  'gr.pp.evo.insufficient': 'Onvoldoende historiek',
  'gr.pp.trend.UP': 'Stijgend',
  'gr.pp.trend.DOWN': 'Dalend',
  'gr.pp.trend.FLAT': 'Stabiel',
  'gr.pp.margin.MISSING': 'Kostprijs ontbreekt',
  'gr.pp.margin.PARTIAL': 'Gedeeltelijke marge',
  'gr.pp.margin.UNVERIFIED': 'Kostprijs niet geverifieerd',
  'gr.pp.margin.RELIABLE': 'Kostprijs geverifieerd',
  'gr.pp.stock.stale': 'Oude meting',
  'gr.pp.stock.unavailable': 'Voorraad onbekend',
  'gr.pp.cover.OUT': 'Uitverkocht',
  'gr.pp.cover.STOCK_UNUSABLE': 'Dekking niet berekend: voorraad onbekend of meting te oud.',
  'gr.pp.cover.INSUFFICIENT_HISTORY': 'Dekking niet berekend: onvoldoende verkoophistoriek.',
  'gr.pp.cover.INSUFFICIENT_SALES_SAMPLE': 'Dekking niet berekend: te weinig verkoop om een ritme te schatten.',
  'gr.pp.cover.NO_DEMAND_OBSERVED': 'Dekking niet berekend: geen vraag waargenomen.',
  'gr.pp.cover.NO_STOCK': 'Voorraad op.',
  'gr.pp.cover.UNKNOWN': 'Dekking niet berekend.',
  'gr.pp.status.push': 'Pushen',
  'gr.pp.status.restock': 'Eerst aanvullen',
  'gr.pp.status.topSeller': 'Topverkoper',
  'gr.pp.status.watch': 'Opvolgen',
  'gr.pp.status.declining': 'Dalend',
  'gr.pp.status.lowMargin': 'Lage marge',
  'gr.pp.status.returns': 'Te veel retouren',
  'gr.pp.status.insufficient': 'Onvoldoende gegevens',
  'gr.pp.status.stable': 'Stabiel',
  'gr.pp.signal.newProduct': 'Nieuw product: minder dan {0} weken verkoop',
  'gr.pp.signal.thinSample': '{0}: te kleine steekproef',
  'gr.pp.signal.outOfStock': 'Vraag aanwezig, voorraad op',
  'gr.pp.signal.coverDays': 'Voorraad voor slechts {0} dagen',
  'gr.pp.signal.returnRate': '{0} van de eenheden terugbetaald',
  'gr.pp.signal.margin': 'Geverifieerde marge van {0}',
  'gr.pp.signal.evolution': '{0} t.o.v. vorige {1} w.',
  'gr.pp.signal.topRank': 'Nr. {0} in verkoop over de periode',
  'gr.pp.signal.none': 'Geen bijzonder signaal',
  'gr.pp.action.increaseVisibility': 'Zichtbaarheid verhogen',
  'gr.pp.action.restockFirst': 'Eerst aanvullen',
  'gr.pp.action.doNotPromote': 'Niet promoten',
  'gr.pp.action.reviewReturns': 'Retouren analyseren',
  'gr.pp.action.checkCost': 'Kostprijs controleren',
  'gr.pp.action.checkStock': 'Voorraad controleren',
  'gr.pp.action.watch': 'Opvolgen',
  'gr.pp.action.keep': 'Beschikbaar houden',
  'gr.pp.action.none': 'Geen actie',
  'gr.pp.actionText.increaseVisibility': 'Geef het meer zichtbaarheid: in de webshop, in de etalage of in een volgende campagne. Voorraad en marge kunnen volgen.',
  'gr.pp.actionText.restockFirst': 'Vul eerst aan vóór elke promotie: nu promoten zou vooral tot tekorten leiden.',
  'gr.pp.actionText.doNotPromote': 'Geen geld aan zichtbaarheid voor dit product zolang marge of retouren niet opgelost zijn.',
  'gr.pp.actionText.reviewReturns': 'Bekijk de redenen van terugbetaling (kwaliteit, maat, beschrijving) voordat u het meer zichtbaarheid geeft.',
  'gr.pp.actionText.checkCost': 'De vraag stijgt maar de marge is niet betrouwbaar: vul de aankoopprijs in of controleer ze om te weten of pushen rendabel is.',
  'gr.pp.actionText.checkStock': 'De vraag stijgt maar de voorraad is niet zeker gekend: controleer ze vóór elke promotie.',
  'gr.pp.actionText.watch': 'Geen onmiddellijke actie: volg de evolutie de komende weken op.',
  'gr.pp.actionText.keep': 'Houd het beschikbaar en zichtbaar zoals nu; extra promotie is niet nodig.',
  'gr.pp.actionText.none': 'Niet genoeg gegevens om een actie aan te bevelen: Nordla wacht op meer verkoop.',
  'gr.pp.reason.COST_MISSING': 'Kostprijs ontbreekt',
  'gr.pp.reason.MARGIN_PARTIAL': 'Gedeeltelijke marge',
  'gr.pp.reason.COST_UNVERIFIED': 'Kostprijs niet geverifieerd',
  'gr.pp.reason.STOCK_STALE': 'Oude voorraadmeting',
  'gr.pp.reason.STOCK_UNAVAILABLE': 'Voorraad onbekend',
  'gr.pp.reason.COVER_UNKNOWN': 'Dekking niet berekenbaar',
  'gr.pp.reason.HIGH_RETURNS': 'Te veel retouren',
  'gr.pp.reason.RETURNS_ELEVATED': 'Hoge retouren',
  'gr.pp.reason.TREND_INSUFFICIENT': 'Onvoldoende historiek',
  'gr.pp.push.title': 'Te pushen producten',
  'gr.pp.push.none': 'Geen enkel product voldoet vandaag aan de vier voorwaarden om te pushen:',
  'gr.pp.push.cond.demand': 'stijgende vraag;',
  'gr.pp.push.cond.cover': 'gekende voorraad voor minstens {0} weken;',
  'gr.pp.push.cond.cost': 'geverifieerde aankoopprijs (betrouwbare marge);',
  'gr.pp.push.cond.returns': 'retouren hoogstens {0}.',
  'gr.pp.push.foot': 'Stijgende vraag, voldoende voorraad, geverifieerde kostprijs en normale retouren.',
  'gr.pp.protect.title': 'Beschermen / niet pushen',
  'gr.pp.protect.none': 'Voorlopig geen product om te beschermen.',
  'gr.pp.protect.foot': 'Aanvullen, retouren, lage marge, tegenstrijdige signalen of daling.',
  'gr.pp.byStatus.title': 'Producten per Growth-status',
  'gr.pp.byStatus.foot': '{0} actieve producten ingedeeld',
  'gr.pp.d.why': 'Waarom deze status',
  'gr.pp.d.evidence': 'Bewijzen (laatste {0} weken)',
  'gr.pp.d.action': 'Aanbevolen actie',
  'gr.pp.d.opportunity': 'Kans aanmaken',
  'gr.pp.d.opportunitySoon': 'Binnenkort: dit product toevoegen aan de Growth-kansen.',
  'gr.pp.d.method': 'Status berekend op basis van de in Nordla gesynchroniseerde verkoop, voorraad, kostprijzen en terugbetalingen. Onbekende gegevens tellen nooit als nul.',
  'gr.pp.ev.sales': 'Netto verkoop excl. btw',
  'gr.pp.ev.salesNote': 'Nr. {0} van de periode',
  'gr.pp.ev.units': 'Verkochte eenheden',
  'gr.pp.ev.velocity': 'gemiddeld {0} per week',
  'gr.pp.ev.evoNote': '{0} st. tegen {1} st. ({2} w. vs {2} w.)',
  'gr.pp.ev.evoNone': 'Minstens {0} weken verkoop nodig om te vergelijken.',
  'gr.pp.ev.snapshot': 'Meting van {0}',
  'gr.pp.ev.snapshotOld': 'Laatste meting op {0}: te oud om te beslissen',
  'gr.pp.ev.noSnapshot': 'Geen gesynchroniseerde voorraadmeting',
  'gr.pp.ev.coverNote': 'Aanvuldrempel: {0} weken',
  'gr.pp.ev.refunds': 'Terugbetalingen',
  'gr.pp.ev.refundNote': 'Terugbetaalde eenheden: {0}',
  'gr.pp.ev.history': 'Waargenomen historiek',
  'gr.pp.ev.weeks': '{0} w.',
  'gr.pp.rule.NEW_PRODUCT': 'Dit product heeft slechts {0} weken waargenomen verkoop; er zijn er minstens {1} nodig voor een aanbeveling.',
  'gr.pp.rule.THIN_SAMPLE': '{0} in {2} weken: er zijn er minstens {1} nodig om te besluiten.',
  'gr.pp.rule.DEMAND_BUT_OUT_OF_STOCK': 'De vraag is goed maar de voorraad is op: promoten zou klanten naar een tekort sturen.',
  'gr.pp.rule.DEMAND_BUT_LOW_COVER': 'De vraag is goed maar de voorraad dekt slechts {0} dagen (minder dan {1} weken): eerst aanvullen vóór elke promotie.',
  'gr.pp.rule.DEMAND_BUT_HIGH_RETURNS': 'De vraag is goed, maar {0} van de verkochte eenheden werd terugbetaald: eerst begrijpen, dan pushen.',
  'gr.pp.rule.HIGH_RETURNS': '{0} van de verkochte eenheden werd terugbetaald (drempel: {1}).',
  'gr.pp.rule.LOW_RELIABLE_MARGIN': 'Betrouwbare marge van {0}, onder de drempel van {1}: elke extra verkoop levert weinig op.',
  'gr.pp.rule.TREND_DOWN': 'De verkoop van de laatste {0} weken daalt ten opzichte van de {0} vorige ({1} st. tegen {2} st.).',
  'gr.pp.rule.PUSH': 'Stijgende vraag ({0} st. tegen {1} st. over {2} weken), voldoende voorraad, geverifieerde kostprijs en normale retouren: het product kan meer zichtbaarheid aan.',
  'gr.pp.rule.BLOCKED': 'De vraag stijgt ({0} st. tegen {1} st. over {2} weken), maar er ontbreekt een voorwaarde om te pushen: {3}.',
  'gr.pp.blocked.checkStock': 'voorraad onbekend of meting te oud',
  'gr.pp.blocked.checkCost': 'aankoopprijs niet geverifieerd',
  'gr.pp.blocked.reviewReturns': 'retouren boven {0}',
  'gr.pp.blocked.watch': 'voorraaddekking niet berekenbaar',
  'gr.pp.rule.TOP_SELLER': 'Nr. {0} in verkoop over de periode, zonder nieuw stijgend signaal: beschikbaar houden volstaat.',
  'gr.pp.rule.TOP_SELLER_RETURNS': 'Topverkoper, maar {0} van de verkochte eenheden werd terugbetaald (meer dan {1}): begrijp deze retouren vóór elke aanvulling of promotie.',
  'gr.pp.rule.NO_SIGNAL': 'Regelmatige verkoop, zonder signaal van stijging, daling of risico.',
  // Audience
  'gr.period.lastDays': 'Laatste {0} dagen',
  'gr.period.daysNote': 'Analyse over de laatste {0} volledige dagen, vergeleken met de {0} dagen ervoor.',
  'gr.au.title': 'Doelgroep',
  'gr.au.subtitle': 'Zie welke klantsegmenten een groeikans vormen.',
  'gr.au.vsPrevious': 'vs vorige periode',
  'gr.au.pts': '{0} ptn',
  'gr.au.daysAgo': '{0} d geleden',
  'gr.au.open': 'Openen',
  'gr.au.openSegment': 'Segment bekijken: {0}',
  'gr.au.kpi.active': 'Actieve klanten',
  'gr.au.kpi.new': 'Nieuwe klanten',
  'gr.au.kpi.repeatRate': 'Herhaalaankoop',
  'gr.au.kpi.aov': 'Gemiddeld winkelmandje',
  'gr.au.kpi.toReactivate': 'Te heractiveren klanten',
  'gr.au.kpi.orders': 'Bestellingen',
  'gr.au.kpi.netSales': 'Omzet excl. btw',
  'gr.au.kpi.returningOrders': 'Bestellingen van terugkerende klanten',
  'gr.au.kpi.multiProduct': 'Mandjes met meerdere producten',
  'gr.au.kpi.noPrevious': 'Geen vergelijkbare vorige periode',
  'gr.au.kpi.notComputable': 'Niet berekenbaar',
  'gr.au.kpi.fromZero': '0 in de vorige periode',
  'gr.au.kpi.sampleGate': 'Minder dan {0} actieve klanten: niet berekend',
  'gr.au.kpi.historyGate': 'Historiek korter dan {0} dagen: niet berekend',
  'gr.au.kpi.indexMissing': 'Aankoopvolgorde niet doorgegeven door de bron',
  'gr.au.dist.title': 'Verdeling van de segmenten',
  'gr.au.dist.ordersTitle': 'Verdeling van de bestellingen',
  'gr.au.dist.value': '{0} ({1})',
  'gr.au.dist.revenue': '{0} van de omzet',
  'gr.au.dist.foot': '{0} geïdentificeerde klanten. Elke klant hoort bij één segment (totaal 100 %). Omzetaandeel: aankopen van de laatste {1} dagen.',
  'gr.au.dist.ordersFoot': 'Bestellingen van de laatste {0} dagen volgens de aankoopvolgorde van de bron. Elke bestelling telt één keer.',
  'gr.au.dist.noIndex': 'Geen enkele van de {0} bestellingen van de periode draagt een door de bron doorgegeven aankoopvolgorde: eerste en herhaalde aankopen zijn niet te onderscheiden.',
  'gr.au.orderGroup.new': 'Eerste aankoop (online)',
  'gr.au.orderGroup.returning': 'Terugkerende klant',
  'gr.au.orderGroup.first_recorded_pos': '1e geregistreerde aankoop in de winkel',
  'gr.au.orderGroup.unknown': 'Aankoopvolgorde onbekend',
  'gr.au.seg.loyal': 'Trouwe klanten',
  'gr.au.seg.returning': 'Terugkerende klanten',
  'gr.au.seg.newReturned': 'Veelbelovende nieuwe klanten',
  'gr.au.seg.new': 'Nieuwe klanten',
  'gr.au.seg.reactivate': 'Te heractiveren klanten',
  'gr.au.seg.occasional': 'Eenmalige kopers om te overtuigen',
  'gr.au.seg.unknown': 'Historiek niet vastgesteld',
  'gr.au.segDef.loyal': '≥ 3 aankopen, waarvan één recent',
  'gr.au.segDef.returning': '2 aankopen, waarvan één recent',
  'gr.au.segDef.newReturned': 'Nieuw, al teruggekomen',
  'gr.au.segDef.new': 'Recente eerste aankoop',
  'gr.au.segDef.reactivate': '≥ 2 aankopen, geen recente',
  'gr.au.segDef.occasional': '1 oude aankoop, niet teruggekomen',
  'gr.au.segDef.unknown': '1 recente aankoop, eerste niet bewezen',
  'gr.au.segRule.loyal': 'Geïdentificeerde klant met minstens 3 gekende bestellingen (of een bronvolgnummer ≥ 3), waarvan minstens één in de laatste {0} dagen.',
  'gr.au.segRule.returning': 'Geïdentificeerde klant met precies 2 gekende bestellingen, waarvan minstens één in de laatste {0} dagen, en een eerste aankoop die niet recent is.',
  'gr.au.segRule.newReturned': 'Bewezen eerste aankoop (bronvolgnummer = 1) in de laatste {0} dagen, en sindsdien minstens één andere bestelling: de klant is al teruggekomen.',
  'gr.au.segRule.new': 'Bewezen eerste aankoop (bronvolgnummer = 1) in de laatste {0} dagen, nog zonder andere bestelling.',
  'gr.au.segRule.reactivate': 'Geïdentificeerde klant met minstens 2 bestellingen (bewezen herhaalkoper) maar geen bestelling in de laatste {0} dagen.',
  'gr.au.segRule.occasional': 'Geïdentificeerde klant met één gekende bestelling, ouder dan {0} dagen, en sindsdien niet teruggekomen.',
  'gr.au.segRule.unknown': 'Eén bestelling in de laatste {0} dagen, zonder betrouwbaar bronvolgnummer (bv. winkelverkoop): onmogelijk te weten of het een eerste aankoop is. Deze groep wordt niet gekwalificeerd.',
  'gr.au.status.priority': 'Prioritair',
  'gr.au.status.activate': 'Te activeren',
  'gr.au.status.develop': 'Te ontwikkelen',
  'gr.au.status.watch': 'Opvolgen',
  'gr.au.status.insufficient': 'Onvoldoende gegevens',
  'gr.au.rule.INSUFFICIENT': 'Niet genoeg gegevens voor een betrouwbare aanbeveling: Growth trekt voorlopig geen conclusie uit dit segment.',
  'gr.au.rule.REPEAT_BUYERS_WITHOUT_RECENT_ORDER': 'Deze klanten hebben bewezen dat ze opnieuw kopen (minstens 2 bestellingen) maar bestelden recent niet meer: een identificeerbare groep om opnieuw te contacteren.',
  'gr.au.rule.REVENUE_SHARE_ABOVE_CUSTOMER_SHARE': 'Dit segment weegt {0} van de recente omzet voor {1} van de actieve klanten: het draagt meer bij dan zijn gewicht.',
  'gr.au.rule.SMALLER_THAN_PREVIOUS_WINDOW': 'Dit segment telt minder klanten dan in de vorige periode ({2}).',
  'gr.au.rule.ONE_ORDER_NOT_REPEATED': 'Deze klanten kochten één keer, langer geleden dan de periode, en kwamen niet terug: een tweede bestelling moet nog komen.',
  'gr.au.rule.ACTIVE_SEGMENT': 'Actief en voldoende groot segment, zonder bijzonder signaal van overbijdrage of daling.',
  'gr.au.reason.SAMPLE_BELOW_MIN_CUSTOMERS': 'Minder dan {0} geïdentificeerde klanten in totaal',
  'gr.au.reason.SEGMENT_BELOW_MIN_GROUP': 'Segment met minder dan {1} klanten',
  'gr.au.reason.SHORT_HISTORY': 'Historiek te kort',
  'gr.au.reason.FIRST_ORDER_NOT_PROVEN': 'Eerste aankoop niet bewezen',
  'gr.au.action.reactivation': 'Heractiveringscampagne voorbereiden',
  'gr.au.action.loyalty': 'Klantentrouw versterken',
  'gr.au.action.secondPurchase': 'Aanbod voor tweede aankoop voorbereiden',
  'gr.au.action.targetedOffer': 'Gericht aanbod testen',
  'gr.au.action.none': 'Voorlopig geen actie',
  'gr.au.actionText.reactivation': 'Deze groep opnieuw contacteren met een eenvoudige boodschap of aanbieding en meten hoeveel klanten terugkomen. Eerst kleinschalig testen.',
  'gr.au.actionText.loyalty': 'Deze klanten erkennen en belonen (trouwvoordeel, vroege toegang) om hun koopritme te behouden.',
  'gr.au.actionText.secondPurchase': 'Een reden geven om terug te komen na de eerste aankoop (productsuggestie, tijdelijk aanbod).',
  'gr.au.actionText.targetedOffer': 'Een aanbod testen dat past bij hun eerste aankoop, op een kleine groep, voor het uit te breiden.',
  'gr.au.actionText.none': 'Growth beveelt niets aan voor dit segment zolang de gegevens onvoldoende zijn.',
  'gr.au.prio.title': 'Prioritaire segmenten',
  'gr.au.prio.foot': 'Gerangschikt op status en daarna op grootte. Statussen uit expliciete regels, zonder score.',
  'gr.au.col.segment': 'Segment',
  'gr.au.col.size': 'Grootte',
  'gr.au.col.revenueShare': 'Omzetaandeel',
  'gr.au.col.status': 'Status',
  'gr.au.col.action': 'Aanbevolen actie',
  'gr.au.col.customers': 'Klanten',
  'gr.au.col.frequency': 'Bestellingen / klant',
  'gr.au.col.revenue': 'Omzet {0} d',
  'gr.au.col.aov': 'Gem. mandje',
  'gr.au.col.recency': 'Laatste aankoop',
  'gr.au.col.statusAction': 'Status · actie',
  'gr.au.sig.title': 'Doelgroepsignalen',
  'gr.au.sig.foot': 'Waargenomen feiten, vergeleken met een referentie. Geen voorspelling.',
  'gr.au.sig.none': 'Geen betrouwbaar signaal: er zijn minstens {0} geïdentificeerde klanten nodig.',
  'gr.au.sig.repeatRevenueShare.title': 'Terugkerende kopers brengen {0} van de omzet op',
  'gr.au.sig.repeatRevenueShare.text': 'Ze vormen {0} van de actieve klanten maar {1} van de omzet van de laatste {2} dagen: ze wegen meer dan hun aantal.',
  'gr.au.sig.reactivation.title': '{0} herhaalkopers zonder aankoop sinds {1} dagen',
  'gr.au.sig.reactivation.text': 'Ze brachten {0} op over de waargenomen historiek: een identificeerbare groep om opnieuw te contacteren.',
  'gr.au.sig.repeatRateUp.title': 'De herhaalaankoop stijgt',
  'gr.au.sig.repeatRateDown.title': 'De herhaalaankoop daalt',
  'gr.au.sig.repeatRateChange.text': '{0} van de actieve klanten kocht al minstens twee keer, tegenover {1} in de {2} dagen ervoor.',
  'gr.au.sig.aovGap.title': 'Gemiddeld mandje: terugkerend vs nieuw',
  'gr.au.sig.aovGap.text': '{0} voor terugkerende klanten tegenover {1} voor nieuwe klanten (waargenomen bestellingen).',
  'gr.au.sig.coverage.title': '{0} van de bestellingen is aan een klant gekoppeld',
  'gr.au.sig.coverage.text': '{0} anonieme bestellingen (vaak in de winkel) zitten in geen enkel segment: de segmenten beschrijven enkel geïdentificeerde klanten.',
  'gr.au.sig.returningOrders.title': '{0} van de bestellingen komt van terugkerende klanten',
  'gr.au.sig.returningOrders.text': 'Op {0} bestellingen met gekende aankoopvolgorde (minimum, de bronhistoriek kan onvolledig zijn).',
  'gr.au.sig.aovUp.title': 'Het gemiddelde mandje stijgt',
  'gr.au.sig.aovDown.title': 'Het gemiddelde mandje daalt',
  'gr.au.sig.aovChange.text': '{0} tegenover {1} in de {2} dagen ervoor.',
  'gr.au.sig.multiProduct.title': '{0} van de bestellingen bevat meerdere producten',
  'gr.au.sig.multiProduct.text': 'Op {0} bestellingen: toont het aandeel gecombineerde aankopen, nuttig voor combinatieaanbiedingen.',
  'gr.au.sig.customerLevelMissing.title': 'Klantsegmenten niet beschikbaar',
  'gr.au.sig.customerLevelMissing.text': 'Geen enkele bestelling draagt een gepseudonimiseerde klant-ID: Nordla kan aankopen niet per klant groeperen. De indicatoren blijven op bestelniveau.',
  'gr.au.list.title': 'Klantsegmenten ({0})',
  'gr.au.list.desc': 'Exclusieve groepen geïdentificeerde klanten, bepaald door hun waargenomen aankopen. „Recent” = in de laatste {0} dagen.',
  'gr.au.list.foot': '{0} geïdentificeerde klanten · {1} van de bestellingen van de periode gekoppeld aan een klant · Geen enkele klant wordt individueel getoond.',
  'gr.au.newSegment': '+ Nieuw segment',
  'gr.au.newSegmentSoon': 'Binnenkort beschikbaar: eigen segmenten worden nog niet in Nordla bewaard.',
  'gr.au.act.title': 'Aanbevolen acties ({0})',
  'gr.au.act.target': 'Doelgroep: {0} ({1} klanten)',
  'gr.au.act.toTest': 'Te testen',
  'gr.au.act.prerequisite': 'Voorwaarde',
  'gr.au.act.none': 'Geen aanbevolen actie: geen voldoende groot of vastgesteld segment.',
  'gr.au.act.foot': 'Enkel kwalitatieve voordelen: geen CRM of e-mailtool gekoppeld, geen resultaat beloofd.',
  'gr.au.actTitle.reactivation': 'Heractiveringscampagne voorbereiden',
  'gr.au.actTitle.loyalty': 'Klantentrouw versterken',
  'gr.au.actTitle.secondPurchase': 'Aanbod voor tweede aankoop voorbereiden',
  'gr.au.actTitle.targetedOffer': 'Gericht aanbod testen',
  'gr.au.actTitle.growSample': 'Wachten op een voldoende steekproef',
  'gr.au.actTitle.enableCustomerKey': 'Gepseudonimiseerde klantidentificatie activeren',
  'gr.au.actWhy.growSample': 'Te weinig geïdentificeerde klanten om segmenten te kwalificeren.',
  'gr.au.actWhy.enableCustomerKey': 'Geen enkele gesynchroniseerde bestelling draagt een gepseudonimiseerde klantsleutel.',
  'gr.au.actBenefit.reactivation': 'Mogelijke heractivering van kopers die hun interesse al bewezen.',
  'gr.au.actBenefit.loyalty': 'Het segment beschermen dat het zwaarst weegt in de omzet.',
  'gr.au.actBenefit.secondPurchase': 'Een eerste aankoop omzetten in een gewoonte.',
  'gr.au.actBenefit.targetedOffer': 'Een tweede bestelling halen bij reeds gewonnen klanten.',
  'gr.au.actBenefit.growSample': 'Betrouwbare segmenten zodra de steekproef bereikt is.',
  'gr.au.actBenefit.enableCustomerKey': 'Ontgrendelt de segmenten (trouw, te heractiveren, nieuw) zonder identiteit op te slaan: enkel een versleutelde vingerafdruk wordt bewaard.',
  'gr.au.noKey.banner': 'Klantniveau niet beschikbaar: geen enkele bestelling draagt een gepseudonimiseerde klant-ID. De pagina blijft op bestelniveau en richt zich op geen enkele individuele klant.',
  'gr.au.noKey.text': 'Deze segmenten vereisen gepseudonimiseerde klantidentificatie, die voor deze winkel niet actief is:',
  'gr.au.d.window': 'Referentie: laatste {0} dagen',
  'gr.au.d.definition': 'Definitie',
  'gr.au.d.sizeValue': 'Grootte en waarde',
  'gr.au.d.size': 'Klanten',
  'gr.au.d.sizeNote': '{0} van de geïdentificeerde klanten',
  'gr.au.d.evolution': 'Vorige periode',
  'gr.au.d.noPrevious': 'Geen vergelijkbare periode',
  'gr.au.d.same': 'Stabiel: {0} klanten',
  'gr.au.d.previous': '{0} klanten in de vorige periode',
  'gr.au.d.noWindowPurchase': 'Geen aankoop in de periode, per definitie',
  'gr.au.d.revenueShare': '{0} van de omzet van actieve klanten',
  'gr.au.d.historyRevenue': 'Waargenomen omzet (historiek)',
  'gr.au.d.historyNote': 'Over {0} dagen geladen historiek',
  'gr.au.d.aovNote': 'Al hun waargenomen bestellingen',
  'gr.au.d.frequencyNote': 'Gekende bestellingen per klant',
  'gr.au.d.recencyNote': 'Mediaan van het segment',
  'gr.au.d.why': 'Waarom Growth het signaleert',
  'gr.au.d.action': 'Voorgestelde actie',
  'gr.au.d.method': 'Segment berekend uit de in Nordla gesynchroniseerde bestellingen, gegroepeerd per gepseudonimiseerde klant-ID. Er worden geen persoonsgegevens gelezen of getoond. Waarneming, geen voorspelling.',
  'gr.au.empty.title': 'Geen bestellingen in de periode',
  'gr.au.empty.text': 'Geen gesynchroniseerde bestellingen: Audience heeft voorlopig niets te analyseren.',
  'gr.au.empty.window': 'Geen gegevens over de laatste {0} dagen.',
  // Contenu
  'gr.ct.title': 'Content',
  'gr.ct.subtitle': 'Spoor onvolledige productfiches op en de verbeteringen die voorrang krijgen.',
  'gr.ct.status.priority': 'Prioritair',
  'gr.ct.status.improve': 'Te verbeteren',
  'gr.ct.status.insufficient': 'Onvoldoende gegevens',
  'gr.ct.status.correct': 'Correct',
  'gr.ct.problem.noImage': 'Zonder afbeelding',
  'gr.ct.problem.noAltText': 'Zonder alt-tekst',
  'gr.ct.problem.noType': 'Zonder categorie',
  'gr.ct.problem.noCollection': 'Buiten collectie',
  'gr.ct.problem.missingSku': 'SKU ontbreekt',
  'gr.ct.problem.duplicateTitle': 'Dubbele naam',
  'gr.ct.kpi.toImprove': 'Te verbeteren producten',
  'gr.ct.kpi.toImproveNote': 'Minstens één probleem, op {0} actieve producten',
  'gr.ct.kpi.noImage': 'Zonder afbeelding',
  'gr.ct.kpi.noImageNote': 'Geen hoofdafbeelding',
  'gr.ct.kpi.noAltText': 'Zonder alt-tekst',
  'gr.ct.kpi.noAltTextNote': 'Afbeelding zonder beschrijving',
  'gr.ct.kpi.noType': 'Zonder categorie',
  'gr.ct.kpi.noTypeNote': 'Producttype leeg',
  'gr.ct.kpi.missingSku': 'SKU ontbreekt',
  'gr.ct.kpi.missingSkuNote': 'Minstens één variant zonder SKU',
  'gr.ct.kpi.unavailable': 'Niet controleerbaar met de huidige gegevens',
  'gr.ct.prio.title': 'Producten per prioriteit',
  'gr.ct.prio.total': 'producten',
  'gr.ct.prio.foot': '{0} actieve producten geanalyseerd, elk één keer geteld.',
  'gr.ct.problems.title': 'Belangrijkste contentproblemen',
  'gr.ct.problems.none': 'Geen probleem gevonden bij de mogelijke controles.',
  'gr.ct.problems.notChecked': 'Niet gecontroleerd met de huidige gegevens: {0}.',
  'gr.ct.na.description': 'beschrijving',
  'gr.ct.na.reviews': 'klantbeoordelingen',
  'gr.ct.na.multipleImages': 'meerdere afbeeldingen',
  'gr.ct.na.seo': 'SEO-titel en -meta',
  'gr.ct.na.attributes': 'productkenmerken',
  'gr.ct.search': 'Product of SKU zoeken',
  'gr.ct.f.status': 'Status',
  'gr.ct.f.allStatuses': 'Alle statussen',
  'gr.ct.f.problem': 'Probleem',
  'gr.ct.f.allProblems': 'Alle problemen',
  'gr.ct.f.category': 'Categorie',
  'gr.ct.f.allCategories': 'Alle categorieën',
  'gr.ct.noSku': 'Zonder SKU',
  'gr.ct.col.product': 'Product',
  'gr.ct.col.category': 'Categorie',
  'gr.ct.col.problems': 'Problemen',
  'gr.ct.col.status': 'Status',
  'gr.ct.col.sales': 'Verkoop ({0} w.)',
  'gr.ct.col.action': 'Actie',
  'gr.ct.noProblemYet': 'Geen probleem gevonden (afbeelding niet controleerbaar)',
  'gr.ct.noProblem': 'Geen probleem gevonden',
  'gr.ct.seeReco': 'Aanbevelingen bekijken',
  'gr.ct.seeDetail': 'Details bekijken',
  'gr.ct.list.title': 'Producten',
  'gr.ct.list.foot': '{0} van {1} actieve producten getoond ({2} in de catalogus, concepten en archief uitgesloten). Gesorteerd op prioriteit en daarna verkoop.',
  'gr.ct.empty.noProducts': 'Geen actief product om te analyseren.',
  'gr.ct.empty.clearTitle': 'Geen contentprobleem gevonden met de momenteel beschikbare gegevens.',
  'gr.ct.empty.clearText': 'Nordla blijft de kwaliteit van de productinformatie opvolgen.',
  'gr.ct.empty.insufficientTitle': 'Onvoldoende gegevens',
  'gr.ct.empty.insufficientText': 'Sommige aspecten van de productcontent zijn nog niet beschikbaar in Nordla: geen enkel product wordt correct verklaard zonder controle.',
  'gr.ct.banner.noImage': 'Afbeeldingen niet controleerbaar: voor deze winkel is nog geen productafbeelding gesynchroniseerd. Nordla kan een product zonder afbeelding dus niet onderscheiden van een niet-doorgegeven afbeelding; deze producten staan op „Onvoldoende gegevens”, nooit „Correct”.',
  'gr.ct.d.problems': 'Gevonden problemen',
  'gr.ct.d.none': 'Geen probleem vast te stellen met de beschikbare gegevens.',
  'gr.ct.d.noneInsufficient': 'Geen probleem gevonden, maar de afbeelding kan niet worden gecontroleerd: het product wordt niet correct verklaard.',
  'gr.ct.d.why': 'Waarom dit belangrijk is',
  'gr.ct.d.sold': 'Dit product werd {0} keer verkocht in de laatste {1} weken: zijn informatie wordt echt door klanten gezien, het verdient voorrang.',
  'gr.ct.d.notSold': 'Geen verkoop in de laatste {0} weken: minder dringend, maar de fiche blijft onvolledig voor later gebruik in Growth of andere kanalen.',
  'gr.ct.d.reco': 'Aanbevelingen',
  'gr.ct.d.unverified': 'Niet controleerbaar met de huidige gegevens',
  'gr.ct.d.improve': 'Dit product verbeteren',
  'gr.ct.d.improveSoon': 'Binnenkort beschikbaar: Nordla past productfiches nog niet aan.',
  'gr.ct.d.method': 'Deterministische controles op de in Nordla gesynchroniseerde productgegevens. Er wordt geen becijferd effect beloofd: het effect van een betere fiche wordt niet gemeten.',
  'gr.ct.rule.MAJOR_PROBLEM': 'Het product heeft geen afbeelding: zonder beeld is het moeilijk te begrijpen of voor te stellen.',
  'gr.ct.rule.MANY_PROBLEMS': 'Minstens {0} problemen tegelijk: de fiche is op meerdere punten onvolledig.',
  'gr.ct.rule.MINOR_PROBLEMS': 'Niet-blokkerende problemen: het product blijft voorstelbaar maar de fiche kan worden aangevuld.',
  'gr.ct.rule.ESSENTIAL_CHECK_UNAVAILABLE': 'Geen probleem gevonden, maar een essentiële controle (de afbeelding) is niet mogelijk met de huidige gegevens.',
  'gr.ct.rule.NO_DETECTABLE_PROBLEM': 'Geen probleem vast te stellen met de gegevens van Nordla. Dat garandeert geen perfecte content.',
  'gr.ct.fact.noImage': 'Er is geen hoofdafbeelding voor dit product.',
  'gr.ct.fact.noAltText': 'De hoofdafbeelding heeft geen alt-tekst.',
  'gr.ct.fact.noType': 'Het producttype is leeg in de bron.',
  'gr.ct.fact.noCollection': 'Het product hoort bij geen enkele huidige collectie.',
  'gr.ct.fact.missingSku': '{0} variant(en) van {1} zonder SKU.',
  'gr.ct.fact.duplicateTitle': '{0} ander(e) actief/actieve product(en) dragen exact dezelfde naam.',
  'gr.ct.explain.noImage': 'Zonder beeld ziet de klant niet wat hij koopt.',
  'gr.ct.explain.noAltText': 'De alt-tekst beschrijft de afbeelding voor toegankelijkheid en zoekmachines.',
  'gr.ct.explain.noType': 'Zonder categorie is het product slecht ingedeeld in de winkel en in de Nordla-analyses.',
  'gr.ct.explain.noCollection': 'Buiten een collectie is het product moeilijker te vinden bij het navigeren.',
  'gr.ct.explain.missingSku': 'Zonder SKU is de variant moeilijk te identificeren in voorraad, kassa of andere kanalen.',
  'gr.ct.explain.duplicateTitle': 'Twee producten met dezelfde naam worden verward door de klant en in rapporten.',
  'gr.ct.reco.noImage': 'Een kwaliteitsvolle productafbeelding toevoegen.',
  'gr.ct.reco.noAltText': 'Een beschrijvende alt-tekst toevoegen.',
  'gr.ct.reco.noType': 'Het product in een bruikbare categorie indelen.',
  'gr.ct.reco.noCollection': 'Het product aan een relevante collectie toevoegen.',
  'gr.ct.reco.missingSku': 'Elke variant een unieke SKU geven.',
  'gr.ct.reco.duplicateTitle': 'Elk product een onderscheidende naam geven.',
  'gr.ct.recoHow.noImage': 'Scherpe foto van het echte product, op neutrale achtergrond, in de winkeltool.',
  'gr.ct.recoHow.noAltText': 'In enkele woorden beschrijven wat de afbeelding toont (product, kleur, gebruik).',
  'gr.ct.recoHow.noType': 'Het producttype invullen in de productfiche van de winkel.',
  'gr.ct.recoHow.noCollection': 'De collectie kiezen waar een klant het zou zoeken.',
  'gr.ct.recoHow.missingSku': 'Het SKU-veld van elke betrokken variant invullen.',
  'gr.ct.recoHow.duplicateTitle': 'Toevoegen wat ze onderscheidt (model, maat, kleur) in de naam.',
  // Croissance magasin
  'gr.st.title': 'Winkelgroei',
  'gr.st.subtitle': 'Analyseer de verkoop van uw fysieke winkel en de lokale acties om te overwegen.',
  'gr.st.vsPrevious': 'vs vorige 8 weken',
  'gr.st.kpi.storeNet': 'Winkelomzet (excl. btw)',
  'gr.st.kpi.storeOrders': 'Winkelbestellingen',
  'gr.st.kpi.storeAov': 'Gem. winkelmandje',
  'gr.st.kpi.storeShare': 'Aandeel winkel',
  'gr.st.kpi.locations': 'Actieve winkels',
  'gr.st.kpi.locationsNote': 'Met verkoop in de periode ({0} gekende locatie(s))',
  'gr.st.kpi.locationsUnknown': '{0} bestelling(en) zonder locatie',
  'gr.st.kpi.noPrevious': 'Geen vergelijkbare vorige periode',
  'gr.st.kpi.notComputable': 'Niet berekenbaar',
  'gr.st.kpi.fromZero': '0 in de vorige periode',
  'gr.st.banner.footfall': 'Bezoekersaantallen niet gekoppeld: de cijfers hieronder zijn verkopen, geen bezoekers. Er wordt geen conversie of bezoekersaantal berekend.',
  'gr.st.perf.title': 'Winkelprestaties',
  'gr.st.perf.metric': 'Indicator',
  'gr.st.perf.sales': 'Winkelomzet per week',
  'gr.st.perf.orders': 'Winkelbestellingen per week',
  'gr.st.perf.channels': 'Winkel vs online (omzet)',
  'gr.st.perf.store': 'Winkel',
  'gr.st.perf.online': 'Online',
  'gr.st.perf.current': 'Laatste 8 weken',
  'gr.st.perf.previous': 'Vorige 8 weken',
  'gr.st.perf.foot': 'Volledige weken; elke week wordt vergeleken met dezelfde positie in de {0} weken ervoor.',
  'gr.st.perf.footNoPrev': 'Volledige weken. Geen vergelijking: de historiek dekt de {0} weken ervoor niet.',
  'gr.st.days.title': 'Verkoopactiviteit per dag',
  'gr.st.days.orders': '{0} best.',
  'gr.st.days.foot': '{0} winkelbestellingen in de periode. Verkoop per weekdag, geen bezoekers; geen vaststelling onder {1} bestellingen.',
  'gr.st.products.title': 'Sterkste producten in de winkel',
  'gr.st.products.detail': '{0} · {1} van de winkelverkoop',
  'gr.st.products.guard': 'Niet in de kijker: {0}',
  'gr.st.products.unknown': 'Product niet gekoppeld aan catalogus',
  'gr.st.products.foot': 'Gerangschikt op winkelomzet over 8 weken. De beveiligingen van Productpotentieel (voorraad, marge, retouren, daling) gelden.',
  'gr.st.diff.title': 'Verschillen winkel / online',
  'gr.st.diff.aov': 'Gemiddeld mandje: {0} in de winkel tegenover {1} online.',
  'gr.st.diff.product': '{0} van de winkelverkoop tegenover {1} online',
  'gr.st.diff.none': 'Geen product weegt minstens twee keer zwaarder in de winkel dan online in de periode.',
  'gr.st.diff.gated': 'Vergelijking beschikbaar vanaf {0} bestellingen aan elke kant (winkel: {1}, online: {2}).',
  'gr.st.diff.foot': 'Waargenomen feiten, zonder veronderstelde verklaring.',
  'gr.st.loc.title': 'Alle winkels ({0})',
  'gr.st.loc.store': 'Winkel',
  'gr.st.loc.orders': 'Bestellingen',
  'gr.st.loc.net': 'Omzet (excl. btw)',
  'gr.st.loc.aov': 'Gem. mandje',
  'gr.st.loc.share': 'Aandeel',
  'gr.st.loc.unnamed': 'Locatie zonder naam',
  'gr.st.loc.unknown': 'Locatie niet ingevuld',
  'gr.st.loc.foot': 'De KPI’s tellen alle winkels op; er wordt geen locatie voor u gekozen.',
  'gr.st.sig.title': 'Winkelsignalen',
  'gr.st.sig.none': 'Geen betrouwbaar signaal: minstens {0} winkelbestellingen per vergeleken periode nodig (nu {1}).',
  'gr.st.sig.foot': 'Waargenomen verkoopfeiten, vergeleken met een referentie. Geen veronderstelde oorzaak.',
  'gr.st.sig.storeFaster.title': 'De winkel groeit sneller dan online',
  'gr.st.sig.onlineFaster.title': 'Online groeit sneller dan de winkel',
  'gr.st.sig.storeVsOnline.text': 'Winkelomzet {0} tegenover {1} online, over de laatste {2} weken vs de vorige.',
  'gr.st.sig.ordersUpAovDown.title': 'Meer bestellingen, lager gemiddeld mandje',
  'gr.st.sig.ordersDownAovUp.title': 'Minder bestellingen, hoger gemiddeld mandje',
  'gr.st.sig.ordersAov.text': 'Winkelbestellingen {0}, gemiddeld mandje {1} tegenover de vorige 8 weken.',
  'gr.st.sig.strongWeekday.title': '{0} is goed voor {1} van de winkelverkoop',
  'gr.st.sig.strongWeekday.text': 'Gelijk verdeeld zou elke dag {0} zijn: deze dag weegt minstens het dubbele.',
  'gr.st.sig.productGap.title': '{0} weegt zwaarder in de winkel',
  'gr.st.sig.productGap.text': '{0} van de winkelverkoop tegenover {1} online.',
  'gr.st.sig.refundsUp.title': 'Meer terugbetalingen in de winkel',
  'gr.st.sig.refundsUp.text': '{0} van de verkochte eenheden terugbetaald tegenover {1} in de vorige 8 weken.',
  'gr.st.act.title': 'Aanbevolen lokale acties ({0})',
  'gr.st.act.none': 'Geen aanbevolen actie: minstens {0} winkelbestellingen in de periode nodig.',
  'gr.st.act.foot': 'Enkel gebaseerd op waargenomen verkoop; geen enkele veronderstelt winkelbezoek.',
  'gr.st.act.restockFirst.title': 'Eerst aanvullen, dan animeren',
  'gr.st.act.restockFirst.text': '{0} verkoopt goed in de winkel maar de voorraad dekt te weinig weken (Productpotentieel).',
  'gr.st.act.highlightProduct.title': 'Een winkelproduct meer in de kijker zetten',
  'gr.st.act.highlightProduct.text': '{0} is goed voor {1} van de winkelverkoop en wordt door geen enkele beveiliging geblokkeerd.',
  'gr.st.act.weekdayHighlight.title': 'Een actie testen op {0}',
  'gr.st.act.weekdayHighlight.text': 'Deze dag realiseert {0} van de winkelverkoop.',
  'gr.st.act.checkAov.title': 'De daling van het gemiddelde mandje nagaan',
  'gr.st.act.checkAov.text': 'Meer bestellingen maar een kleiner mandje: kortingen en productmix bekijken.',
  'gr.st.future.title': 'Verder gaan',
  'gr.st.future.footfall': 'Winkelbezoek',
  'gr.st.future.googleBusiness': 'Google Business Profile',
  'gr.st.future.posEnriched': 'Uitgebreide kassa',
  'gr.st.future.unlocks': 'Zou ontgrendelen: {0}',
  'gr.st.future.u.conversion': 'winkelconversie',
  'gr.st.future.u.visitors': 'bezoekers',
  'gr.st.future.u.salesPerVisitor': 'verkoop per bezoeker',
  'gr.st.future.u.directions': 'routeaanvragen',
  'gr.st.future.u.calls': 'oproepen',
  'gr.st.future.u.localVisibility': 'lokale zichtbaarheid',
  'gr.st.future.u.staff': 'verkoop per verkoper',
  'gr.st.future.u.paymentMethods': 'betaalmiddelen',
  'gr.st.future.u.hours': 'betrouwbare uren',
  'gr.st.future.notConnected': 'Bron niet gekoppeld',
  'gr.st.future.audience': 'Winkelpubliek',
  'gr.st.future.audienceNone': 'Winkelpubliek niet identificeerbaar: winkelbestellingen dragen geen gepseudonimiseerde klant-ID.',
  'gr.st.future.audienceShare': '{0} van de winkelbestellingen gekoppeld aan een klant (geaggregeerd, zie Doelgroep).',
  'gr.st.future.partial': 'Gedeeltelijk',
  'gr.st.future.notIdentifiable': 'Niet identificeerbaar',
  'gr.st.future.foot': 'Geen enkele van deze bronnen is gekoppeld: binnenkort beschikbaar. Intussen wordt niets gesimuleerd.',
  'gr.st.empty.noStoreTitle': 'Geen herkenbare winkelverkoop in deze periode.',
  'gr.st.empty.noStoreText': 'Growth kan de winkel analyseren zodra er een bron van fysieke verkoop is. Geen enkele bestelling komt van een winkelkanaal: dat is geen „nul verkoop”, maar een ontbrekende bron.',
  'gr.st.empty.window': 'Geen winkelverkoop in de laatste {0} weken.',
  // Shared page states
  'gr.state.loading': 'Gegevens laden…',
  'gr.state.errorTitle': 'Gegevens niet beschikbaar',
  'gr.state.error.TENANT_NOT_CONFIGURED': 'Er is geen winkel geconfigureerd voor Growth op deze server.',
  'gr.state.error.DATA_UNAVAILABLE': 'De winkelgegevens konden momenteel niet worden gelezen.',
  'gr.state.error.NETWORK': 'De Growth-server antwoordt niet. Controleer de verbinding.',
  'gr.state.error.UNKNOWN': 'Een onverwachte fout verhinderde het laden van deze pagina.',
  'gr.state.retry': 'Opnieuw proberen',
  // Overview: capabilities not connected (deep audit P1-2)
  'gr.pulse.visitorsNotConnected': 'Bezoekersaantallen niet gekoppeld',
  'gr.pulse.visitorsNotConnectedText': 'Er is geen bron voor bezoekersaantallen gekoppeld: Nordla kent het aantal winkelbezoekers niet.',
  'gr.camp.newCustomers': '{0} nieuwe klanten',
  'gr.store.notConnected': 'Niet gekoppeld',
  'gr.store.footfallNote': 'Geen bron voor bezoekersaantallen',
  'gr.store.realRevenue': 'Winkelomzet (laatste {0} w.)',
  'gr.store.realChip': 'Echte gegevens',
  'gr.store.noStore': 'Geen herkenbare winkelverkoop',
  'gr.store.unavailable': 'Gegevens niet beschikbaar',
});
