'use strict';
// Nederlands - Nordla Growth.
window.NORDLA_DICTS = window.NORDLA_DICTS || {};
window.NORDLA_DICTS.nl = Object.assign(window.NORDLA_DICTS.nl || {}, {
  'gr.brand': 'Nordla AI',
  'gr.dash': '—',
  'gr.vsPrevious': 'vs vorige periode',
  'gr.nav.aria': 'Growth-navigatie',
  'gr.nav.overview': 'Overzicht',
  'gr.nav.opportunities': 'Kansen',
  'gr.nav.campaigns': 'Campagnes',
  'gr.nav.content': 'Content',
  'gr.nav.storeGrowth': 'Winkelgroei',
  'gr.nav.audience': 'Doelgroep',
  'gr.nav.experiments': 'Experimenten',
  'gr.nav.ai': 'Nordla AI',
  'gr.nav.settings': 'Instellingen',
  'gr.nav.soon': 'Binnenkort beschikbaar',
  'gr.demo': 'Demogegevens',
  'gr.demoShort': 'Demo',
  'gr.demoTitle': 'Er is nog geen Growth-bron gekoppeld: alle cijfers op deze pagina zijn voorbeelden.',
  'gr.period.last30': 'Laatste 30 dagen',
  'gr.period.fixed': 'Vast',
  'gr.period.fixedNote': 'De Growth-weergave toont de laatste 30 dagen.',
  'gr.title': 'Growth',
  'gr.subtitle': 'Zet uw bedrijfsgegevens om in meetbare groeikansen.',
  'gr.kpi.revenueInfluenced': 'Beïnvloede omzet',
  'gr.kpi.activeOpportunities': 'Actieve kansen',
  'gr.kpi.highPriority': 'hoge prioriteit',
  'gr.kpi.activeCampaigns': 'Actieve campagnes',
  'gr.kpi.performingWell': 'presteren goed',
  'gr.kpi.roas': 'ROAS',
  'gr.kpi.experimentsRunning': 'Lopende experimenten',
  'gr.kpi.endingThisWeek': 'eindigt deze week',
  'gr.pulse.title': 'Growth Pulse',
  'gr.pulse.metric': 'Getoonde indicator',
  'gr.pulse.revenue': 'Omzet',
  'gr.pulse.traffic': 'Winkelbezoek',
  'gr.pulse.total': 'Totale omzet',
  'gr.pulse.influenced': 'Omzet beïnvloed door Growth',
  'gr.pulse.visitors': 'Winkelbezoekers',
  'gr.pulse.share': '{0} % beïnvloed door Growth',
  'gr.pulse.foot': 'Per dag, van {0} tot {1}. Omzet en bezoek hebben andere eenheden en worden apart getoond.',
  'gr.ai.title': 'Nordla AI-inzichten',
  'gr.ai.badge': 'Nordla AI',
  'gr.ai.foot': 'Nordla AI verklaart; de cijfers komen uit de rekenmotor.',
  'gr.att.title': 'Vraagt uw aandacht',
  'gr.att.status.pending': 'Goed te keuren',
  'gr.att.status.new': 'Nieuw',
  'gr.att.status.endingSoon': 'Loopt bijna af',
  'gr.att.action.approve': 'Bekijken',
  'gr.att.action.review': 'Bekijken',
  'gr.att.action.results': 'Resultaten',
  'gr.att.soon': 'Beschikbaar met de pagina Approvals (binnenkort)',
  'gr.ch.title': 'Prestaties per kanaal',
  'gr.ch.channel': 'Kanaal',
  'gr.ch.revenue': 'Omzet',
  'gr.ch.reach': 'Bezoeken / bereik',
  'gr.ch.conversion': 'Conversie',
  'gr.ch.roas': 'ROAS',
  'gr.ch.unit.visits': 'bezoeken',
  'gr.ch.unit.reach': 'bereik',
  'gr.ch.unit.actions': 'acties',
  'gr.ch.organic': 'organisch',
  'gr.ch.foot': 'ROAS = toegewezen omzet ÷ advertentie-uitgaven. „organisch” = kanaal zonder uitgaven.',
  'gr.camp.title': 'Campagnes',
  'gr.camp.activeCount': '{0} actief',
  'gr.camp.spend': '{0} besteed van {1}',
  'gr.camp.noBudget': 'Geen budget (organisch)',
  'gr.camp.status.performing': 'Presteert',
  'gr.camp.status.active': 'Actief',
  'gr.camp.status.watch': 'Opvolgen',
  'gr.camp.roas': 'ROAS {0}',
  'gr.camp.conversions': '{0} conversies',
  'gr.camp.actions': '{0} acties',
  'gr.content.title': 'Contentprestaties',
  'gr.content.kind.reel': 'Reel',
  'gr.content.kind.video': 'Video',
  'gr.content.kind.carousel': 'Carrousel',
  'gr.content.kind.post': 'Post',
  'gr.content.views': '{0} weergaven',
  'gr.content.perf.best': 'Best presterend',
  'gr.content.perf.good': 'Goed',
  'gr.content.perf.below': 'Onder gemiddeld',
  'gr.store.title': 'Winkelgroei',
  'gr.store.traffic': 'Winkelbezoek',
  'gr.store.conversion': 'Conversiegraad',
  'gr.store.revenue': 'Winkelomzet',
  'gr.store.pts': '{0} ptn',
  'gr.opp.title': 'Belangrijkste kansen',
  'gr.opp.source': 'Bron: {0}',
  'gr.opp.priority.high': 'Hoge prioriteit',
  'gr.opp.priority.medium': 'Gemiddelde prioriteit',
  'gr.opp.status.recommended': 'Aanbevolen',
  'gr.opp.status.review': 'Te bekijken',
  'gr.opp.status.planned': 'Gepland',
  'gr.opp.estimate': 'Geschatte omzet',
  'gr.opp.foot': 'Schattingen over 30 dagen, te valideren vóór elke actie.',
  'gr.exp.title': 'Experimenten',
  'gr.exp.kpi': 'Geteste KPI: {0}',
  'gr.exp.status.running': 'Loopt',
  'gr.exp.status.endingSoon': 'Loopt bijna af',
  'gr.exp.duration': '{0} dagen',
  'gr.exp.ends': 'Einde',
  'gr.noData': 'Gegevens niet beschikbaar',
  'gr.loadError': 'De Growth-weergave kon niet worden geladen.',
  'gr.op.title': 'Kansen',
  'gr.op.subtitle': 'Identificeer en prioriteer de meest veelbelovende groeihefbomen voor uw activiteit.',
  'gr.op.kpi.priority': 'Prioritaire kansen',
  'gr.op.kpi.highPriority': '{0} hoge prioriteit',
  'gr.op.kpi.potential': 'Potentiële omzet',
  'gr.op.kpi.active': '{0} actieve kansen',
  'gr.op.kpi.ready': 'Klaar voor goedkeuring',
  'gr.op.kpi.readyNote': 'Acties die kunnen starten',
  'gr.op.kpi.inProgress': 'Lopend',
  'gr.op.kpi.inProgressNote': 'Kansen in uitvoering',
  'gr.op.kpi.wins': 'Successen deze maand',
  'gr.op.kpi.winsNote': '{0} gegenereerd',
  'gr.op.pipe.title': 'Pijplijn van kansen',
  'gr.op.pipe.desc': 'Identificeer, prioriteer en volg de groeikansen die Nordla detecteert.',
  'gr.op.pipe.foot': '{0} kansen getoond · {1} potentiële omzet. Schattingen, te valideren vóór elke actie.',
  'gr.op.f.source': 'Bron',
  'gr.op.f.allSources': 'Alle bronnen',
  'gr.op.f.status': 'Status',
  'gr.op.f.allStatuses': 'Alle statussen',
  'gr.op.f.sort': 'Sortering',
  'gr.op.f.sort.priority': 'Sorteren op prioriteit',
  'gr.op.f.sort.revenue': 'Sorteren op potentiële omzet',
  'gr.op.f.sort.confidence': 'Sorteren op betrouwbaarheid',
  'gr.op.col.name': 'Kans',
  'gr.op.col.source': 'Bron',
  'gr.op.col.priority': 'Prioriteit',
  'gr.op.col.revenue': 'Potentiële omzet',
  'gr.op.col.confidence': 'Betrouwbaarheid',
  'gr.op.col.effort': 'Inspanning',
  'gr.op.col.status': 'Status',
  'gr.op.col.actions': 'Acties',
  'gr.op.actionsSoon': 'Acties binnenkort beschikbaar',
  'gr.op.noMatch': 'Geen kans komt overeen met deze filters.',
  'gr.op.src.store': 'Winkelanalyse',
  'gr.op.src.stock': 'Voorraad',
  'gr.op.src.market': 'Markttrend',
  'gr.op.src.ai': 'Nordla AI',
  'gr.op.src.customers': 'Klantgedrag',
  'gr.op.src.experiment': 'Winkelexperiment',
  'gr.op.src.seasonality': 'Seizoensgebondenheid',
  'gr.op.src.sales': 'Verkoop',
  'gr.op.src.local': 'Lokale gegevens',
  'gr.op.src.margin': 'Marges',
  'gr.op.status.ready': 'Klaar voor goedkeuring',
  'gr.op.status.inProgress': 'Lopend',
  'gr.op.status.analysis': 'Analyse',
  'gr.op.status.planned': 'Gepland',
  'gr.op.priority.high': 'Hoog',
  'gr.op.priority.medium': 'Gemiddeld',
  'gr.op.priority.low': 'Laag',
  'gr.op.effort.low': 'Laag',
  'gr.op.effort.medium': 'Gemiddeld',
  'gr.op.effort.high': 'Hoog',
  'gr.op.ai.title': 'Aanbevelingen Nordla AI',
  'gr.op.ai.potential': 'Potentiële omzet',
  'gr.op.ai.confidence': 'betrouwbaarheid {0}',
  'gr.op.mx.title': 'Impact vs inspanning',
  'gr.op.mx.impact': 'Impact',
  'gr.op.mx.effortLow': 'Lage inspanning',
  'gr.op.mx.effortHigh': 'Gemiddelde tot hoge inspanning',
  'gr.op.mx.highLow': 'Hoge impact · lage inspanning',
  'gr.op.mx.highHigh': 'Hoge impact · hoge inspanning',
  'gr.op.mx.lowLow': 'Lage impact · lage inspanning',
  'gr.op.mx.lowHigh': 'Lage impact · hoge inspanning',
  'gr.op.mx.foot': 'De {0} prioritaire kansen, geplaatst volgens geschatte impact en inspanning.',
  'gr.op.appr.title': 'Vraagt uw goedkeuring',
  'gr.op.appr.budget': 'Voorgesteld budget {0}',
  'gr.op.appr.expected': 'verwachte omzet {0}',
  'gr.op.appr.approve': 'Goedkeuren',
  'gr.op.appr.soon': 'De goedkeuringsworkflow is nog niet beschikbaar',
  'gr.op.appr.foot': 'Er wordt geen actie gestart zonder uw beslissing.',
  'gr.op.seg.title': 'Segmenten met hoog potentieel',
  'gr.op.seg.foot': 'Geschatte groei van het potentieel per segment.',
  'gr.op.wins.title': 'Recente successen',
  'gr.op.wins.target': 'Doel {0} · {1} behaald',
});
